Eventual-Inc/Daft

- daft/viz/dataframe_display.py
- notebooks/tutorials/quickstart.ipynb
- notebooks/tutorials/text_to_image/text_to_image_generation.ipynb
Relying on class and module names to detect PIL Images doesn't work for certain corner-cases, such as loading from a JPEG file.
This PR uses the existence of `_repr_png_` to determine whether we should display an image.
> use _repr_png_ to display PIL images instead of relying on class/module names

- notebooks/tutorials/text_to_image/text_to_image_generation.ipynb
* Use the DALL-E model instead of Stable Diffusion for our text to image generation GPU usage tutorial
* This simplifies tutorial setup, no longer requiring learners to create a Huggingface account and grab an API token
> Use DALL-E model for tutorial instead of Stable Diffusion

- tests/conftest.py
- tests/stress_tests/test_tpch.py
* Enables TPCH bench mark via `--tpch_benchmark`
* disables use of sqllite generation unless needed
* creates parquet files for benchmarking
> TPCH Benchmark mode

- daft/logging.py
- daft/runners/blocks.py
- daft/runners/partitioning.py
- tests/stress_tests/test_tpch.py
* Refactors partition implementation to use arrow slicing rather than `np.split`.
* [yields over 38% speed for some benchmarks such as tpch](https://docs.google.com/spreadsheets/d/1MZ9iVi9zu5uTC6me4JOFkRub0aql_FQkiNkQQatzWqQ/edit?usp=sharing)
* Fixes null handling with partition since we're no longer casting to numpy
> Slice Partitioning

- poetry.lock
- pyproject.toml
We can now remove our dependency on pydantic after the refactor of `daft.config` in #198
> Remove pydantic from dependencies

- poetry.lock
- pyproject.toml
* Adds polars as a dependency (for #200 )
* Updates `typing-extensions` to `>=4.0.0` to satisfy polars dependency requirements. This has been tested locally to pass unit tests and typechecks in a Python 3.7 venv.
> Add Polars as a dependency

- daft/dataframe/schema.py
- daft/execution/operators.py
- daft/viz/dataframe_display.py
- daft/viz/repr_html.py
Prettier Google Colab display:
* Add `class="dataframe"` tag which gives the table custom CSS from Google Colab
* Refactors the code to be much simpler, rely on Pandas for `__repr__` and only do custom handling for `_repr_html_`
> Refactor HTML repr code for prettier colab display

- daft/runners/blocks.py
- daft/runners/partitioning.py
- daft/udf.py
- tests/dataframe_cookbook/test_python_list_cols.py
- tests/dataframe_cookbook/test_udf.py
See: #200 for the rationale behind this change
* add a deprecation warning to `@udf` that it will be removed in 0.1.0
* make_block has to be polars-aware and properly parse incoming Polars Series
* unit tests updated
* documentation updated
> Adds a @polars_udf that uses polars.Series as the input parameters

- build.py
* fixes issue when multithreaded cython build is set. the following error appears:
```RuntimeError:
An attempt has been made to start a new process before the
current process has finished its bootstrapping phase.
This probably means that you are not using fork to start your
child processes and you have forgotten to use the proper idiom
```
* Related to https://github.com/cython/cython/issues/3262
> MacOS build bug when multiprocessing method is set to spawn

- daft/runners/ray_runner.py
`ray.init()` errors out if it is called more than once
However, there are situations where a user may call `ray.init()` outside of Daft, for example to initialize runtime environments. In this case, Daft will log a warning and allow this behavior, opting to reuse the already-initialized Ray context.
> Allow RayRunner to proceed when Ray context has already been initialized

- daft/__init__.py
- docs/source/api_docs.rst
- docs/source/api_docs/context.rst
- docs/source/api_docs/udf.rst
- docs/source/learn/user_guides.rst
- docs/source/learn/user_guides/remote_cluster_execution.rst
- docs/source/learn/user_guides/udf.rst
* Fix broken UDF docs codeblocks
* imports polars_udf on the toplevel daft package
* Adds new documentation for how to connect to a Ray cluster
> Update Daft documentation for UDFs and remote execution

- benchmarking/tpch/answers.py
- daft/dataframe/dataframe.py
- daft/execution/logical_op_runners.py
- daft/internal/kernels/memory_view.h
- daft/internal/kernels/search_sorted.cc
- daft/internal/kernels/search_sorted.h
- daft/internal/kernels/search_sorted.pyx
- daft/logical/logical_plan.py
- daft/runners/blocks.py
- daft/runners/partitioning.py
- daft/runners/shuffle_ops.py
- tests/dataframe_cookbook/test_sorting.py
- tests/internal/test_search_sorted.py
- tests/runners/test_partitioning.py
- tests/stress_tests/test_tpch.py
* Implements Arrow Table multicolumn Search Sorted needed for multicolumn partitioning
* Drops np quantile for vPartition Level one. Should be able to handle NULLs.
* Enables multiblock search sorted for vPartition
* Enabled DataFrame sort where multiple columns can be sorted with `desc` set for each of them.
* TPCH queries now don't depend on pandas for multi value sorting
> Multi-column DataFrame sorting

- daft/experimental/schema.py
- daft/internal/kernels/search_sorted.cc
- daft/runners/blocks.py
- poetry.lock
- pyproject.toml
- tests/experimental/test_schema.py
* Drops min arrow version to 6.0
* have to use newer version of icebridge also with arrow downgrade
* Uses polars for grouped aggregations
* fixes for experimental daft schema for older version of arrow (no `to_pylist`)
> Downgrade minimum Arrow version to 6.0

- daft/dataframe/dataframe.py
- tests/dataframe_cookbook/test_dataloading.py
* Loads each file's metadata as one row. File metadata consists of name, size and anything else the underlying filesystem provides when we list files.
NOTE: File listing is potentially a very slow operation, and users should manually chunk (zip files up) where possible. Exploding zipped files into one file per row in the future could be a pretty useful operation!
> Add `DataFrame.from_files` function

- daft/dataframe/dataframe.py
- daft/logical/logical_plan.py
- daft/logical/optimizer.py
- daft/logical/schema.py
- tests/dataframe_cookbook/test_computations.py
* `df.with_column("foo", ...)` now works even if `"foo"` is an existing column - it overrides the existing column in the dataframe
> Allow .with_column to override an existing column name

- daft/expressions.py
- daft/runners/blocks.py
- tests/dataframe_cookbook/test_python_list_cols.py
* Instead of using the expression types for deciding which OperatorEvaluator to use, we use the runtime type of the block. This ensures that we will select the most efficient and correct kernel to use, even if our typing system is wrong
For instance, running `col("foo").as_py(Foo).name.str.contains("bar")` will fail, even if all the Foo objects actually do contain a string name.
> Fix ExpressionExecutor eval's dispatching of OperatorEvaluator

- benchmarking/tpch/__main__.py
Adds a --skip_questions flag in TPC-H benchmarking script for skipping questions
* Example usage: `python benchmarking/tpch/__main__.py --skip_questions 9 --skip_questions 10 ...`
> Skip questions flag for TPC-H benchmarking

- docs/source/release_notes.rst
- docs/source/release_notes/0.0.13.rst
- pyproject.toml
* v0.0.12 was yanked from PyPi due to some build issues
* Docs are updated to start the changelog at 0.0.13 instead
> Update docs to reflect yanked 0.0.12 version

- daft/dataframe/dataframe.py
- daft/logical/logical_plan.py
- tests/dataframe_cookbook/test_explodes.py
* When `.explode()` is followed by a `.select` which selects a subset of columns, the optimizer goes into an infinite loop
* This was caused by an error in the `Explode` LogicalPlan, which created a new CallExpression on every initialization
> Fix explode column pruning optimizer bug

- daft/dataframe/dataframe.py
- daft/execution/operators.py
- daft/runners/blocks.py
- tests/dataframe_cookbook/test_aggregations.py
* Enables `agg` method on DataFrame which allows for mixed aggregation without groups
* Enables min/max aggregation on other dtypes besides numeric
* Introduces Bug with min/max on string in a grouped aggregation. Must push a fix to Polars
* adds min/max syntactic sugar to DataFrame and GroupedDataFrame
> DataFrame Global Aggs API

- daft/dataframe/dataframe.py
- tests/dataframe/test_creation.py
- tests/dataframe/test_filter.py
- tests/dataframe/test_projection.py
- tests/dataframe/test_scan.py
* Allows for getitem selection from a DataFrame
`df['foo', 'bar']` to subselect columns as well as `df[0,1] or df[::-1]` 
* adds a column and column names property [changes method for column names to property]
> GetItem semantic to select from DataFrame

- daft/runners/blocks.py
- tests/conftest.py
- tests/dataframe_cookbook/test_filter.py
- tests/null_tests/test_aggregations.py
* Fix issue in `merge_blocks` where merging empty blocks would throw an error because we do not properly propagate the block types
* Fix global sum when all values are null in a partition, to return 0 instead of null
* Fix groupby count to properly return number of non-null rows instead of a count of all rows
> Fixes and unit tests for aggregations on null items

- daft/experimental/schema.py
- daft/internal/kernels/hashing.cc
- daft/internal/kernels/memory_view.h
- daft/internal/kernels/search_sorted.cc
- tests/internal/test_search_sorted.py
* Fixes bug when running search sorted on a memory view
* This is due to inconsistent behavior for `GetValues` in Arrow.
* Rename Primative -> Primitive
> Search Sorted Offset Fix for Arrow Views

- pyproject.toml
The latest Polars release will break on import if `backports.zoneinfo` is not installed in Python < 3.9. We have to install it with the extras `["timezone"]` specified.
> Install polars with extra dependencies ["timezone"]

- docs/source/release_notes.rst
- docs/source/release_notes/0.0.16.rst
- poetry.lock
- pyproject.toml
0.0.15 was partially uploaded and failed to build wheels for Python versions 3.7/3.8. This PR fixes the issues (caused by a failure to update the lock file) and updates documentation to reflect the yanked 0.0.15 version.
> 0.0.16 release with fix for dependency lock file

- daft/execution/logical_op_runners.py
* Falls back onto Arrow's PyFileSystem with FSSpecHandler support when an HTTP URL is supplied
* Caches locally with fsspec's SimpleCacheFileSystem
> Add HTTP URL handling for DataFrame.from_parquet

- daft/runners/partitioning.py
- daft/runners/shuffle_ops.py
- tests/runners/test_partitioning.py
Quantile computations are wrong if the number of partitions >> the number of samples points, causing segfaults when we index outside of the array's bounds
> Fix quantile calculations in sort

- daft/logical/logical_plan.py
* This yields a speedup for tpch q5 and q9 over the over way
> Change min(left, right) to max(left, right) for join partitioning

- daft/context.py
- daft/dataframe/dataframe.py
- daft/execution/logical_op_runners.py
- daft/filesystem.py
When scanning remote files, we use a simple disk-based cache that will cache whole files as they are read.
The location of this cache can be controlled with either the `DAFT_CACHE` environment variable, or with `daft.context.set_daft_cache` at runtime. The cache can be disabled by setting either `DAFT_CACHE=` or `daft.context.set_daft_cache(None)`.
> Use a simple disk-based cache for remote file scans

- .github/workflows/ray-compatibility.yml
- poetry.lock
- pyproject.toml
Closes #336 
Ray versions before 1.10.0 do not have the kwarg `@ray.remote(scheduling_strategy="SPREAD")` which we use in the reduce phase for our shuffle operations.
Moreover, Ray documentation for versions below 1.11.0 is hard to find. Thus we are pinning Daft to  ray>=1.10.0
> Pin Daft requirements to Ray >= 1.10.0

- .github/workflows/python-publish.yml
* Fixes for poetry versioning for daft python package building
* enable cron schedule for nightly publishing to https://anaconda.org/daft-nightly/getdaft
* enable tagged version publishing to https://anaconda.org/daft/getdaft
> Fixes for anaconda publishing and enable CRON publishing

- .github/workflows/python-publish.yml
* Perform git deep clone for tag up rather than a shallow clone.
> Daft nightly fix -- add correct git clone for tag pickup

- daft/logical/logical_plan.py
* Drop use of backspace character which causes wrong rendering in a notebook as seen in https://github.com/jupyter/notebook/issues/5381
* fixes https://github.com/Eventual-Inc/Daft/issues/360
> Drop use of backspace to render explain correctly in notebook

- .github/workflows/python-publish.yml
- Cargo.lock
- Cargo.toml
- ci/upload_wheels.sh
- pyproject.toml
- tools/patch_package_version.py
* Use maturin instead of cibuilwheel to build prod wheels
* Use abi3 wheels instead of specific version ones
* Custom script to patch Cargo version for wheel version
> Rust Wheel Publishing to PYPI and Anaconda Nightly

- daft/dataframe/dataframe.py
* Since ray is an optional dep, this should not be in the top level which causes import problems when not installed
> move RayPartitionSet import out of DataFrame top level and into ray_dataset_conversion

- pyproject.toml
* boto is currently not used anywhere outside of serving rn
> drop boto from aws extras; 

- .github/workflows/python-publish.yml
* Pip is having an issue picking up some of our wheels due the manylinux compatibility
> [Rust wheel publish] Set manylinux version to auto for max compatibility

- pyproject.toml
- requirements-dev.txt
* Numpy 1.24 has new behavior for np.split when dealing with list[np.ndarray]. Pin to a lower version until we factor it out
> Pin numpy < 1.24 to avoid partition bug for pylist

- daft/dataframe/dataframe.py
- daft/runners/partitioning.py
Fixes a bug introduced in the Ray runner where column IDs were coming into conflict due to schema inference happening in Ray workers instead of locally.
> Fix schema inferencing column ID conflicts on RayRunner

- .github/workflows/python-publish.yml
- docs/source/docs/release_notes/0.0.20.rst
Publishing is currently failing on a missing `twine` package
> Add twine install to publishing steps

- .github/workflows/python-publish.yml
1. Build Daft with `DAFT_PKG_BUILD_TYPE=release` environment variable on release builds (with `v*` tags)
2. Build Daft with `DAFT_PKG_BUILD_TYPE=nightly` environment variable on other builds
> Add DAFT_PKG_BUILD_TYPE to python-publish CI job

- .github/workflows/python-publish.yml
- src/lib.rs
The maturin build tool that we use corner-cases certain environment variable prefixes to be forwarded into the Docker container that is uses for building: https://github.com/PyO3/maturin-action/blob/main/src/index.ts#L507-L512
Here we change our environment variable to be prefixed with `RUST*` to circumvent this.
> Change envvar DAFT_PKG_BUILD_TYPE to RUST_DAFT_PKG_BUILD_TYPE

- daft/analytics.py
- docs/source/docs/telemetry.rst
- tests/test_analytics.py
- Remove daemon thread
- Use an in-memory list as a buffer, and flush events from the main thread
> Simplify Analytics Client to single-threaded implementation

- requirements-dev.txt
- tests/conftest.py
- tests/dataframe_cookbook/test_pandas_cookbook.py
- tests/stress_tests/test_tpch.py
- Removes Sentry (#435)
- Cleans up Pandas cookbook tests: enables tests that Daft can now handle and skips the rest with a `.skip` instead of a `tdd` flag
> Cookbook test cleanups

- daft/runners/partitioning.py
- tests/test_viz.py
Closes #447 
Bug introduced by https://github.com/Eventual-Inc/Daft/pull/299/files#diff-8ce570b3f2f114483c776e449047082aaebf681b7f965f8ec989d12337a421bdR210-R214 which would skip evaluation of aliases because AliasExpressions have the same ID as its children nodes.
Add a test and fix for this bug
> Fix alias evaluation

- pyproject.toml
* right now the quickstart notebooks breaks on importing `aiobotocore` when doing the read_json call. 
* @jaychia
> add http to fsspec package

- tools/patch_package_version.py
* Prepends 0s to dev version to ensure pip installs the right one.
> Daft nightly publishing prepend 0s to dev version to fix pip lexical ordering

- pyproject.toml
- requirements-dev.txt
- tests/benchmarks/test_aggregations.py
* Adds pytest benchmarking to run regression suites which is disabled by default in pyproject.toml
* To run benchmarks: run `pytest --benchmark-only` which will yield an output like:
* to produce a json report run: `pytest --benchmark-only --benchmark-json=out.json`
Which looks like:
> Add pytest benchmarking for benchmark suites with a simple agg test

- .github/workflows/docs-github-pages-publish.yml
- .github/workflows/notebook-checker.yml
- .github/workflows/python-package.yml
- .github/workflows/python-publish.yml
- .github/workflows/ray-compatibility.yml
Disables telemetry in CI jobs with the `DAFT_ANALYTICS_ENABLED=0` environment flag
> Disable telemetry in CI jobs

- daft/dataframe/dataframe.py
- daft/filesystem.py
- daft/runners/partitioning.py
- daft/runners/pyrunner.py
- daft/runners/ray_runner.py
- docs/source/docs/api_docs/dataframe.rst
- docs/source/docs/api_docs/dataframe_methods/daft.DataFrame.from_files.rst
- docs/source/docs/api_docs/dataframe_methods/daft.DataFrame.from_glob_path.rst
- docs/source/docs/api_docs/dataframe_methods/daft.DataFrame.rst
- docs/source/docs/learn/10-min.ipynb
- tests/dataframe_cookbook/test_dataloading.py
- tutorials/image_querying/top_n_red_color.ipynb
* Adds a new `DataFrame.from_glob_path` method
* New method returns a dataframe with 3 columns only: path, size and type
* New method runs file globbing operations inside of the runner instead of on the driver
* Deprecates the old `DataFrame.from_files` method in favor of `DataFrame.from_glob_path`
Closes #426
> Add DataFrame.from_glob_path, deprecating DataFrame.from_files

- daft/filesystem.py
Closes #503 
We may require a less "magical" solution by allowing users to specify AWS configurations for things such as:
1. Passing in `requester_pays=True` to allow usage of buckets that are set to requester paying for accesses
2. Passing in custom credentials that should be used for accessing data, instead of inheriting from the environment
> Add custom handling of s3 filesystem creation when no credentials are found

- daft/execution/logical_op_runners.py
- daft/runners/partitioning.py
- tests/dataframe_cookbook/test_sorting.py
- tests/runners/test_partitioning.py
* #299 fixes sorts by avoiding recomputations on Expressions that have IDs that already exist in the current vPartition
* However, moving forward Expressions will be ID-less
* This PR fixes sorts in a different way, no-opping expression evaluation in `quantile_reduce_func` during sort sampling
> Fixes #299 to work without relying on expression IDs

- pyproject.toml
Polars issue https://github.com/pola-rs/polars/issues/6584 is currently breaking our local aggregations. We pin our polars version here temporarily until this is fixed.
> Pin polars to versions <= 0.15.18 due to issue #6584

- daft/execution/execution_step.py
- daft/execution/logical_op_runners.py
- daft/logical/logical_plan.py
- daft/runners/partitioning.py
- tests/dataframe_cookbook/test_joins.py
Fixes bug in self join where we get a key error when we join two dataframes that have name conflict for the non join keys
```
daft_df = daft_df.select(col("Unique Key"), col("Borough"))
daft_df = daft_df.join(daft_df, col("Unique Key"))
```
would yield:
```
/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/daft/runners/partitioning.py in eval_expression(self, expr)
198         required_blocks = {}
199         for name in required_cols:
--> 200             block = self.columns[name].block
201             required_blocks[name] = block
202         exec = ExpressionExecutor()
KeyError: 'right.Borough'
```
> Fix self join where column name can conflict

- daft/__init__.py
- daft/dataframe/dataframe.py
- daft/execution/logical_op_runners.py
- daft/expressions.py
- daft/logical/logical_plan.py
- daft/logical/map_partition_ops.py
- daft/logical/optimizer.py
- daft/resource_request.py
- daft/runners/pyrunner.py
- daft/runners/ray_runner.py
- daft/runners/shuffle_ops.py
- daft/udf.py
- docs/source/docs/learn/user_guides/udf.rst
- tests/logical/test_logical_plan.py
- tests/test_resource_requests.py
- tutorials/image_querying/top_n_red_color.ipynb
- tutorials/text_to_image/text_to_image_generation.ipynb
- tutorials/text_to_image/using_cloud_with_ray.ipynb
1. Expressions no longer have an associated `.resource_request()` function, only LogicalPlans.
2. `@udf(...)` no longer allows users to specify resource requests in the UDF
3. The only DataFrame method that allows for custom resource requests is `.with_column("x", expr, resource_request=...)`
> Refactor resource requests out of Expressions

- daft/expressions.py
- tests/dataframe/test_filter.py
> Fix Expression input_mapping query optimization bug

- .github/workflows/property-based-tests.yml
The Ray runner is too slow for the tight loops in property based testing, so we skip it
> Skip Ray runner tests in property based testing

- src/kernels/search_sorted.rs
- tests/internal/test_search_sorted.py
* Here we fix the behavior of nulls and nans in Search Sorted.
* fixed a bug for Nulls when sorting in reverse
* set ordering of nans to be `value < nan < null`
* fix bug when sorting in reverse that led to bisect left behavior rather than bisect right
> [bugfix] Fix Behavior in Search Sorted (Partitioning) for Nulls and NaNs

- src/kernels/search_sorted.rs
- tests/internal/test_search_sorted.py
* Fixes edge case for handling nulls when search sorted in reverse
> [bugfix] Fix bisect left behavior when search sorting in reverse for utf8 and numeric arrays

- .github/workflows/python-package.yml
* We can now publish rust code coverage from python tests
* I had to consolidate all the CI steps for building with maturin and pytest since github has weird handling of EnvVars
> [codecov] Enable Code Coverage for Rust From python tests

- tests/property_based_testing/strategies.py
- tests/property_based_testing/test_sort.py
* Fixes Hypothesis test to assert that nulls are "greater than" all values, regardless of sort ordering
* Modifies test to only run single-column sorts for now (see: issue #546)
* Enables `.repartition` and `.with_column` branches of the test
> Fix hypothesis test to assert that nulls greater than all values

- pyproject.toml
- requirements-dev.txt
Ray is having issues with the new `1.52.0` release of `grpcio`: https://github.com/ray-project/ray/issues/32246
We pin our version of grpcio as a temporary workaround.
> Fix Ray grpcio issues in CI

- daft/execution/execution_step.py
- daft/execution/physical_plan.py
- daft/execution/physical_plan_factory.py
- daft/runners/dynamic_runner.py
- daft/runners/ray_runner.py
1. `OpenExecutionQueue` -> `ExecutionStepBuilder`
2. `MaterializeResultBase` removed, its properties are promoted into `ExecutionStep`
3. `MaterializationRequest` -> `ExecutionStepSingle(ExecutionStep)`
4. `MaterializationRequestMulti` -> `ExecutionStepMulti(ExecutionStep)`
5. Added type alias `InProgressPhysicalPlan` which is an iterator that returns either `None | ExecutionStepBuilder | ExecutionStep` - we use this in the internals of physical_plan_factory when constructing the physical plan
6. Added type alias `MaterializedPhysicalPlan` which is a Generator that yields either `None | ExecutionStep` (cannot yield `ExecutionStepBuilder`) and stops with a `list[PartitionT]` - this is the final result that a client of physical_plan_factory will receive
Old inheritance hierarchy:
``` …
```
> Naming and class refactors for physical plan

- daft/dataframe/dataframe.py
- daft/execution/operators.py
- daft/logical/logical_plan.py
- daft/runners/partitioning.py
- tests/dataframe/test_creation.py
- tests/dataframe_cookbook/test_dataloading.py
- tests/dataframe_cookbook/test_explodes.py
- tests/null_tests/test_aggregations.py
- tests/null_tests/test_distinct.py
- tests/null_tests/test_joins.py
- tests/null_tests/test_sorts.py
* Refactors DataFrame.from_pydict to take in Python lists only, vastly simplifying the logic and helping testing
* Closes #507 - adds validation for `.from_pylist()`
* Adds validation for `.from_pydict()`
> Better testing and validation of DataFrame.from_py* constructors

- daft/__init__.py
- daft/series.py
- src/array/from.rs
- src/array/iterator.rs
- src/array/mod.rs
- src/array/ops/arange.rs
- src/array/ops/arithmetic.rs
- src/array/ops/comparison.rs
- src/array/ops/downcast.rs
- src/array/ops/mod.rs
- src/array/ops/take.rs
- src/datatypes/mod.rs
- src/dsl/arithmetic.rs
- src/dsl/expr.rs
- src/python/series.rs
- src/series/mod.rs
- src/series/ops/arithmetic.rs
- src/series/ops/comparision.rs
- src/series/ops/mod.rs
- src/series/ops/take.rs
- src/table/mod.rs
- tests/series/test_arithmetic.py
- tests/series/test_comparisions.py
- tests/series/test_series.py
* Implements Series in rust, pyo3 and Python
* Implements arange kernel for numerics
* Implements into_iter method
* Update arithmetic kernels for array to return a result instead of panicking
* Implement comparisons kernels for arrays [numeric, boolean, utf] via the DaftCompare Trait
* Downcast kernel for Boolean Array
* Depreciate "Divide" and now only have TrueDivide and FloorDivide
* Implement PySeries Methods for comparison and arithmetic operations 
* Provide access to Array kernels in Series via macros
* Implement Series in Python that wraps PySeries
* Testing for Series in Python that covers all the types for comparison and arithmetic operations as well as repr and creation methods like from_arrow and from_pylist
* repr method for Series using pretty table
> [rust] Series including kernels for comparisons, arithmetic and broadcasting, etc

- .pre-commit-config.yaml
CI's `isort` seems to be broken if any changes are made to the pre-commit config
> Fix style CI isort issue

- .github/workflows/python-package.yml
- daft/__init__.py
* init code coverage in daft init if we detect code coverage is being ran
* This should give us our code coverage for when we use the ray runner.
> Run code coverage per process to get better ray coverage

- daft/__init__.py
- daft/viz/__init__.py
- daft/viz/html_viz_hooks.py
- daft/viz/repr.py
- tests/dataframe/test_repr.py
* Visualization logic can be registered with Daft at runtime with `daft.viz.register_viz_hook`
* Refactors code for visualizing PIL and Numpy to now be registered with `register_viz_hook` at import-time of the module
> Refactor code to retrieve visualization logic from a registry

- daft/dataframe/dataframe.py
- daft/runners/partitioning.py
- daft/types.py
- tests/dataframe/test_creation.py
* Our hypothesis tests create data using Arrow arrays, so `.from_pydict()` needs to be able to accept Arrow arrays
* Our benchmarking tests create data using Numpy arrays, so `.from_pydict()` needs to be able to accept numpy arrays
> Allow for creation of DataFrames from numpy/Pyarrow arrays in .from_pydict

- daft/logical/logical_plan.py
- daft/runners/partitioning.py
- tests/dataframe_cookbook/test_pandas_cookbook.py
* Closes: https://github.com/Eventual-Inc/Daft/issues/442
* Fixes 2 bugs:
- When we join and left and right have different names but the same value
- in vPartition Join: when we are joining, we can clobber names from the left side with the right blocks.
> Fixes Joins when we have duplicate names from each source

- Cargo.toml
- daft/expressions2.py
- daft/table.py
- src/array/from.rs
- src/array/mod.rs
- src/array/ops/arithmetic.rs
- src/array/ops/take.rs
- src/datatypes/mod.rs
- src/dsl/expr.rs
- src/dsl/lit.rs
- src/python/expr.rs
- src/python/table.rs
- src/schema.rs
- src/series/mod.rs
- src/series/ops/arithmetic.rs
- src/series/ops/mod.rs
- src/series/ops/take.rs
- src/table/mod.rs
- tests/series/test_arithmetic.py
- tests/table/test_table.py
- tests/test_expressions2.py
* Python daft.expressions2.Expression: Replacement for daft expressions that are backed by rust
* Python: Daft.Table: a local Table Implementation backed by our rust table
* [rust + python] Series / Table take kernels
* [rust + python] Series / Table head kernels
* bugfix for series div that hit the add kernel instead
* handle the panic when we perform a `rem` kernel with a null on the `rhs` side
* Handle python bytes literals
* Test cases for making literals from python
* Add remaining comparisons to eval_expression for table
* Add Table::empty creator for easier debugging
* Allow renaming a series
> Rust Expressions / Table integration into Python

- daft/logical/logical_plan.py
- daft/runners/blocks.py
* drops np.split in favor an python list iteration due to numpy trying to coerce as_array methods to np
* reduce more types in pretty printer to ensure 80 character printing
> Drop numpy split for pylist block and enhance pretty printing for explain()

- daft/dataframe/dataframe.py
- tests/dataframe/test_show.py
Closes: #607 
* Set show to default to showing 8 rows
* Refactor to simplify logic and avoid multiple calls to limit the dataframe
> Set show to default to showing 8 rows

- daft/dataframe/dataframe.py
- daft/logical/aggregation_plan_builder.py
- tests/dataframe_cookbook/test_aggregations.py
Our previous aggregation logic was getting hard to work with, entirely contained within the DataFrame `._agg` method.
This refactor cleans up the code and introduces a `AggregationPlanBuilder` builder class. This will help us introduce more complicated aggregations soon (count_distinct, count_keys etc).
> Refactor aggregation logic into a AggregationPlanBuilder class

- daft/dataframe/dataframe.py
- daft/expressions.py
- daft/udf.py
- daft/udf_library/url_udfs.py
- docs/source/learn/10-min.ipynb
- docs/source/learn/user_guides/udf.rst
- tests/dataframe_cookbook/test_literals.py
- tests/dataframe_cookbook/test_python_list_cols.py
- tests/dataframe_cookbook/test_udf.py
- tests/expression_operators/test_cast.py
- tests/expression_operators/test_udf.py
- tests/property_based_testing/test_sort.py
- tests/test_resource_requests.py
- tutorials/image_querying/top_n_red_color.ipynb
- tutorials/mnist.ipynb
- tutorials/text_to_image/text_to_image_generation.ipynb
Closes #591 
* Remove type annotation inference from UDFs
* Rename `return_type=` to `return_dtype=`
* Rename `type_hints=` to `input_columns=` and make this non-optional
* Update documentation
* UDF invocation will fail if parameters marked as columns are not called on Expressions
> Remove type annotation inference from UDFs

- daft/__init__.py
- daft/udf.py
- daft/udf_library/url_udfs.py
* UDF class has a `.func` convenience accessor to access the underlying function. Users can now access a function they wrapped with `@udf` simply by calling `f.func(...)` and use it normally
* Removes `@polars_udf`
> Refactor @udf to return a UDF class instead of wrapped functions

- daft/dataframe/dataframe.py
- daft/execution/execution_step.py
- daft/execution/logical_op_runners.py
- daft/execution/physical_plan.py
- daft/execution/physical_plan_factory.py
- daft/runners/partitioning.py
- daft/runners/pyrunner.py
- daft/runners/ray_runner.py
- daft/runners/shuffle_ops.py
- tests/runners/test_partitioning.py
* We don't actually use `.partition_id` anywhere
* Removing it makes transitioning over from `vPartition -> Table` much easier since they now map 1:1
> Remove partition_id from vPartition

- daft/dataframe/dataframe.py
- daft/execution/execution_step.py
- daft/runners/partitioning.py
- daft/runners/pyrunner.py
- daft/runners/ray_runner.py
- tests/dataframe/test_creation.py
Refactor `.from_pydict()` such that schema inference is performed from inside the function, rather than provided as an external argument.
> Refactor .from_pydict() to infer schema in the method

- daft/logical/schema2.py
- daft/table.py
- src/python/mod.rs
- src/python/schema.rs
- src/python/table.rs
- src/schema.rs
- src/table/mod.rs
- tests/logical/test_schema2.py
Adds a `schema2.py` which includes Rust bindings for schema
> Add Rust bindings for Schema

- daft/expressions.py
- daft/logical/logical_plan.py
- daft/logical/map_partition_ops.py
- daft/logical/schema.py
- daft/logical/schema2.py
- daft/runners/partitioning.py
- src/python/schema.rs
- tests/logical/test_logical_plan.py
- tests/logical/test_schema2.py
`Schema()` is currently initialized with `Fields` in its `__init__`. However, in `schema2.py` this will no longer be allowed since the new schemas are Rust datastructures.
This refactor changes all locations where we do this intialization to a call to `Schema._from_field_name_and_types` instead, which takes in a simple Python list of tuples, so that integration will be easier.
> Refactor Schema initialization in the codebase

- daft/dataframe/dataframe.py
- daft/expressions.py
- daft/expressions2.py
- daft/logical/logical_plan.py
- daft/logical/map_partition_ops.py
- daft/logical/schema.py
- daft/logical/schema2.py
- daft/table.py
- tests/logical/test_schema2.py
- tests/test_expressions_projection.py
* Add `ExpressionsProjection` abstraction to `expressions2.py` to replace `ExpressionList`
* Some other minor refactors as well to facilitate this:
* We had a circular dependency in `.to_schema()` in ExpressionList. This has been refactored and moved into `Schema.resolve_expressions()` such that Schema has a dependency on Expressions, but not the other way around.
* Simplify the `ExpressionList.union()` function and remove the `other_override` kwarg. The client has to do this themselves now.
> Add ExpressionsProjection to replace ExpressionList

- daft/dataframe/dataframe.py
- daft/expressions.py
- daft/expressions2.py
- daft/logical/logical_plan.py
- daft/logical/map_partition_ops.py
- daft/logical/schema.py
- daft/runners/partitioning.py
- tests/test_expressions_projection.py
* Refactors all usage of `ExpressionList.exprs` to instead iterate and create a list, and make the `.exprs` a private var
* Refactors all usage of `ExpressionList.exprs[idx/slice]` to instead use `ExpressionList.__getitem__`
* Refactors all usage of `Schema.fields` to instead use `Schema.__iter__` for accessing fields
> Expressions and Schema refactors for v2 compatibility

- daft/dataframe/dataframe.py
- daft/runners/partitioning.py
- daft/runners/pyrunner.py
- daft/runners/ray_runner.py
- daft/runners/runner.py
- daft/runners/runner_io.py
* Refactors `PartitionSetFactory` into `RunnerIO`, which is responsible for executing code on the Runner (Py or Ray) that performs I/O outside of the DataFrame API
* The two use-cases right now are: 
* `glob_paths_details`: subsumes functionality from `PartitionSetFactory` to list filepaths and details about those files
* `get_schema_from_first_filepath`: samples Schema objects from filepaths
> Runner IO code

- daft/datatype.py
- daft/expressions2/expressions.py
- daft/logical/schema2.py
- daft/table.py
- daft/table_io.py
This PR tags our code with areas that need to be implemented to run our TPC-H queries on our Rust backend, as well as adding more Expression APIs to allow us to do so.
Tags:
1. `[RUST-INT][TPCH]`: required functionality for running TPC-H tests
2. `[RUST-INT][PY]`: functionality relating to Python types
3. `[RUST-INT][UDF]`: functionality relating to UDFs
4. `[RUST-INT][NESTED]`: functionality relating to nested types (e.g. explodes)
5. `[RUST-INT]`: other functionality that is nice to have and rounds out our Expressions API
> Add more Rust python binding requirements for TPC-H

- daft/dataframe/dataframe.py
- daft/execution/execution_step.py
- daft/experimental/serving/endpoint.py
- daft/expressions.py
- daft/expressions2/expressions.py
- daft/logical/aggregation_plan_builder.py
- daft/logical/logical_plan.py
- daft/logical/map_partition_ops.py
- daft/logical/optimizer.py
- daft/logical/schema.py
- daft/logical/schema2.py
- src/python/expr.rs
- src/python/field.rs
- src/python/mod.rs
- src/python/schema.rs
- tests/experimental/test_serving.py
- tests/logical/test_logical_plan.py
- tests/logical/test_schema2.py
- tests/optimizer/test_pushdown_predicates.py
- tests/runners/test_partitioning.py
- tests/test_expressions_projection.py
* Fixes a circular dependency between schema.py and expressions.py - we now follow the semantics in our Rust code, Expressions depends on Schema but not the other way around
* Adds `ExpressionsProjection.resolve_schema` functionality, leveraging our underlying Rust `Expr`'s `.to_field(schema)`.
> Add resolve_schema functionality to expressions2

- daft/series.py
- daft/table.py
- src/array/ops/len.rs
- src/python/series.rs
- src/python/table.rs
- src/series/mod.rs
- src/series/ops/len.rs
- src/series/ops/mod.rs
- src/table/mod.rs
- tests/series/test_series.py
- tests/table/test_table.py
* Adds `size_byte` which gives the min number of bytes a table or series requires in memory
> [rust] size_bytes for Table and Series

- .github/workflows/python-package.yml
- Cargo.lock
- daft/series.py
- daft/table/table.py
- src/array/from.rs
- src/array/ops/mod.rs
- src/array/ops/pairwise.rs
- src/array/ops/search_sorted.rs
- src/python/table.rs
- src/schema.rs
- src/series/ops/arithmetic.rs
- src/series/ops/broadcast.rs
- src/series/ops/mod.rs
- src/series/ops/search_sorted.rs
- src/table/mod.rs
- src/table/ops/hash.rs
- src/table/ops/joins/naive_join.rs
- src/table/ops/mod.rs
- src/table/ops/partition.rs
- src/table/ops/search_sorted.rs
- tests/series/test_arithmetic.py
- tests/series/test_comparisions.py
- tests/table/test_partitioning.py
* Enables Partitioning a Table by Hash, Random, or by Range (with boundaries)
* enabled search sorted for series and table (internal only for now)
* Adds `from` for DataArray from a Vec
* Raise a TypeError when having the wrong type in python instead of ValueError
> [rust] Partitioning Ops (Hash, Random, Range)

- daft/table/table.py
* When we create Tables from PyArrow tables, we can only handle one batch at the moment
* This causes some issues when running our TPC-H unit tests, ostensibly because the parquet files define multiple Parquet row groups
* This PR adds a temporary fix to unblock running our new Rust code on TPC-H by calling to `.combine_chunks()` before creating the table so that we only have one batch
> Unblocking [RUST-INT][TPCH]: Add a call to .combine_chunks() when creating a Table from arrow

- src/array/ops/sort.rs
- tests/table/test_table.py
* Fixes bug when sorting multiple keys with string first. 
* Issue was using .values() on the arrow array which returns a Buffer of the string characters rather than the &str
> [rust] String multikey sorting bug fix

- daft/runners/partitioning.py
- daft/runners/runner_io.py
- tests/runners/test_partitioning.py
* Change Parquet schema inference to use 0 rows
* Schema inference logic is then changed to use the inferred schema from the Arrow schema rather than from the parsed data
> Fix schema inference of reads from Parquet and empty vPartitions

- daft/expressions2/expressions.py
- daft/series.py
- src/array/ops/mod.rs
- src/array/ops/utf8.rs
- src/datatypes/dtype.rs
- src/dsl/functions/mod.rs
- src/dsl/functions/utf8/endswith.rs
- src/dsl/functions/utf8/mod.rs
- src/kernels/utf8.rs
- src/python/expr.rs
- src/python/series.rs
- src/series/ops/mod.rs
- src/series/ops/utf8.rs
- tests/series/test_utf8.py
- tests/table/utf8/test_endswith.py
- tests/test_runtime_matches_static_types.py
1. Adds a `.utf8_endswith` kernel to Series + unit tests on the Series level
2. Adds a `.str.endswith` to Expressions + quick unit test on the Table for some corner-cases (using `lit` vs `"foo"` vs `Expression` as the pattern)
3. Checks type resolution logic by adding to the tests into our `test_runtime_matches_static_types.py` test
> Add endswith kernel to Series

- src/dsl/functions/numeric/abs.rs
- src/dsl/functions/utf8/endswith.rs
SchemaMismatch error should be thrown only at schema-resolving-time.
> Use ValueError instead of SchemaMismatch in FunctionExpr evaluation

- src/dsl/expr.rs
- src/dsl/functions/utf8/endswith.rs
- src/error.rs
* ExprResolveTypeError is too complicated and difficult to use, slowing down kernel development velocity
* This PR removes ExprResolveTypeError, but we open a new issue for better expression schema resolution errors
> Remove ExprResolveTypeError in favor of a plain TypeError

- daft/logical/logical_plan.py
* The new `DataType` implementations don't implement `__hash__`
* This fix helps integration with the new DataTypes in Rust
> Remove use of ExpressionType.__hash__ in logicalplan

- daft/dataframe/dataframe.py
- daft/runners/ray_runner.py
- daft/types.py
- tests/ray/test_datasets.py
Adds an API to create a DataFrame from a Ray dataset. This is useful when using Daft together with Ray, to allow for analysis of experimental results (e.g. an output Dataset from running evaluation-during-training).
> Add DataFrame.from_ray_dataset

- src/python/series.rs
- src/python/table.rs
- src/series/ops/len.rs
- src/table/mod.rs
- tests/series/test_series.py
* `.size_bytes` currently panics if run on logical types (e.g. dates)
* This PR fixes that behavior by first casting into a Physical type
> Fix size_bytes for logical types

- src/array/ops/arithmetic.rs
- src/series/ops/arithmetic.rs
- src/table/mod.rs
- tests/series/test_arithmetic.py
* When broadcasting, series arithmetic logic is wrong when assigning names to the resulting series
* In general, it seems to be a bad idea to have `name()` be an array-level attribute, because of the potential mismatch in naming logic between `to_field()` and `evaluate()`. This is just one example of a place where this may cause errors.
> Fix Series arithmetic naming logic

- daft/context.py
* Currently, if users call `set_runner_ray(...)` more than once per process, they will incur a RuntimeError. The intention here is to be very explicit that this behavior is not encouraged, as setting the runner more than once can potentially corrupt the state of Daft's caching.
* This PR adds a kwarg `noop_if_initialized`. If set to `True`, subsequent calls to `set_runner_ray` are ignored and have no effect. We log a warning when this happens.
> Ignore multiple calls to set_runner_ray with kwarg noop_if_initialized

- daft/expressions2/expressions.py
- daft/series.py
- src/array/ops/if_else.rs
- src/array/ops/mod.rs
- src/dsl/expr.rs
- src/python/expr.rs
- src/python/series.rs
- src/series/ops/if_else.rs
- src/series/ops/mod.rs
- src/table/mod.rs
- tests/series/test_if_else.py
- tests/table/test_table.py
Adds an `if_else` kernel that works with only numeric arrays and utf8 arrays for now
* Note that on the Rust series/array level, the syntax is: `if_true.if_else(if_false, predicate)` because we can use the static type of `if_true` to determine what kernel to dispatch
* However, on the Python series/expression level, the syntax is: `predicate.if_else(if_true, if_false)` because this is the current API. Under the hood we re-order the arguments when calling into Rust
> Add if_else kernel to Series

- daft/expressions2/expressions.py
* `if_else` fails if the input arguments are literals
* This PR adds a fix by running `Expression._to_expression` on its inputs before running
> Convert input arguments in if_else to Expressions

- daft/expressions2/expressions.py
- src/dsl/mod.rs
- src/dsl/optimization.rs
- src/python/expr.rs
* Implements expression methods that are used during query optimization
* It's a little annoying that we have to define logic to reconstruct every expression every single time. One possible optimization that can be made here is if we have each expression define a `.to_children` method which will return an ordered Vec of its children, and a `.from_children` which takes as input an ordered Vec of modified children. But that optimization is left as an exercise for another PR.
* Testing is performed in `tests/optimizer`, but does not run on `main` because `expressions2` is not yet integrated with main. All optimizer tests pass on our Rust integration branch.
> Add optimization functions to expressions

- .github/workflows/python-package.yml
* Currently `rust-main` runs CI twice because we have a PR open against `main`
* This PR disables running CI from main in `rust-main`
> [Rust] Disable CI checks for PRs against main from rust-main

- daft/runners/blocks.py
- daft/runners/ray_runner.py
- tests/ray/test_datasets.py
- tests/series/test_series.py
Ray compatibility tests are breaking due to multiple reasons which are fixed in this PR
1. Recent changes to our Ray Dataset integrations are incompatible with older versions of Ray, specifially around the Ray Dataset's ArrowTensor type, which does not seem to work for tensors of differing shapes prior to v2.2.0
2. The `Dataset.dataset_format()` API which we use in our unit tests was only made public in Ray versions >2.2.0
3. PyArrow `Array.nbytes` has differing behavior from v0.0.7 onwards. We rely on the new behavior for Series unit tests, so those tests have to be skipped when we are on PyArrow <0.0.7, which is the case for Ray <2.2.0 that has the PyArrow dependency pinned
> Fix Ray compatibility tests

- daft/dataframe/dataframe.py
- daft/expressions/expressions.py
https://github.com/Eventual-Inc/Daft/pull/731 added a dependency to dataframe.py on `Expression.is_nan`
This PR adds a stub implementation of `Expression.float.is_nan` for `rust-main` to type-check
> [RUST] Add stub code for Expression.float.is_nan

- src/array/ops/downcast.rs
- src/array/ops/if_else.rs
- src/array/ops/take.rs
- src/dsl/expr.rs
- src/series/ops/if_else.rs
- src/series/ops/mod.rs
- src/series/ops/take.rs
- tests/expressions/typing/test_if_else.py
- tests/series/test_if_else.py
- tests/series/test_series.py
- tests/series/test_take.py
* Previously, If/Else only worked for numeric and string types. Our tests and schema resolution code had blocks to skip types that were not supported
* This PR implements kernels for the other physical types and enables tests
> [Rust] If/Else kernel implementation for rest of physical types

- src/array/ops/take.rs
- src/dsl/expr.rs
- tests/expressions/typing/conftest.py
- tests/expressions/typing/test_arithmetic.py
* Designates binary types as "non-comparable" (see issue: #688)
* Makes binary types non-addable as well
> [RUST] Fix binary typing kernel tests

- src/array/ops/cast.rs
- src/array/ops/compare_agg.rs
- src/array/ops/downcast.rs
- src/series/ops/agg.rs
- src/series/ops/cast.rs
- src/series/ops/if_else.rs
- src/utils/supertype.rs
- tests/expressions/typing/conftest.py
- tests/table/test_table.py
* Adds custom logic for date casts, because Arrow doesn't like casting dates to many types
* Fixes our `Series.min/max` logic to cast to physical
* Fixes our `Series.if_else` logic to cast to physical
* Adds some more Date entries to our Supertype table, so that Dates are supertypeable with all numeric types
```
(Date, UInt8) => Some(Int64),
(Date, UInt16) => Some(Int64),
(Date, Int8) => Some(Int32),
(Date, Int16) => Some(Int32),
```
> [RUST] Activate tests for date types

- tests/benchmarks/test_join.py
- tests/benchmarks/test_sort.py
Add new join microbenchmarks.
Starts with a baseline of integer one-to-one joins.
Additionally evaluates the impact of:
- key size
- data size
- low cardinality LHS vs RHS
- single vs multicolumn
All tests include single and multi-partition.
Data scales chosen are sized to complete within 1 second.
Update: Added sort microbenchmarks as well, which evaluates similar dimensions to join.
---------
> New join and sort microbenchmarks (#758)

- tests/dataframe_cookbook/test_aggregations.py
- tests/expression_operators/test_datetime.py
* Pandas 2.0 landed on April 3 2023 which broke some tests
* The types in some datetime operations were changed from int64 to int32
* Indexing API for `df[c1, c2]` was deprecated, and we have to do `df[[c1, c2]]` now
> Add test fixes for Pandas 2.0

- daft/expressions/expressions.py
- daft/series.py
- src/array/ops/date.rs
- src/dsl/functions/temporal/day.rs
- src/dsl/functions/temporal/day_of_week.rs
- src/dsl/functions/temporal/mod.rs
- src/dsl/functions/temporal/month.rs
- src/dsl/functions/temporal/year.rs
- src/python/expr.rs
- src/python/series.rs
- src/series/ops/date.rs
- tests/expressions/test_expressions.py
- tests/expressions/typing/test_dt.py
- tests/series/test_temporal_ops.py
- tests/table/test_table.py
This PR adds the missing date kernels, `dt.month`, `dt.day`, and `dt.day_of_week`, to the Rust expression path.
This is the first of two PRs for https://github.com/Eventual-Inc/Daft/issues/759.
> [Missing Expression Kernels - 1/3] Add missing date kernels: `dt.month`, `dt.day`, and `dt.day_of_week`

- src/array/mod.rs
- src/array/ops/arrow2/comparison.rs
- src/array/ops/arrow2/mod.rs
- src/array/ops/mod.rs
- src/datatypes/dtype.rs
- src/datatypes/field.rs
- src/kernels/search_sorted.rs
- src/python/schema.rs
- src/python/table.rs
- src/schema.rs
- src/table/mod.rs
- src/table/ops/agg.rs
- src/table/ops/joins/hash_join.rs
- src/table/ops/joins/mod.rs
- src/table/ops/joins/naive_join.rs
- tests/table/test_joins.py
* Implements simple and naive hash joins for table which is upto 300x faster in some cases
* implements is_equal operator function since our other comparator assumes total ordering and can not parameterize if nulls and nans are equal
*  refactor agg grouper to use is_equal rather than old comparator
> [rust] Implement Hash Joins for table

- daft/execution/execution_step.py
- daft/table/table.py
- src/python/schema.rs
- src/python/table.rs
- src/table/mod.rs
Bug description:
* When a partitioning key contains all null or is empty, the computed boundaries used for range partitioning is empty
* This causes issues in our code which assumes N_OUTPUT_PARTITIONS number of partitions to be returned
This commit fixes this behavior by padding the results with empty tables, ensuring that we always return the number of partitions requested
> [RUST] Fix range partitioning for empty/all-null partition keys

- src/array/from.rs
- src/array/mod.rs
- src/array/ops/broadcast.rs
- src/array/ops/compare_agg.rs
- src/array/ops/count.rs
- src/array/ops/full.rs
- src/array/ops/if_else.rs
- src/array/ops/mean.rs
- src/array/ops/null.rs
- src/array/ops/sum.rs
* For DataArray use a Box to an Arrow Array over an Arc. This avoids another allocation since an Arc to a pointer to a rc and object as seen [here](https://docs.google.com/presentation/d/1q-c7UAyrUlM-eZyTo1pd8SZ0qwA_wYxmPZVOQkoDmH4/edit#slide=id.p).
* This results is about a 5% speed for large partition sizes
> [rust] Refactor base array arc to box

- daft/datatype.py
- src/datatypes/dtype.rs
- src/datatypes/field.rs
- src/python/datatype.rs
Allows hashing of DataTypes using the Rust `Hash` trait. This is useful when testing in Python and lets us use DataTypes as keys for dictionaries, put DataTypes into sets etc.
> [RUST] Hashing of DataTypes

- daft/expressions/expressions.py
- daft/series.py
- src/array/ops/float.rs
- src/array/ops/mod.rs
- src/array/ops/utf8.rs
- src/dsl/functions/float/is_nan.rs
- src/dsl/functions/float/mod.rs
- src/dsl/functions/mod.rs
- src/dsl/functions/utf8/contains.rs
- src/dsl/functions/utf8/endswith.rs
- src/dsl/functions/utf8/length.rs
- src/dsl/functions/utf8/mod.rs
- src/dsl/functions/utf8/startswith.rs
- src/python/expr.rs
- src/python/series.rs
- src/series/ops/float.rs
- src/series/ops/mod.rs
- src/series/ops/utf8.rs
- tests/expressions/test_expressions.py
- tests/expressions/typing/test_float.py
- tests/expressions/typing/test_str.py
- tests/series/test_float.py
- tests/series/test_utf8_ops.py
- tests/table/test_table.py
- tests/table/utf8/test_length.py
This PR adds the missing `str.length()`, `str.concat()`, and `float.is_nan()` kernels to the Rust expression path.
**Drivebys:** ports `to_field()` methods for `str.contains()`, `str.startswith()`, and `str.endswith()` to structural matching.
This PR is the second of two PRs, a follow-up for: https://github.com/Eventual-Inc/Daft/pull/771
Closes https://github.com/Eventual-Inc/Daft/issues/759
> [Missing Expression Kernels - 2/2] Add missing `str.length()`, `str.concat()`, and `float.is_nan()` kernels.

- tests/table/test_table.py
Noticed this while working on the expressions PR, going to let the CI run to make sure the test passes.
> [Hotfix] Add missing assert to `if_else` test.

- .github/workflows/daft-profiling.yml
- benchmarking/tpch/__main__.py
- requirements-dev.txt
* Produce a flamegraph using py-spy in CI which will only run post-merges to `rust-main`
* Uploads a speedscope output file which can be used at `https://www.speedscope.app/`
* Adds flag to benchmarking code to enable skipping warmup
which would look something like this:
> Enable Profiling of Daft on TPCH on rust-main

- src/dsl/expr.rs
- src/dsl/functions/float/is_nan.rs
- src/dsl/functions/utf8/contains.rs
- src/dsl/functions/utf8/endswith.rs
- src/dsl/functions/utf8/length.rs
- src/dsl/functions/utf8/startswith.rs
- src/table/mod.rs
Now that `Field` implements the `Display` trait, we should display Fields to the user using this trait instead of showing the Debug view
> [RUST] Change usage of Debug display of Fields to Display

- daft/datatype.py
- daft/table/table.py
- src/ffi.rs
- src/python/table.rs
- tests/table/test_table_io.py
* We observed that our calls to combine_chunks was 6% of time spent in TPC-H tests
* We previously called it twice, making that 12% of time spent
* This PR removes those calls, and instead uses `Table::concat` in Rust to combine rowgroups into one Table
NOTE: In the future, we can have chunked Tables which will make this operation even cheaper!
> [RUST] Remove extraneous calls to combine_chunks in favor of using Table::concat

- .github/workflows/python-package.yml
- Cargo.toml
- src/kernels/hashing.rs
- src/kernels/mod.rs
- src/kernels/search_sorted.rs
- src/lib.rs
Hides our Python functionality behind a `python` Cargo feature flag
1. All PyO3-related functionality should be localized to `src/python/**`
2. Deleted Python-related functionality in `src/kernels` which was dead code that we don't call anymore
3. Added compilation feature flags to avoid compiling Python-related modules where required
> [RUST] Python feature flag

- daft/internal/rule_runner.py
- daft/logical/optimizer.py
* Our new Rust Expression implementation is immutable, and hence we should remove our logic in our optimizer which relies on `deepcopy` to avoid mutating existing Expression objects
* Also note that `deepcopy` will incur a pickling of the underlying Rust expression, so this PR will eliminate this pickling behavior at query optimization time
> [RUST] Removes deepcopy usage in optimizer

- src/dsl/functions/python/partial_udf.rs
- tests/expressions/test_udf.py
* Fills in the PartialEq implementation for PartialUDF which allows for comparison of two UDFExpressions
> [RUST] Add PartialEq implementation for PartialUDF

- src/array/ops/arithmetic.rs
- src/array/ops/broadcast.rs
- src/array/ops/comparison.rs
- src/array/ops/filter.rs
- src/array/ops/full.rs
- src/array/ops/if_else.rs
- src/array/ops/utf8.rs
- src/dsl/lit.rs
- src/ffi.rs
- src/series/ops/arithmetic.rs
- src/series/ops/broadcast.rs
- src/series/ops/full.rs
- src/table/mod.rs
- tests/table/test_table_io.py
* Creation of tables from parquet/csv/json may pass in an Arrow array with type `List` instead of `LargeList` - we need to perform a cast at runtime to account for this
* Changes to `DataArray::full_null` and `DataArray::empty` to accept a `DataType` argument and construct the array using the `DataType` instead of the `DaftDataType`. This is required because `DaftDataType` doesn't contain the child-type information required to create the appropriate (null/empty) arrow arrays.
> [RUST] Fix creation of tables for list type

- tests/benchmarks/conftest.py
- tests/benchmarks/test_groups_and_aggs.py
* Adds string groupby benchmarks
* Changes delim in benchmarks to `-` and `:` so we can use `pytest -k`
> Add string grouping benchmarks

- src/array/ops/comparison.rs
- src/array/ops/if_else.rs
- src/utils/arrow.rs
- tests/series/test_if_else.py
Fixes bug in if_else kernel which would fail where the nulls in the predicate completely override nulls in the if_true/if_false arrays
> [RUST] Fix if_else kernel behaviour for None values.

- src/utils/arrow.rs
- tests/series/test_take.py
- tests/table/test_from_py.py
This PR fixes our coverage for recursive nested type casting when ingesting Arrow data into Daft, and adds some more test coverage thereof.
> [Nested Types] Fix array casting on ingest for nested types, add test coverage for nested type ingest.

- .github/workflows/daft-profiling.yml
* Bump timeout to 20 minutes
* Bump python version to 3.8
* Use dev-bench profile instead of custom -g flag
* set cpu-target to native
> [ci] Github Actions: Daft Profiling: increase timeout, bump python version and set target-cpu to native

- daft/dataframe/dataframe.py
- daft/runners/ray_runner.py
- daft/table/table.py
- docs/source/api_docs/dataframe.rst
- requirements-dev.txt
- tests/ray/test_dask.py
- tests/ray/test_datasets.py
This PR adds a Dask DataFrame integration, allowing for converting a Dask DataFrame to a Daft DataFrame:
```python
df = daft.DataFrame.from_dask_dataframe()
```
and for converting a Daft DataFrame to a Dask DataFrame:
```python
ddf = df.to_dask_dataframe()
```
This is currently only supported for the Ray runner; we could add support for converting a local Daft DataFrame to a local Dask DataFrame, and vice versa, in a future PR.
- Fix `daft.Table.to_pandas()` so it properly handles Python object columns.
- Raise `ValueError`s if a Ray runner isn't configured for the Ray Datasets integration rather than raising an `AssertionError`.
> [Integrations] Add Dask DataFrame integration.

- daft/dataframe/dataframe.py
- daft/runners/ray_runner.py
- daft/series.py
- daft/table/table.py
- docs/source/api_docs/dataframe.rst
- tests/dataframe/test_creation.py
- tests/ray/test_datasets.py
- tests/table/test_from_py.py
This PR adds `DataFrame.from_pandas()` and `DataFrame.from_arrow()`.
The fallback conversion strategy for `Table.from_pandas()` is as follows:
1. Try to convert the entire pandas DataFrame into an Arrow Table and go through the `Table.from_arrow()` route.
2. Convert the pandas DataFrame to a Python dict of `pd.Series`, and go through the the `Table.from_pydict()` path. For each column:
a. Try to convert the `pd.Series` directly to an Arrow Array.
b. Try to convert the `pd.Series` to a NumPy ndarray and go the `Series.from_numpy()` path.
c. Convert the `pd.Series` to a Python list and go the `Series.from_pylist()` path.
Overall, this should keep the happy path where the pandas DataFrame --> Arrow Table conversion works fast, then fall back to trying to convert each column to a form that …
> [Integrations] Add `from_pandas()` and `from_arrow()`.

- .pre-commit-config.yaml
- Makefile
- daft/execution/execution_step.py
- daft/internal/treenode.py
- daft/runners/partitioning.py
- pyproject.toml
- requirements-dev.txt
Output of a fresh `maturin develop`:
```
...
Installing collected packages: urllib3, tabulate, psutil, numpy, multidict, loguru, idna, fsspec, frozenlist, charset-normalizer, certifi, attrs, async-timeout, yarl, requests, pyarrow, aiosignal, aiohttp
```
Some notes:
1. I removed `pydot` as a dependency, and moved `import pydot` into our TreeNode visualization method. This means that this will fail if called at runtime - cc @samster25 to make sure this is fine?
2. `numpy` is still installed as a transitive dependency of pyarrow.
3. All of `aiohttp, aiosignal, async-timeout, attrs, certifi, charset-normalizer, frozenlist, idna, multidict, requests, urllib, yarl` are transitive dependencies of `fsspec[http]`. We can get rid of this only if we remove our dependency on fsspec.
If we remove the …
> Python requirements cleanup

- daft/datatype.py
- pyproject.toml
Problem 1: import of `ray.data.extensions` will fail if Ray is not installed (i.e. if Daft is installed without `[ray]`). This is solved by moving the import into a guarded import with a global boolean flag.
Problem 2: import of `ray.data.extensions` fails for Python versions < 3.10. See Ray issue: https://github.com/ray-project/ray/issues/34806
> Fix import of ray.data.extensions

- tests/dataframe/test_aggregations.py
- tests/dataframe/test_creation.py
- tests/dataframe/test_distinct.py
- tests/dataframe/test_joins.py
- tests/dataframe/test_to_integrations.py
- tests/utils.py
Pyarrow only introduced `pa.Table.sort_by` in PyArrow > 7.0
This PR adds a `tests.utils.sort_arrow_table` utility to replace all calls in our tests of `pa.Table.sort_by` for backward compatibility.
**Drive-by:**
Also fixes `test_create_dataframe_arrow` which uses `pa.Table.from_pylist` which is similarly not available in earlier versions of PyArrow.
> Fixes arrow table sorts for backward compatibility during testing

- daft/series.py
- tests/series/test_size_bytes.py
Fixes the testing logic for our size_bytes tests
Updated `Series.size_bytes` for correct description of its intended behavior:
> Returns the total sizes of all buffers used for representing this Series.
>
> In particular, this includes the:
>
> 1. Buffer(s) used for data (applies any slicing if that occurs!)
> 2. Buffer(s) used for offsets, if applicable (for variable-length arrow types)
> 3. Buffer(s) used for validity, if applicable (arrow can choose to omit the validity bitmask)
> 4. Recursively gets .size_bytes for any child arrays, if applicable (for nested types)
Also updated tests to reflect this behavior, including additional calculations in places that require it:
1. Any automatic casting of `list -> large_list`, `string -> large_string` etc requires adding additional bytes for …
> Fix size_bytes tests

- daft/io/parquet.py
- tutorials/image_querying/top_n_red_color.ipynb
* Fixes a bad call to DataFrame.from_glob_path in our tutorials
* Also fixes some stale documentation on `daft.read_parquet`
> Fix deprecated call to DataFrame.from_glob_path

- daft/datatype.py
- daft/logical/schema.py
- daft/runners/ray_runner.py
- daft/series.py
- daft/table/table.py
- tests/dataframe/test_creation.py
- tests/table/test_from_py.py
This PR adds an automatic fallback to the Python object type for unsupported Arrow types, such as `pa.timestamp()` and extension types, including the Ray Datasets tensor extension type.
> [Arrow Types] Add automatic Python object fallback for unsupported Arrow types.

- docs/source/10-min.ipynb
I was reading the 10 minute tutorial (very nice by the way) and came across this little typo. :+1:
> Fix typo: CSV -> Parquet

- daft/expressions/expressions.py
- daft/filesystem.py
- daft/udf_library/url_udfs.py
- tests/udf_library/test_url_udfs.py
* Adds a fix for URLs with multiple colons
* Adds a "strict" mode for `.url.download()` using the kwarg `on_error="raise"`. We default to this behavior now because the other behavior `"null"` could cause idempotency issues and unexpected user behavior.
* Fixes the try/catch block to be reduce its surface area - just to catch the `fsspec.cat_file` call
> Fix colon URL downloads and default to strict mode for .url.download()

- pyproject.toml
- tests/dataframe/test_temporals.py
* Only adds timestamp types for the `test_temporal_file_roundtrip` test if using a large enough PyArrow version (>=7.0.0)
* Pins `pyarrow >= 6.0.1` because we use a kwarg `existing_data_behavior="overwrite_or_ignore"` when writing data in `table_io.py`
> Fix temporal unit tests for older versions of pyarrow

- daft/table/table_io.py
1. This greatly speeds up file reads
2. However we lose the ability to push row limits into the read step for CSV and JSON, since PyArrow exposes no such functionality natively
> Use PyArrow filesystem for tabular file reads

- pyproject.toml
Daft uses some functionality from `tabulate==0.9.0` for limiting the maximum number of characters per row, and needs to pin the requirement
> Update requirement of tabulate to >=0.9.0

- Cargo.lock
- Cargo.toml
- daft/datatype.py
- daft/series.py
- src/array/ops/as_arrow.rs
- src/array/ops/cast.rs
- src/array/ops/filter.rs
- src/array/ops/if_else.rs
- src/array/ops/sort.rs
- src/array/ops/take.rs
- src/datatypes/dtype.rs
- src/datatypes/logical.rs
- src/datatypes/matching.rs
- src/datatypes/mod.rs
- src/dsl/expr.rs
- src/error.rs
- src/lib.rs
- src/python/datatype.rs
- src/python/mod.rs
- src/python/series.rs
- src/series/array_impl/logical_array.rs
- src/series/ops/list.rs
- src/table/ops/explode.rs
- tests/conftest.py
- tests/dataframe/test_creation.py
- tests/dataframe/test_logical_type.py
- tests/series/test_cast.py
- tests/series/test_embedding.py
* Enables Embedding Logical Type
* Enables running of extension types in Ray
* Enables LogicalType exports to ExtensionArrays and Back via Daft Super Types
* Enables Casts from python to [list, fixed_sized_list, embedding]
* Enables pyo3 logging for rust -> python logging
* Enables arr.lengths namespace for list like operations
> Extension Types for Ray Runner and Embedding Logical Type

- daft/series.py
- src/datatypes/dtype.rs
- tests/series/test_concat.py
- tests/table/test_from_py.py
* Fix `from_arrow` for Extension ChunkedArrays for pyarrow <= 7.0
* Fix tests for list dtype comparisions since it checks for the field name
> fix concats for extension array for old versions of pyarrow

- daft/__init__.py
- daft/filesystem.py
- daft/table/table_io.py
- tests/dataframe/test_creation.py
This PR ports to our filesystem inference to create `pyarrow` `FileSystem` instances by default, only falling back to fsspec if the URI protocol is not supported. We also change our reading narrow waist to be around pyarrow `NativeFile` handles.
> [I/O] Port to `pyarrow` filesystems by default.

- .github/workflows/python-publish.yml
* Fix for issue when trying to publish nightly wheel: https://github.com/Eventual-Inc/Daft/actions/runs/5053346792
> [ci] [daft publish] pin urllib to < 2 for conda

- tests/ray/test_datasets.py
Datasets partition ordering is now nondeterministic, so any tests that assert equality with some cross-partition ordering will need to sort or freeze the data before comparison. This PR applies the fix from https://github.com/Eventual-Inc/Daft/pull/917 (freezing) to the tensor test.
> [CI] Fix flaky Ray Datasets integration test.

- daft/__init__.py
- daft/daft.pyi
- daft/datatype.py
- requirements-dev.txt
- src/array/ops/as_arrow.rs
- src/array/ops/cast.rs
- src/array/ops/filter.rs
- src/array/ops/if_else.rs
- src/array/ops/sort.rs
- src/array/ops/take.rs
- src/datatypes/dtype.rs
- src/datatypes/image_mode.rs
- src/datatypes/logical.rs
- src/datatypes/matching.rs
- src/datatypes/mod.rs
- src/python/datatype.rs
- src/python/mod.rs
- src/series/array_impl/logical_array.rs
- src/series/ops/list.rs
- tests/dataframe/test_logical_type.py
- tests/series/test_cast.py
- tests/series/test_image.py
This PR adds a logical type for variable-shaped and fixed-shape images.
1. Create the egress-side for Daft --> Python, taking tensor-ish Daft logical types and representing those arrays as NumPy ndarrays in Python land.
2. Add image processing compute kernels.
3. Add imagery tutorial to the docs.
4. Expand Python --> ImageArray support.
> [Images] [1/N] Logical type for variable-shaped and fixed-shaped images.

- daft/datatype.py
- docs/source/api_docs/datatype.rst
- docs/source/api_docs/expressions.rst
- docs/source/api_docs/index.rst
- docs/source/learn/user_guides.rst
- docs/source/learn/user_guides/datatypes.rst
- docs/source/learn/user_guides/expressions.rst
Cleanups to the DataType userguide and API docs:
1. Adds DataType API docs where we autogenerate stubs for the DataType class
2. Cleanup the DataType userguide to be more of a walkthrough the main categories of DataTypes rather than just a list, and link to the DataType API docs where appropriate
> Clean up DataType userguide/API docs

- requirements-dev.txt
- src/array/from.rs
- src/array/ops/cast.rs
- src/array/ops/image.rs
- src/array/ops/mod.rs
- src/datatypes/image_mode.rs
- src/series/ops/image.rs
- tests/series/test_image.py
- tests/table/test_from_py.py
This PR adds basic support for decoding uint8 images.
> [Images] [3/N] Add image decoding for uint8 images.

- daft/internal/rule_runner.py
- tests/udf_library/test_url_udfs.py
During optimization, there are bugs that occur because we mutate the old plan when constructing the new plan
More testing needs to be performed to isolate a test-case where this is happening. It seems to be an issue related to aliasing of names and predicate pushdowns.
> Revert change to optimizer to perform deepcopy of logical plan

- src/array/ops/as_arrow.rs
- src/array/ops/broadcast.rs
- src/array/ops/cast.rs
- src/array/ops/image.rs
- tests/series/test_image.py
This PR adds an `Image` series --> Python egress path via the casting kernel, where elements in an `ImageArray` series are converted to NumPy ndarrays when hit with a `.cast(DataType::Python)`. This is added for both the fixed-shape image and variable-shape image arrays.
Automatic conversion of PIL images on `Series.from_pylist()` and to NumPy ndarrays on `Series.to_pylist()` is saved for a future PR.
> [Images] [4/N] Add `Image` series --> Python (NumPy) series casting.

- daft/__init__.py
- daft/daft.pyi
- daft/datatype.py
- daft/expressions/expressions.py
- daft/series.py
- docs/source/api_docs/datatype.rst
- docs/source/api_docs/datetype_image_format/daft.ImageFormat.from_format_string.rst
- docs/source/api_docs/datetype_image_format/daft.ImageFormat.rst
- docs/source/api_docs/expressions.rst
- src/array/ops/image.rs
- src/datatypes/image_format.rs
- src/datatypes/mod.rs
- src/dsl/functions/image/encode.rs
- src/dsl/functions/image/mod.rs
- src/python/expr.rs
- src/python/mod.rs
- src/python/series.rs
- src/series/ops/image.rs
- tests/cookbook/test_image.py
- tests/series/test_image.py
This PR adds support for encoding and image column into a binary column, containing bytes encoded into the specified file format.
This serves as a precursor to both more user-friendly reprs in Jupyer Notebooks and saving/uploading images to specified URIs.
> [Images] [7/N] Add image encoding support.

- daft/execution/logical_op_runners.py
- daft/logical/schema.py
- daft/table/table.py
- daft/table/table_io.py
- src/python/field.rs
- src/python/schema.rs
- src/python/table.rs
- src/table/mod.rs
- tests/table/table_io/test_read_time_cast.py
* Adds table casting logic to coerce the table that was read to the schema that was required
* Adds also a strong assertion after reading the tables on each table's schema so that we catch any reading issues early, rather than silently letting it through which will cause VERY weird issues down the line
Note that after this PR, certain reads may throw errors (e.g. reading two JSONs with incompatible nested struct fields). This is expected, and if we want to support those use-cases we need to fix our `cast` implementation for those types!
> [Table-Read-Schema 2/3] Add table casting logic

- daft/expressions/expressions.py
- docs/source/api_docs/expressions.rst
- src/array/ops/list.rs
- src/dsl/functions/list/join.rs
- src/dsl/functions/list/mod.rs
- src/python/expr.rs
- src/series/ops/list.rs
- tests/table/list/test_list_join.py
* Adds the `.list` namespace on Expressions
* Adds implementation for a `.join` that only works if the nested child type is a string
> Add kernels for .list.join on a list[utf8] column

- daft/convert.py
- daft/dataframe/dataframe.py
- docs/source/release_notes/0.0.18.rst
Fixes some links that were broken on the latest documentation on ray.io
> Fix links to ray.io latest docs

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Adds workflow and config for release-drafter (https://github.com/release-drafter/release-drafter)
This will keep a running release changelog draft as we add PRs.
PRs are categorized based on their labels. We currently check for the following labels:
1. `highlight` - manually add this label to a PR to surface it as a highlight of the release
2. `breaking` - add `[BREAKING]` to your PR title
3. `enhancement` - add `[FEAT]` to your PR title
4. `performance` - add `[PERF]` to your PR title
5. `bug` - add `[BUG]` to your PR title
6. `chore` - add `[CHORE]` to your PR title (for things such as changes to our build, pure cleanups etc)
7. `documentation` - add `[DOC]` to your PR title, but should be automatically picked up as well if you change any `*.rst/html/ipynb` files
> [CHORE] Add release-drafter files

- .github/workflows/enforce-pr-labels.yml
- .github/workflows/release-drafter.yml
Adds a new GitHub Action which will prevent the merging of a PR unless it has one of the following labels:
```
[enhancement | performance | bug | chore | documentation | dependencies]
```
> [CHORE] Add a GitHub action to enforce labels are added to the PR before merging

- tests/ray/test_datasets.py
This should fix this test on pyarrow < 7.0.0.
> [CHORE][CI] Use pyarrow Table sort API that's compatible with older pyarrow versions

- .github/workflows/enforce-pr-labels.yml
Actions taken by the `github-actions` bot cannot trigger workflows. Thus when the Release Drafter autolabeller adds a new label to our PRs (using the `github-actions` bot), the label enforcer workflow does not trigger.
This PR adds a new trigger condition to re-run the Enforce Pull Request workflow after the release drafter workflow is run, on any non-main branch.
> [CHORE] Add new trigger to run PR label enforcement after Release Drafter

- daft/datatype.py
- daft/series.py
- src/array/ops/cast.rs
- src/python/datatype.rs
- tests/cookbook/test_image.py
- tests/series/test_cast.py
- tests/series/test_embedding.py
- tests/series/test_image.py
This PR automatically casts logical types (dates, timestamps, images, embeddings) into their Python representation when `Series.to_pylist()` is called. This results in a representation that's much easier to work with in Python UDFs and when egressing from Daft.
You'd need to manually cast logical series to the `Python` type before calling `.to_pylist()`, otherwise you'd get our internal Arrow representation:
```python
list_of_sensible_objs = s.cast(DataType.python()).to_pylist()
```
Now, this is done automatically for the user.
```python
list_of_sensible_objs = s.to_pylist()
```
> [FEAT] Automatically cast logical types to Python objects on `Series.to_pylist()`.

- .github/workflows/python-publish.yml
* Pin python version used in publishing as a workaround to https://github.com/actions/setup-python/issues/682
> pin the version of python used in publishing

- src/array/ops/cast.rs
- src/datatypes/image_mode.rs
- src/python/series.rs
- tests/dataframe/test_logical_type.py
- tests/series/test_cast.py
- tests/series/test_image.py
This PR infers the `Image` type for PIL images provided to `Series.from_pylist()`, and therefore for `Table.from_pydict()` and `DataFrame.from_pydict()`.
> [FEAT] [Images] [9/N] Infer `Image` type for PIL images on ingress.

- daft/series.py
- daft/viz/html_viz_hooks.py
- src/array/ops/repr.rs
- src/python/series.rs
- tests/dataframe/test_logical_type.py
- tests/dataframe/test_repr.py
- tests/series/test_image.py
Closes: #1077 and #1075 
* Adds a fix for `Series.from_pylist(..., pyobj="force")` when the list is a list of PIL Images (cc @clarkzinzow)
* Re-enables our HTML viz hooks in Python, for Python objects when calling into the HTML repr for Python arrays
> [BUG] Reenable HTML viz hooks for np.ndarray and PIL Images

- docs/source/api_docs/expressions.rst
This should fix the bad generation of `.rst` files for `ExpressionListNamespace.join`
cc @samster25
> [CHORE] Fix filepath for autogeneration of .list.join docs

- requirements-dev.txt
Unpins numpy for Python 3.8, which has been dropped by Numpy 1.25.0
> [CHORE] unpin numpy version for py<3.8

- .github/workflows/python-package.yml
* Refactors integration test workflow to build a wheel (similar to how we build for release) instead of doing a `maturin develop --release` in-place build with llvm-cov
> [CHORE] Refactor integration test to use wheel built for release

- src/daft-core/src/schema.rs
- src/daft-table/src/lib.rs
- tests/dataframe/test_repr.py
When DataFrame cells get too large, they currently expand to accommodate all of its contents.
This is an issue because many of our outputs are not truncated (e.g. printing a giant Python object).
This PR fixes the behavior to employ overflow scrolling behavior where appropriate:
Closes #621
> [FEAT] Better styling of large dataframe cells in HTML

- src/daft-io/src/http.rs
- src/daft-io/src/lib.rs
- src/daft-io/src/local.rs
- src/daft-io/src/s3_like.rs
* Enables auto retrying and client creation when a s3 fetch is different than the current bucket.
* Enables multiple s3 client to support multi region workloads
* Enables credential checking when creating s3 client and propagation
> [FEAT] Automatic Region Retrying for S3 Native Downloader

- .github/workflows/python-package.yml
Fixes our integration test build to use a separate (different) cache from other builds, by changing the cache key
Driveby: Fix what seems to be a typo in the Rust test cache's `restore-keys` argument as well
> [CHORE] Fix CI caching to cache integration test builds separately

- daft/api_annotations.py
- daft/io/_csv.py
- daft/io/_json.py
- daft/io/common.py
- daft/io/file_path.py
- daft/io/parquet.py
- daft/runners/pyrunner.py
- daft/runners/ray_runner.py
- daft/runners/runner_io.py
- tests/dataframe/test_creation.py
Adds the ability to pass in a list of URLs into our `read_*` APIs.
For example:
```python
daft.read_parquet(["s3://my-bucket/file.pq", "s3://my-other-bucket/file2.pq"])
```
Note that our schema inference is naive and will sample from just the first file! Users can override this behavior by explicitly passing in `schema_hints={...}`.
Closes: #1081
> [FEAT] Enable reading a list of URLs in read_* APIs

- .github/workflows/daft-profiling.yml
- .github/workflows/property-based-tests.yml
- .github/workflows/python-package.yml
- .github/workflows/ray-compatibility.yml
Previously we were only caching `~/.cargo/registry` and `~/.cargo/git`, which would cache the source files being pulled by cargo.
This PR takes it a step further by caching the build data itself in `target/` so that we can speed up CI times.
> [CHORE] Cache build artifacts in target folder

- Cargo.lock
- Cargo.toml
- daft/table/table.py
- src/daft-core/Cargo.toml
- src/daft-core/src/schema.rs
- src/daft-io/Cargo.toml
- src/daft-io/src/http.rs
- src/daft-io/src/lib.rs
- src/daft-io/src/local.rs
- src/daft-io/src/object_io.rs
- src/daft-io/src/s3_like.rs
- src/daft-parquet/Cargo.toml
- src/daft-parquet/src/lib.rs
- src/daft-parquet/src/metadata.rs
- src/daft-parquet/src/python.rs
- src/daft-parquet/src/read.rs
- src/lib.rs
* Adds Native parquet downloader to Daft.
* `Table.read_parquet("s3://daft-public-data/test_fixtures/parquet-dev/mvp.parquet")`
> [FEAT] Native Parquet Downloader

- tests/integration/io/conftest.py
- tests/integration/io/test_url_download_s3_minio.py
Cleans up IO integration test fixtures. This allows for easier re-use to test other things such as Parquet files.
> [CHORE] Cleans up IO integration test fixtures for re-use

- benchmarking/parquet/README.md
- benchmarking/parquet/conftest.py
- benchmarking/parquet/test_num_rowgroups.py
- requirements-dev.txt
Adds Parquet benchmarking using `pytest-benchmark`
See: `benchmarking/parquet/README.md` for instructions.
Some screenshots of the benchmarks in action:
**Benchmarking just Daft, grouped by the benchmarking "suite" (e.g. increasing number of rowgroups)**:
```
pytest benchmarking/parquet/ --benchmark-only --benchmark-group-by=group -k daft
```
**Benchmarking Daft against other tools (grouped by Parquet file)**:
```
pytest benchmarking/parquet/ --benchmark-only --benchmark-group-by=param:path
```
**Running with memray enabled**:
If you want to see how all these tools perform in terms of peak memory usage as well
```
pytest benchmarking/parquet/ --benchmark-only --benchmark-group-by=param:path --memray
```
> [CHORE] Add parquet benchmarking

- .github/workflows/daft-profiling.yml
- .github/workflows/property-based-tests.yml
- .github/workflows/python-package.yml
- .github/workflows/python-publish.yml
- .github/workflows/ray-compatibility.yml
* Our former cache of `./target` was steadily growing since we didn't purge out of date artifacts which this https://github.com/Swatinem/rust-cache does correctly.
* Move over all cargo caches to this paradigm
> [CHORE] [CI] use smarter github rust cache action

- tests/integration/io/parquet/test_remote_reads.py
* Enables Decimal Type Integration test
* TODO: Still need Parquet Binary -> Decimal reading for old parquet files
> [CHORE] Enable Parquet Integration tests for decimal types

- daft/table/table.py
- src/daft-io/src/s3_like.rs
- src/daft-parquet/src/lib.rs
- src/daft-parquet/src/metadata.rs
- src/daft-parquet/src/python.rs
- src/daft-parquet/src/read.rs
- src/daft-parquet/src/read_planner.rs
* Enables simple read planning (coalesce and parallelize) for parquet using the metadata to construct a read plan
* Enables Parallel fetching for s3 requests
* Enables non contiguous range reader
> [PERF] Simple Read Planner and RangeReader for Native Parquet Reader

- benchmarking/parquet/README.md
- benchmarking/parquet/benchmark-requirements.txt
- benchmarking/parquet/conftest.py
- benchmarking/parquet/test_num_rowgroups.py
1. Adds a naive "whole file downloader" read method
2. Adds stub for a native Daft read_parquet Table method
3. Adds more configurations of benchmarks (one column vs multi-column vs multi-sparse-columns vs all columns)
> [CHORE] More Parquet benchmarking

- daft/expressions/expressions.py
- src/daft-core/src/array/ops/image.rs
- src/daft-core/src/series/ops/downcast.rs
- src/daft-core/src/series/ops/image.rs
- src/daft-dsl/src/functions/image/crop.rs
- src/daft-dsl/src/functions/image/mod.rs
- src/daft-dsl/src/python.rs
- tests/table/image/test_crop.py
Adds an expression for cropping images based on a column of bounding boxes
> [FEAT] Add .image.crop Expression

- .pre-commit-config.yaml
For some reason this is only happening in CI but not locally, breaking our CI builds.
Let's disable this since ipynb files are not human-readable anyways.
> [CHORE] Exclude JSON pre-commit fixer for ipynb files

- daft/expressions/expressions.py
- daft/series.py
- docs/source/api_docs/expressions.rst
- src/daft-core/src/python/series.rs
- src/daft-core/src/series/ops/list.rs
- src/daft-dsl/src/functions/list/lengths.rs
- src/daft-dsl/src/functions/list/mod.rs
- src/daft-dsl/src/python.rs
- src/daft-table/src/ops/explode.rs
- tests/series/test_cast.py
- tests/table/list/test_list_lengths.py
Closes: #1056 
* Consolidates on using `.list` as the namespace on both Series and Expression list operations
* As a driveby, exposes the `.list.lengths()` expression (the functionality on a Series was already implemented)
> [FEAT] Consolidate to list namespace

- daft/logical/schema.py
- daft/table/table.py
- src/daft-parquet/src/file.rs
- src/daft-parquet/src/lib.rs
- src/daft-parquet/src/metadata.rs
- src/daft-parquet/src/python.rs
- src/daft-parquet/src/read.rs
- src/daft-parquet/src/read_planner.rs
* Refactors Native parquet reader (without perf improvements)
* adds ability to add offset and limit to number of rows
* adds python: `Table.read_parquet_statistics` to grab basic stats from a series of urls
* adds python: `Schema.from_parquet` to generate Schema from parquet file
> [FEAT] parquet reader refactor, add parquet_stats_reader and parquet_schema_reader (1/2)

- Cargo.lock
- Cargo.toml
- src/daft-io/Cargo.toml
- src/daft-io/src/lib.rs
- src/daft-parquet/Cargo.toml
- src/daft-parquet/src/file.rs
- src/daft-parquet/src/lib.rs
- src/daft-parquet/src/read.rs
- src/daft-parquet/src/read_planner.rs
* Improves perf of parquet reader by performing pipelining between compute and IO
* Uses rayon and oneshot channels to fan out expensive work to blocking threads
> [PERF] native streaming parquet

- tests/conftest.py
This removes warnings when running tests like:
```
tests/integration/io/test_url_download_http.py:18
/Users/charles/daft/tests/integration/io/test_url_download_http.py:18: PytestUnknownMarkWarning: Unknown pytest.mark.integration - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
@pytest.mark.integration()
```
> [CHORE] Add pytest marker for integration

- tests/integration/docker-compose/retry_server/main.py
- tests/integration/docker-compose/retry_server/retry-server-requirements.txt
- tests/integration/docker-compose/retry_server/routers/get_retries_parquet_bucket.py
- tests/integration/docker-compose/retry_server/routers/head_retries_parquet_bucket.py
- tests/integration/docker-compose/retry_server/routers/rate_limited_echo_gets_bucket.py
- tests/integration/docker-compose/retry_server/utils/responses.py
- tests/integration/io/parquet/test_reads_local_fixtures.py
- tests/integration/io/test_url_download_s3_local_retry_server.py
Adds FastAPI endpoints for integration tests, simulating rate-limiting on AWS S3 buckets.
Drive-by: refactors our code to use FastAPI sub-apps instead of Routers. This is needed to enable better control around rate limiting per-"app", where each app corresponds to an S3 bucket with certain characteristics.
Closes: #1179 
More work needs to be done here once we support customizable retry policies, so that we can verify that these retry strategies work.
> [CHORE] Add endpoints to simulate rate-limiting on AWS S3 buckets

- .github/workflows/nightlies-tests.yml
* Disables mac x86 testing on github actions since the docker install is flakey
> [CHORE] disable mac test for lack of docker

- src/daft-io/src/config.rs
- src/daft-io/src/python.rs
- src/daft-io/src/s3_like.rs
- tests/integration/io/conftest.py
- tests/integration/io/test_url_download_private_aws_s3.py
- tests/integration/io/test_url_download_public_aws_s3.py
* Adds `session_token` field to `S3Config` allowing users to pass temp session tokens (like from sts)to daft.
* Adds IO integration tests to ensure that we can use the IOConfig to access s3 with a signed request. 
* Closes: https://github.com/Eventual-Inc/Daft/issues/1216
> [FEAT] add session token as input to io config

- src/daft-parquet/src/lib.rs
- src/daft-parquet/src/read.rs
* Validates the number of rows and columns are correct (from parquet metadata) before returning a Table from the native reader.
> [FEAT] native parquet correctness checks

- daft/io/config.py
- docs/source/api_docs/input_output.rst
- src/daft-dsl/src/python.rs
- src/daft-io/src/python.rs
- src/daft-parquet/src/python.rs
Adds documentation for IOConfig and S3Config
Closes: #1106
> [DOCS][CHORE] Add docs for IOConfig and S3Config

- tests/table/table_io/test_parquet.py
- tests/table/table_io/test_read_time_cast.py
> [CHORE] Add unit tests for int96 timestamps

- benchmarking/parquet/conftest.py
- benchmarking/parquet/test_bulk_reads.py
- daft/table/table.py
- src/daft-parquet/src/python.rs
- src/daft-parquet/src/read.rs
- tests/integration/io/parquet/test_reads_public_data.py
* Adds parquet bulk reader which can parallelize across files for IO and compute
* Yielding up to a 5.3x speed up compared to the daft non bulk reader.
> [PERF] Native Parquet Bulk Reader

- daft/context.py
- daft/dataframe/dataframe.py
- daft/execution/execution_step.py
- daft/execution/physical_plan.py
- daft/io/_csv.py
- daft/io/_json.py
- daft/io/_parquet.py
- daft/io/common.py
- daft/io/file_path.py
- daft/logical/builder.py
- daft/logical/logical_plan.py
- daft/logical/rust_logical_plan.py
- daft/planner/__init__.py
- daft/planner/planner.py
- daft/planner/py_planner.py
- daft/planner/rust_planner.py
- daft/runners/pyrunner.py
- daft/runners/ray_runner.py
- daft/runners/runner.py
- tests/dataframe/test_accessors.py
- tests/optimizer/test_drop_projections.py
- tests/optimizer/test_drop_repartition.py
- tests/optimizer/test_fold_projections.py
- tests/optimizer/test_prune_columns.py
- tests/optimizer/test_pushdown_clauses_into_scan.py
- tests/optimizer/test_pushdown_limit.py
- tests/optimizer/test_pushdown_predicates.py
This PR introduces `LogicalPlanBuilder` and `QueryPlanner` interfaces to the `DataFrame` API and execution layers in order to hide the query planner implementation. This should allow us to build out the new Rust query planner without having to switch on the `use_rust_planner` feature flag everywhere, as well as allowing the logical plan --> executable tasks translation to deviate more, if we wish.
> [CHORE] [New Query Planner] Introduce `LogicalPlanBuilder` and `QueryPlanner` interfaces to hide query planner implementations.

- Cargo.lock
- src/daft-io/Cargo.toml
- src/daft-io/src/config.rs
- src/daft-io/src/python.rs
- src/daft-io/src/s3_like.rs
- tests/integration/io/conftest.py
- tests/integration/io/test_url_download_s3_local_retry_server.py
* allows user to specify the number of tries and the initial backoff duration
```
io_config=IOConfig(
s3=S3Config(num_tries=10, retry_initial_backoff_ms=1000),
)
```
> [FEAT] Native Downloader add Retry Config parameters

- Cargo.lock
- Cargo.toml
- tests/integration/io/parquet/test_reads_public_data.py
Update Daft to use decimal byte array fixes in our fork of arrow2
> [BUG] Fix decimal byte arrays

- .github/workflows/python-package.yml
- Cargo.lock
- daft/io/__init__.py
- daft/io/config.py
- pyproject.toml
- requirements-dev.txt
- src/common/error/src/error.rs
- src/daft-io/Cargo.toml
- src/daft-io/src/azure_blob.rs
- src/daft-io/src/config.rs
- src/daft-io/src/lib.rs
- src/daft-io/src/python.rs
- src/daft-parquet/src/file.rs
- src/daft-parquet/src/lib.rs
- src/daft-parquet/src/metadata.rs
- tests/integration/io/conftest.py
- tests/integration/io/parquet/test_reads_public_data.py
- tests/integration/io/test_url_download_http.py
- tests/integration/io/test_url_download_public_aws_s3.py
- tests/integration/io/test_url_download_public_azure.py
* Add Azure Blob Storage Support to Daft native reader (`az://` or `adfs://`) protocols
* requires`storage_account` to be set in IOConfig or env variable.
```
daft.io.IOConfig(
azure=daft.io.AzureConfig(
storage_account="dafttestdata",
access_key="...",
#anonymous = True
)
)
```
* Bumps up `integration-tests-io` python version to 3.8 since adls doesn't support anon mode
> [FEAT] Add Azure Support for Native Downloader

- daft/execution/physical_plan.py
- daft/execution/physical_plan_factory.py
- daft/execution/rust_physical_plan_shim.py
- daft/logical/rust_logical_plan.py
- src/daft-plan/src/builder.rs
- src/daft-plan/src/logical_plan.rs
- src/daft-plan/src/ops/distinct.rs
- src/daft-plan/src/ops/mod.rs
- src/daft-plan/src/ops/repartition.rs
- src/daft-plan/src/ops/sort.rs
- src/daft-plan/src/partitioning.rs
- src/daft-plan/src/physical_ops/fanout.rs
- src/daft-plan/src/physical_ops/mod.rs
- src/daft-plan/src/physical_ops/reduce.rs
- src/daft-plan/src/physical_ops/sort.rs
- src/daft-plan/src/physical_ops/split.rs
- src/daft-plan/src/physical_plan.rs
- src/daft-plan/src/planner.rs
- tests/cookbook/test_sorting.py
- tests/dataframe/test_distinct.py
- tests/dataframe/test_sort.py
This PR adds support for `df.sort()`, `df.repartition()`, and `df.distinct()` in the new query planner.
> [FEAT] [New Query Planner] Add support for Sort, Repartition, and Distinct in new query planner.

- tests/table/table_io/test_parquet.py
PyArrow only adds the flag after version 11
> [CHORE] Update test to only use store_schema kwarg for pa>=11

- daft/execution/rust_physical_plan_shim.py
- daft/logical/rust_logical_plan.py
- src/daft-plan/src/builder.rs
- src/daft-plan/src/lib.rs
- src/daft-plan/src/logical_plan.rs
- src/daft-plan/src/ops/mod.rs
- src/daft-plan/src/ops/sink.rs
- src/daft-plan/src/physical_ops/csv.rs
- src/daft-plan/src/physical_ops/json.rs
- src/daft-plan/src/physical_ops/mod.rs
- src/daft-plan/src/physical_ops/parquet.rs
- src/daft-plan/src/physical_plan.rs
- src/daft-plan/src/planner.rs
- src/daft-plan/src/sink_info.rs
- tests/cookbook/test_write.py
This PR adds support for tabular writes (`df.write_parquet()` and `df.write_csv()`).
> [FEAT] [New Query Planner] Add support for tabular writes.

- daft/logical/rust_logical_plan.py
- src/daft-plan/src/builder.rs
- src/daft-plan/src/logical_plan.rs
- src/daft-plan/src/ops/concat.rs
- src/daft-plan/src/ops/mod.rs
- src/daft-plan/src/physical_ops/concat.rs
- src/daft-plan/src/physical_ops/mod.rs
- src/daft-plan/src/physical_plan.rs
- src/daft-plan/src/planner.rs
- tests/dataframe/test_concat.py
This PR adds support for `df.concat()`, our first plan-binary logical operator. This PR is stacked on top of https://github.com/Eventual-Inc/Daft/pull/1252, so the actual diff is contained in commit https://github.com/Eventual-Inc/Daft/pull/1254/commits/98a7c6ad73443d5edad8bbb24541a7d1e3ea93f9.
> [FEAT] [New Query Planner] Add support for Concat.

- daft/logical/schema.py
- tests/test_schema.py
Create a Daft schema from PyArrow schema
> [FEAT] Add Schema.from_pyarrow

- daft/execution/rust_physical_plan_shim.py
- daft/logical/rust_logical_plan.py
- src/daft-core/src/datatypes/field.rs
- src/daft-dsl/src/expr.rs
- src/daft-plan/src/builder.rs
- src/daft-plan/src/ops/agg.rs
- src/daft-plan/src/physical_ops/agg.rs
- src/daft-plan/src/physical_plan.rs
- src/daft-plan/src/planner.rs
- tests/cookbook/test_aggregations.py
- tests/dataframe/test_aggregations.py
This PR adds support for `df.groupby()`, fixes misc. things with aggregations, and adds support for the remaining (non-sum) aggregation ops.
This PR builds off of https://github.com/Eventual-Inc/Daft/pull/1257, where @xcharleslin implemented the core meat of this PR (this PR just wires things together and fixes a few minor things). From that PR's description:
"Ported over the logic in our existing AggregationPlanBuilder. Groupby-aggregates should now be fully supported (including multi-partition).
Additionally, this PR improves on Daft's existing aggregation logic by using semantic IDs in intermediate results, so that redundant intermediates are not computed.
E.g. before, getting the Sum and Mean of a column would compute and carry around two copies of the intermediate sum, one for the …
> [FEAT] [New Query Planner] Groupby support, aggregation fixes, support for remaining aggregation ops

- Cargo.lock
- daft/io/__init__.py
- pyproject.toml
- requirements-dev.txt
- src/daft-io/Cargo.toml
- src/daft-io/src/config.rs
- src/daft-io/src/google_cloud.rs
- src/daft-io/src/lib.rs
- src/daft-io/src/python.rs
- src/daft-io/src/s3_like.rs
- tests/integration/io/parquet/test_reads_local_fixtures.py
- tests/integration/io/parquet/test_reads_public_data.py
* Adds GCS support to the native io reader for urls with `gs://` or `gcs://` paths.
* io_config can be configured for GCS via
```
daft.io.IOConfig(
gcs=daft.io.GCSConfig(
project_id="...",
#anonymous = True
)
)
```
> [FEAT] native google cloud reader

- daft/expressions/expressions.py
- daft/logical/rust_logical_plan.py
- daft/series.py
- src/daft-core/src/array/ops/count.rs
- src/daft-core/src/array/ops/mean.rs
- src/daft-core/src/array/ops/mod.rs
- src/daft-core/src/count_mode.rs
- src/daft-core/src/lib.rs
- src/daft-core/src/python/series.rs
- src/daft-core/src/series/ops/agg.rs
- src/daft-dsl/src/expr.rs
- src/daft-dsl/src/optimization.rs
- src/daft-dsl/src/python.rs
- src/daft-plan/src/planner.rs
- src/daft-table/src/lib.rs
- src/lib.rs
- tests/cookbook/test_count_rows.py
This PR adds support for `df.count_rows()`, the final missing implementation from the `LogicalPlanBuilder` interface for the new query planner.
> [FEAT] [New Query Planner] Add support for `df.count_rows().

- .github/workflows/python-publish.yml
- pyproject.toml
* Downgrade container version to use `manylinux_2_24` so we can publish manylinux2014 wheels so that older versions of pip will work with daft.
> [BUG] Use manylinux_2_24 for aarch64 linux to be able to publish manylinux2014

- src/daft-core/src/array/growable/arrow_growable.rs
- src/daft-core/src/array/growable/logical_growable.rs
- src/daft-core/src/array/growable/mod.rs
- src/daft-core/src/array/growable/python_growable.rs
- src/daft-core/src/array/mod.rs
- src/daft-core/src/array/ops/as_arrow.rs
- src/daft-core/src/array/ops/if_else.rs
- src/daft-core/src/datatypes/dtype.rs
- src/daft-core/src/datatypes/matching.rs
- src/daft-core/src/datatypes/mod.rs
- src/daft-core/src/series/ops/downcast.rs
- src/daft-dsl/src/functions/float/is_nan.rs
- tests/benchmarks/test_if_else.py
Growables are generally useful for abstracting "physical" operations such as:
1. Take
2. Broadcast
3. Filter
This will become much more important as we add new Array types (FixedSizeListArray, StructArray etc). These arrays can just implement their own Growable classes, and implementations for the physical kernels will be easy to implement.
1. Adds a new `Growable<Arr>` trait that is a growable to build the specified `Arr`
2. Adds a new `GrowableArray` trait which is implemented by `DataArray` and `LogicalArray`: these types can now create a growable using their associated `::make_growable` functions
3. Refactors `if_else` to use the new growables, reducing quite a bit of code and nasty macro usage
> [CHORE] Implement growables for array types

- src/daft-core/src/array/growable/mod.rs
- src/daft-core/src/array/ops/if_else.rs
- src/daft-core/src/series/array_impl/logical_array.rs
1. Cleans up our GrowableArray macros -- they actually all look the same across the arrow and logical ones and can be unified
2. Also cleans up the implementation of Logical SeriesLike if/elses -- we can just delegate directly to the physical arrays
> [CHORE] Code reduction in growable macros + logical if/else refactor

- src/daft-plan/src/lib.rs
- src/daft-plan/src/ops/source.rs
- src/daft-plan/src/optimization/optimizer.rs
- src/daft-plan/src/optimization/rules/mod.rs
- src/daft-plan/src/optimization/rules/push_down_limit.rs
This PR adds support for limit pushdown optimizations in the new query planner. In particular, it adds limit pushdown for repartitions, coalesces, projections, and scans.
> [FEAT] [New Query Planner] Add support for `PushDownLimit`

- src/daft-plan/src/logical_plan.rs
- src/daft-plan/src/optimization/optimizer.rs
- src/daft-plan/src/optimization/rules/drop_repartition.rs
- src/daft-plan/src/optimization/rules/mod.rs
- src/daft-plan/src/partitioning.rs
- src/daft-plan/src/planner.rs
This PR adds support for the `DropRepartition` optimization rule to the new query planner.
> [FEAT] [New Query Planner] Add support for `DropRepartition`

- daft/execution/execution_step.py
- daft/execution/physical_plan.py
- daft/execution/physical_plan_factory.py
- daft/execution/rust_physical_plan_shim.py
- daft/filesystem.py
- daft/io/common.py
- daft/io/file_path.py
- daft/logical/builder.py
- daft/logical/logical_plan.py
- daft/logical/optimizer.py
- daft/logical/rust_logical_plan.py
- daft/runners/pyrunner.py
- daft/runners/ray_runner.py
- daft/runners/runner_io.py
- src/daft-plan/src/builder.rs
- src/daft-plan/src/lib.rs
- src/daft-plan/src/ops/source.rs
- src/daft-plan/src/physical_plan.rs
- src/daft-plan/src/source_info.rs
- src/daft-plan/src/test/mod.rs
- tests/cookbook/test_dataloading.py
- tests/cookbook/test_image.py
- tests/optimizer/test_pushdown_clauses_into_scan.py
This PR refactors the file globbing logic by exposing `FileInfos` from the new query planner to Python and using it for both the old query planner and the new query planner. Hopefully the upcoming Rust-native file globber will be able to leverage the `FileInfos` struct or something akin to it, allowing it to be a ~drop-in replacement for the existing Python file globber.
> [FEAT] [New Query Planner] Refactor file globbing logic by exposing `FileInfos` to Python

- daft/dataframe/dataframe.py
- daft/logical/builder.py
- daft/logical/logical_plan.py
- daft/logical/rust_logical_plan.py
- src/daft-plan/src/builder.rs
- src/daft-plan/src/logical_plan.rs
- src/daft-plan/src/ops/concat.rs
- src/daft-plan/src/ops/filter.rs
- src/daft-plan/src/ops/join.rs
- src/daft-plan/src/ops/sort.rs
- src/daft-plan/src/optimization/logical_plan_tracker.rs
- src/daft-plan/src/optimization/optimizer.rs
- src/daft-plan/src/optimization/rules/drop_repartition.rs
- src/daft-plan/src/optimization/rules/push_down_filter.rs
- tests/dataframe/test_joins.py
- tests/dataframe/test_sort.py
This PR removes `ExpressionsProjection` from the `LogicalPlanBuilder` interface and the `RustLogicalPlanBuilder` implementation, and moves construction-time validation into `LogicalOp::try_new()` for misc. logical ops.
> [CHORE] [New Query Planner] Remove `ExpressionsProjection` from builder, move validation into `Op::try_new()`

- daft/execution/execution_step.py
- daft/execution/physical_plan.py
- daft/logical/logical_plan.py
- src/daft-plan/src/builder.rs
- src/daft-plan/src/source_info.rs
- tests/cookbook/test_dataloading.py
- tests/cookbook/test_image.py
This PR reverts back to the original column names for the file info partition, since these are user-facing and we're not wanting to break backwards compatibility at the moment.
> [BUG] [New Query Planner] Revert file info partition column names.

- Cargo.lock
- Cargo.toml
- tests/table/table_io/test_parquet.py
This PR incorporates changes in our [Arrow2 fork](https://github.com/Eventual-Inc/arrow2/commit/766eb727a9a06e99fc94de1880f6e5c2b1e211ee)
Previously, if Daft/arrow2 encountered an Arrow schema embedded in Parquet metadata, that Arrow schema was used as the source-of-truth for an inferred schema from the parquet file
After this change, this arrow schema is instead used as "hints" to rectify the inferred schema from Parquet.
This allows us to still leverage user-provided configurations (such as timeunit for int96 timestamps), but also still leverage information provided by the arrow schema for inferring correct arrow types.
NOTE: This PR also adds a fix for inferring Arrow `Null` types from Parquet `LogicalType::Unknown`
> [BUG] Fix Table.read_parquet behavior when it encounters arrow_schema

- src/daft-core/src/array/ops/cast.rs
- src/daft-core/src/array/ops/from_arrow.rs
- src/daft-core/src/array/ops/full.rs
- src/daft-core/src/series/mod.rs
- src/daft-table/src/lib.rs
We use `with_match_daft_types!` in a bunch of places that really should just be delegated to the `Series` instead.
This PR centralizes that logic under dedicated methods on `Series::full_null/empty/from_arrow` which account for most of the usage of `with_match_daft_types!` outside of specific places that still require it (`make_growable` and `repr`)
> [CHORE] Add Series::full_null/empty/from_arrow to reduce code duplication

- src/daft-core/src/array/growable/fixed_size_list_growable.rs
- src/daft-core/src/array/growable/list_growable.rs
- src/daft-core/src/array/growable/struct_growable.rs
- src/daft-core/src/array/ops/filter.rs
- src/daft-core/src/array/ops/full.rs
- tests/benchmarks/test_filter.py
This PR optimizes the new filter on nested arrays that uses growables
1. Adds some fixes for FullNull impls of the arrays, which was broken due to some naming problems
2. Adds microbenchmarks for filter
3. Adds optimizations for our filter and growable impls:
a. Make `self.growable_validity` optional, which speeds up the case where `use_validity=False`
b. Adds an early return for when the mask is all true/all false
4. Share a generic filter implementation across ListArray, StructArray and FixedSizeListArray
> [PERF] Optimize filter on nested growables

- tests/benchmarks/test_take.py
Adds microbenchmarks for takes
No optimizations were added, we are somewhere between 10-50x faster than the previous arrow2 implementation, which appears to be highly inefficient: https://github.com/jorgecarleitao/arrow2/blob/main/src/compute/take/list.rs#L31-L61
> [PERF] Add microbenchmarks for takes

- src/daft-core/src/schema.rs
Fixes Display for schema, which affects how our dataframe is displayed when not yet collected.
> [BUG] Schema Display should use dtype Display instead of Debug

- tests/integration/docker-compose/retry_server/routers/get_retries_parquet_bucket.py
- tests/integration/docker-compose/retry_server/routers/head_retries_parquet_bucket.py
- tests/integration/docker-compose/retry_server/routers/rate_limited_echo_gets_bucket.py
- tests/integration/docker-compose/retry_server/utils/responses.py
- tests/integration/io/parquet/test_reads_local_fixtures.py
Some retry logic only triggers on the string status code in the `<Code></Code>` section of the XML response from S3, not on the actual int status code itself
This PR adds the ability to supply this string status code to our local test fixtures so we can test for these cases.
> [CHORE] Add status code to IO integration tests

- daft/dataframe/dataframe.py
- daft/logical/builder.py
- daft/logical/logical_plan.py
- daft/logical/rust_logical_plan.py
- src/daft-plan/src/builder.rs
- src/daft-plan/src/display.rs
- src/daft-plan/src/logical_plan.rs
- src/daft-plan/src/optimization/optimizer.rs
This PR:
- adds a `simple: bool` option to `df.explain()`, which prints out a node-name-only logical plan tree for quick visualizations;
- changes the optimizer to use a fixed-point policy for its single rule batch, which adds back some dropped optimizations in certain cases (e.g. `PushDownProjection` producing a `Filter` node which never has a chance to push through other upstream nodes).
> [CHORE] [New Query Planner] Add simple `df.explain()` option; change to fixed-point policy for rule batch

- src/common/io-config/src/python.rs
- src/common/io-config/src/s3.rs
- src/daft-io/Cargo.toml
- src/daft-io/src/azure_blob.rs
- src/daft-io/src/google_cloud.rs
- src/daft-io/src/http.rs
- src/daft-io/src/object_io.rs
- src/daft-io/src/s3_like.rs
* Adds flag to S3Config that limits the number of connections to S3, default to 25 (recommended in the [aws-cpp-sdk](https://github.com/aws/aws-sdk-cpp/blob/c859aa7a1d85c5137f0416e4aa75b86ceb32e216/docs/ClientConfiguration_Parameters.md?plain=1#L46))
> [FEAT] Add flag to limit number of connections to S3

- Cargo.lock
- Cargo.toml
- src/daft-parquet/Cargo.toml
- src/daft-parquet/src/file.rs
- src/daft-parquet/src/read_planner.rs
* Improves wall clock time for reading parquet by 5-15%
* Reduces memory usage by < 5%
> [PERF] Used owned Stream in Parquet Page Iterator

- requirements-dev.txt
* Fix for adlfs transitive dep `azure-storage-blob`: https://github.com/fsspec/adlfs/issues/424
> [CHORE] pin azure-storage-blob due to breaking new version

- benchmarking/parquet/conftest.py
- daft/daft.pyi
- daft/table/__init__.py
- daft/table/table.py
- src/daft-parquet/src/python.rs
- src/daft-parquet/src/read.rs
- tests/integration/io/parquet/test_reads_public_data.py
* Adds a bulk reader `daft.table.read_parquet_into_pyarrow_bulk` for reading parquet into pyarrow tables
* TODO: Limit parallelism for parquet decoding.
> [FEAT] bulk parquet pyarrow reader

- daft/api_annotations.py
This PR fixes the type annotations for functions/methods that are wrapped with the public API decorator. Namely, we replace `Callable[..., Any]` for the input and return type of the decorator with `Callable[P, T]`, where `T = TypeVar("T")` and `P = ParamSpec("P")`; we then bind `T` to the return type and `P.args` and `P.kwargs` to the args and kwargs, respectively, of the wrapper function. This ensures that the type annotations of the wrapped function/method are properly propagated to the returned wrapper function.
> [BUG] Fix public API decorator type annotations.

- daft/context.py
Enable new query planner by default. We retain the feature flag + the old query planner for now, in case a nightly wheel user hits an issue that needs a quick workaround, so we also keep the query planner feature flag in the CI matrix.
We shouldn't merge this until:
> [FEAT] [New Query Planner] Enable new query planner by default.

- src/daft-io/src/lib.rs
- src/daft-io/src/object_io.rs
- src/daft-io/src/s3_like.rs
- tests/integration/io/conftest.py
- tests/integration/io/test_list_files_s3_minio.py
* Fixes s3 listing infinte loop
* correct error propagation in the recursive file lister
* return directories in the recursive file lister
* Fixes bug when you pass in an exact file
* Adds tests to cover the above cases
* Adds s3fs recursive lister utility
> [BUG] Fixes to S3 Native Lister with correct Error propagation

- .github/workflows/python-package.yml
- src/daft-io/src/google_cloud.rs
- tests/integration/io/test_list_files_gcs.py
Implements `ls` functionality for GCS
> [FEAT] Native Rust listing of GCS

- src/daft-io/src/google_cloud.rs
- tests/integration/io/test_list_files_gcs.py
* Fix gs listing to include 0 sized marker files (these files are created when manually creating folders in the UI)
* Fixes also for multiple trailing delimiters
* More test coverage for recursive cases
> [BUG] Fix gs listing to include 0 sized marker files

- .github/workflows/python-package.yml
- .github/workflows/python-publish.yml
- daft/filesystem.py
- requirements-dev.txt
- src/daft-io/src/lib.rs
- src/lib.rs
- tests/cookbook/test_dataloading.py
- tests/dataframe/test_creation.py
- tests/dataframe/test_repr.py
- tests/integration/test_tpch.py
- tests/series/test_concat.py
- tests/series/test_tensor.py
- tests/table/table_io/test_parquet.py
- tests/test_schema.py
- tests/udf_library/test_url_udfs.py
* Implements fixes for daft to be able to build for windows
* implements protocol checking in filesystem.py for windows style paths
* implements protocol checking in native local objectio for windows style paths.
* fix unit tests to use os libraries to construct path
* rewrite file io unit tests to not use a open file descriptor which breaks on windows
* disable AVX for x86 builds for mac and windows
* implement unit test, rust tests and import tests CI for windows 
* implements windows wheel building for publish pipeline
* disables query plan toggle for CI
* fix REPR style unit tests for `\r`
> [FEAT] Add support for windows in daft

- daft/daft.pyi
- daft/execution/rust_physical_plan_shim.py
- daft/planner/planner.py
- daft/planner/py_planner.py
- daft/planner/rust_planner.py
- daft/runners/pyrunner.py
- daft/runners/ray_runner.py
- src/daft-plan/src/physical_plan.rs
This PR fixes `is_ray_runner` check at plan execution time in the new query planner. Previously, we were checking the Daft context at execution time, which wouldn't be properly set under the Ray runner, since we don't propagate the Daft context to all Ray workers. This PR changes the runner check to be based on an explicit flag passed from the runner to the physical plan execution API.
Closes #1433
> [BUG] Fix runner check at plan execution time for new query planner

- src/daft-io/src/s3_like.rs
- tests/integration/io/test_list_files_gcs.py
I think the "deadlocking" in #1432 is actually caused by Python's difflib being really slow on the diff of the bad result.
Also, because our io integration tests on that workflow isn't provided with GCP credentials, it is defaulting to the "anonymous" GCS client which is s3 based. We should fix that once we verify that this fix works.
Closes: #1432
> [BUG] Fix scheme bug in GCS anonymous mode

- src/daft-plan/src/planner.rs
- tests/dataframe/test_repartition.py
This PR fixes the number of input partitions in our `Coalesce` implementation. The new query planner was incorrectly using the current logical node's `num_partitions` for the number of _input_ partitions, which for a `Coalesce` op, is equal to the _output_ number of partitions; we should instead be using the input (child) logical node's `num_partitions`.
The microbenchmarking failure also illustrated that we didn't have any unit testing coverage of `Coalesce` (i.e. `df.into_partitions(n)` where `n` is smaller than the current number of partitions), so we also add a sanity unit test.
Closes #1434
> [BUG] Fix num input partitions in coalesce.

- Cargo.lock
- src/daft-io/Cargo.toml
- src/daft-io/src/http.rs
- tests/integration/docker-compose/nginx-serve-static-files.conf
- tests/integration/io/conftest.py
- tests/integration/io/test_list_files_http.py
Adds capabilities for our HTTP source to perform file listing
Logic is roughly adapted from fsspec's [HTTPFileSystem](https://filesystem-spec.readthedocs.io/en/latest/_modules/fsspec/implementations/http.html) in order to maintain some parity with how it behaves.
Current differences in behavior:
1. We don't support fsspec's `simple_links=True` option, which would search for any text starting with `http(s)://` and that aren't encased in a HTML `<a href=...>` tag.
2. When pointed at a single file, fsspec returns an empty list but we detect whether the file is HTML and return a list with just the file itself if we see that it is not HTML.
> [FEAT] Native listing of http URLs

- Cargo.lock
- Cargo.toml
- src/common/error/src/error.rs
- src/daft-io/Cargo.toml
- src/daft-io/src/local.rs
- src/daft-io/src/object_io.rs
- tests/integration/io/test_list_files_local.py
This PR adds an `ls` implementation for the native local filesystem.
> [FEAT] Add local native filesystem globbing.

- Cargo.lock
- src/daft-io/Cargo.toml
- src/daft-io/src/glob.rs
- src/daft-io/src/lib.rs
- src/daft-io/src/object_io.rs
- src/daft-io/src/python.rs
- tests/integration/io/test_list_files_s3_minio.py
Adds a new `io_glob` Python function that performs globbing using the rules provided by the globset crate (https://docs.rs/globset/latest/globset/)
> [FEAT] Native `glob` functionality

- src/daft-io/src/azure_blob.rs
- src/daft-io/src/glob.rs
- src/daft-io/src/google_cloud.rs
- src/daft-io/src/http.rs
- src/daft-io/src/local.rs
- src/daft-io/src/object_io.rs
- src/daft-io/src/python.rs
- src/daft-io/src/s3_like.rs
- tests/integration/io/benchmarks/test_benchmark_glob.py
- tests/integration/io/test_list_files_s3_minio.py
Adds early stopping capabilities for our native globbing to prevent runaway parallelism when listing adverserial cases (one file per folder)
Other changes in this PR:
1. Adds benchmarks on 10k local files
2. Adds a new `posix` argument to `ls` and `iter_dir`: this controls whether the operation will perform a posix-like list (of just the next level), or an object-store-like prefix list (of all files starting with the provided prefix)
3. `delimiter` is no longer an `Option` argument and is required by all the ObjectSources: it could actually be argued that this should be automatically determined by the ObjectSource itself?
Not in scope in this PR:
1. Prefix listing for GCS/Azure/Local/HTTP are not implemented in this PR, thus the globbing algorithm will actually not work for those cases
2. …
> [PERF] Native globbing early stopping

- daft/table/schema_inference.py
This PR leverages pyarrow's streaming CSV reader for schema inference; instead of reading and parsing the entire CSV file to fetch the schema, this will fetch the schema from the first "block" read by the streaming reader. The block size is configurable at the pyarrow level as part of the CSV `ReadOptions` (although we don't currently expose this to the user), with a [default of 1 MB](https://github.com/apache/arrow/blob/5ad1cae024a0f3bc67ac49fa6d4d72d36afb2384/cpp/src/arrow/csv/options.h#L144-L149).
> [Hotfix] Change to streaming reader for CSV schema inference.

- src/daft-io/src/azure_blob.rs
- src/daft-io/src/google_cloud.rs
- src/daft-io/src/http.rs
- src/daft-io/src/local.rs
- src/daft-io/src/object_io.rs
- src/daft-io/src/object_store_glob.rs
- src/daft-io/src/s3_like.rs
- tests/io/test_list_files_local.py
Addresses part of [#1466](https://github.com/Eventual-Inc/Daft/issues/1466) which is currently failing because of globbing in windows on: #1467
> [BUG] Fixes globbing on windows by consolidating on posix-style paths

- Cargo.lock
- Cargo.toml
- daft/daft.pyi
- daft/execution/rust_physical_plan_shim.py
- daft/io/_csv.py
- daft/logical/schema.py
- daft/table/schema_inference.py
- daft/table/table.py
- daft/table/table_io.py
- src/daft-csv/Cargo.toml
- src/daft-csv/src/lib.rs
- src/daft-csv/src/metadata.rs
- src/daft-csv/src/python.rs
- src/daft-csv/src/read.rs
- src/daft-io/src/local.rs
- src/daft-parquet/Cargo.toml
- src/daft-plan/src/physical_plan.rs
- src/lib.rs
- tests/dataframe/test_creation.py
- tests/table/table_io/test_csv.py
This PR adds a simple native CSV reader. Local reads are fully async, while remote object store reads currently bulk-download each file into a byte buffer; streaming remote read support will be added in a follow-up PR.
**NOTE:** This PR required some changes to Arrow2's async CSV reading machinery, namely:
1. Schema inference was broken for headerless CSV files ([commit](https://github.com/Eventual-Inc/arrow2/commit/a14e8c7ec9eac77cc1aa5ee08b62c9d18f2408cf)).
2. Type inference was broken for CSV columns that contain nulls ([commit](https://github.com/Eventual-Inc/arrow2/commit/065a31da8fd8a75cbece5f99295a4068713a71ed)).
The requisite changes are contained on this branch: https://github.com/jorgecarleitao/arrow2/compare/main...Eventual-Inc:arrow2:clark/async-csv-fixes?expand=1
Closes #1462
> [FEAT] [Native I/O] Add a native CSV reader.

- daft/table/table.py
- daft/table/table_io.py
We never had streaming CSV reads at the execution layer, so we would be reading a whole CSV file regardless of how many rows needed. Now we use pyarrow CSV stream reader to get record batches, and from those only get the rows we need.
> [FEAT] Streaming CSV reads

- daft/runners/ray_runner.py
Updates the number of cores available before/after every batch dispatch
This should allow us to take advantage of autoscaling of the Ray cluster better as we will schedule larger batches of tasks + more total inflight tasks as the cluster autoscales.
> [PERF] Update number of cores on every iteration

- tests/integration/io/test_list_files_azure.py
> [CHORE] Add tests and fixes for Azure globbing

- daft/daft.pyi
- daft/execution/execution_step.py
- daft/io/_parquet.py
- daft/table/table_io.py
- src/common/io-config/src/python.rs
- src/daft-io/src/lib.rs
- src/daft-io/src/s3_like.rs
- src/daft-plan/src/source_info/file_format.rs
Passes the `multithreaded_io=False` flag through when running on the Ray Runner for read_parquet
> [PERF] Pass-through multithreaded_io flag in read_parquet

- src/common/io-config/src/s3.rs
We were seeing some issues with timeouts and retries
> [CHORE] Update default num_tries on S3Config to 25

- src/daft-io/src/lib.rs
- src/daft-io/src/s3_like.rs
* Fixes 2 issues: 
* We always set to default region even when the system can provide us creds
* We reran the credential chain even though we can leverage a cache
> [PERF] Use region from system and leverage cached credentials when making new clients

- daft/series.py
* Use pyarrow table for pickling rather than ChunkedArray so we can exploit ray's special pickling for arrow tables which doesn't work on ChunkedArray
> [PERF] Use pyarrow table for pickling rather than ChunkedArray

- src/daft-csv/src/metadata.rs
- src/daft-csv/src/python.rs
- src/daft-csv/src/read.rs
- src/daft-dsl/src/functions/uri/download.rs
- src/daft-io/src/azure_blob.rs
- src/daft-io/src/google_cloud.rs
- src/daft-io/src/http.rs
- src/daft-io/src/lib.rs
- src/daft-io/src/local.rs
- src/daft-io/src/object_io.rs
- src/daft-io/src/object_store_glob.rs
- src/daft-io/src/python.rs
- src/daft-io/src/s3_like.rs
- src/daft-io/src/stats.rs
- src/daft-io/src/stream_utils.rs
- src/daft-parquet/src/file.rs
- src/daft-parquet/src/metadata.rs
- src/daft-parquet/src/python.rs
- src/daft-parquet/src/read.rs
- src/daft-parquet/src/read_planner.rs
* Implements IOStats via atomics that will track the number of:
* GetRequests
* HeadRequests
* ListRequests
* BytesRead
When the `IOStatsContext` goes out of scope it will debug log its output:
For a parquet read:
```
IOStatsContext: read_parquet: for uri s3://eventual-dev-benchmarking-fixtures/parquet-benchmarking/tpch/200MB-2RG/daft_200MB_lineitem_chunk.RG-2.parquet, Gets: 17, Heads: 1, Lists: 0, BytesRead: 213627535, AvgGetSize: 12566325
```
For our io_glob:
```
IOStatsContext: io_glob for s3://daft-segment-data/segment-logs/**, Gets: 0, Heads: 0, Lists: 237, BytesRead: 0, AvgGetSize: 0
```
Currently the context is threaded through our python Apis for `io_glob`, `read_parquet`, and `read_csv`
IOStats is currently implemented for:
* S3
* GCS
* HTTP
* Azure
> [FEAT] IOStats for Native Reader

- daft/execution/execution_step.py
- daft/logging.py
- daft/runners/pyrunner.py
1. Reduces the verbosity of physical planner debug logs by logging only the number of partitions rather than printing the partition itself
2. Adds a `setup_debug_logging` function for convenience when performing local/dogfooding
> [CHORE] Better logging for physical plan

- daft/runners/ray_runner.py
Previously prior to this change, if an error occurs during execution in the RayRunner:
1. The "run_plan" thread will error out and die before sending any information on the return queue
2. The Scheduler actor will block forever on the next result on the return queue via a `.get()`
This change re-raises those errors so that it surfaces in the scheduler, and prevents that issue from occurring.
> [BUG] Re-raise exceptions in rayrunner

- Cargo.lock
- src/daft-csv/Cargo.toml
- src/daft-csv/src/lib.rs
- src/daft-csv/src/metadata.rs
- src/daft-csv/src/read.rs
- src/daft-csv/src/schema.rs
- src/daft-decoding/Cargo.toml
- src/daft-decoding/src/deserialize.rs
- src/daft-decoding/src/inference.rs
- src/daft-decoding/src/lib.rs
Moves code out from `daft-csv` that currently perform decoding of CSV data (bytes to typed Daft data) into a new `daft-decoding` crate so that they can be re-used
> [CHORE] Move code from daft-csv to daft-decoding

- docs/source/learn/user_guides/datatypes.rst
> [DOCS]: fix typo in doc

- Cargo.lock
- daft/daft.pyi
- src/daft-io/src/azure_blob.rs
- src/daft-io/src/google_cloud.rs
- src/daft-io/src/http.rs
- src/daft-io/src/lib.rs
- src/daft-io/src/local.rs
- src/daft-io/src/object_io.rs
- src/daft-io/src/object_store_glob.rs
- src/daft-io/src/python.rs
- src/daft-io/src/s3_like.rs
- src/daft-scan/Cargo.toml
- src/daft-scan/src/glob.rs
- src/daft-scan/src/lib.rs
- tests/integration/io/test_list_files_s3_minio.py
Initial implementation of the GlobScanOperator that leverages our Rust globbing implementation
Closes: #1531
> [FEAT] GlobScanOperator

- requirements-dev.txt
Reverts Eventual-Inc/Daft#1542
It appears Pandas dropped support for Python 3.8 in >=2.1.0
> [CHORE] Revert "Bump pandas from 2.0.3 to 2.1.2"

- src/daft-plan/src/builder.rs
- src/daft-plan/src/optimization/rules/push_down_limit.rs
- src/daft-plan/src/planner.rs
- src/daft-scan/src/lib.rs
- src/daft-scan/src/python.rs
Performs equality on the Arc pointer instead of relying on logic to check the underlying `dyn ScanOperator` trait object for equality, which could be tricky because of some custom vtable logic.
> [CHORE] [ScanOperator-Follow-Ons-1] Pointer Equality using Arc newtype instead of on `dyn ScanOperator` trait object

- src/daft-micropartition/src/micropartition.rs
- src/daft-micropartition/src/ops/agg.rs
- src/daft-micropartition/src/ops/cast_to_schema.rs
- src/daft-micropartition/src/ops/concat.rs
- src/daft-micropartition/src/ops/eval_expressions.rs
- src/daft-micropartition/src/ops/filter.rs
- src/daft-micropartition/src/ops/join.rs
- src/daft-micropartition/src/ops/partition.rs
- src/daft-micropartition/src/ops/slice.rs
- src/daft-micropartition/src/ops/sort.rs
- src/daft-micropartition/src/ops/take.rs
- src/daft-micropartition/src/python.rs
Also refactors `MicroPartition::new` into explicit `::new_loaded` and `::new_unloaded` variants:
1. Helps us enforce that `TableStatistics` is `Some` when the state is `TableState::Unloaded` at construction-time
2. Cleans up client code, because `TableState` no longer needs to be exposed externally and we can hide the calculations for TableMetadata inside of the `::new_loaded` constructor
3. `::from_scan_task_batch` is very explicit and clean. It tries `::new_unloaded` first, but falls back on `::new_loaded` if the ScanTaskBatch is not provided with both metadata/statistics
> [CHORE] [ScanOperator-Follow-Ons-2] Refactor MicroPartition to have non-optional TableMetadata

- daft/daft.pyi
- daft/execution/rust_physical_plan_shim.py
- daft/table/micropartition.py
- daft/table/table.py
- src/daft-micropartition/src/micropartition.rs
- src/daft-micropartition/src/ops/cast_to_schema.rs
- src/daft-micropartition/src/python.rs
- src/daft-plan/src/physical_ops/scan.rs
- src/daft-plan/src/physical_plan.rs
- src/daft-plan/src/planner.rs
- src/daft-scan/src/anonymous.rs
- src/daft-scan/src/glob.rs
- src/daft-scan/src/lib.rs
- src/daft-scan/src/python.rs
1. Replaces `ScanTask` with `ScanTaskBatch`, which mostly like `ScanTask` except that it is multi-file
2. This helps us deduplicate information representation between `ScanTask` and `ScanTaskBatch`
> [CHORE][ScanOperator 2/3] Refactor ScanTask to be multi-file and removes ScanTaskBatch

- Cargo.lock
- daft/io/common.py
- src/daft-micropartition/Cargo.toml
- src/daft-micropartition/src/micropartition.rs
- src/daft-plan/src/optimization/rules/push_down_projection.rs
- src/daft-scan/src/glob.rs
- src/daft-scan/src/lib.rs
Adds various fixes to daft v2 scans:
1. Fix for how we handle schema hints in the Python logical scan node builder
2. Fix for our ScanGlobOperator not correctly prefixing local paths with `file://` schemes
3. Adds a branch in micropartitions for materializing from a ScanTask that is a CSV
4. Implements column pruning pushdown rules, and correct handling during ScanTask materialization
> [BUG][ScanOperator 3/3] Incremental bugfixes for daft v2 scans

- src/daft-micropartition/src/python.rs
- src/daft-scan/src/python.rs
fixes deadlock with glob in the following test
```
DAFT_MICROPARTITIONS=1 DAFT_V2_SCANS=1 pytest --ignore tests/dataframe/test_creation.py -k "test_tpch_q6[gen_tpch:2]"
```
> [BUG] add allow threads for io pool operations

- src/daft-csv/src/read.rs
- src/daft-micropartition/src/lib.rs
- src/daft-micropartition/src/micropartition.rs
- src/daft-micropartition/src/python.rs
- src/daft-scan/src/glob.rs
- src/daft-scan/src/lib.rs
- src/daft-scan/src/python.rs
- tests/dataframe/test_creation.py
This PR adds support for the Python I/O layer to `MicroPartition` reads, which thereby adds support for reading `MicroPartition`s from JSON files with the scan operator path.
As a driveby, this PR also fixes a column ordering bug when out-of-order column projections are provided to our native CSV reader.
This PR is stacked on top of https://github.com/Eventual-Inc/Daft/pull/1559
> [FEAT] [Scan Operator] Add Python I/O support (+ JSON) to `MicroPartition` reads

- Cargo.lock
- daft/daft.pyi
- daft/io/common.py
- src/daft-io/src/azure_blob.rs
- src/daft-io/src/google_cloud.rs
- src/daft-io/src/http.rs
- src/daft-io/src/lib.rs
- src/daft-io/src/local.rs
- src/daft-io/src/object_io.rs
- src/daft-io/src/s3_like.rs
- src/daft-scan/Cargo.toml
- src/daft-scan/src/glob.rs
- src/daft-scan/src/python.rs
1. Converts GlobScanOperator to utilize Iterators and tokio channels to provide end-to-end streaming of glob results
2. Allows `GlobScanOperator` to be created from a list of glob files, which will chain the results into a single return stream
> [CHORE] Convert GlobScanOperator to perform streaming into result and take a list of glob paths

- pyproject.toml
We currently use `from typing import ParamSpec` and fallback onto `from typing_extensions import ParamSpec` when on a version of Python < 3.10
We need to upgrade our requirements to reflect this!
> [BUG] Update requirements for typing_extensions

- src/daft-micropartition/src/micropartition.rs
- src/daft-plan/src/builder.rs
- src/daft-plan/src/logical_ops/source.rs
- src/daft-plan/src/optimization/rules/push_down_limit.rs
- src/daft-plan/src/optimization/rules/push_down_projection.rs
- src/daft-plan/src/physical_ops/csv.rs
- src/daft-plan/src/physical_ops/json.rs
- src/daft-plan/src/physical_ops/parquet.rs
- src/daft-plan/src/physical_plan.rs
- src/daft-plan/src/planner.rs
- src/daft-plan/src/source_info/mod.rs
- src/daft-plan/src/test/mod.rs
- src/daft-scan/src/anonymous.rs
- src/daft-scan/src/glob.rs
- src/daft-scan/src/lib.rs
This PR refactors the parallel pushdown optimization + execution paths to use a shared `Pushdowns` struct, simplifying a good bit of code.
> [FEAT] [Scan Operator] Refactor planning and execution code to use shared `Pushdowns` struct.

- daft/runners/ray_runner.py
- tests/ray/runner.py
* adds `stop_plan` method on the Ray Scheduler when is called when the `RayRunner.run_iter` goes out of scope.
* This fixes the issues where we have a hanging thread at the end of execution
* closes: https://github.com/Eventual-Inc/Daft/issues/1591
> [BUG] clean up ray scheduler threads after computing partial results

- daft/dataframe/dataframe.py
Fixes #1583.
When a user does not specify columns in df aggregation methods, e.g. `df.count()`:
- Default to running aggregation on all columns
- Log warning messages with an example to pass in columns.
> [CHORE] Improve error messages when calling aggregation methods on dataframe without input columns

- Makefile
I noticed after following the [contributing guide](https://github.com/Eventual-Inc/Daft/blob/main/CONTRIBUTING.md#development-environment) and running 'make hooks', the pre-commit hooks did not run when I commit changes. 
Not sure if this was intended, but looking at https://pre-commit.com/#pre-commit-install-hooks:
```
pre-commit install-hooks does not install the pre-commit script. 
To install the script along with the hook environments in one command, use pre-commit install --install-hooks.
```
See also: https://github.com/pre-commit/pre-commit.com/issues/255
> [CHORE] Edit 'make-hooks' command to install pre-commit script

- src/daft-io/src/stats.rs
- src/daft-micropartition/src/micropartition.rs
- src/daft-micropartition/src/ops/agg.rs
- src/daft-micropartition/src/ops/concat.rs
- src/daft-micropartition/src/ops/eval_expressions.rs
- src/daft-micropartition/src/ops/filter.rs
- src/daft-micropartition/src/ops/join.rs
- src/daft-micropartition/src/ops/partition.rs
- src/daft-micropartition/src/ops/slice.rs
- src/daft-micropartition/src/ops/sort.rs
- src/daft-micropartition/src/ops/take.rs
- src/daft-micropartition/src/python.rs
- src/daft-parquet/src/python.rs
* Makes IOStats required for micropatition ops that may be lazy and call `tables_or_read, concat_or_read`.
* Add annotations for all ops that call the methods above
* update iostats to use `Cow<'static, str>` since many of the strings we use is static.
> [CHORE] add IOStats to all micropartition ops

- src/daft-core/src/series/ops/take.rs
- src/daft-micropartition/src/ops/join.rs
- src/daft-micropartition/src/ops/slice.rs
- src/daft-micropartition/src/ops/take.rs
Return empty micropartitions when we know the result is going to be empty. This allows us to avoid IO in places where it is not needed
> [PERF] Speed Up MicroPartition Ops when we know the result is empty

- tutorials/embeddings/daft_tutorial_embeddings_stackexchange.ipynb
The change in #1592 introduced a bug where the inferred PyArrow S3FileSystem doesn't correctly infer the region of the bucket
To work-around this, we can manually specify the `region_name` in our IOConfig. This problem should be less common once we move towards all-native reads.
> [BUG] Manually specify region in tutorial read_json

- daft/datatype.py
- src/daft-core/src/datatypes/dtype.rs
- src/daft-core/src/utils/arrow.rs
* Enables reads of fixed sized binary data
* I hit some issues reading UUIDs from parquet files
> [BUG] enable fixed size binary ingest to daft binary

- daft/table/table.py
- tests/integration/io/parquet/test_reads_s3_minio.py
Before this fix, empty returns would error out in `Table.read_parquet_statistics` because we wrongly create a `Series.from_pylist([])` of a Null DataType.
> [BUG] Add better handling for case where glob of parquet files returns empty

- daft/runners/ray_runner.py
- tests/dataframe/test_concat.py
Problem: when performing a dataframe concat with itself, our RayRunner will break on a `.wait()` call which waits on some duplicate object IDs
> [BUG] Self-concat breaks with the RayRunner

- pyproject.toml
- requirements-dev.txt
* Drop ray default feature due to the fact that pyiceberg requires pydantic > 2.0
* for context: https://github.com/ray-project/ray/issues/37019
> [CHORE] drop ray default dep to make room for Pydantic > 2.0

- tests/io/test_csv_roundtrip.py
- tests/io/test_parquet_roundtrip.py
Tests round-trip code (Daft write into a Daft read) for CSV and Parquet
> [BUG] Roundtrip tests for CSVs and Parquet

- Cargo.lock
- Cargo.toml
- tests/io/test_parquet_roundtrip.py
This required a fix in our arrow2 fork: https://github.com/Eventual-Inc/arrow2/commit/3a23c780d4d59ef0c9c8751675480e07f4e1c311
Essentially when Parquet has a type that is "timezone aware", Arrow2 will always infer it as `"+00:00"` (not `None` as previously assumed). However if the embedded Arrow schema on the Parquet file tells us that the timezone should actually be something else, we need to override `"+00:00"` with the one provided by the embedded Arrow schema.
> [BUG] Fix parquet timestamp tz roundtrip inference

- src/daft-io/src/object_store_glob.rs
- src/daft-io/src/s3_like.rs
- tests/integration/io/test_list_files_gcs.py
This should fix CI failures: https://github.com/Eventual-Inc/daft-benchmarking/actions/runs/6899343721/job/18770787773
> [BUG] Filter out size-0 directory marker files during s3 globs

- pyproject.toml
- requirements-dev.txt
failure when running on remote clusters:
```
File "/runner/_work/daft-benchmarking/daft-benchmarking/.venv/lib/python3.10/site-packages/ray/client_builder.py", line 99, in __init__
raise ValueError(
ValueError: Ray Client requires pip package `ray[client]`. If you installed the minimal Ray (e.g. `pip install ray`), please reinstall by executing `pip install ray[client]`.
```
> [CHORE] add ray client to deps

- daft/runners/progress_bar.py
* We currently were only using a background thread when updating the done tasks. Now we also check if new tasks are enqueued to perform a refresh.
> [CHORE] enable refresh on tqdm total updates

- daft/dataframe/dataframe.py
- tests/dataframe/test_show.py
This PR ensures that a preview cached via a `df.collect()` is used in `df.show()`, rather than recomputing output tables from scratch.
> [FEAT] Use cached preview from `df.collect()` in `df.show()`.

- daft/dataframe/dataframe.py
- daft/dataframe/preview.py
- daft/runners/progress_bar.py
- tests/dataframe/test_show.py
On the pyrunner:
On the local RayRunner:
On the remote RayRunner:
When executed from a python script (tested also across py, local-ray and remote-ray):
> [FEAT] Print the results of a df.show() to stdout if running in non-interactive mode

- Cargo.lock
- Cargo.toml
- daft/dataframe/dataframe.py
- src/daft-core/Cargo.toml
- src/daft-core/src/schema.rs
- src/daft-core/src/series/mod.rs
- src/daft-core/src/utils/display_table.rs
- src/daft-core/src/utils/mod.rs
- src/daft-csv/src/read.rs
- src/daft-table/Cargo.toml
- src/daft-table/src/lib.rs
- tests/dataframe/test_repr.py
- tests/series/test_tensor.py
- tests/test_schema.py
- tests/utils.py
* Implements Terminal (tty) aware printing to avoid wrap arounds
* Implements dynamic column printing (the wider the terminal, the more columns print)
* factor out our printing code to be shared between table, series and schema
Closes: https://github.com/Eventual-Inc/Daft/issues/901
when showing a dataframe:
when performing a show:
when we resize the terminal: (second call is after zooming out in terminal)
and the case when we truncate both rows and columns:
> [FEAT] Dynamic Responsive Printing of Tables, Schema and Series

- src/daft-core/src/utils/display_table.rs
- tests/dataframe/test_repr.py
* we hit a unicode slicing bug in the property based testing
> [BUG] favor char indices instead of slicing to deal with unicode

- src/daft-core/src/schema.rs
- src/daft-micropartition/src/micropartition.rs
- src/daft-parquet/src/statistics/column_range.rs
- src/daft-parquet/src/statistics/table_stats.rs
- src/daft-stats/src/column_stats/mod.rs
- src/daft-stats/src/table_stats.rs
1. We should disallow creation of ColumnRangeStatistics from non-comparable types to avoid issues at runtime
2. We also add validation when creating MicroPartitions:
* The column names in a MicroPartition's schema must be found in its ScanTask's schema
* When creating Statistics for a MicroPartition, we cast those Statistics to the MicroPartition's schema to ensure type compatibility
> [BUG] Add an allowlist of DataTypes that ColumnRangeStatistics supports and validation of TableStatistics

- src/daft-core/src/utils/display_table.rs
* Shows the number of columns truncated
> [FEAT] show number of truncated columns

- Cargo.lock
- src/daft-io/Cargo.toml
- src/daft-io/src/google_cloud.rs
* `google-cloud-storage` crate now supports anonymous mode from this [issue](https://github.com/yoshidan/google-cloud-rust/issues/213) thanks to this [PR](https://github.com/yoshidan/google-cloud-rust/pull/217)
* This lets us drop S3 Compatibility mode for GCS
> [CHORE] drop s3 compat mode for gcs for anonymous mode

- daft/datatype.py
- src/daft-core/src/datatypes/binary_ops.rs
- src/daft-core/src/series/array_impl/binary_ops.rs
- src/daft-core/src/utils/supertype.rs
- src/daft-dsl/src/expr.rs
- tests/expressions/typing/conftest.py
- tests/expressions/typing/test_compare.py
- tests/series/test_comparisons.py
* Enables comparisons between Timestamps of no / same / different timezones and units
* Enables comparisons between dates and timestamps
* Adds Date / Timestamps to expression fixtures
* However we do not allow compare a TimeStamp with no tz with one that has one.
> [FEAT] Enable Comparison between timestamp / dates 

- src/daft-plan/src/planner.rs
Hotfix for checking whether the larger side of a join is already-partitioned, when determining whether to use a broadcast join or a hash join.
> [BUG] [Hotfix] [Join Optimization] Fix pre-partitioned check for larger side of join.

- src/daft-plan/src/optimization/rules/push_down_limit.rs
This PR fixes an uncaught compilation error in a test that's not run (or compiled) in CI.
> [BUG] [Hotfix] Fix limit pushdown test.

- daft/execution/execution_step.py
- daft/runners/progress_bar.py
- daft/runners/ray_runner.py
Annotates Ray Tasks with name of instructions
Also adds stage id to TQDM bar to make it more clear that they are separate stages
> [FEAT] annotate ray tasks with name of instructions

- daft/runners/ray_runner.py
error in question
```
virtualenv/lib/python3.8/site-packages/daft/runners/ray_runner.py", line 529, in _run_plan
cores: int = next(num_cpus_provider) - self.reserved_cores
File "/tmp/ray/session_2023-12-14_10-43-11_589430_8/runtime_resources/pip/6268584d5ab6509fe9044d782b6939e786ec5677/virtualenv/lib/python3.8/site-packages/daft/runners/ray_runner.py", line 400, in _ray_num_cpus_provider
last_num_cpus_queried = int(ray.cluster_resources()["CPU"])
KeyError: 'CPU'
```
> [BUG] bugfix when cluster has no workers and key error happens when fetching num cores

- src/daft-core/src/array/ops/concat.rs
- tests/benchmarks/test_concat.py
* before Were we using Arrow Growable for Concating UTF8 and Binary Arrays, which only allocated memory for the offset array
* Now we preallocate the value array since we know the complete size of the target array.
> [PERF] Greatly speed up Variable Length Concat

- Cargo.lock
- src/daft-decoding/Cargo.toml
- src/daft-decoding/src/deserialize.rs
- src/daft-decoding/src/inference.rs
* Leads to a 7% reduction in walltime for the local airbnb csv
* Switch to simd parsing instructions for csv
* Preallocate UTF8Array value capacity before copying slices in
> [PERF] Speed up CSV Reader with SIMD and reduced allocations

- src/daft-io/src/lib.rs
- tests/integration/io/conftest.py
- tests/integration/io/parquet/test_reads_public_data.py
- tests/integration/io/test_list_files_s3_minio.py
- tests/integration/io/test_url_download_private_aws_s3.py
- tests/integration/io/test_url_download_public_aws_s3.py
* We missed a check in `daft-io` client that would let `s3a` protocol use the s3 client.
> [BUG] Add check for protocol S3A (s3 compatible)

- daft/io/_iceberg.py
- docs/source/api_docs/creation.rst
- docs/source/user_guide/basic_concepts/read-and-write.rst
- docs/source/user_guide/index.rst
- docs/source/user_guide/integrations.rst
- docs/source/user_guide/integrations/data_catalogs.rst
1. Add docstring
2. Add API docs
3. Adds a new section in `user_guide/integrations` for `data_catalogs`
> [DOCS] Add documentation for read_iceberg

- src/daft-plan/src/physical_ops/explode.rs
- src/daft-plan/src/physical_plan.rs
- src/daft-plan/src/planner.rs
* Invalidates PSpec when we explode a column that it runs on.
> [BUG] Invalidate PartitionSpec when we run Explode on it

- daft/dataframe/dataframe.py
- tests/cookbook/test_write.py
Closes #582 
**Materialize Dataframes created from file writes, i.e. write_csv and write_parquet**
Changes:
- Populate _result_cache and _preview for dataframes returned from write methods
- Modify test cases for write methods to check that len() can be called and previews are populated.
Todo:
- Edit docs, for example: https://www.getdaft.io/projects/docs/en/latest/10-min.html#writing-data. Will do this in separate PR.
> [BUG] Materialize Dataframes created from file writes

- daft/execution/physical_plan.py
This PR fixes a scheduler deadlock that results from an "in-progress input tasks" state mismatch between the join operator and the runner under concurrent broadcast joins.
This closes #1793.
- Physical plan scheduling operators (such as `broadcast_join()`) yield `None` back to the runner to signal that the operator is waiting for its inputs to finish executing, telling the runner to run more tasks ([example](https://github.com/Eventual-Inc/Daft/blob/4bc895273eccfe7ab093bca48280c1993c29aaec/daft/execution/physical_plan.py#L398)).
- The Python runner was failing an assertion that there are tasks to run when it receives a None from an operator ([link to assertion](https://github.com/Eventual-Inc/Daft/blob/4bc895273eccfe7ab093bca48280c1993c29aaec/daft/runners/pyrunner.py#L239-L241)); this …
> [BUG] Fix scheduler deadlock on concurrent broadcast joins.

- daft/dataframe/dataframe.py
- tests/dataframe/test_accessors.py
Closes  #1813
Add `__contains__` magic method for Dataframe so users can check if column names exist in the Dataframe using `in`, e.g. `"x" in df`
> [FEAT] Dataframe __contains__ magic method

- daft/dataframe/dataframe.py
- daft/logical/builder.py
- src/daft-dsl/src/expr.rs
- src/daft-dsl/src/functions/mod.rs
- src/daft-dsl/src/functions/python/udf.rs
- src/daft-dsl/src/treenode.rs
- src/daft-plan/src/builder.rs
- src/daft-plan/src/logical_ops/project.rs
- src/daft-plan/src/planner.rs
- src/daft-table/src/lib.rs
- src/daft-table/src/ops/agg.rs
- tests/cookbook/conftest.py
- tests/cookbook/test_aggregations.py
- tests/dataframe/test_map_groups.py
Closes #1630 
Added the `map_groups` method which allows for custom aggregation logic using a UDF in a group_by context. Usage: `df.group_by('group').map_groups(udf(col('a'), col('b')))`
Changes:
- Added map_groups API
- Added map_groups expression
- Implemented map_groups logic
- Added tests
> [FEAT] Add group_by.map_groups

- src/common/io-config/src/s3.rs
- src/daft-io/src/lib.rs
- src/daft-parquet/src/lib.rs
- src/daft-parquet/src/read_planner.rs
- tests/integration/io/parquet/test_reads_public_data.py
This PR fixes a double-await concurrency bug on `JoinHandle`s in the Parquet reader. The bug appears to arise when an a byte range fetch fails: we currently short-circuit that fetch and return an error to the stream mapper without changing the range cache state. This means that future fetches that overlap with that byte range will try to `.await` on the same `JoinHandle`, which is not allowed.
This PR fixes this by storing a `Result<Bytes, Error>` in `RangeCacheState::Ready()`, so we can stash errors from past fetches.
> [BUG] [Parquet] Fix double-await on `JoinHandle`s concurrency bug in Parquet reader.

- docs/source/user_guide/integrations.rst
- docs/source/user_guide/integrations/microsoft-azure.rst
Adds some starter documentation for using Daft with Azure services
> [DOCS] Add docs for Azure IO

- src/daft-plan/src/physical_ops/monotonically_increasing_id.rs
- src/daft-plan/src/physical_plan.rs
#1827 was failing in CI, here's the fix
> [CHORE] Fix monotonically_increasing_id physical op

- docs/source/user_guide/integrations.rst
- docs/source/user_guide/integrations/aws.rst
Integration docs on how to use Daft with AWS S3. Thanks @jaychia for paving the way with your azure docs.
> [DOCS] Add docs for AWS S3 IO

- src/daft-micropartition/src/micropartition.rs
- tests/dataframe/test_creation.py
Schema hints were not being propagated, leading to fields being dropped. 
This stemmed from an issue when reading large jsons from s3 where the fields changed only late into the file, so schema inference doesn't pick it up.
> [BUG] Schema hints not working properly for json reads

- daft/context.py
- daft/runners/partitioning.py
- daft/runners/pyrunner.py
- daft/runners/ray_runner.py
* Fixes race condition with Daft is being ran with multiple threads and creates multiple Runners. This leads to the issue of cached partition sets being dropped. Like we see in https://github.com/Eventual-Inc/Daft/issues/1843
closes: https://github.com/Eventual-Inc/Daft/issues/1843
> [BUG] Protect Global Context With Mutex

- daft/daft.pyi
- src/common/io-config/src/python.rs
- src/common/io-config/src/s3.rs
- src/daft-io/src/s3_like.rs
- src/daft-plan/src/planner.rs
This PR enables reads from S3 buckets with a requester pays policy. This configuration is set in the S3 IO Config.
Todo: integration tests? will we need to set up a requester pays bucket for this? I did test it on the 1tr row parquets tho, so it is working.
> [FEAT] Enable Requester Pay for S3 reads

- daft/analytics.py
* Uses a new segment workspace
* Update ID to restrict it to a set of 8000 unique IDs
> [CHORE] Update segment logging to use restricted set of IDs

- src/daft-scan/src/scan_task_iters.rs
- tests/io/test_merge_scan_tasks.py
> [BUG] Fix bug with merge tasks that allows for tasks larger than max size allowed

- src/daft-io/src/s3_like.rs
This should fix issues if the user provides a region and the sdk still attempts to grab region info from the provider which shows up as the following issue:
```
failed to load region from IMDS err=failed to load IMDS session token
```
This should also fix our IMDSv2 credential timeout issue we see on EKS
> [BUG] Attempt to skip IMDS if region or credentials are provided 

- daft/io/_csv.py
- daft/io/_json.py
- daft/io/_parquet.py
Schema hint documentation was out of date after: #1636 
This PR fixes our docs
> [DOCS] Update schema hints documentation

- daft/execution/execution_step.py
- daft/execution/rust_physical_plan_shim.py
- daft/runners/ray_runner.py
This PR forces a `SPREAD` scheduling strategy for scan tasks when using the Ray runner. This should result in better load balancing of read tasks across the Ray cluster, yielding:
- better utilization of the aggregate network bandwidth of the cluster,
- better memory stability due to a more even post-read object distribution,
- better performance of downstream parallel compute operations due to a more even distribution of data over the compute bandwidth of the cluster.
Closes #1940
> [PERF] Spread scan tasks over Ray cluster.

- daft/delta_lake/delta_lake_scan.py
DeltaLake SDK does not support anonymous mode access (see: issue https://github.com/delta-io/delta-rs/issues/1554)
We throw an error if a user attempts to supply `anonymous=True`.
> [CHORE] Disables anonymous mode for S3 accesses in DeltaLake

- Cargo.lock
- src/daft-micropartition/Cargo.toml
- src/daft-micropartition/src/micropartition.rs
- src/daft-micropartition/src/ops/cast_to_schema.rs
- src/daft-micropartition/src/python.rs
- src/daft-scan/src/lib.rs
This PR makes some changes to how we use `cast_to_schema` in our codebase, and also some subtle fixes which makes our code easier to refactor later on for field IDs.
I added a bunch of documentation to our structs, detailing what the correct semantics for each `schema` field is on ScanTask and MicroPartition.
Additinally:
1. `MicroPartition::new_unloaded` no longer takes in as input a schema. Instead, the unloaded MicroPartition's schema is simply its ScanTask's `materialized_schema`.
2. `materialize_scan_task` now does not take as input a `cast_to_schema` argument. Instead, it just uses the ScanTask's `materialized_schema` and `partition_spec()` for the fill map to correctly coerce all the materialized Tables.
**Share code**: Move shared code into a …
> [CHORE] Simplify cast to schema

- daft/udf.py
- tests/expressions/test_udf.py
Enables using `*args` to pass an arbitrary number of Daft series to a UDF.
> [FEAT] Enable UDF to handle arbitrary number of Daft series

- .github/workflows/python-package.yml
- daft/daft.pyi
- daft/delta_lake/delta_lake_scan.py
- requirements-dev.txt
- src/common/io-config/src/azure.rs
- src/common/io-config/src/python.rs
- src/daft-io/src/azure_blob.rs
- tests/io/delta_lake/conftest.py
- tests/io/delta_lake/mock_s3_server.py
- tests/io/test_url_download_local.py
This PR adds test coverage for reading Delta Lake tables from Azure Blob Storage (or more specifically, Azure Data Lake Storage gen2 on ABS). Since the ABS emulating server only runs on Windows, we run a session-scoped Docker container containing the cross-platform [Azurite](https://github.com/Azure/Azurite) emulator. We use a Docker container rather than a background process in order to not introduce another heavy dev dependency (`node.js`/`npm`).
Closes #1971
> [CHORE] [Catalogs] [Delta Lake] Add test coverage for Delta Lake reads on Azure.

- daft/__init__.py
- daft/io/__init__.py
- daft/io/_delta_lake.py
- daft/io/catalog.py
- pyproject.toml
- requirements-dev.txt
- tests/io/delta_lake/conftest.py
- tests/io/delta_lake/mock_aws_server.py
- tests/io/delta_lake/test_table_read.py
- tests/io/delta_lake/test_table_read_pushdowns.py
This PR adds support for reading Delta Lake tables via AWS Glue Data Catalog and Databricks Unity Catalog table references, rather than a direct data lake table URI in cloud storage.
Closes #1988 
Closes #1989
> [FEAT] [Catalogs] [Delta Lake] Add support for AWS Glue Catalog and Databricks Unity Catalog integrations to Delta Lake reader

- src/daft-io/src/object_store_glob.rs
- tests/integration/io/parquet/test_reads_s3_minio.py
> [BUG] Filter out marker files from glob scan

- pyproject.toml
The `pyarrow < 7.0.0` upper bound is needlessly restrictive, since
1. Ray already has that upper-bound since their pickle bug workaround doesn't work for Windows, so if a Windows user is using Ray + Daft, their pyarrow should already satisfy that upper bound.
2. If a user isn't using Ray, then they shouldn't need that upper bound anyway, since we're not using pyarrow + pickle when only using the local runner.
> [CHORE] [Hotfix] Remove pyarrow upper bound for Windows.

- src/daft-core/src/series/array_impl/logical_array.rs
- tests/table/struct/test_struct_get.py
Struct getters on logical types were failing with:
```
Mismatch of expected expression data type and data type from computed series, <logical> vs <physical>
```
This PR fixes this by fixing the implementation of `.with_validity` on our logical arrays, which previously were erroneously returning Series of the physical type.
> [BUG] Fix struct getters on logical types

- daft/daft.pyi
- daft/iceberg/iceberg_scan.py
- daft/iceberg/schema_field_id_mapping_visitor.py
- src/daft-micropartition/src/micropartition.rs
- src/daft-micropartition/src/python.rs
- src/daft-parquet/src/file.rs
- src/daft-parquet/src/lib.rs
- src/daft-parquet/src/metadata.rs
- src/daft-parquet/src/python.rs
- src/daft-parquet/src/read.rs
- src/daft-scan/src/file_format.rs
- src/daft-scan/src/glob.rs
- src/daft-scan/src/scan_task_iters.rs
- tests/integration/iceberg/docker-compose/provision.py
- tests/integration/iceberg/test_table_load.py
Adds capability for parsing Parquet files using a `field_id_mapping` supplied by table formats such as Apache Iceberg.
The approach taken by this PR is to mutate the Parquet `FileMetaData` object obtained through our `read_parquet_metadata` helper. We mutate this object, taking care to:
1. Rename all fields when we find a corresponding entry in the field_id_mapping
2. Drop all fields when we don't find a corresponding entry, or if the field_id is `None`
> [FEAT] Support reading Parquet files with Field ID

- requirements-dev.txt
- src/daft-core/src/datatypes/field.rs
- tests/integration/iceberg/test_pyiceberg_written_table_load.py
* Ignores metadata when comparing Fields
* Adds test that reads table written by pyiceberg
closes: https://github.com/Eventual-Inc/Daft/issues/2004
> [BUG] skip metadata check for field equality

- src/daft-micropartition/src/micropartition.rs
- src/daft-scan/src/scan_task_iters.rs
- tests/io/delta_lake/test_table_read.py
Fixes bugs in 3 places:
1. Our `num_rows` was not properly accounted for when performing ScanTask splitting
2. When creating unloaded MicroPartitions in the case where a data catalog provides file statistics, we inadvertently create these MicroPartitions with wrong `TableMetadata.length` in cases where a limit or a filter was applied in the pushdown
3. When running `read_parquet_into_micropartition` in the case where a data catalog does not provide file statistics, we wrongly create an unloaded MicroPartition when a limit was applied in the pushdown
> [BUG] deltalake read pq splitting bug

- src/daft-core/src/datatypes/binary_ops.rs
- src/daft-core/src/series/ops/is_in.rs
- src/daft-dsl/src/expr.rs
- tests/expressions/typing/test_compare.py
- tests/series/test_comparisons.py
- tests/table/test_is_in.py
* Disables comparisons between Utf8 and numeric types
> [BUG] Disable Numeric and String comparison 

- requirements-dev.txt
Use psycopg-binary as benchmarking runner does not have required libraries installed. Fixed here: https://github.com/Eventual-Inc/daft-benchmarking/actions/runs/8291353023
Use connector-x 0.2.3 on linux on aarch-64. Fixed here: https://github.com/Eventual-Inc/Daft/actions/runs/8291745511
> [BUG] Fix connector-x and psycopg dependencies for CI

- docs/source/api_docs/expressions.rst
`is_in` seems to not be very discoverable, I think this should fix it a litle.
> [CHORE] Fix is_in docs

- docs/source/user_guide/integrations/delta_lake.rst
This PR breaks the data skipping optimizations into a separate section, to give it a stronger emphasis.
> [DOCS] [Hotfix] [Delta Lake] Break data skipping optimizations into different section.

- daft/io/_delta_lake.py
Add expert IO multithreading arg to `daft.read_delta_lake()`, allowing the user to explicitly enable or disable IO multithreading.
> [PERF] [Delta Lake] Add IO multithreading arg to `daft.read_delta_lake()`.

- src/daft-core/src/array/ops/full.rs
- src/daft-core/src/array/ops/image.rs
- src/daft-core/src/series/ops/downcast.rs
- tests/table/image/test_decode.py
Fixes bug where a fast-path for `ImageArray` with all nulls would cause a length-0 array to be created
> [BUG] Fix all-null ImageArray length issues

- daft/daft.pyi
- daft/sql/sql_scan.py
- src/daft-scan/src/python.rs
Add min max column range stats from read_sql when possible.
> [CHORE] Add column range stats from read_sql

- src/daft-core/src/array/ops/if_else.rs
- tests/table/test_if_else.py
When predicate is broadcasted in the if_else kernel and the predicate is false, the if_false series is cloned and the name is unchanged, which causes a 
```
ValueError: DaftError::ComputeError Mismatch of expected expression name and name from computed series
```
at expression evaluation time because the expected field name is the [if_true series name. ](https://github.com/Eventual-Inc/Daft/blob/main/src/daft-dsl/src/expr.rs#L530)
Example code to reproduce:
```
df = daft.from_pydict({"predicate": [False], "if_true": ["true"], "if_false": ["false"]})
df = df.select((df["predicate"] == True).if_else(df["if_true"], df["if_false"]))
df.show()
```
> [BUG] Fix if_else series naming from predicate broadcast

- daft/filesystem.py
- tests/integration/io/test_write_files_s3_minio.py
> [BUG] Allow for writes to s3a and s3n paths

- docs/source/user_guide/daft_in_depth/dataframe-operations.rst
Fixed some typos + suggestion to reformulate `repartition` sentence to apply to both parallel and distributed scenarios
> [DOCS] Typos in user guide

- src/daft-core/src/array/ops/utf8.rs
- tests/series/test_utf8_ops.py
Currently a lot of our string kernels have duplicated code to check for empty arrs and null arrs. They also have giant match statements to determine if broadcasting is needed. 
This PR unifies the empty arr checks, null arr checks, and broadcastable length checks into a single helper function. The actual broadcasting logic is simplified by an enum that wraps either a broadcasted repeat iter, or a normal non-broadcastet iter. 
Prior work on this was done in the [str.replace](https://github.com/Eventual-Inc/Daft/pull/2048/files#diff-42205d5e909fe98537eb8d32b1d41037aec1a24e5cded377d0544304551ae070R15-R62) PR, which otherwise would have had like a 12 way match statement or smth.
Additionally, this PR adds a `unary_broadcasted_op` helper function to simplify the code for single argument …
> [CHORE] Refactor string kernels

- Makefile
- requirements-dev.txt
`uv` is much faster than `pip` and there have been many projects that have used it to replace `pip`.
> [CHORE] Using `uv` in MakeFile

- .readthedocs.yaml
`uv` discovers virtual envs using:
> An activated virtual environment based on the VIRTUAL_ENV environment variable.
This PR adds this environment variable in our readthedocs environment so that `uv` can correctly discover the venv.
> [CHORE] Fix documentation build with uv

- .readthedocs.yaml
Second attempt at fixing the readthedocs build
> [CHORE] Fixing readthedocs build

- daft/io/_delta_lake.py
This PR sets the account Id into glue call, so users can access catalog in another account.
Tested in our dev environment.
> deltalake _delta_lake.py: Allow Glue catalog cross account access

- src/daft-micropartition/src/micropartition.rs
- tests/integration/iceberg/test_table_load.py
- tests/io/delta_lake/test_table_read_pushdowns.py
Fixes pushdowns for column selection on partition keys in DeltaLake and Iceberg.
When table formats such as Iceberg and Delta Lake store the data for a partition column, they will strip the column from the actual Parquet data files that they write out. Then when we want to select only specific columns, our Parquet reader fails when it is not able to find those columns in the file.
NOTE: Seems like Iceberg only does this for identity transformed partition columns
Follow-on issue for selection of **only** the partition keys: https://github.com/Eventual-Inc/Daft/issues/2129
> [BUG] Fix reading partition key columns in DeltaLake

- .github/workflows/release-drafter.yml
Triggers the auto-labelling CI using the `pull_request_target` trigger instead of `pull_request`, which should fix issues relating to that CI step not passing from PRs initiated from forks.
> [CHORE] Fix autolabeller CI step for forks

- .github/workflows/release-drafter.yml
It appears the `github.ref` when using `pull_request_target` will be the target branch, and not the PR's branch. This results in the checking step skipping, and all PRs are allowed even if they don't contain the required labels.
> [CHORE] Fix the labeller CI step which is not triggering

- README.rst
Fixes the odd underlines in our README's code.
See: https://github.com/orgs/community/discussions/113792
> [CHORE] Fix underlines in README

- daft/analytics.py
- daft/api_annotations.py
> [FEAT] hide stack traces of wrappers for pytest / ipython

- daft/udf.py
- tests/expressions/test_udf.py
Allow for `**kwargs` in UDFs, similar to how we implemented `*args`
> [FEAT] Allow for variadic kwargs in UDFs

- src/daft-scan/src/glob.rs
This adds a more descriptive error message to the `glob_scan` to direct users towards recursive listing capabilities
Closes #2109
> [CHORE] improve recursive listing error msg

- Cargo.lock
- Cargo.toml
* fixes an issue where we have non-type-aligned buffers passing into arrow 2 with https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html#safety
* Newer versions of the rust complier introduce a check for type aligned pointers.
> [BUG] bump arrow2 to use copy ptr instead of from_raw_parts

- daft/delta_lake/delta_lake_scan.py
Enables anonymous mode for deltalake reading
Verified that this works:
```
df = daft.read_delta_lake("s3://daft-public-data/nyc-taxi-dataset-2023-jan-deltalake/", io_config=daft.io.IOConfig(s3=daft.io.S3Config(anonymous=True, region_name="us-west-2")))
```
> [FEAT] Enable anonymous S3 access for Delta

- Cargo.lock
- Cargo.toml
closes #2211 
```sh
> otool -L daft/daft.abi3.so | grep 'liblzma'   
```
> [CHORE]: statically link liblzma

- src/daft-io/src/lib.rs
- src/daft-io/src/object_io.rs
- src/daft-parquet/src/file.rs
- src/daft-parquet/src/read_planner.rs
* Wait on errors for the first chunk to finish in the parquet reader
* No longer panic on error when encountering them in the byte reader
* Unwrap cached error when exporting
> [BUG] Propagate errors when hitting them in parquet byte stream

- docs/source/faq/dataframe_comparison.rst
- docs/source/migration_guides/coming_from_dask.rst
This PR:
- converts the Dask Migration Guide to .rst format
- adds a section for Dask in the dataframe comparison FAQ with a link to the migration guide
> [Docs] Add Dask to DF Comparison FAQ

- daft/__init__.py
- daft/daft.pyi
- daft/delta_lake/delta_lake_scan.py
- daft/io/__init__.py
- daft/io/_lance.py
- daft/io/_lancedb.py
- daft/io/object_store_options.py
- pyproject.toml
- requirements-dev.txt
- src/daft-micropartition/src/micropartition.rs
- src/daft-micropartition/src/python.rs
- src/daft-plan/src/physical_planner/translate.rs
- src/daft-scan/src/file_format.rs
- src/daft-scan/src/glob.rs
- src/daft-scan/src/lib.rs
- src/daft-scan/src/python.rs
- src/daft-scan/src/scan_task_iters.rs
- tests/io/delta_lake/conftest.py
- tests/io/delta_lake/test_table_read.py
- tests/io/delta_lake/test_table_read_pushdowns.py
- tests/io/lancedb/test_lancedb_reads.py
Adds the ability to read a Lance dataset: https://lancedb.github.io/lance/read_and_write.html
> [FEAT] Read from LanceDB

- daft/dataframe/dataframe.py
- daft/execution/physical_plan.py
- daft/io/file_path.py
- daft/runners/partitioning.py
- daft/runners/pyrunner.py
- daft/runners/ray_runner.py
* When enabling AQE, we introduce intermediate materializations for a query with multiple shuffles.
* The problem with this is that metadata is not preserved across materialization boundaries. 
* So if we are running a SortMergeJoin and we draw a boundary after the sort and before the join, the algorithm errors out because the `boundaries` value is not set on the `MaterializedResult`.
* This happens because at the `.collect()` point, we place `Micropartitions` into the cache rather than the `MaterializedResult` which contains both the data and `PartitionMetadata`.
We already do this behavior for the ray runner, this PR formalizes it for all runners.
> [PERF] enable metadata preservation across materialization points

- src/daft-dsl/src/expr.rs
- src/daft-table/src/lib.rs
- tests/table/test_if_else.py
Closes #2190 
If the predicate for an if_else statement is a boolean, i.e true/false, we only need to evaluate one side of the expression.
> [PERF] Evaluate only true/false side of if_else if predicate is boolean

- src/daft-csv/src/read.rs
- src/daft-json/src/read.rs
this is just a small change to remove the usage of unstable [trait_aliases](https://doc.rust-lang.org/unstable-book/language-features/trait-alias.html) in favor of trait impls. 
This greatly improves the developer experience because rust-analyzer can now properly detect the types.
> [CHORE]: remove trait aliases

- src/daft-dsl/src/expr.rs
- src/daft-dsl/src/functions/list/count.rs
- src/daft-dsl/src/functions/python/udf.rs
- src/daft-dsl/src/python.rs
- src/daft-plan/src/builder.rs
- src/daft-plan/src/logical_ops/join.rs
- src/daft-plan/src/logical_ops/project.rs
- src/daft-plan/src/logical_optimization/rules/push_down_filter.rs
- src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
- src/daft-plan/src/physical_ops/explode.rs
- src/daft-plan/src/physical_ops/project.rs
- src/daft-plan/src/physical_planner/translate.rs
- src/daft-table/src/lib.rs
- src/daft-table/src/ops/explode.rs
- src/daft-table/src/ops/joins/mod.rs
We return a `DaftResult<&str>` for expression names, but currently there's no case that would raise an error. Having the return type as `&str` should be sufficient.
> [CHORE] Return &str for expression name

- daft/expressions/expressions.py
Fixes tab completion for our namespaced accessors:
One crappy part is that it shows some of the `@property` functions (e.g. `def fget`) in there. This is because the jedi interpreter/parser is seeing that it could potentially be aliased in the Sphinx path.
Here's where there is a strong assertion about the name having to be `@property` instead of some alias like we have here.
https://github.com/davidhalter/jedi/blob/f7c9ee943390d9d3102b1992c9d3b6c7d224c16c/jedi/parser_utils.py#L341-L345
> [BUG] Fix tab completion on expression namespaced accessors

- src/daft-core/src/series/ops/utf8.rs
A few fixes to reduce a lot of boilerplate:
- Add a method, `with_utf8_array`, that properly handles Series to Utf8Array conversion, so that string kernels have consistent behavior with NullArrays
- Convert all of the integer matching code to use the `with_match_integer_daft_types` macro.
> [CHORE] Clean up string kernel code

- daft/runners/progress_bar.py
Finally figured out the issue! When using `tqdm.auto`, the library does correctly fall back to regular tqdm if the `ipywidgets` library is not present, but the thing is that `tqdm` by default actually writes to STDERR instead of STDOUT, which shows up in a notebook but no the command line. 
This fix changes the default file from `sys.stderr` to `sys.stdout` for tqdm when we are in an IPython environment.
Resolves #2083
> [BUG] Fix red line in Jupyter notebook

- .github/workflows/python-package.yml
- requirements-dev.txt
The latest version of docker-py fails on the latest version of requests
See: https://github.com/docker/docker-py/issues/3256
> [CHORE] Pin requests to fix docker-py CI issue

- daft/runners/ray_runner.py
- tests/dataframe/test_repartition.py
Fixes a user-reported bug around `into_partitions` failing on the Ray runner for a specific corner-case: when **some** input partition wasn't split, the RayRunner was performing an overly-aggressive assert that should be relaxed.
> [BUG] Fix multi-output tasks in RayRunner

- daft/runners/ray_runner.py
Uses a detached named actor for the RayRunner.
This means that if multiple Daft executions are run from different clients on a Ray cluster, they will all run on the same Ray actor.
> [FEAT] Use detached named actor for RayRunner

- daft/daft.pyi
- daft/table/table.py
- src/daft-parquet/src/lib.rs
- src/daft-parquet/src/python.rs
- src/daft-parquet/src/read.rs
- tests/integration/io/parquet/test_reads_public_data.py
* This implements a file level timeout for parquet reader into pyarrow with a default of 15 minutes.
> [FEAT] implement timeout for parquet reader

- daft/sql/sql_scan.py
When running `read_sql` against SQL server using a SQL Alchemy connection, for example:
```
connection_url = sqlalchemy.engine.URL.create(
"mssql+pyodbc",
username=user,
password=password,
host=host,
port=1433,
database=database,
query={
"driver": "ODBC Driver 18 for SQL Server",
},
)
def create_conn():
return sqlalchemy.create_engine(connection_url).connect()
df = daft.read_sql("SELECT * FROM test_data", create_conn)
```
The query errors with `Unsupported dialect: mssql, please refer to the documentation for supported dialects`.
This is because SQLGlot, the library that read_sql uses for query construction, does not recognize `mssql` as a dialect, it instead recognizes `tsql`, which is the name of the SQL dialect for Microsoft SQL Server: …
> [BUG] Translate mssql to tsql in read_sql scan

- Cargo.lock
- daft/daft.pyi
- daft/io/_iceberg.py
- daft/io/object_store_options.py
- src/common/io-config/src/azure.rs
- src/common/io-config/src/gcs.rs
- src/common/io-config/src/python.rs
- src/daft-io/Cargo.toml
- src/daft-io/src/azure_blob.rs
Adds:
- login via shared access signatures (SAS)
- login via Entra ID (active directory) using tenant id + client id + client secret
- fallback to environment variables using azure-sdk-for-rust
Tested locally 👍
> [FEAT] Add additional Azure authentication methods

- daft/filesystem.py
- daft/hudi/hudi_scan.py
- daft/hudi/pyhudi/table.py
- daft/hudi/pyhudi/timeline.py
- daft/hudi/pyhudi/utils.py
Closes https://github.com/Eventual-Inc/Daft/issues/2295
This PR modifies the path joining logic in read_hudi to only use `os.path.join` if the file system is a local filesystem, and otherwise manually join paths using `/`. This fixes the issue of reading Hudi from S3 on a Windows machine.
Simulated a hudi read from Windows with:
```
from unittest.mock import patch
import daft
with patch("os.path.join", side_effect=lambda *args: "\\".join(args)):
df = daft.read_hudi("s3://daft-public-data/hudi/v6_simplekeygen_nonhivestyle/")
df.show()
```
> [BUG] Use os.path.join in read_hudi only for local fs

- src/daft-csv/src/metadata.rs
- src/daft-csv/src/read.rs
- src/daft-io/src/azure_blob.rs
- src/daft-io/src/google_cloud.rs
- src/daft-io/src/http.rs
- src/daft-io/src/lib.rs
- src/daft-io/src/object_io.rs
- src/daft-io/src/s3_like.rs
- src/daft-json/src/read.rs
- src/daft-json/src/schema.rs
```
(ScanWithTask-Aggregate [Stage:2] pid=331774) Received Socket Error when streaming bytes! Attempt 1 out of 3 tries. Trying again in 197ms
(ScanWithTask-Aggregate [Stage:2] pid=331774) Details
(ScanWithTask-Aggregate [Stage:2] pid=331774) Unable to read data from file s3://XXX/redpajama-data-v2/v1.1.0/data/2023-06/2023-06_2081_en_middle.parquet: error reading a body from connection: end of file before message length reached
```
> [BUG] Add Retry on Streaming Errors when collecting stream into bytes

- Cargo.lock
- src/daft-plan/Cargo.toml
- src/daft-plan/src/display.rs
Introduces text wrapping when explaining a plan:
> [FEAT] Introduce terminal wrap around when explaining plans

- tests/integration/io/test_list_files_azure.py
Added some JSON files that broke these tests, this quick change will fix it
> [BUG] Allow any file extension in Azure directory listing test

- src/daft-scan/src/python.rs
- src/daft-stats/src/partition_spec.rs
- tests/io/delta_lake/conftest.py
- tests/io/delta_lake/test_table_read.py
- tests/io/delta_lake/test_table_read_pushdowns.py
Closes https://github.com/Eventual-Inc/Daft/issues/2292
Currently Daft panics if there are nulls in a partition column, the detailed error message can be found in the linked issue.
A simple reproduction:
```
from deltalake import write_deltalake
import pandas as pd
import daft
df = pd.DataFrame(
{
"group": [1, 2, 3, None],
"num": list(range(4)),
}
)
write_deltalake("z", df, partition_by="group", mode="overwrite")
df = daft.read_deltalake("z")
df.show()
```
This PR modifies the partition spec equality logic and partition pruning semantics to allow reading nulls in partition columns.
> [BUG] Allow nulls in partition column

- CONTRIBUTING.md
I was setting up daft dev environment on my local and was following along the contribution guidelines. my default python env is currently at `3.12` and noticed that the `make .venv` keeps failing due to dependency on `ray[data]==2.10.0`. the failure happens because the current `ray-data` is only compatible till `python3.11`.
> [DOCS] the project currently uses ray which is not compatible with python 3.12

- docs/source/user_guide/basic_concepts/read-and-write.rst
- docs/source/user_guide/integrations/sql.rst
I was having trouble using `read_sql` today because I was following the usage recommended [here](https://www.getdaft.io/projects/docs/en/latest/user_guide/basic_concepts/read-and-write.html#from-databases).
Made a few small changes to correct the syntax and make it easier for folks to find the SQL integration user guide which lists required dependencies etc.
> [DOCS] improve SQL docs

- daft/udf.py
- tests/dataframe/test_iter.py
- tests/expressions/test_udf.py
- tests/integration/io/test_url_download_http.py
- tests/udf_library/test_url_udfs.py
This PR adds some context around failures of UDFs, and also has the side-effect of quite nicely isolating the actual exception to just the UDF code so users can be sure that the code failed in the UDF rather than in some part of Daft.
```
In [4]: daft.from_pydict({"foo": [1]}).with_column("identity", throws_error_if_len_1(daft.col("foo"))).collect()
Project [Stage:2]:   0%|                                                                                                    | 0/1 [00:00<?, ?it/s]---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~/code/Daft/daft/udf.py:108, in PartialUDF.__call__(self, evaluated_expressions)
107 try:
--> 108     result = func(*args, **kwargs)
109 except …
```
> [FEAT] Add more context when UDFs fail

- .github/workflows/python-package.yml
- Cargo.lock
- daft/dataframe/dataframe.py
- daft/expressions/expressions.py
- src/common/daft-config/src/lib.rs
- src/daft-core/Cargo.toml
- src/daft-core/src/utils/display_table.rs
Add tests for our docs to CI
Currently the tests don't affect the CI checks because of the extra `|| true` after the test command, but once all the examples have been fixed I'll remove it.
See the run here: https://github.com/Eventual-Inc/Daft/actions/runs/9490371825/job/26153717399?pr=2362
I also changed our `daft.col` example to make it work and show that it actually runs and is tested.
> [CHORE] Run doctests in CI

- daft/expressions/expressions.py
closes https://github.com/Eventual-Inc/Daft/issues/2366
> [BUG]: ide completions for expr namespaces

- .github/workflows/python-package.yml
- tests/integration/io/docker-compose/retry_server/retry-server-requirements.txt
Pins numpy version, otherwise we get an error while running Docker-compose up.
Seems like the latest numpy version dropped yesterday (v2.0.0) isn't compatible with pyarrow 12 because pyarrow was built against numpy 1.
> [BUG] Fix IO integration tests

- src/daft-execution/src/stage/planner.rs
* Print node type when hitting todo in execution stage planner
> [FEAT] print more info when hitting todo in stage planner

- src/daft-core/src/array/ops/cast.rs
- tests/series/test_slice.py
Resolves https://github.com/Eventual-Inc/Daft/issues/2394
When we call `into_partitions` on a dataframe with list arrays, the list arrays are sliced. However, the implementation of [list array slice](https://github.com/Eventual-Inc/Daft/blob/main/src/daft-core/src/array/list_array.rs#L139) simply slices the offsets, and leaves the data unchanged.
If the column is then casted to a fixed size list array (and there is no validity bitmap), we will just copy the data, which leads to a series length mismatch error.
This PR makes a fix to slice the data during a cast.
Example:
```
import daft
import numpy as np
import pandas as pd
N_ROWS = 4
N_ELEMENTS_IN_LIST = 2
N_PARTITIONS = 2
num = [i for i in range(N_ROWS)]
fixed_list = [np.random.randint(0, 100, size=N_ELEMENTS_IN_LIST).tolist() for _ in …
```
> [BUG] Slice array if necessary when casting from list to fixed size list

- daft/iceberg/iceberg_scan.py
- daft/io/_iceberg.py
- tests/integration/iceberg/docker-compose/provision.py
- tests/integration/iceberg/test_table_load.py
> [FEAT] Add ability to specify snapshot_id for iceberg read

- daft/daft.pyi
- daft/io/object_store_options.py
- src/common/io-config/src/azure.rs
- src/common/io-config/src/python.rs
- src/daft-io/src/azure_blob.rs
Adds the `bearer_token` parameter to `daft.io.AzureConfig`
Raised in #2427
> [FEAT] Add bearer token authentication for Azure

- src/arrow2/src/io/parquet/mod.rs
- src/common/error/src/error.rs
- src/parquet2/src/error.rs
* This allows errors raised during thrift decoding to be raised up as daft transient errors
> [FEAT] thread through transport errors

- daft/execution/rust_physical_plan_shim.py
- src/daft-plan/src/physical_planner/translate.rs
- src/daft-scan/src/scan_task_iters.rs
- tests/io/test_merge_scan_tasks.py
Unblocks #2383, users can now set the `parquet_inflation_factor` execution config to prevent large scan tasks from merging and tasks from scheduling when there isn't enough memory
In the future we might want to read a few files/metadata to obtain a better estimate
> [BUG] Use estimated in-memory size for scan task merging and resource requests

- daft/expressions/expressions.py
I realized I forgot to remove this when we decided that `Expression.map.get` should not support syntactic sugar
> [DOCS] Remove unsupported map get doc example

- daft/daft.pyi
- daft/io/object_store_options.py
- docs/source/user_guide/integrations/microsoft-azure.rst
- src/common/io-config/src/azure.rs
- src/common/io-config/src/python.rs
- src/daft-io/src/azure_blob.rs
Adds the ability for users to connect to Microsoft Fabric without having to pass in a custom endpoint URL. Also includes updates to documentation and tutorials.
Thank you to @djouallah in #2460 for the help in updating the docs!
> [FEAT] Microsoft Fabric support in AzureConfig

- docs/source/_static/custom.js
- docs/source/conf.py
This PR adds the RunLLM chat widget to the Daft documentation site.
> [DOCS] Adds RunLLM widget

- .github/workflows/build-artifact-s3.yml
This helps print a message so we can copy-paste it to install the built artifact
> [CHORE] Add a helpful message in build-artifact-s3 workflow

- daft/udf.py
Updates the typing for `class UDF` to allow for both function UDFs and stateful class UDFs
> [CHORE] Add better typing for class UDFs

- daft/table/table_io.py
- requirements-dev.txt
Daft had some bad code when handling newer versions of delta-rs
> [BUG] Support delta-rs version >0.17.4 in deltalake writes

- daft/delta_lake/delta_lake_scan.py
**Before:** Without user intervention (by passing in explicit credentials), Daft would pass in `None` for credentials when instantiating the `DeltaTable` objects, causing auth issues with S3.
**After:** We detect and special-case when there are no credentials being passed in, and try to use Daft's credentials chain to override the empty credentials before instantiating the `DeltaTable`
> [BUG] Use Daft s3 credentials chain for deltalake reads

- src/daft-core/src/array/ops/groups.rs
- src/daft-core/src/array/ops/hash.rs
- src/daft-core/src/datatypes/matching.rs
- src/daft-core/src/series/ops/groups.rs
- src/daft-core/src/series/ops/hash.rs
- tests/series/test_hash.py
- tests/table/test_table_aggs.py
Implements hashing and groupby on lists and fixed-size lists. Works by recursively hashing the inner items and then hashing the hashes.
Closes #1983
Example:
```
>>> df = daft.from_pydict({"a": [[1, 2], [1, 2], [1, 3, 4], [1, 2], [1, 3, 4]], "b": [1, 2, 3, 4, 5]})
>>> df.groupby("a").agg_list("b").show()
╭─────────────┬─────────────╮
│ a           ┆ b           │
│ ---         ┆ ---         │
│ List[Int64] ┆ List[Int64] │
╞═════════════╪═════════════╡
│ [1, 3, 4]   ┆ [3, 5]      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ [1, 2]      ┆ [1, 2, 4]   │
╰─────────────┴─────────────╯
```
> [FEAT] Implement hashing and groupby on lists

- daft/table/table_io.py
Writes to cloudflare R2 storage sometimes fail when a timeout is reached. In the current retry logic, this error is not being caught. This PR allows catching this error by looking for the substring `curlCode: 28, Timeout was reached` which is thrown by the arrow parquet writer when timeouts are reached.
> [BUG] Add retries for write timeout errors

- daft/dataframe/dataframe.py
- docs/source/api_docs/dataframe.rst
- tests/dataframe/test_transform.py
As in PySpark, the transform functionality allows you to split your transformations into units of work, creating a function for each, and then call them on your DataFrame, enabling the ability to chain transformations.
Having your transformations as functions helps in unit testing them.
```
def bussines_rule_1(df):
df = (
df
.with_column(......)
.with_column(......)
.with_column(......)
)
return df
def bussines_rule_2(df):
df = (
df
.with_column(......)
.with_column(......)
)
return df
df = (
df
.transform(bussines_rule_1)
.transform(bussines_rule_2)
)
```
[PySpark reference](https://spark.apache.org/docs/latest/api/python/_modules/pyspark/sql/dataframe.html#DataFrame.transform)
> [FEAT] adding transform functionality

- Cargo.lock
- daft/daft.pyi
- daft/io/_csv.py
- daft/io/_json.py
- daft/io/_parquet.py
- daft/io/common.py
- src/daft-micropartition/src/micropartition.rs
- src/daft-micropartition/src/python.rs
- src/daft-parquet/src/python.rs
- src/daft-parquet/src/read.rs
- src/daft-parquet/src/stream_reader.rs
- src/daft-plan/src/physical_planner/planner.rs
- src/daft-scan/Cargo.toml
- src/daft-scan/src/anonymous.rs
- src/daft-scan/src/glob.rs
- src/daft-scan/src/lib.rs
- src/daft-scan/src/python.rs
related to https://github.com/Eventual-Inc/Daft/issues/2257
Notes for reviewer:
this kind of feels like a "brute force" approach as I just added `parquet_metadata` field to `AnonymousDataFile`, but I couldn't find a better way of doing it without sufficient refactoring. If there are better alternatives, I'm all ears 😄 
I also didn't really like that I had to pass it down to all of the different `*_read_parquet_*` functions, but once again, I wanted to avoid unnecessary refactoring. 
Some local tests using the file mentioned in the issue show over 100% increase. 
- main: 25sec 782ms
- feature branch: 11sec 641ms
> [PERF]: dont read parquet metadata multiple times

- src/daft-plan/src/logical_plan.rs
- tests/dataframe/test_sample.py
Addresses: #2510
Fixed:
```
import daft
x1 = daft.from_pydict({"foo": [1, 2], "bar": [1, 2]}) 
x2 = daft.from_pydict({"foo": [3, 4], "bar": [3, 4]}) 
x1 = x1.sample(0.5) 
x2 = x2.sample(0.5) 
xx = x1.concat(x2) 
xx = xx.select('foo') 
print(xx.collect())
```
> [BUG] With_new_children not implemented for sample

- daft/table/table.py
- src/daft-csv/src/read.rs
- src/daft-execution/src/task/mod.rs
- src/daft-execution/src/test/mod.rs
- src/daft-json/src/local.rs
- src/daft-json/src/read.rs
- src/daft-parquet/src/file.rs
- src/daft-parquet/src/lib.rs
- src/daft-parquet/src/python.rs
- src/daft-parquet/src/read.rs
- src/daft-parquet/src/stream_reader.rs
- src/daft-plan/src/source_info/file_info.rs
- src/daft-stats/src/table_stats.rs
- src/daft-table/src/ffi.rs
- src/daft-table/src/lib.rs
- src/daft-table/src/ops/agg.rs
- src/daft-table/src/ops/explode.rs
- src/daft-table/src/ops/joins/hash_join.rs
- src/daft-table/src/ops/joins/mod.rs
- src/daft-table/src/ops/pivot.rs
- src/daft-table/src/ops/unpivot.rs
- src/daft-table/src/python.rs
- tests/dataframe/test_creation.py
- tests/integration/io/parquet/test_reads_s3_minio.py
- tests/table/table_io/test_parquet.py
Fixes to allow for reading Parquet files and specifying **columns that do not exist in the Parquet file**.
This is common when we try to "apply" a schema from some external source (e.g. a data catalog). In that case, old Parquet files may not have certain columns because the schema evolved over time. We want to make sure that reads still succeed on these files, and we get back tables with the appropriate number of rows (even if no columns were read!)
**Fixes to Parquet reader**
1. Allows for reads of Parquet files with `column` names that may not exist in the file. These columns will just be missing from the returned `Table`. Note that this potentially means we get empty `Tables` with valid number of rows.
**Fixes on `Table`**
1. Fixes `Table` to allow empty (num_rows=0) tables that still …
> [BUG] Allow for Parquet reading from files with differing schemas

- src/daft-plan/src/physical_planner/translate.rs
- tests/dataframe/test_aggregations.py
Previously, putting an any_value in an aggregate function would result in no output column:
```python
>>> df = daft.from_pydict({
...     "a": [1, 3, 2],
...     "b": [1, 2, 2],
... }).into_partitions(2)
>>> res = df.groupby("b").agg(col("a").any_value())
>>> res.show()
╭───────╮    
│ b     │                                   
│ ---   │                            
│ Int64 │                           
╞═══════╡
│ 1     │
├╌╌╌╌╌╌╌┤
│ 2     │
╰───────╯
```
New output:
```python
>>> df = daft.from_pydict({
...     "a": [1, 3, 2],
...     "b": [1, 2, 2],
... }).into_partitions(2)
>>> res = df.groupby("b").agg(col("a").any_value())
>>> res.show()
╭───────┬───────╮ 
│ b     ┆ a     │
│ ---   ┆ ---   │
│ Int64 ┆ Int64 │
╞═══════╪═══════╡
│ 1     ┆ 1     │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2     ┆ 3     │ …
```
> [BUG] Fix bug with multi-partition `any_value`

- daft/runners/pyrunner.py
1. Fixes the thread pool aspect of #2493 by lifting the `thread_pool` from a local per-generator variable to a shared `self._thread_pool` in the singleton runner
2. Fixes the shared resources aspect of #2493 by lifting the `inflight_tasks_resources` and `inflight_tasks` to shared variables in the singleton runner
The second part of this is a little dangerous because of the way these variables are used that can introduce a potential race condition:
1. `self._can_admit_task` checks against the `inflight_tasks_resources` to see if a task can be admitted
2. If so, we then proceed with submitting a task to the thread pool and updating `inflight_tasks_resources`
If another iterator is somehow able to update `inflight_tasks_resources` between steps 1 and 2, then our resource accounting would …
> [BUG] Use shared thread pool for multiple running instances of df on pyrunner
