- notebooks/tutorials/quickstart.ipynb
Simplifies the quickstart aggregation step, which previously performed a recall calculation that was a little too difficult to understand for a Quickstart tutorial
> Simplify quickstart aggregation step

- daft/dataframe/dataframe.py
- daft/expressions.py
- daft/udf.py
Cleans up public-facing docstrings in:
* dataframe.py
* expressions.py
* udf.py
> Cleanup on docstrings for API docs

- daft/viz/dataframe_display.py
Fixes Issue #184 
* Use a `HAS_PILLOW` variable to perform an optional import of `PIL`. We can then use `PIL` to appropriately resize images before displaying.
> Resize images when displaying in table

- daft/dataframe/dataframe.py
- daft/datasources.py
- daft/execution/logical_op_runners.py
- daft/execution/operators.py
- daft/logical/logical_plan.py
- daft/runners/blocks.py
- daft/runners/partitioning.py
- tests/dataframe_cookbook/test_write.py
* Enables Parquet and CSV File writing
* supports compression for Parquet
* supports column partitioning for csv and parquet
> DataFrame File Write

- daft/viz/repr_html.py
* The tabulate library's maxcolwidth argument does not work with HTML tables
* It appends \n characters, which manifest as spaces in the text instead of breaking the line with a HTML <br> tag
> Fix random spaces appearing in long strings in tables

- docs/source/_templates/layout.html
- docs/source/conf.py
- docs/source/dataframe_comparison.rst
- docs/source/index.rst
* Adds Dataframe Comparison docs
* Makes the ``pip install`` blurb on index stand out more with styling
* Adds backlink to github page
* Adds analytics
> [Docs] Dataframe comparison

- daft/internal/kernels/search_sorted.cc
* Fixes wrongful assertion when having a empty table in search_sorted
> Fix bug in search sorted when table is empty and has no chunks

- daft/runners/blocks.py
* Introduces a hack to handle the case when we are performing a take on a 32 but var len array.
> Arrow Negative Slice Bug Fix

- daft/dataframe/schema.py
- daft/execution/operators.py
- daft/expressions.py
- daft/logical/logical_plan.py
- daft/runners/partitioning.py
- daft/types.py
- daft/viz/repr_html.py
- tests/dataframe_cookbook/test_dataloading.py
- tests/dataframe_cookbook/test_python_list_cols.py
- tests/logical/test_logical_plan.py
- tests/test_expression_types.py
* [REFACTOR] Moves ExpressionTypes from daft.execution.operators to daft.types module
> Refactor ExpressionTypes in daft.execution.operators to daft.types module

- daft/runners/blocks.py
* BugFix: rounding error when performing large take on binary/string array
* This now allows TPCH benchmarking q9 to pass
> BugFix: rounding error when performing large take on binary/string array

- benchmarking/tpch/__main__.py
- pyproject.toml
* Removes try in benchmarking when error is thrown
> Remove try in benchmarking

- poetry.lock
- pyproject.toml
* fixes crash when using ray and py37
> add pickle5 to requirements when under python3.8

- poetry.lock
- pyproject.toml
- tests/assets/assets.py
- tests/dataframe_cookbook/conftest.py
- tests/dataframe_cookbook/test_dataloading.py
- tests/experimental/datarepo/test_datarepo_client.py
- tests/runners/test_pyrunner.py
- tests/stress_tests/test_tpch.py
* We had an issue where we pushed a broken wheel to PYPI. This PR ensures that we now test it before it gets uploaded
> Test Wheels after building to verify they work

- daft/dataframe/dataframe.py
- daft/execution/logical_op_runners.py
- daft/logical/logical_plan.py
- daft/logical/optimizer.py
- daft/runners/blocks.py
- tests/dataframe_cookbook/test_aggregations.py
- tests/dataframe_cookbook/test_distinct.py
* This allows us to remove the hack in projection aggregate pass for column pruning that tries to eliminate our dummy column that we use to makeshift aggregate as distinct
* Allows agg_with_groups in blocks.py to be run without any columns to agg
> implement distinct logical plan and remove hack in aggregate

- daft/execution/logical_op_runners.py
* Filter out nulls when sampling data to run sort function
> Filter out nulls when running sample function for sort shuffle op

- daft/internal/kernels/memory_view.h
- daft/internal/kernels/search_sorted.cc
- tests/conftest.py
- tests/internal/test_search_sorted.py
- tests/null_tests/test_sorts.py
* Adds Null handling in search sorted where NULL is greater than all values
* Adds tests for sorting with nulls
> add new kernels for search sorted to handle nulls

- daft/dataframe/dataframe.py
- daft/execution/logical_op_runners.py
- daft/internal/kernels/hashing.cc
- daft/logical/logical_plan.py
- daft/runners/blocks.py
- tests/null_tests/test_aggregations.py
- tests/null_tests/test_distinct.py
- tests/null_tests/test_joins.py
- tests/null_tests/test_sorts.py
* Add tests for nulls during joins/groupbys/aggregations/sorts/distinct
* Adds fix for joins to work on columns with nulls
> Null tests for sorts/aggregates/joins/distinct and fixes

- benchmarking/tpch/__main__.py
- daft/dataframe/dataframe.py
* Installs a Daft wheel in the Ray cluster at initialization
> Adds a setup_ray step in benchmarking

- tests/dataframe_cookbook/conftest.py
- tests/dataframe_cookbook/test_aggregations.py
- tests/dataframe_cookbook/test_computations.py
- tests/dataframe_cookbook/test_dataloading.py
- tests/dataframe_cookbook/test_distinct.py
- tests/dataframe_cookbook/test_filter.py
- tests/dataframe_cookbook/test_joins.py
- tests/dataframe_cookbook/test_sorting.py
- tests/dataframe_cookbook/test_udf.py
* These tests were likely flakily failing tests that relied on doing a `.limit`
> Remove dataframe_cookbook tests with 2 CSVs

- daft/context.py
- daft/dataframe/dataframe.py
- daft/datasources.py
- daft/execution/logical_op_runners.py
- daft/logical/logical_plan.py
- daft/runners/partitioning.py
- daft/runners/pyrunner.py
- daft/runners/ray_runner.py
- daft/runners/runner.py
- tests/dataframe/test_scan.py
- tests/dataframe_cookbook/test_dataloading.py
- tests/dataframe_cookbook/test_explodes.py
- tests/dataframe_cookbook/test_write.py
- tests/expression_operators/test_cast.py
- tests/logical/test_logical_plan.py
- tests/null_tests/test_aggregations.py
- tests/null_tests/test_distinct.py
- tests/null_tests/test_joins.py
- tests/null_tests/test_sorts.py
- tests/test_expression_types.py
* Remove Partition Manager for runner
* Adds use of PartitionCache which is now used for DataFrame Caching and InMemoryScans
* Fixes race condition bug with ray runner and side effects
* Adds `to_pydict()` to DataFrame API
> Dataframe Partition Caching and InMemoryScans

- daft/execution/url_operators.py
Requires unit testing but we need something like minio to test
> Fix .url.download() for s3 URLs

- .github/workflows/broken-link-checker.yml
* fixes workflow for Broken Link Checker for GetDaft
> Fix Broken Link Checker

- benchmarking/tpch/__main__.py
Adds a step for pulling files into the local file cache during the warmup step of benchmarking
> Cache files locally during setup phase in benchmarking

- benchmarking/tpch/__main__.py
- benchmarking/tpch/data_generation.py
- daft/dataframe/dataframe.py
- docs/source/docs/api_docs/dataframe.rst
- docs/source/docs/learn/10-min.ipynb
- docs/source/docs/learn/quickstart.ipynb
- tests/dataframe/test_creation.py
- tests/dataframe_cookbook/conftest.py
- tests/dataframe_cookbook/test_dataloading.py
- tests/dataframe_cookbook/test_write.py
- tests/runners/test_pyrunner.py
- tests/stress_tests/test_tpch.py
- tutorials/quickstart.ipynb
- tutorials/text_to_image/text_to_image_generation.ipynb
- tutorials/text_to_image/using_cloud_with_ray.ipynb
> Deprecate from_csv/from_json/from_parquet in favor of read_*

- .github/workflows/ray-compatibility.yml
- poetry.lock
- pyproject.toml
Adds a workflow that runs nightly, testing Daft on a range of Ray versions
> Add CI nightly job for checking compatibility with a list of Ray versions

- daft/logical/optimizer.py
- daft/runners/pyrunner.py
- daft/runners/ray_runner.py
* Drops no-op Projections which are largely introduced when running the column pruning optimizer pass
> add drop projections pass to drop no-op projections

- .github/workflows/python-publish.yml
- ci/upload_wheels.sh
- pyproject.toml
* Workflow to publish to anaconda PYPI repos: daft and daft-nightly
* Adds git tag versioning for version name
> workflow for anaconda upload to daft / daft-nightly org

- tutorials/image_querying/top_n_red_color.ipynb
Demo notebook for PyData Global 2022
> Demo notebook for top N most red images

- poetry.lock
- pyproject.toml
* Adds psutil as a daft dependency
* caught as test failure when cutting nightly here: https://github.com/Eventual-Inc/Daft/actions/runs/3635991783/jobs/6135577235
> Add psutil as daft dep

- daft/expressions.py
Cleans up Expression code so that no evaluation happens in the Expression class
> Move evaluation of UDF expression to ExpressionExecutor

- daft/expressions.py
- daft/runners/blocks.py
- daft/runners/ray_runner.py
- daft/udf.py
Cleans up polars imports to eventually remove dependency on Polars
> Clean up Polars imports to eventually be optional dependency

- .github/workflows/docs-github-pages-publish.yml
- .github/workflows/python-package.yml
* Fixes doc build by moving from poetry to pip.
* This was caused by the rust refactor
> Drop Poetry for doc building

- .github/workflows/docs-github-pages-publish.yml
* When building sphinx docs, we get an error that it can find the internal daft import
> build rust library for building docs

- .github/workflows/python-package.yml
* add CI step to install wheel and see if it imports without optional deps
> Add CI step to test imports without optional deps

- Cargo.lock
- Cargo.toml
- benchmarking/tpch/__main__.py
- daft/__init__.py
- src/lib.rs
- tools/patch_package_version.py
* expose daft version from rust daft build
* fix `g` prefix when computing nightly version
> Add daft version from rust build

- .github/workflows/ray-compatibility.yml
Fixes the build for our Ray compatibility matrix job to use the new Rust toolchain, and remove all usage of poetry
> Fix build for Ray compatibility CI

- .github/workflows/ray-compatibility.yml
Clean up how we pin Ray and Protobuf in our Ray compatiblity CI job
> Clean up Ray compatiblity CI jobs Ray and Protobuf installations

- benchmarking/tpch/__main__.py
- daft/context.py
- daft/filesystem.py
1. Removes all filesystem caching and associated utilities
2. Removes cache warmup step from benchmarking
> Remove caching from filesystems and benchmarking

- daft/viz/repr.py
- docs/source/docs/learn/10-min.ipynb
1. Adds fixes for #425 that causes errors in our 10 minute tutorial
2. Refreshes our 10 minute tutorial with new functionality and best practices
> Refreshes our 10 minute tutorial

- daft/runners/partitioning.py
- tests/dataframe_cookbook/test_sorting.py
- tests/runners/test_partitioning.py
* Sorts are broken when run on a column that is not just a ColumnExpression
> Sorts on non-column expression

- .github/workflows/broken-link-checker.yml
- .github/workflows/notebook-checker.yml
* Adds CI step to check if notebooks run daily at noon PST
> Check doc notebooks daily at noon

- Cargo.lock
- Cargo.toml
- docs/source/docs/release_notes/0.0.21.rst
Adds a changelog for the v0.0.21 release
> Add changelog for 0.0.21

- daft/runners/pyrunner.py
- daft/runners/ray_runner.py
- tests/dataframe/test_creation.py
> Add handling of missing filepaths with FileNotFoundError

- daft/filesystem.py
- daft/runners/ray_runner.py
- docs/source/docs/learn/install.rst
> Better user messages on import errors of optional dependencies

- .pre-commit-config.yaml
- Cargo.toml
- pyproject.toml
CI is currently breaking because of an issue with the `toml-sort` library in our pre-commit step. This PR upgrades the pre-commit library to fix it.
See issue: https://github.com/macisamuele/language-formatters-pre-commit-hooks/issues/133
> Fix CI issue with pre-commit toml sorting

- daft/filesystem.py
* Fixes anonymous s3 file access when no credentials are available for the `.url.download()` expression
> Fix anonymous s3 file access in .url.download()

- daft/execution/execution_step.py
* Fixes #510 for dynamic runners
> Fix dynamic runners sorting

- .github/workflows/python-package.yml
- requirements-dev.txt
* Enables code coverage tools for Daft
* publishes report for python tests to codecov
> Codecov Python Code Coverage

- .github/workflows/python-package.yml
- .github/workflows/rust-package.yml
* Factors out rust tests from python package
* generate and submit rust code coverage to codecov
> add rust to code coverage

- .github/workflows/property-based-tests.yml
- .gitignore
- Makefile
- daft/dataframe/dataframe.py
- pyproject.toml
- requirements-dev.txt
- tests/property_based_testing/strategies.py
- tests/property_based_testing/test_sort.py
Initializes property based tests with Hypothesis
> Property based testing

- daft/dataframe/dataframe.py
- tests/dataframe_cookbook/test_aggregations.py
* Adds unit tests for grouped and non-grouped Aggs for DataFrame
> Add simple unit tests for Aggs

- daft/execution/execution_step.py
- daft/execution/physical_plan.py
- daft/execution/physical_plan_factory.py
- daft/runners/dynamic_runner.py
- daft/runners/ray_runner.py
- tests/test_resource_requests.py
Closes: https://github.com/Eventual-Inc/Daft/issues/529
> Add resource request to dynamic runners

- codecov.yml
* Update CodeCov threshold to 1%
> [Coverage] Update CodeCov Threshold to 1 percent

- daft/logical/logical_plan.py
- daft/runners/blocks.py
- tests/dataframe/test_sort.py
* Add tests (and fixes) for validation of expression types that can be sorted on
* Add tests for sorting on float columns
* Add tests for sorting on string columns
* Adds a fix for null placement on sorts
* Adds a (skipped) test for multi-col null placements, see: #546
> Add sort tests

- .pre-commit-config.yaml
- daft/expressions.py
- daft/runners/blocks.py
- daft/udf.py
- daft/udf_library/url_udfs.py
- docs/source/docs/learn/10-min.ipynb
- docs/source/docs/learn/user_guides/udf.rst
- docs/source/docs/release_notes/0.0.13.rst
- tests/dataframe_cookbook/test_python_list_cols.py
- tests/dataframe_cookbook/test_udf.py
- tests/expression_operators/test_udf.py
- tutorials/image_querying/top_n_red_color.ipynb
- tutorials/mnist.ipynb
> Refactor @udf to use type annotations

- docs/source/learn/10-min.ipynb
- tutorials/mnist.ipynb
* Fix colab link in 10-min notebook (Closes #574 )
* Fix MNIST notebook for #96
> Fix tutorial notebooks

- daft/__init__.py
- daft/datatype.py
- daft/series.py
- src/datatypes/dtype.rs
- src/datatypes/field.rs
- src/datatypes/time_unit.rs
- src/dsl/expr.rs
- src/python/datatype.rs
- src/python/expr.rs
- src/python/mod.rs
- src/python/series.rs
- src/table/mod.rs
- tests/series/test_series.py
* Implement DataTypes from Rust for Python vs PyDataTypes
* Implements Casting operator for Series and Expressions
* Testing for Casting on Series for all pyarrow numerics
> [rust] PyDataTypes and casting operators

- daft/filesystem.py
- tests/dataframe/test_creation.py
> Fix reading CSV/JSON errors from https

- daft/udf.py
- docs/source/api_docs/udf.rst
* Remove `@polars_udf` from docs
* Reword some of `@udf` docs
> Cleanup UDF docs

- .readthedocs.yaml
- docs/source/api_docs/dataframe_methods/daft.DataFrame.rst
- docs/source/api_docs/expression_methods/daft.expressions.Expression.rst
Leverage `make` targets for RTD build.
Build:
Docs: https://getdaft-jeev-test.readthedocs.io/en/latest/index.html
> Cleanup RTD docs build

- daft/logical/logical_plan.py
- daft/logical/optimizer.py
- tests/optimizer/test_filter.py
- tests/optimizer/test_join.py
* Factors out required_columns and input_mapping for logical node to be per child rather than global
* Adds tests for optimizer to verify optimizations for prune columns
> Fixes Join Optimizer Bug

- daft/expressions.py
- daft/udf_library/url_udfs.py
Speeds up `.url.download()` by a large amount using multithreading
> Add multithreading to .url.download()

- daft/dataframe/dataframe.py
- daft/internal/kernels/hashing.py
- daft/runners/partitioning.py
- daft/types.py
- tests/dataframe/test_joins.py
1. Also enables PyArrow ChunkedArrays in `.from_pydict()`
> Fix join bug with empty PyArrow chunked arrays

- daft/series.py
- daft/table.py
- src/array/ops/comparison.rs
- src/array/ops/filter.rs
- src/array/ops/full.rs
- src/array/ops/mod.rs
- src/array/ops/take.rs
- src/dsl/expr.rs
- src/python/series.rs
- src/python/table.rs
- src/series/ops/comparision.rs
- src/series/ops/filter.rs
- src/series/ops/full.rs
- src/series/ops/mod.rs
- src/table/mod.rs
- tests/series/test_comparisions.py
- tests/series/test_series.py
- tests/table/test_table.py
* Implements Filter for Series and Table
* Implements DaftLogical which allows for Logical Operations like and, or, xor
* Implement DaftLogical Trait for BooleanArray and Series
* Add NullType to DaftComparable
* Test Cases in Python for Series and Table
> [rust] Table, Series Filter with DaftLogical Operators

- daft/runners/blocks.py
* When ArrowDataBlocks contain pa.ChunkedArrays, sometimes these ChunkedArrays contain chunks that share buffers or uses a buffer that is much bigger than what it actually needs
* Each chunk is serialized alongside all its underlying buffers, resulting in much larger serializations that required
* This is a problem when reading large Parquet files with small number of row groups, in PyArrow > 7.0.0
> Fix serialization of ArrowDataBlocks with shared buffers

- daft/series.py
- src/array/ops/arrow2/mod.rs
- src/array/ops/arrow2/sort/mod.rs
- src/array/ops/arrow2/sort/primitive/common.rs
- src/array/ops/arrow2/sort/primitive/indices.rs
- src/array/ops/arrow2/sort/primitive/mod.rs
- src/array/ops/arrow2/sort/primitive/sort.rs
- src/array/ops/mod.rs
- src/array/ops/sort.rs
- src/kernels/search_sorted.rs
- src/python/series.rs
- src/series/ops/mod.rs
- src/series/ops/sort.rs
- src/table/mod.rs
- tests/series/test_series.py
* Adds sorting and argsort for Series (both asending and descending)
* Adds arrow2 sort kernels to adapt for non total ordering of floats
> [Rust] Series Sorting and Argsort

- daft/table.py
- src/python/table.rs
- src/series/ops/comparision.rs
- src/series/ops/downcast.rs
- src/series/ops/filter.rs
- src/table/mod.rs
- tests/table/test_table.py
* Implements single column Table sorts and argsorts
* Multicolumn to be implemented
> [rust] Single Column Table Sorts

- daft/table.py
Add stub code to Table so that it can be a drop-in replacement for vPartition.
> Add stub code to Table

- daft/dataframe/dataframe.py
- daft/expressions.py
- daft/expressions2/expressions.py
- daft/expressions2/testing.py
- daft/logical/optimizer.py
- daft/runners/partitioning.py
- tests/dataframe/test_getitem.py
- tests/test_expressions.py
Adds required methods for Expression2 to work with our optimizer
* `_replace_column_with_expression`
* `_is_column`
* `.agg.*` aggregation functions
> Expression2 optimizer methods

- daft/table.py
- src/array/ops/mod.rs
- src/array/ops/pairwise.rs
- src/python/table.rs
- src/schema.rs
- src/series/ops/mod.rs
- src/series/ops/pairwise.rs
- src/table/mod.rs
- src/table/ops/joins/mod.rs
- src/table/ops/joins/naive_join.rs
- src/table/ops/mod.rs
- tests/table/test_joins.py
* Implement Single Column joins in Rest with Naive Algorithm
* Implement Array Pairwise kernels
* Implement pairwise equal operation for Series used in Naive Algorithm
> [rust] Single Column Naive Join

- daft/logical/aggregation_plan_builder.py
- daft/runners/partitioning.py
- tests/stress_tests/test_tpch.py
* Fix q1 issue introduced by: #627 
* Fix long-standing multi-col join issues in q5/q9
> Add multi-partition TPC-H unit test and fixes

- Cargo.lock
- Cargo.toml
- daft/table.py
- src/python/table.rs
- src/table/mod.rs
- tests/table/test_table.py
* Implements sample and quantile operations needed for TPCH queries
> [rust] Table Sample and Quantile operations

- daft/expressions2/expressions.py
- daft/series.py
- src/array/ops/abs.rs
- src/array/ops/apply.rs
- src/array/ops/arithmetic.rs
- src/array/ops/mod.rs
- src/datatypes/dtype.rs
- src/dsl/expr.rs
- src/dsl/functions/mod.rs
- src/dsl/functions/numeric/abs.rs
- src/dsl/functions/numeric/mod.rs
- src/dsl/mod.rs
- src/python/expr.rs
- src/python/series.rs
- src/series/ops/abs.rs
- src/series/ops/mod.rs
- src/table/mod.rs
- tests/series/test_series.py
- tests/table/test_table.py
- tests/test_expressions2.py
* Implements FunctionExpressions to build expressions for arbitrary  functions
* Implements using Abs as a Numeric Expression
* Adds repr tests for expressions
> [rust] Function Expressions and Abs Expression

- daft/logical/logical_plan.py
This makes it possible to run our TPC-H questions with the optimizer turned off without implementing all the Expressions2 functionality required for the optimizer.
> Unblocking [RUST-INT][TPCH]: Remove calls to Expression._required_columns outside of optimizer

- daft/expressions2/expressions.py
- src/datatypes/dtype.rs
- src/series/mod.rs
- src/series/ops/comparision.rs
- src/series/ops/filter.rs
- src/series/ops/hash.rs
- src/series/ops/mod.rs
- src/series/ops/search_sorted.rs
- src/series/ops/sort.rs
- src/series/ops/take.rs
- src/utils/supertype.rs
- tests/series/test_comparisions.py
- tests/series/test_series.py
- tests/table/test_table.py
- tests/test_expressions2.py
* Use as physical operations to enable simple ops with Date
> [rust] Simple Date operations via as_physical operations

- daft/execution/execution_step.py
- tests/dataframe/test_joins.py
> Issue #707: Fix join run_partial_metadata logic

- daft/expressions2/expressions.py
- daft/series.py
- src/array/mod.rs
- src/array/ops/date.rs
- src/array/ops/mod.rs
- src/datatypes/dtype.rs
- src/dsl/functions/mod.rs
- src/dsl/functions/temporal/mod.rs
- src/dsl/functions/temporal/year.rs
- src/python/expr.rs
- src/python/series.rs
- src/series/ops/date.rs
- src/series/ops/mod.rs
- src/series/ops/take.rs
- tests/series/test_series.py
- tests/series/test_temporal.py
- tests/table/test_table.py
- tests/test_expressions2.py
- tests/test_runtime_matches_static_types.py
* added Year for Date types
* add way to slice DataType array
> [rust] Date Year and Array Slices

- Cargo.lock
- Cargo.toml
- daft/series.py
- daft/table/table.py
- src/python/datatype.rs
- src/python/field.rs
- src/python/schema.rs
- src/schema.rs
- tests/logical/test_schema2.py
- tests/series/test_series.py
- tests/table/test_table_io.py
- tests/test_datatypes.py
- tests/test_expressions2.py
* Adds pickling methods for DataType, Field, Expr, Series and Table
* adds tests to ensure correctness
> [rust] Rust Data structures pickling

- daft/datatype.py
- daft/expressions2/expressions.py
- daft/logical/schema2.py
- src/python/datatype.rs
- src/python/expr.rs
- src/python/field.rs
- src/python/schema.rs
* fixes issues with cloudpickle issues with ray when serializing expr or schemas
> [rust] leverage getstate directly in rust wrappers

- daft/expressions2/expressions.py
Cleans up how we construct ExpressionNamespace with proper mypy typing
> Add ExpressionNamespace construction similar to SeriesNamespace

- daft/expressions.py
* is_nan returns null for null values
* Updates documentation to reflect this
> Fix is_nan expression documentation for null behavior

- .github/workflows/python-package.yml
* Adds CI workflow to `rust-main` branch
> Add github CI workflow to rust-main

- src/array/ops/broadcast.rs
- src/series/ops/broadcast.rs
- tests/table/test_broadcasts.py
Expands Series broadcast to work for all physical types
> [RUST] Implement broadcast for all physical types

- daft/datatype.py
- src/datatypes/dtype.rs
- tests/dataframe/test_repr.py
- tests/test_schema.py
* Changes DataType display by removing the `DataType[]` wrapper
* Adds custom implementation for display of List and Struct types
> [RUST] Change dtype Display and repr tests

- daft/expressions/expressions.py
- tests/expressions/test_apply.py
* Implements `Expression.apply` which will cast each element in the column to Python and run a per-row UDF
* This is intended to be a convenience method on top of UDFs
> [RUST] Implement Expression.apply using UDFs

- daft/datatype.py
- daft/table/table.py
- src/array/ops/broadcast.rs
- src/array/ops/cast.rs
- src/array/ops/downcast.rs
- src/array/ops/filter.rs
- src/array/ops/if_else.rs
- src/array/ops/take.rs
- src/datatypes/dtype.rs
- src/datatypes/matching.rs
- src/ffi.rs
- src/python/datatype.rs
- src/python/series.rs
- src/series/ops/cast.rs
- src/utils/arrow.rs
- src/utils/mod.rs
- tests/series/test_filter.py
- tests/series/test_if_else.py
- tests/series/test_size_bytes.py
- tests/series/test_take.py
- tests/table/test_from_py.py
- tests/table/test_table_io.py
This PR adds support for `StructArray`s.
> [Datatypes] [Nested Types - 2/N] Add support for `StructArray`s. 

- docs/source/10-min.ipynb
- docs/source/conf.py
- docs/source/index.rst
- docs/source/learn/index.rst
- docs/source/learn/key_concepts.rst
- docs/source/learn/user_guides.rst
- docs/source/learn/user_guides/partitioning.rst
* Moves 10 min guide to top-level guide
* Adds a "key concepts" guide to the learn tab
> Add Key Concepts doc

- Cargo.lock
- Cargo.toml
- src/array/ops/count.rs
- src/array/ops/groups.rs
- src/array/ops/mod.rs
- src/series/ops/groups.rs
- src/series/ops/mod.rs
- src/table/mod.rs
- src/table/ops/agg.rs
- src/table/ops/groups.rs
- src/table/ops/mod.rs
- tests/table/__init__.py
- tests/table/test_table_aggs.py
* `IntoGroups` Trait that converts a Series/Table into groups
* Impl `IntoGroups` for single column tables (Series) as well as multicolumn
* fast path for groups=1 when doing a grouped aggregation
* Add test cases for various grouped aggs for different dtypes
> [rust] static dispatch groupbys single col

- src/ffi.rs
* Uses Pyarrow `columns` call when reading record batches to save multiple calls to python
> [rust] FFI use pyarrow columns instead of column(i) for each record batch

- Cargo.lock
- Cargo.toml
- daft/dataframe/dataframe.py
- daft/expressions/expressions.py
- daft/logical/aggregation_plan_builder.py
- daft/utils.py
- src/array/mod.rs
- src/array/ops/concat_agg.rs
- src/array/ops/list_agg.rs
- src/array/ops/mod.rs
- src/datatypes/dtype.rs
- src/datatypes/field.rs
- src/dsl/expr.rs
- src/dsl/functions/list/explode.rs
- src/dsl/optimization.rs
- src/python/expr.rs
- src/python/series.rs
- src/series/ops/agg.rs
- src/table/mod.rs
- src/table/ops/agg.rs
- tests/cookbook/test_aggregations.py
- tests/dataframe/test_aggregations.py
- tests/table/test_table_aggs.py
* Implements List aggregations (converting a column to a list) with or without a group
* Implements List concat aggregations combining Lists that either globally or in the same group
> List and Concat (grouped) Aggregations

- Cargo.lock
- Cargo.toml
- daft/datatype.py
- daft/series.py
- daft/table/table.py
- src/ffi.rs
- tests/cookbook/test_literals.py
- tests/dataframe/test_creation.py
- tests/dataframe/test_to_integrations.py
- tests/series/test_concat.py
- tests/series/test_filter.py
- tests/series/test_if_else.py
- tests/series/test_size_bytes.py
- tests/series/test_slice.py
- tests/series/test_take.py
- tests/table/test_blackbox_kernels.py
- tests/table/test_from_py.py
- tests/table/test_table_io.py
This PR adds more thorough test coverage for nested types, adds pyarrow 7 support, and includes misc. fixes required to make the added tests pass.
> [Nested Types] Test coverage, pyarrow 7 support, misc. fixes

- daft/datatype.py
- daft/runners/ray_runner.py
- tests/ray/test_datasets.py
This PR fixes some Ray Datasets compatibility issues with older versions of Ray.
> [Ray Datasets] Fix Ray Datasets compatibility.

- daft/udf_library/url_udfs.py
> Fix fsspec multithreading clobbering issue

- requirements-dev.txt
* Pin python requirements for CI testing
* TODO use dependabot to update deps
* TODO add test matrix for python 3.11
> pinned deps for requirements-dev.txt

- .github/workflows/python-package.yml
* Also run python 3.10 in matrix to test post 3.7 deps
> enable python 3.10 unit tests

- tests/ray/test_datasets.py
This PR hopefully fixes the flaky Datasets integration test in CI.
> [CI] Fix flaky Datasets integration test.

- Cargo.lock
- Cargo.toml
Reduces compile time 97.20s -> 87.61s (10%)
> finer feature flags for arrow2 for faster compile

- daft/execution/execution_step.py
- daft/table/table.py
- src/python/table.rs
- src/table/mod.rs
- tests/dataframe/test_repartition.py
* Implements IntoPartitions and Table Slice
> Table Slice and IntoPartitions Fix

- daft/viz/repr.py
- tests/dataframe/test_repr.py
Closes: #977
Also adds fix for the non-html repr case
> Add test case for HTML repr bug

- docs/source/api_docs/datatype.rst
- docs/source/api_docs/expressions.rst
- docs/source/conf.py
- docs/source/learn/user_guides/datatypes.rst
This PR adds some missing API references and user guide content for the `Image` type.
> [Images] [5/N] Add to image type docs.

- .gitignore
- daft/__init__.py
- daft/daft.pyi
- daft/datatype.py
- docs/source/api_docs/context.rst
- docs/source/api_docs/dataframe.rst
- docs/source/api_docs/datatype.rst
- docs/source/api_docs/datatype_image_mode/daft.ImageMode.from_mode_string.rst
- docs/source/api_docs/datatype_image_mode/daft.ImageMode.rst
- docs/source/api_docs/expressions.rst
- docs/source/api_docs/groupby.rst
- docs/source/api_docs/input_output.rst
- docs/source/learn/user_guides/datatypes.rst
- src/datatypes/image_mode.rs
This PR fixes the `DataType.image()` dtype docs in a few places.
> [Images] [6/N] Fix image dtype docs.

- tests/ray/test_datasets.py
This PR fixes flakiness in our Datasets integration tests caused by nondeterministic partition ordering in Datasets. We fix this by sorting the output on the pseudo-index column that we include in each test dataframe before checking for equality with the expected data.
> [CI] Fix flakiness in Datasets integration tests.

- daft/series.py
- daft/udf.py
- docs/source/10-min.ipynb
- docs/source/api_docs/expressions.rst
- docs/source/api_docs/groupby.rst
- docs/source/api_docs/index.rst
- docs/source/api_docs/series.rst
- docs/source/api_docs/series/daft.Series.rst
- docs/source/conf.py
- docs/source/dataframe_comparison.rst
- docs/source/index.rst
- docs/source/install.rst
- docs/source/learn/key_concepts.rst
- docs/source/learn/user_guides/dataframe-operations.rst
- docs/source/learn/user_guides/datatypes.rst
- docs/source/learn/user_guides/expressions.rst
- docs/source/learn/user_guides/intro-dataframes.rst
- docs/source/learn/user_guides/read-write.rst
- docs/source/learn/user_guides/udf.rst
- docs/source/technical_architecture.rst
- requirements-dev.txt
This PR does a generic pass over the docs:
- Adds cross-reference links where appropriate.
- Makes code blocks copyable.
- Minor grammar fixes/prose tweaks.
> [Docs] Add initial docs pass, adding lots of cross-reference links.

- daft/dataframe/dataframe.py
- daft/execution/physical_plan.py
- daft/execution/physical_plan_factory.py
- daft/logical/logical_plan.py
- daft/logical/optimizer.py
- docs/source/api_docs/dataframe.rst
- tests/dataframe/test_concat.py
- tests/optimizer/test_prune_columns.py
- tests/optimizer/test_pushdown_predicates.py
Closes: #486 
Adds a DataFrame method to concat it with another Dataframe.
Note that the dataframes must have the same schema, or we throw an error at LogicalPlan-creation-time
> Dataframe Concats

- Cargo.lock
- Cargo.toml
Updates versions in cargo.toml for v0.1.6
> [CHORE] Update cargo version to v0.1.6

- src/array/ops/cast.rs
- src/array/ops/image.rs
- src/array/ops/take.rs
- src/datatypes/dtype.rs
- src/datatypes/image_mode.rs
- src/datatypes/logical.rs
- src/dsl/expr.rs
- src/dsl/functions/float/is_nan.rs
- src/dsl/functions/image/decode.rs
- src/dsl/functions/image/encode.rs
- src/dsl/functions/image/resize.rs
- src/dsl/functions/list/explode.rs
- src/dsl/functions/list/join.rs
- src/dsl/functions/mod.rs
- src/dsl/functions/numeric/abs.rs
- src/dsl/functions/python/udf.rs
- src/dsl/functions/temporal/day.rs
- src/dsl/functions/temporal/day_of_week.rs
- src/dsl/functions/temporal/month.rs
- src/dsl/functions/temporal/year.rs
- src/dsl/functions/utf8/contains.rs
- src/dsl/functions/utf8/endswith.rs
- src/dsl/functions/utf8/length.rs
- src/dsl/functions/utf8/startswith.rs
- src/python/datatype.rs
- src/series/ops/image.rs
- tests/series/test_image.py
This PR adds support for encoding and resizing fixed-shape images and encodes images via a single buffer/writer to elide a copy.
> [FEAT] [Images] [8/N] Add encoding and resizing support for fixed-shape images.

- tests/series/test_image.py
This PR fixes a failing test due to a PR being merged with an out-of-date base.
> [BUG] [CI] Fix merge conflict due to out-of-date base.

- .github/dependabot.yml
* Set schedule for dependabot to weekly
> [CHORE] set dependabot schedule to weekly

- src/daft-io/src/s3_like.rs
* Sets region to us-east-1 when can not detect a region
> [BUG] S3 Downloader set default region when region not detected

- Cargo.lock
- src/daft-io/Cargo.toml
- src/daft-io/src/config.rs
- src/daft-io/src/python.rs
- src/daft-io/src/s3_like.rs
* Enables Anonymous Mode for S3 which allows for requests to S3 with credentials
* Automatically enables Anonymous Mode if there are no credentials on the system.
> [FEAT] Native S3 Downloader Anonymous Mode

- .github/workflows/python-publish.yml
This should fix failing build: https://github.com/Eventual-Inc/Daft/actions/runs/5408646720
> [CHORE] Install wheel together with requirements in release build

- Cargo.lock
- src/daft-io/Cargo.toml
- src/daft-io/src/http.rs
- src/daft-io/src/lib.rs
- src/daft-io/src/local.rs
- src/daft-io/src/object_io.rs
- src/daft-io/src/s3_like.rs
* Implements Range gets for Native Downloader
> [FEAT] Ranged Get Native Downloader

- .pre-commit-config.yaml
- Cargo.lock
- src/daft-core/src/series/series_like.rs
- src/daft-io/Cargo.toml
- src/daft-io/src/http.rs
- src/daft-io/src/lib.rs
- src/daft-io/src/local.rs
- src/daft-io/src/object_io.rs
- src/daft-io/src/s3_like.rs
- tests/udf_library/test_url_udfs.py
* Fixes clippy in a workspace setting
* refactor s3 client to be multiregion inside S3Client rather than use static variable
* run io tests twice to ensure that multiple reads work
* TODO factor ownership of all the client to a IOClient
* TODO: Fix cargo check
> [BUG] Ownership of Runtime and Clients

- .pre-commit-config.yaml
- src/daft-io/src/http.rs
* Update precommit to use cargo workspace
> [CHORE] Use workspace for cargo check

- tests/integration/parquet/test_remote_reads.py
Adds a list of parquet files for testing
> [CHORE] No-op test for various parquet files

- README.rst
> [CHORE] Update README.rst typo

- daft/table/table.py
- src/daft-parquet/src/read.rs
- tests/integration/parquet/test_remote_reads.py
* Adds Parquet Integration tests and compares results to Pyarrow
* Fixes nested struct deserialization
* Fixes segfault issue when dealing with many small pages
> [CHORE] Native Parquet Integration Tests

- .github/workflows/nightlies-tests.yml
- .github/workflows/python-package.yml
- tests/integration/docker-compose/Dockerfile.nginx
- tests/integration/docker-compose/Dockerfile.s3_retry_server
* Runs integration tests on our nightly wheels for mac, linux-x86 and linux-arm64
> [CHORE] integration tests for nightly platform wheels

- rust-toolchain.toml
- src/daft-core/src/array/ops/cast.rs
- src/daft-core/src/array/ops/image.rs
- src/daft-core/src/array/ops/repr.rs
- src/daft-core/src/array/ops/utf8.rs
- src/daft-core/src/array/pseudo_arrow/python.rs
- src/daft-core/src/kernels/utf8.rs
- src/daft-io/src/s3_like.rs
- src/daft-parquet/src/file.rs
Bumping our compiler version might solve some flaky CI compilation issues: https://github.com/Eventual-Inc/Daft/actions/runs/5824394989
> [CHORE] Bump rust nightly channel date

- daft/table/table.py
* add flag in `to_arrow` that convert large string and binary arrays to their int32 offset counterparts
> [FEAT] Add Flag to_arrow to convert large string arrays

- daft/table/table.py
- src/daft-io/src/lib.rs
- src/daft-parquet/src/python.rs
- tests/integration/io/parquet/test_reads_public_data.py
* add flag that allows to toggle multithreaded_io
> [FEAT] add flag to use multithreaded io for parquet_read_table

- tests/table/table_io/test_parquet.py
Fixes our tests for PyArrow version 13.0.0: https://github.com/Eventual-Inc/Daft/actions/runs/5993949629
Note that the root cause of this issue was that comparisons of `DataType::List` compares the subfield's name, which PyArrow changed in 13.0.0 from `"item"` to `"element"`.
I think ideally equality of the list dtype should maybe ignore the subfield's name? That's a change we can look to make at some point.
> [CHORE] Add fix for list schema inference tests using PyArrow 13.0.0

- .pre-commit-config.yaml
- Cargo.lock
- daft/filesystem.py
- src/daft-io/Cargo.toml
- tools/check_for_rustls.sh
* Switch over from rustls to vendored openssl
> [CHORE] Switch to openssl

- .github/workflows/python-publish.yml
- Cargo.lock
- Cargo.toml
- src/daft-parquet/src/file.rs
- src/lib.rs
* Switches allocator to Jemalloc
* Leverages background threads for linux with drop rate of 1 second
* Use 65k size pages for linux arm64
> [PERF] enable jemalloc with background threads

- .github/workflows/python-publish.yml
* move jemalloc flag to inside container for redhat installations
> [FEAT] export jemalloc arm64 flag inside container

- .github/workflows/broken-link-checker.yml
* Enables broken link checker CI job to be retried
> [CHORE] add retries for broken link checker

- daft/daft.pyi
- daft/table/table.py
- src/daft-parquet/src/python.rs
- src/daft-parquet/src/read.rs
adds `num_parallel_tasks` argument (defaults to 128)
> [FEAT] Parameter to set  num_parallel_tasks for bulk readers

- src/daft-io/src/s3_like.rs
> [BUG] Fix handling of special characters in S3LikeSource

- src/daft-parquet/src/file.rs
- src/daft-parquet/src/stream_reader.rs
- tests/table/table_io/test_parquet.py
> [BUG] Fix reads of empty parquet files

- src/daft-io/src/lib.rs
Use a `tokio::runtime::Builder::new_multi_thread()` with 1 worker thread when a `multithreaded_io=False` is specified
While this likely incurs more overhead than using a current_thread runtime, this helps us work around the many deadlocking issues that may occur when multiple conflicting current_thread runtimes are inadvertently created.
> [BUG] Use multithreaded tokio runtime with one thread for multithreaded_io=False

- daft/series.py
This reverts commit e1e5eaf4789aff982767396d9493c9a61f628a04.
It appears that this was causing a performance regression
> [PERF][REVERT] Reverts: use pyarrow table for pickling rather than ChunkedArray (#1488)

- daft/analytics.py
- daft/execution/physical_plan.py
- daft/runners/profiler.py
- daft/runners/pyrunner.py
- daft/runners/ray_runner.py
- daft/table/table.py
* Fixes bug where we rendered f strings even when we didn't need to.
> [BUG] remove f strings from logging

- daft/daft.pyi
- daft/io/_csv.py
- daft/table/table_io.py
- src/daft-csv/src/lib.rs
- src/daft-csv/src/metadata.rs
- src/daft-csv/src/read.rs
- src/daft-micropartition/src/micropartition.rs
- src/daft-micropartition/src/python.rs
- src/daft-scan/src/file_format.rs
> [CHORE] Fix style lints from #1582

- daft/datatype.py
- daft/runners/ray_runner.py
- tests/ray/test_datasets.py
> [CHORE] Fixed bug in ray version

- Cargo.lock
- src/daft-io/Cargo.toml
- src/daft-io/src/s3_like.rs
* Adds exponential backoff when grabbing credentials that timeout
> [FEAT] add retries to s3 credential provider timeouts

- daft/runners/ray_runner.py
- tests/ray/runner.py
* Fixes hang when queue is full from an eagar limit and thread is asked to quit
> [BUG] Check queue state while waiting to place inside

- Cargo.lock
- Cargo.toml
* Pin daft version to 0.2.0+dev0 to make it more clear that its a dev version
> [CHORE] update dev version to 0.2.0 dev

- src/daft-core/src/array/ops/cast.rs
- src/daft-core/src/datatypes/binary_ops.rs
- tests/series/test_cast.py
- tests/series/test_comparisons.py
* Fixes bug when casting a Date to Timestamp
* Fixes logic when comparing a Date and a TimeStamp
> [BUG] Fix comparing date and timestamps

- docs/source/learn/user_guides.rst
- docs/source/learn/user_guides/memory.rst
- docs/source/learn/user_guides/udf.rst
Adds documentation and troubleshooting advice for memory management in Daft
> [DOCS] Add documentation on memory

- docs/source/_html/robots.txt
- docs/source/_html/sitemap-override.xml
- docs/source/conf.py
Solution proposed here: https://stackoverflow.com/questions/63542354/readthedocs-robots-txt-and-sitemap-xml
> [DOCS] Add proper robots.txt and sitemap.xml to index only latest and stable

- docs/source/api_docs/expressions.rst
> [CHORE] Add not_null to docs

- docs/source/api_docs/dataframe.rst
> [CHORE] Add sample to docs

- docs/source/10-min.ipynb
- docs/source/user_guide/basic_concepts/dataframe_introduction.rst
- docs/source/user_guide/daft_in_depth/udf.rst
Leftover todo from #582 
Update docs to reflect materialized Dataframes from writes and in-memory reads
> [CHORE] Update docs to reflect materialized Dataframes from writes and in-memory reads

- daft/dataframe/dataframe.py
> [DOCS] Add warning during repartition to use into_partitions instead

- docs/source/api_docs/expressions.rst
> [CHORE] Add is_in to docs

- src/daft-core/src/schema.rs
- src/daft-plan/src/logical_ops/source.rs
- src/daft-plan/src/optimization/optimizer.rs
- src/daft-plan/src/optimization/rules/drop_repartition.rs
- src/daft-plan/src/optimization/rules/push_down_filter.rs
- src/daft-plan/src/optimization/rules/push_down_limit.rs
- src/daft-plan/src/optimization/rules/push_down_projection.rs
- src/daft-plan/src/physical_ops/scan.rs
- src/daft-scan/src/anonymous.rs
- src/daft-scan/src/glob.rs
- src/daft-scan/src/lib.rs
- src/daft-scan/src/python.rs
> [BUG] Scan Operator Fix + Physical Plan Scan Task Summary

- daft/runners/ray_runner.py
> [BUG] Fix Ray autoscaling from zero worker CPUs

- src/daft-io/src/azure_blob.rs
- src/daft-io/src/google_cloud.rs
- src/daft-io/src/http.rs
- src/daft-io/src/lib.rs
- src/daft-io/src/local.rs
- src/daft-io/src/object_store_glob.rs
- src/daft-io/src/s3_like.rs
- tests/integration/io/test_list_files_http.py
closes: https://github.com/Eventual-Inc/Daft/issues/1890
> [FEAT] perform head operation instead of list when given a file without regex or /

- daft/analytics.py
Updates segment endpoint to use new endpoint, and rate-limit to 800 IDs
> [CHORE] Update segment endpoint

- docs/source/user_guide/integrations.rst
- docs/source/user_guide/integrations/delta_lake.rst
- docs/source/user_guide/poweruser/scaling-up.rst
This PR adds a user guide for Delta Lake reads.
> [DOCS] [Delta Lake] Add user guide for Delta Lake reads.

- .github/workflows/broken-link-checker.yml
Passed run: https://github.com/Eventual-Inc/Daft/actions/runs/8381402823
> [CHORE] Exclude Twitter and LinkedIn from broken link checker

- .github/workflows/python-package.yml
- tests/integration/conftest.py
- tests/integration/test_tpch.py
Fixed wheels publishing: https://github.com/Eventual-Inc/Daft/actions/runs/8471104649
> [CHORE] Refactor sql tpch tests

- .gitignore
I assume you are all vscode users. This PR will make jetbrains fanatics happy 😉
> [CHORE] Update .gitignore for JetBrains IDE and pyenv user

- docs/source/user_guide/integrations/iceberg.rst
Adds information about iceberg writes in our integration docs
> [DOCS] Update iceberg integration docs to add writes

- Makefile
Forget to give it the path to find virtual env when remove the source command. 😞
> [CHORE] Fix build command

- src/daft-plan/src/planner.rs
* Minor refactor to separate logic and transversal for Physical plan translation
> [CHORE] Bottom Up Logical To Physical translation

- daft/udf.py
- tests/expressions/test_udf.py
> [BUG] Fix tuple inputs in UDF

- src/daft-core/src/array/ops/utf8.rs
- tests/series/test_utf8_ops.py
- tests/table/utf8/test_replace.py
Fixes string kernels to correctly work on empty input arrays (they should just return an empty result)
> [BUG] Fix empty inputs case for string kernels

- docs/source/user_guide/integrations.rst
Make Hudi guide visible in the integration section.
> [DOCS] Add Hudi integration entry

- src/daft-core/src/array/ops/cast.rs
- tests/expressions/test_expressions.py
- tests/series/test_cast.py
> [CHORE] Improve timestamp repr

- .github/workflows/notebook-checker.yml
- .github/workflows/property-based-tests.yml
- .github/workflows/python-package.yml
- .ruff.toml
- Cargo.toml
- daft/api_annotations.py
- daft/dataframe/dataframe.py
- daft/execution/execution_step.py
- daft/expressions/expressions.py
- daft/filesystem.py
- daft/logical/schema.py
- daft/runners/partitioning.py
- daft/series.py
- daft/udf_library/url_udfs.py
- pyproject.toml
- tests/expressions/typing/conftest.py
- tests/integration/iceberg/conftest.py
- tests/io/iceberg/test_iceberg_writes.py
- tests/io/lancedb/test_lancedb_reads.py
* Drop support for Python 3.7 which has been EOL for about a year now.
> [CHORE] Drop Python 3.7

- daft/udf.py
- tests/expressions/test_udf.py
See relevant thread: https://linen.getdaft.io/t/18793130/hey-team-loving-daft-so-far-i-noticed-a-discrepencey-between#14aad685-8634-4670-9bda-b9bb74fc8a92
> [FEAT] Allow returning of pyarrow arrays from UDFs

- .github/workflows/python-package.yml
- codecov.yml
- rust-toolchain.toml
* It seems like downgrading to ubuntu 20.04 seems to fix the segfault we were seeing with the collection!
> [CHORE] turn on cov again

- Cargo.lock
- src/daft-core/src/schema.rs
- src/daft-json/Cargo.toml
- src/daft-json/src/decoding.rs
- src/daft-json/src/lib.rs
- src/daft-json/src/local.rs
- src/daft-json/src/options.rs
- src/daft-json/src/read.rs
closes https://github.com/Eventual-Inc/Daft/issues/2196
> [PERF]: local json reader

- daft/iceberg/iceberg_scan.py
I would like to clean up the `record_fields()` method: https://github.com/apache/iceberg-python/pull/580/
You should not check the name of the `_partition` since it can be anything (technically). In Iceberg we look up the partition by position based on the partition spec.
> [CHORE]: Don't use record fields

- src/daft-plan/src/logical_ops/join.rs
- tests/dataframe/test_joins.py
> [BUG]Fix missing columns after join

- Cargo.toml
- src/daft-core/src/array/ops/time.rs
- src/daft-decoding/src/deserialize.rs
- src/daft-json/src/decoding.rs
- src/daft-json/src/read.rs
This PR updates the chrono version to 0.4.38 and fixes deprecation warnings
> [CHORE] Bump chrono to 0.4.38 

- docs/source/user_guide/integrations/delta_lake.rst
this adds Delta writer functionality to the integration page
> [DOCS] add Delta writer functionality

- daft/expressions/expressions.py
- docs/source/api_docs/expressions.rst
Add missing doc gen for `Expression.float.is_nan`
> [EXPRESSIONS] Add missing doc gen for Expression.float.is_nan

- daft/io/_json.py
- tests/dataframe/test_creation.py
> [FEAT] Replace schema_hints with schema and infer_schema for read_json

- src/daft-execution/src/stage/sink/limit.rs
Simple scan + limit currently breaks on new executor. This is because the sink stage runner does not try to drain the receiving channel after the task scheduler has completed execution. 
Example failure:
```
import daft
import tempfile
import daft.context
with tempfile.TemporaryDirectory() as td:
daft.context.set_execution_config(enable_aqe=False, enable_native_executor=False)
df = daft.from_pydict({"a": [1]})
df.write_parquet(td)
daft.context.set_execution_config(enable_aqe=True, enable_native_executor=True)
df = daft.read_parquet(td)
df.show()
```
Error: 
```
daft.exceptions.DaftCoreException: DaftError::ValueError Need at least 1 MicroPartition to perform concat
```
Todo:
- Add better error handling
> [BUG] [New Executor] Drain channel in limit sink

- src/daft-table/src/ops/joins/hash_join.rs
Removes a debug print from anti join
> [BUG] Remove debug print

- daft/dataframe/dataframe.py
> [DOCS] Improve groupby and agg docs

- src/daft-core/src/utils/display_table.rs
Fixes panicking of display of Time64 fields
> [BUG] Enable display of time64 with seconds unit

- daft/runners/pyrunner.py
- tests/benchmarks/test_local_tpch.py
* adds benchmarking fixture for running tpch on local execution engines
```
pytest --benchmark-only tests/benchmarks/test_local_tpch.py
```
> [CHORE] add pytest benchmarking for local testing of execution engine

- .vscode/settings.json
> [CHORE] Enable all features for rust-analyzer

- Cargo.lock
- src/daft-csv/src/lib.rs
- src/daft-csv/src/read.rs
- src/daft-io/src/lib.rs
- src/daft-local-execution/Cargo.toml
- src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
- src/daft-local-execution/src/lib.rs
- src/daft-local-execution/src/pipeline.rs
- src/daft-local-execution/src/sinks/sink.rs
- src/daft-local-execution/src/sources/scan_task.rs
- src/daft-micropartition/Cargo.toml
- src/daft-micropartition/src/micropartition.rs
Enables streaming csv reads for the new executor.
> [FEAT] Streaming CSV Reads

- docs/source/10-min.ipynb
- docs/source/user_guide/fotw/fotw-000-data-access.ipynb
- tutorials/mnist.ipynb
This should fix the notebook checker CI failures
> [CHORE] Fix imports on jupyter notebook examples

- requirements-dev.txt
- tests/benchmarks/conftest.py
- tests/benchmarks/test_local_tpch.py
Tracks memory as part of the benchmarking:
> [CHORE] Track memory for swordfish tpch

- src/arrow2/src/io/parquet/read/deserialize/nested_utils.rs
- tests/io/test_parquet.py
#2586 did not consider the case when `.show()` or `.limit()` was used. In these cases, the result is typically truncated to a few rows of data. With the fix in #2586, when calling `.show()` or `.limit()` on a parquet file with a `list` column, our parquet reader would read every data page until all values have been read despite only needing a few data pages. This gives result Series that have mismatching lengths, e.g. one might see an error: `daft.exceptions.DaftCoreException: DaftError::ValueError While building a Table with Table::new_with_size, we found that the Series lengths did not match. Series named: line_ids had length: 23054 vs the specified Table length: 8`.
This PR fixes the issue by zeroing out the number of values left to read in a nested column once we know that we have …
> [BUG] Fix nested parquet reads for .show() and .limit()

- .gitignore
Add entry for ignoring helix editor configurations.
> [CHORE] Add ignore for helix editor

- Cargo.lock
- src/common/io-config/Cargo.toml
- src/common/io-config/src/azure.rs
- src/common/io-config/src/gcs.rs
- src/common/io-config/src/lib.rs
- src/common/io-config/src/python.rs
- src/common/io-config/src/s3.rs
- src/daft-io/src/azure_blob.rs
- src/daft-io/src/google_cloud.rs
- src/daft-io/src/s3_like.rs
> [FEAT] use ObfuscatedString to hide creds when Display IOConfig

- src/daft-local-execution/src/sinks/hash_join.rs
Q2 wasn't working due to `DaftError::ValueError Attempting to make a Schema with duplicate field names: P_PARTKEY`
This is because the JoinMapper was removed in a previous PR, so this PR implements a similar logic that prunes common join keys from the right side of an inner join.
Q2 works now:
> [BUG] Fix swordfish inner joins

- daft/dataframe/dataframe.py
- tests/table/test_from_py.py
closes https://github.com/Eventual-Inc/Daft/issues/2679
> [FEAT]: add to_arrow_iter

- src/daft-scan/src/lib.rs
Previously, if a scan task had many sources, all of them would be printed. Now, we add ellipses if there are more than 6.
> [FEAT] Ellipsize scan task sources if too many

- docs/source/user_guide/fotw/fotw-001-images.ipynb
Skips the notebook because it hits private buckets
> [CHORE] Fix FOTW #001 images notebook

- .github/workflows/python-package.yml
- CONTRIBUTING.md
- benchmarking/parquet/README.md
- benchmarking/tpch/data_generation.py
- pyproject.toml
- requirements-dev.txt
- tests/benchmarks/conftest.py
- tests/benchmarks/test_concat.py
- tests/benchmarks/test_local_tpch.py
Runs TPCH benchmarks (sf 0.2, in memory, 1 file) for the local executor in CI via codspeed. 
https://codspeed.io/Eventual-Inc/Daft/runs/66c57c43109f0eaa1b6b0933
> [CHORE] Enable codspeed benchmarking

- daft/runners/pyrunner.py
Addresses #2810 
Needs some testing to make sure that it fixes all of it
> [BUG] Perform cleanup of tasks and results when iterator is deleted

- .github/workflows/build-docs.yml
Fixes:
1. Fixes the conditional check on when to run publishing
2. Checks that no warnings are emitted when building docs (otherwise it fails CI)
3. Changes the alias so we get a unique link per-PR
4. Disables the Gihub deploy thing
> [CHORE] Update netlify publishing

- daft/expressions/expressions.py
- docs/source/api_docs/expressions.rst
Also fixes link in `Expression.approx_count_distinct`
> [DOCS] Add docs to hash and hash to docs

- daft/dataframe/dataframe.py
- daft/runners/partitioning.py
- docs/source/api_docs/dataframe.rst
- tests/dataframe/test_to_pylist.py
resolves #2578 
- Added `to_pylist` function in Dataframe to convert the dataframe into python list.
- Added testcases for the feature.
> [FEAT] Add `to_pylist` on DataFrame

- daft/context.py
- daft/daft/__init__.pyi
- src/common/daft-config/src/lib.rs
- src/common/daft-config/src/python.rs
- src/daft-plan/src/physical_planner/translate.rs
- tests/dataframe/test_joins.py
Reverts Eventual-Inc/Daft#2844
> Revert "[FEAT]: `shuffle_join_default_partitions` param"

- daft/__init__.py
- daft/sql/__init__.py
> [CHORE]: Move daft.sql.sql module to daft.sql

- src/daft-sql/src/lib.rs
- src/daft-sql/src/planner.rs
- tests/sql/test_exprs.py
> [BUG]: sql nested and wildcard

- src/daft-core/src/array/fixed_size_list_array.rs
- src/daft-core/src/array/ops/list_agg.rs
- src/daft-core/src/array/ops/mod.rs
- src/daft-core/src/array/struct_array.rs
- tests/table/test_table_aggs.py
> [FEAT] agg_list support for list and struct types

- src/daft-sql/src/planner.rs
- tests/sql/test_exprs.py
closes https://github.com/Eventual-Inc/Daft/issues/3057
> [FEAT]: sql between

- src/daft-sql/src/modules/aggs.rs
- src/daft-sql/src/planner.rs
- src/daft-sql/src/table_provider/mod.rs
- tests/sql/test_joins.py
- tests/sql/test_sql.py
- closes https://github.com/Eventual-Inc/Daft/issues/3065
- closes https://github.com/Eventual-Inc/Daft/issues/3059
> [FEAT]: sql tbl alias, and compount ident for joins

- daft/__init__.py
- daft/analytics.py
- tests/test_analytics.py
- tests/test_context.py
> [BUG] Always run telemetry codepath

- .github/workflows/run-command-on-ray.yaml
- create workflow to just minimally setup stuff on ray-cluster
- not fully working yet :(
> [FEAT] Create new run workflow

- .github/ci-scripts/templatize_ray_config.py
- .github/workflows/run-cluster.yaml
Address leftover comments on https://github.com/Eventual-Inc/Daft/pull/3461.
> [CHORE] Address comments on previous PR

- daft/runners/pyrunner.py
Warn users that pyrunner is going to be deprecated and they should switch to native.
> [CHORE] Add warning in PyRunner to switch to Native

- src/daft-local-execution/src/intermediate_ops/anti_semi_hash_join_probe.rs
- src/daft-local-execution/src/intermediate_ops/cross_join.rs
- src/daft-local-execution/src/intermediate_ops/inner_hash_join_probe.rs
- src/daft-local-execution/src/lib.rs
- src/daft-local-execution/src/pipeline.rs
- src/daft-local-execution/src/sinks/cross_join_collect.rs
- src/daft-local-execution/src/sinks/hash_join_build.rs
- src/daft-local-execution/src/sinks/outer_hash_join_probe.rs
- src/daft-local-execution/src/state_bridge.rs
Follow on from https://github.com/Eventual-Inc/Daft/pull/3437#discussion_r1872261677
> refactor(swordfish): Generic broadcast state bridge

- daft/context.py
- daft/dataframe/dataframe.py
- daft/runners/pyrunner.py
- src/daft-local-plan/src/translate.rs
Set swordfish as default
Note:
- Disables printing of physical plan explains for now
> feat: Default native runner

- src/arrow2/src/compute/cast/boolean_to.rs
- tests/expressions/test_list_.py
- tests/series/test_cast.py
This PR fixes,
* #3740 
* #3769
> fix: boolean casts to strings and null propagation

- benchmarking/tpch/ray_job_runner.py
For TPC-DS benchmarks, we record planning time, execution time, as well as the query plan. Do the same for TPC-H benchmarks.
> ci: Record info for TPCH benchmarks

- README.rst
> docs: update README.rst diagram

- src/daft-core/src/array/ops/comparison.rs
- src/daft-logical-plan/src/builder/mod.rs
found a couple printlns that were left from dev/debugging.
> chore: remove accidental printlins

- daft/io/writer.py
Closes https://github.com/Eventual-Inc/Daft/issues/3783
Closes https://github.com/Eventual-Inc/Daft/issues/3723
> fix: protocol in iceberg writes

- src/daft-sql/src/planner.rs
- src/daft-sql/src/table_provider/read_csv.rs
- src/daft-sql/src/table_provider/read_json.rs
- src/daft-sql/src/table_provider/read_parquet.rs
- tests/sql/test_sql_table_functions.py
* removes unnecessary clones since aliases are now added in get_table https://github.com/Eventual-Inc/Daft/pull/3848
* uses factoring suggestion from https://github.com/Eventual-Inc/Daft/pull/3836#discussion_r1964181812
* adds additional table-value function tests
> chore: minor cleanup to table-value functions

- daft/scarf_telemetry.py
Update scarf_telemetry method to also respect `DAFT_ANALYTICS_ENABLED` env var along with scarf env vars
> docs: respect daft analytics env var

- daft/dataframe/display.py
Fixes: https://github.com/Eventual-Inc/Daft/issues/3866
> fix: Add metadata to subgraph options in python

- src/arrow2/src/compute/cast/mod.rs
- src/daft-core/src/array/ops/from_arrow.rs
- src/daft-core/src/datatypes/logical.rs
- src/daft-core/src/series/from.rs
- src/daft-core/src/utils/arrow.rs
- src/daft-schema/src/dtype.rs
- tests/dataframe/test_creation.py
- tests/series/test_if_else.py
> fix: arrow to Series for nested map array

- daft/series.py
Fixes: https://github.com/Eventual-Inc/Daft/issues/3879
> fix: Add check for numpy in from_pylist

- .github/workflows/build-wheel.yml
- .github/workflows/nightly-publish-s3.yml
- .github/workflows/publish-dev-s3.yml
- .github/workflows/publish-pypi.yml
- daft/__init__.py
- pyproject.toml
- requirements-dev.txt
Also adds a warning if users install Daft via `getdaft`
> build: build and publish daft package

- daft/dataframe/dataframe.py
- tests/io/lancedb/test_lancedb_writes.py
Fixes https://github.com/Eventual-Inc/Daft/issues/3923 and updates `test_lancedb_writes.py` to test append mode behaviour.
> fix: write_lance append mode when storage_options required

- daft/__init__.py
- daft/catalog/__iceberg.py
- daft/catalog/__init__.py
- daft/session.py
- docs/mkdocs.yml
- docs/mkdocs/catalogs.md
- docs/mkdocs/css/extra.css
- docs/mkdocs/sessions.md
This PR is in preparation of the upcoming release with a detailed look into leveraging sessions.
> docs: adds additional catalog and session documentation

- daft/sql/sql_connection.py
- tests/integration/sql/conftest.py
- tests/integration/sql/test_sql.py
Fixes: https://github.com/Eventual-Inc/Daft/issues/3947
> fix: Add target dialect when making subquery in read_sql

- README.rst
> chore: fix slack link in readme

- .github/assets/tpch-bench.yaml
- .github/ci-scripts/distributed_tpch.py
- .github/workflows/benchmark-distributed-tpch.yml
- benchmarking/tpch/answers_sql.py
* change Ray cluster AMI to Amazon linux 2023, which is more performant than ubuntu
* download traces from Ray cluster and save them 
* get S3 config from master node instead of worker nodes
> ci: update distributed tpch benchmark

- src/daft-algebra/src/simplify/numeric.rs
`1 / x != x` and `0 - x != x`
Closes #3983 
Fixes the incorrect simplify expression rule.
> fix: Fix incorrect numeric identity optimizations

- daft/analytics.py
- tests/test_analytics.py
closes https://github.com/Eventual-Inc/Daft/issues/3982
> fix: datetime deprecation

- src/daft-algebra/src/simplify/boolean.rs
`x != true` should transform into `!x`.
> fix: Fix boolean expression simplifier

- Cargo.lock
- src/daft-local-execution/Cargo.toml
> chore: Upgrade kanal to 0.1

- docs/mkdocs/integrations/s3tables.md
Fix some typos, missing info, on s3 tables docs.
> docs: Fix s3 tables docs

- docs/mkdocs/install.md
Add docs
https://github.com/Eventual-Inc/Daft/issues/3564
docs
> docs: update install instructions for daft-lts and nightly

- src/daft-logical-plan/src/optimization/rules/reorder_joins/brute_force_join_order.rs
- src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
In https://github.com/Eventual-Inc/Daft/pull/4003 we forgot to swap the conditions when the left and right sides swap :'(
This PR fixes this and also makes sure we can properly construct a logical plan from the given join order.
> fix: Fix join condition swaps when left/right sides swap

- daft/__init__.py
- daft/runners/native_runner.py
- daft/runners/pyrunner.py
- daft/runners/ray_runner.py
- daft/scarf_telemetry.py
- tests/test_scarf_telemetry.py
> chore: Track imports on scarf

- src/daft-sql/src/planner.rs
- tests/sql/test_aggs.py
adds support for sql GROUP BY ROLLUP
We don't yet have documentation for groupbys, So it was a bit out of scope to add all of the documentation in to this PR.
> feat(sql): Add basic ROLLUP support

- daft/expressions/expressions.py
> docs: permalink works and takes to docs site

- docs/mkdocs/core_concepts.md
Add a section called numbering rows that explains how to add ids to rows with monotonically increasing id
> docs: Add numbering rows section

- docs/mkdocs/integrations/delta_lake.md
Updates to documentation for deltalake types.
#4117 
#4109
> docs: fix deltalake type docs

- daft/unity_catalog/unity_catalog.py
Changes are from Nikk but needed to format and release. 
closes #4105
closes #4106
> feat: @nikkthegreek adds support for creating managed tables

- src/daft-core/src/array/ops/arrow2/sort/primitive/common.rs
- src/daft-core/src/array/ops/sort.rs
- tests/dataframe/test_sort.py
> fix: sorting with nulls_first

- .github/ISSUE_TEMPLATE/bug_report.yml
Replace python runner with native runner in bug report.
> chore: Update bug_report.yml to use native runner

- daft/filesystem.py
- tests/io/test_write_modes.py
Expand the path when we resolve it
Closes https://github.com/Eventual-Inc/Daft/issues/4183
> fix: Fix local writes with relative dir

- benchmarking/common_crawl/extract.py
> chore: Add warc workload to benchmarking

- pyproject.toml
> chore: Pin pyarrow <= 16.0.0

- daft/udf.py
- docs/catalogs.md
- docs/integrations/iceberg.md
- fix format of udf docstring (resource requests + >>>)
- remove TableSource from Catalogs doc
- update headings in Iceberg doc
n/a
> docs: small fixes

- tests/integration/iceberg/docker-compose/Dockerfile
- tests/integration/iceberg/test_dataloading.py
- tests/integration/io/test_dataloading.py
Adds an integration test to ensure that Glue/Iceberg -> Pytorch dataloading works.
> test: Add Glue/Iceberg to Pytorch dataloading test

- daft/dataframe/dataframe.py
- tests/dataframe/test_pipe.py
Adds a DataFrame pipe method.
* https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.pipe.html
* https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pipe.html
* Closes #4112 
> feat: adds DataFrame pipe method

- CONTRIBUTING.md
We support up to python 3.12 (there are some dependency issues with 3.13).
> chore: Update supported python version in CONTRIBUTING.md

- daft/window.py
- tests/window/test_running_agg.py
Small issue with copying window
> feat(window): fix window copy issue

- .pre-commit-config.yaml
- daft/daft/__init__.pyi
Updates to the latest mypy and updates to [latest member-attribute definition for Enums](https://typing.python.org/en/latest/spec/enums.html#defining-members).
n/a
> chore: updates mypy to 1.15.0

- CONTRIBUTING.md
- daft/series.py
- src/daft-dsl/src/functions/scalar.rs
- tests/expressions/conftest.py
- tests/expressions/test_utf8.py
- update `contributing.md` with a section about adding expressions
- simplify the testing pattern for new expressions.
> refactor(exprs): update testing and contributing guide

- src/daft-functions/src/uri/mod.rs
> fix: Remove dbg! in url download

- Cargo.lock
- src/daft-local-execution/Cargo.toml
Fix failing Rust test on CI due to an import issue.
> fix: Add Rust Testing Import

- daft/delta_lake/delta_lake_write.py
- daft/dependencies.py
- daft/iceberg/iceberg_write.py
- daft/io/_generator.py
- daft/io/catalog.py
- daft/io/writer.py
- daft/lazy_import.py
> chore: Fix some strict mypy errors

- .vscode/settings.json
- daft/catalog/__glue.py
- daft/catalog/__iceberg.py
- daft/catalog/__init__.py
- daft/catalog/__memory.py
- daft/catalog/__s3tables.py
- daft/catalog/__unity.py
Fixes some mypy checks in the `daft.catalog` package.
> fix: mypy catalog fixes

- src/daft-distributed/src/pipeline_node/in_memory_source.rs
- src/daft-distributed/src/pipeline_node/intermediate.rs
- src/daft-distributed/src/pipeline_node/limit.rs
- src/daft-distributed/src/pipeline_node/materialize.rs
- src/daft-distributed/src/pipeline_node/mod.rs
- src/daft-distributed/src/pipeline_node/scan_source.rs
- src/daft-distributed/src/python/ray/task.rs
- src/daft-distributed/src/scheduling/dispatcher.rs
- src/daft-distributed/src/scheduling/mod.rs
- src/daft-distributed/src/scheduling/scheduler/default.rs
- src/daft-distributed/src/scheduling/scheduler/mod.rs
- src/daft-distributed/src/scheduling/scheduler/scheduler_actor.rs
- src/daft-distributed/src/scheduling/task.rs
- src/daft-distributed/src/scheduling/tests.rs
- src/daft-distributed/src/scheduling/worker.rs
- src/daft-distributed/src/stage/mod.rs
> feat(flotilla): Materialize pipeline

- .github/workflows/broken-link-checker.yml
> ci: Update base url in broken link checker

- docs/core_concepts.md
> docs: Dynamic execution docs

- tests/sql/test_select_expr.py
i tried to reproduce the panic in #4180 but i failed to reproduce it, this pr only adds a test case described in #4180
closes #4180
> chore: add test case over #4180

- src/daft-distributed/src/pipeline_node/actor_udf.rs
- src/daft-distributed/src/pipeline_node/in_memory_source.rs
- src/daft-distributed/src/pipeline_node/intermediate.rs
- src/daft-distributed/src/pipeline_node/limit.rs
- src/daft-distributed/src/pipeline_node/mod.rs
- src/daft-distributed/src/pipeline_node/scan_source.rs
- src/daft-distributed/src/pipeline_node/translate.rs
> chore(flotilla): PipelineNode `.start` accept `Arc<Self>` to simplify cloning

- daft/dataframe/dataframe.py
Args were duplicated and slightly incorrect. This PR corrects this.
> docs: Fix docstring for DataFrame.sort()

- src/daft-ir/src/lib.rs
issue = private constructors with public fields
> fix: add missing distinct field

- src/daft-io/src/s3_like.rs
> feat: add some throttling error for tos

- README.rst
> fix: fix pypi image url

- .github/workflows/pr-test-suite.yml
- codecov.yml
- daft/filesystem.py
- daft/runners/flotilla.py
- daft/runners/ray_runner.py
- daft/utils.py
- tests/benchmarks/test_local_tpch.py
Improve codecov, especially adding flotilla to be tracked by codecov.
This requires that we run the flotilla scheduler not on a ray actor, because it the codecov doesn't reach the ray actor. So we use the current model that we have, only run on ray actor if we are on ray client mode. Otherwise it is ran locally, which should be already on the ray head node.
> chore: Improve codecov

- src/common/daft-config/src/lib.rs
- src/daft-writers/src/lib.rs
- src/daft-writers/src/parquet_writer.rs
- src/daft-writers/src/physical.rs
Enables native remote writer by default.
> feat: Enable native remote writer by default

- daft/runners/flotilla.py
Add try_autoscale function.
Closes https://github.com/Eventual-Inc/Daft/issues/4691
> fix(flotilla): Add back autoscaling function

- src/daft-local-execution/src/runtime_stats/mod.rs
> chore: disable another flaky test

- README.rst
update readme banner image link (currently broken on mobile)
> fix: update readme banner image link

- src/common/daft-config/src/lib.rs
- tests/window/test_partition_only.py
- tests/window/test_partition_order_by_lag_lead.py
- tests/window/test_partition_order_by_rank.py
- tests/window/test_running_agg.py
> fix: `DAFT_FLOTILLA` env var should check for false conditions now

- daft/expressions/expressions.py
> fix: fix explode expr doc test

- daft/runners/ray_runner.py
If it errors it will not get caught and will hang everything
> fix: Put to_partition_tasks call in try block

- src/daft-distributed/src/python/mod.rs
> fix: Change dashboard warning to info

- src/daft-distributed/src/statistics/http_subscriber.rs
> fix: mark all pending nodes completed when plan completes

- mkdocs.yml
Left this redirect on a previous draft of the docs rewrite. Removing it.
> docs: Remove redirect for installation page

- docs/api/expressions.md
> docs: adds coalesce to docs

- daft/execution/execution_step.py
- daft/execution/physical_plan.py
- daft/execution/rust_physical_plan_shim.py
- src/daft-physical-plan/src/ops/limit.rs
- src/daft-physical-plan/src/ops/top_n.rs
- src/daft-physical-plan/src/optimization/optimizer.rs
- src/daft-physical-plan/src/physical_planner/translate.rs
- src/daft-physical-plan/src/plan.rs
- src/daft-scheduler/src/scheduler.rs
- tests/dataframe/test_limit_offset.py
> feat: Add offset operator support to DataFrame for Ray Runner

- docs/examples/document-processing.md
- docs/examples/window-functions.md
- docs/gen_pages/gen_txt_files.py
- docs/gen_pages/generate_llms_txt.py
- mkdocs.yml
For each markdown page, generate a .txt equivalent for our llms.txt
> docs: Generate files for llms.txt

- src/daft-distributed/src/pipeline_node/limit.rs
- src/daft-distributed/src/pipeline_node/top_n.rs
- src/daft-distributed/src/pipeline_node/translate.rs
- src/daft-distributed/src/stage/stage_builder.rs
> feat: Add offset support to Flotilla Engine

- daft/expressions/expressions.py
- docs/examples/document-processing.md
update from colab links to section headers
> docs: update links in document processing example

- src/daft-sql/src/lib.rs
- src/daft-sql/src/planner.rs
- tests/dataframe/test_limit_offset.py
- tests/sql/test_limit_offset.py
> feat: Add offset syntax support to SQL

- daft/__init__.py
- daft/daft/__init__.pyi
- daft/io/__init__.py
- daft/io/_huggingface.py
- docs/connectors/huggingface.md
- requirements-dev.txt
- src/common/io-config/src/config.rs
- src/common/io-config/src/huggingface.rs
- src/common/io-config/src/lib.rs
- src/common/io-config/src/python.rs
- src/daft-connect/src/session.rs
- src/daft-io/src/huggingface.rs
- src/daft-io/src/lib.rs
- src/daft-parquet/src/metadata.rs
- tests/integration/io/test_read_huggingface.py
Adds `daft.read_huggingface`
#2841
> feat: basic read_huggingface functionality

- docs/js/reo.js
- mkdocs.yml
> docs: add reo script to docs

- daft/io/huggingface/sink.py
When using `DataFrame.write_huggingface`, no longer show the progress bar displayed by the huggingface_hub library. Daft already has a progress bar so theirs is unnecessary.
none
> chore: disable hugging face library progress bars

- .github/workflows/pr-test-suite.yml
#4992 had to be reverted because of required checks. We do it for real this time.
> ci: Don't run pr test suite on non-code changes fr

- docs/index.md
Adds a more interactive description of Daft in the documentation overview page
https://github.com/user-attachments/assets/facd437c-4520-4f3a-bf33-40c9a8f5964c
I think it could use some improvement in terms of brevity, open to suggestions
> docs: Add better description in overview page

- docs/index.md
We made dark mode look good but forgot about light mode
> docs: Make overview page legible for light mode

- docs/SUMMARY.md
- docs/connectors/turbopuffer.md
Add a clean powerful example for using turbopuffer with daft
> docs: Document write_turbopuffer in the user guide

- .github/CODEOWNERS
> chore: Remove docs codeowners

- docs/SUMMARY.md
- docs/connectors/custom.md
- docs/use-case/batch-inference.md
> docs: Add batch inference use case

- README.rst
Add TrendShift trending repository badge to README
> docs: add TrendShift badge to README

- .github/workflows/pr-test-suite.yml
- Cargo.lock
Ran `cargo update -p aws-lc-rs --precise 1.14.1`
Successful build: https://github.com/Eventual-Inc/Daft/actions/runs/17987890706
> chore(deps): Upgrade aws lc rs

- docs/SUMMARY.md
- docs/api/datasets.md
- docs/api/index.md
- docs/datasets/common-crawl.md
Add documentation for the newly introduced Common Crawl dataset. See https://github.com/Eventual-Inc/Daft/discussions/5248 for more details.
> docs: Document Common Crawl dataset

- src/daft-core/src/array/ops/from_arrow.rs
- src/daft-schema/src/dtype.rs
prerequesite for `use_process`.
> feat: make file-array serializable

- src/daft-csv/src/local.rs
Our parallel CSV reader assumed that files separated records via \n. If \r\n is used, we would read the whole file before parsing the CSV content.
With this PR, we now perform parallel parsing even when records are delimited by \r\n.
Additionally, this PR fixes an issue where users had to explicitly specify the escape char for speculative parsing to work well.
> perf: Support parallel CSV parsing when files contain carriage returns

- .github/ci-scripts/distributed_tpch.py
- .github/ci-scripts/run_ai_benchmark.py
- .github/workflows/benchmark-ai.yml
- benchmarking/ai/audio_transcription/cluster.yaml
- benchmarking/ai/document_embedding/cluster.yaml
- benchmarking/ai/image_classification/cluster.yaml
- benchmarking/ai/video_object_detection/cluster.yaml
- tools/ci_bench_utils.py
Make the ai benchmarks runnable from github actions.
> ci: Add ai benchmarks ci
