Eventual-Inc/Daft

- .readthedocs.yaml
Seems like PDFs are having an issue in readthedocs. This PR only generates HTMLzip instead
> [DOCS] Do not generate PDFs

- src/daft-local-execution/src/pipeline.rs
- src/daft-local-execution/src/sinks/hash_join.rs
- src/daft-local-execution/src/sinks/mod.rs
- src/daft-local-execution/src/sinks/sort.rs
- src/daft-physical-plan/src/local_plan.rs
- src/daft-physical-plan/src/translate.rs
- src/daft-plan/src/lib.rs
- tests/benchmarks/test_local_tpch.py
> [FEAT] Add hashjoin, sort, and hashagg ops to new executor

- daft/daft
- daft/daft.pyi
- daft/io/_parquet.py
- src/daft-micropartition/src/micropartition.rs
- src/daft-scan/src/anonymous.rs
- src/daft-scan/src/file_format.rs
- src/daft-scan/src/glob.rs
- tests/io/test_parquet.py
> [FEAT]: support optional rowgroups to `read_parquet`

- daft/daft.pyi
- daft/dataframe/dataframe.py
- daft/table/table_io.py
- src/daft-scan/src/file_format.rs
- tests/cookbook/test_write.py
[#2373](https://github.com/Eventual-Inc/Daft/issues/2373)
> [FEAT] Create file when writing dataframe with no rows

- src/daft-core/src/array/ops/utf8.rs
- tests/series/test_utf8_ops.py
- tests/table/utf8/test_length.py
Previously, the `.str.length()` method would count the number of bytes in the UTF-8 string. This is inconsistent with Python's `len()` and pandas' `str.len()` which count Unicode codepoints. For instance, on the string "😉test", the number of bytes is 8, whereas the number of codepoints is 5. This PR makes Daft consistent with that behavior.
There doesn't seem to be a way now to reproduce the original behavior; maybe we should add a `.byte_length()` method for that.
> [BUG] Fix `.str.length()` on Unicode strings

- .github/workflows/python-package.yml
- daft/runners/pyrunner.py
Together with #2566 , closes #2561 
This PR changes the way the PyRunner performs resource accounting. Instead of updating the number of CPUs, GPUs and memory used only when futures are retrieved, we do this just before each task completes. These variables are protected with a lock to allow for concurrent access from across worker threads.
Additionally, this PR now tracks the inflight `Futures` across all executions globally in the PyRunner singleton. This is because there will be instances where a single execution might not be able to make forward progress (e.g. there are only 8 CPUs available, and there are 8 other currently-executing partitions). In this case, we need to wait for **some** execution globally to complete before attempting to make forward progress on the current …
> [FEAT] Fix resource accounting in PyRunner

- .github/workflows/python-package.yml
- benchmarking/parquet/benchmark-requirements.txt
- daft/dataframe/dataframe.py
- daft/table/table_io.py
- requirements-dev.txt
- tests/integration/io/docker-compose/retry_server/retry-server-requirements.txt
PyIceberg v0.7.0 was [just released](https://github.com/apache/iceberg-python/releases/tag/pyiceberg-0.7.0). One of the new changes is the Transaction API, which replaces some of the private functions that we have been using. This PR adds support for those changes
> [FEAT] Add support for pyiceberg v0.7

- src/arrow2/src/array/ord.rs
- tests/dataframe/test_temporals.py
- tests/series/test_comparisons.py
Specifically, this means that columns with dtype e.g. `Timestamp(Milliseconds, Some("UTC"))` can be compared. However, this is a naïve comparison, as e.g. "UTC" and "+00:00" still cannot be compared.
> [FEAT] Add comparison of timestamps with same timezone

- src/arrow2/src/array/dyn_ord.rs
- src/arrow2/src/array/mod.rs
- src/daft-core/src/schema.rs
- src/daft-core/src/utils/dyn_compare.rs
- src/daft-core/src/utils/mod.rs
- src/daft-table/src/growable/mod.rs
- src/daft-table/src/lib.rs
- src/daft-table/src/ops/joins/mod.rs
- src/daft-table/src/ops/mod.rs
- src/daft-table/src/probe_table/mod.rs
* Enables Dyn Compare + Partial Probe Table creation
`Fn(&dyn Array, &dyn Array, usize, usize) -> Ordering`
> [PERF] Dyn Compare + Probe Table

- src/daft-plan/src/logical_optimization/optimizer.rs
Fixes #2616
From Slack:
> Essentially the project and the limit are being pushed down in the same rule batch, at the same time. However, this means that if a project and a limit are in the same tree, the project gets pushed down, but then the limit gets immediately pushed down beneath it, resulting in no change, and the project never gets to merge with the scan.
This PR moves limit pushdowns into a different rule batch than projection pushdowns, meaning they no longer conflict with each other.
> [BUG] Fix projection pushdowns not working with limits

- src/daft-parquet/src/file.rs
- src/daft-parquet/src/read.rs
- src/daft-parquet/src/read_planner.rs
- src/daft-parquet/src/stream_reader.rs
- src/parquet2/src/read/page/stream.rs
Adds streaming reads to remote parquet files.
The algorithm is similar to that for local parquet files:  Read bytes into memory -> get arrow chunk iterator -> emit table per chunk
Q6 Memory Profile:
Streaming 
Bulk
> [FEAT] Remote parquet streaming

- daft/expressions/expressions.py
- daft/series.py
This is a **breaking change**. Now every option needs to be toggled on, instead of off, which I feel is slightly more usable.
> [CHORE] Set `Expression.str.normalize()` options to False by default

- daft/daft.pyi
- daft/expressions/expressions.py
- daft/udf.py
- src/daft-dsl/src/functions/python/mod.rs
- src/daft-dsl/src/functions/python/udf.rs
- src/daft-dsl/src/python.rs
- src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
- tests/expressions/test_udf.py
Lets you specify a batch size for your UDFs, and then inputs are split up into batches of at most that size before being passed in to the UDF.
> [FEAT] Add input batching for UDFs

- src/daft-plan/src/logical_optimization/rules/push_down_filter.rs
- src/daft-plan/src/logical_plan.rs
- tests/integration/iceberg/docker-compose/docker-compose.yml
- tests/integration/io/docker-compose/docker-compose.yml
There are some additional optimizations I would like to make but I decided to keep this PR minimal. Aside from splitting a filter into its conjunctions to allow for partial predicate pushdowns, this PR does the same optimizations as the original when it is correct to do so.
Also a flyby change on some `docker-compose.yaml` files to remove some image specifiers that were causing some failed tests and were probably meant to actually describe the name of the service?
TODO:
> [BUG] Fix filter pushdown into non-inner joins

- src/daft-core/src/array/ops/groups.rs
- src/daft-core/src/array/ops/hash.rs
- src/daft-core/src/datatypes/matching.rs
- tests/series/test_hash.py
- tests/table/test_table_aggs.py
This only works within a given schema - structs with different field names are not guaranteed to be hashed differently. Hashes may also be different depending on the ordering of the fields.
> [FEAT] Add hashing and groupby on structs

- daft/expressions/expressions.py
- tests/table/struct/test_to_struct.py
e.g. `to_struct("a", "b")` instead of `to_struct(col("a"), col("b"))`
> [FEAT] Support passing in column name strings to `to_struct`

- daft/dataframe/dataframe.py
- tests/cookbook/test_count_rows.py
- tests/io/test_parquet.py
Closes: #1996 
Our new `df.count()` behavior will be similar to `SELECT COUNT(*)` in SQL, returning a new dataframe with a single `"count"` column.
> [FEAT] Changes the default count() behavior to perform a global row count instead

- src/daft-core/src/array/ops/hash.rs
- tests/table/test_hash.py
and this is why you always write table tests
> [BUG] Fix struct `.hash()` naming bug

- Cargo.lock
- src/daft-local-execution/Cargo.toml
- src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
- src/daft-local-execution/src/lib.rs
- src/daft-local-execution/src/pipeline.rs
- src/daft-local-execution/src/run.rs
- src/daft-local-execution/src/sinks/blocking_sink.rs
- src/daft-local-execution/src/sinks/hash_join.rs
- src/daft-local-execution/src/sinks/streaming_sink.rs
- src/daft-local-execution/src/sources/in_memory.rs
- src/daft-local-execution/src/sources/scan_task.rs
- src/daft-local-execution/src/sources/source.rs
Example:
```
df = daft.from_pydict({"a": ["foo", "bar", "baz"]})
df = df.select(df["a"].str.match("["))
df.show()
Error when running pipeline node ProjectOperator
File "test.py", line 21, in <module>
df.show()
File "/Users/colinho/Desktop/Daft/daft/api_annotations.py", line 26, in _wrap
return timed_method(*args, **kwargs)
File "/Users/colinho/Desktop/Daft/daft/analytics.py", line 185, in tracked_method
return method(*args, **kwargs)
File "/Users/colinho/Desktop/Daft/daft/dataframe/dataframe.py", line 2278, in show
dataframe_display = self._construct_show_display(n)
File "/Users/colinho/Desktop/Daft/daft/dataframe/dataframe.py", line 2235, in _construct_show_display
for table in get_context().runner().run_iter_tables(builder, results_buffer_size=1):
File …
```
> [CHORE] Add error snafus for local executor

- daft/dataframe/dataframe.py
- docs/source/api_docs/dataframe.rst
1. Changes default `results_buffer_size` on our dataframe iteration methods to use the total number of available CPUs on the current machine instead of `1`, which was empirically observed by users to significant slow down processing speeds
2. Adds a new `df.iter_rows()` API which is used by `__iter__`, but provides an alternative API if a user needs to configure `results_buffer_size`
> [FEAT] Add dataframe iteration on rows and change default buffer size

- daft/analytics.py
- tests/test_analytics.py
Add a simple timeout to the `urllib.request.urlopen` invocation made inside of `_post_segment_track_endpoint`.
> [BUG] Add timeout to analytics client

- daft/io/_csv.py
- daft/io/_json.py
- daft/io/_parquet.py
- tests/dataframe/test_creation.py
- tests/io/test_parquet.py
Fully deprecates schema hints from read_csv / json / parquet and removes the warning. See https://github.com/Eventual-Inc/Daft/pull/2326 for origin
> [CHORE] Deprecate schema hints

- .github/workflows/python-package.yml
- tests/io/test_parquet.py
1. Uses numpy to generate data
2. Uses `to_arrow` when possible to do equality comparisons.
Notes:
- I had to change the `lists` to `large_lists` in order to do the arrow comparisons, this is because our `to_arrow` method converts lists to large lists. (I don't think this affects the tests?)
- I also made some minor refactors, such as changing the `is_arrow` flag to be an `is_instance` check instead of an argument passed by the caller. 
Before:
After:
> [CHORE] Speed up parquet integration test

- Cargo.lock
- daft/daft.pyi
- daft/io/_csv.py
- daft/io/_json.py
- daft/io/_parquet.py
- daft/io/common.py
- src/daft-micropartition/src/micropartition.rs
- src/daft-parquet/Cargo.toml
- src/daft-parquet/src/file.rs
- src/daft-parquet/src/metadata.rs
- src/daft-parquet/src/read.rs
- src/daft-parquet/src/stream_reader.rs
- src/daft-scan/src/glob.rs
- src/daft-scan/src/python.rs
- src/daft-scan/src/scan_task_iters.rs
- src/parquet2/Cargo.toml
- src/parquet2/src/metadata/column_chunk_metadata.rs
- src/parquet2/src/metadata/file_metadata.rs
- src/parquet2/src/metadata/mod.rs
- src/parquet2/src/read/mod.rs
When reading files from AWS, the logical to physical plan translator previously fetched the metadata for the files sequentially, which could be very slow if there are many files. (This bug was introduced in #2358.)
This PR makes it so that we only cache the metadata upon splitting, and when we do so we only cache the row groups that are actually relevant to each scan task. This avoids serializing the entire metadata for each Ray runner, which should improve performance.
Benchmark results:
> [PERF] Fix excessive parquet metadata reading

- daft/__init__.py
- daft/context.py
- daft/runners/ray_runner.py
- docs/source/api_docs/configs.rst
- src/daft-parquet/src/file.rs
- src/daft-parquet/src/read.rs
- tests/benchmarks/test_local_tpch.py
- tests/conftest.py
- tests/cookbook/test_write.py
- tests/dataframe/test_aggregations.py
- tests/integration/io/parquet/test_reads_public_data.py
- tests/integration/sql/test_sql.py
- tests/io/delta_lake/test_table_read.py
- tests/io/delta_lake/test_table_write.py
- tests/io/test_merge_scan_tasks.py
- tests/io/test_split_scan_tasks.py
- tests/ray/runner.py
1. Adds a context manager to perform overrides of the configs that will reset themselves afterwards
2. Adds some fixes for splitting of Parquet files
> [BUG] Add a with_execution/planning_config context manager and fix tests for splitting of parquet

- daft/expressions/expressions.py
- docs/source/api_docs/dataframe.rst
- docs/source/migration_guides/coming_from_dask.rst
- docs/source/user_guide/integrations/delta_lake.rst
- docs/source/user_guide/integrations/hudi.rst
- docs/source/user_guide/integrations/huggingface.rst
- docs/source/user_guide/integrations/microsoft-azure.rst
- docs/source/user_guide/integrations/sql.rst
- docs/source/user_guide/poweruser/distributed-computing.rst
- docs/source/user_guide/poweruser/partitioning.rst
> [DOCS] Partitioning user guide and small doc fixes

- src/daft-plan/src/logical_ops/actor_pool_project.rs
- src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
- src/daft-plan/src/logical_optimization/rules/split_actor_pool_projects.rs
Adds some fixes for performing projection pushdowns performed by actor pool project
> [FEAT] Fix projection pushdowns in actor pool project

- daft/dataframe/dataframe.py
- tests/table/test_from_py.py
see https://github.com/Eventual-Inc/Daft/issues/2679
> [BUG]: use recordbatch instead of table for `df.to_arrow_iter`

- daft/udf.py
There were a few inconsistencies in the UDF documentation w.r.t resource requests that I noticed while perusing the docs.
> [DOCS]: Fix typos in UDF documentation

- src/daft-core/src/array/ops/cast.rs
- src/daft-core/src/array/ops/get.rs
see https://github.com/Eventual-Inc/Daft/issues/2723
> [BUG]: fsl to list with validity

- daft/dataframe/dataframe.py
- tests/dataframe/test_count.py
By adding wildcard expansion, this started expanding out into all columns, which is not the expected behavior from SQL.
> [BUG] Fix `count("*")` behavior

- src/daft-core/src/array/ops/sum.rs
- src/daft-core/src/datatypes/agg_ops.rs
- src/daft-core/src/series/ops/agg.rs
- tests/dataframe/test_decimals.py
- tests/expressions/typing/conftest.py
- tests/expressions/typing/test_aggs.py
Resolves #2527. 
~Might need another test, I don't think the sum test (which is a decimal-specific copy of other sum aggregation test) does anything to actually confirm the sum itself produces correct numbers.~ (added)
With this, one can do like:
```pyimport daft
df = daft.from_pydict({"foo": [1, 1, 2, 2, 3, 3]})
df = df.with_column("foo_decimal", df["foo"].cast(daft.DataType.decimal128(7, 2)))
df = df.sum("foo_decimal")
df.collect()
```
yields 
```
╭──────────────────╮                                                                                                                               
│ foo_decimal      │
│ ---              │
│ Decimal128(7, 2) │
╞══════════════════╡
│ 12.00            │
╰──────────────────╯
(Showing first 1 of 1 rows)
```
> [FEAT] Add support for sum aggregation for decimal128 type

- daft/daft.pyi
- daft/execution/execution_step.py
- src/daft-plan/src/physical_ops/scan.rs
- src/daft-scan/src/lib.rs
- src/daft-scan/src/python.rs
Fixes memory estimations for ScanTask when limits are pushed down
* Adds a new`approx_num_rows` API to ScanTask, which is distinct from the `num_rows` API which is expected to provide an exact number of rows if available
* Adds some heuristics for determining the approximate number of rows with the available information, including accounting for limits
* Fixes `num_rows` to account for limit pushdowns as well
> [BUG] Fix ScanTask memory estimations when limits are provided

- src/daft-parquet/src/stream_reader.rs
- tests/integration/io/parquet/test_reads_public_data.py
- tests/io/test_parquet.py
When reading local parquet files containing multiple row groups with a limit applied, sometimes the resulting table does not respect the given limit, causing errors such as `DaftError::ValueError While building a Table with Table::new_with_size, we found that the Series lengths did not match. Series named: col had length: 2048 vs the specified Table length: 1034` to be thrown.
The issue was a small bug where each row group range being read would take the global limit passed into the parquet read, instead of the pre-computed row group limit, which is aware of how many rows had been read by previous row groups. This caused the parquet reader to read more rows from a row group than specified.
To fix this, we pass the pre-computed row group limit properly to the reader.
For example, consider …
> [BUG] Fix parquet reads with limit across row groups

- .pre-commit-config.yaml
Fixes issue where a test could be invalid rust but still pass precommit
> [CHORE] Enable all targets for cargo check

- src/daft-plan/src/physical_planner/translate.rs
- tests/dataframe/test_aggregations.py
- tests/dataframe/test_approx_percentiles_aggregations.py
- tests/dataframe/test_map_groups.py
Fixes: https://github.com/Eventual-Inc/Daft/issues/1376
Groupby expressions are evaluated during aggregations. This means multistage aggs involving groupby's with aliases will have those aliases evaluated in the initial stage, thereby changing the name of the column. The later stage groupby's should reflect this, and use the name of the original expression instead of the expression itself.
> [BUG] Groupby with alias not working

- src/common/treenode/src/lib.rs
- src/daft-plan/src/logical_ops/project.rs
- src/daft-plan/src/logical_optimization/mod.rs
- src/daft-plan/src/logical_optimization/optimizer.rs
- src/daft-plan/src/logical_optimization/rules/drop_repartition.rs
- src/daft-plan/src/logical_optimization/rules/mod.rs
- src/daft-plan/src/logical_optimization/rules/push_down_filter.rs
- src/daft-plan/src/logical_optimization/rules/push_down_limit.rs
- src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
- src/daft-plan/src/logical_optimization/rules/rule.rs
- src/daft-plan/src/logical_optimization/rules/split_actor_pool_projects.rs
- src/daft-plan/src/logical_optimization/test/mod.rs
Follow-up from #2791 after offline conversation.
This PR still uses the existing logical plan optimizer, but now uses `common_treenode::Transformed` instead of a custom implementation. In addition, it removes the apply order logic from the optimizer and replaces it with `common_treenode::TreeNode` transforms done in the optimizer rules themselves.
This PR should not cause any functional changes to any of the optimizer rules or the way they are applied, except for the fact that rules in a batch are now each applied to the whole tree before the next rule, instead of each being applied to a single plan node if they have the same apply order. Future PRs will separate the rules out and make better use of treenode.
> [CHORE] Use treenode for tree traversal in logical optimizer rules

- daft/filesystem.py
Addresses: https://github.com/Eventual-Inc/Daft/issues/2788
Propogates the S3Config.num_tries config to the pyarrow S3 filesystem.
Note that the other relevant parameters on S3Config, `retry_mode` and `retry_initial_backoff_ms`, are ignored as pyarrow's [S3RetryStrategy](https://github.com/apache/arrow/blob/ab0a40ee34217070f14027776682074c55d0b507/python/pyarrow/_s3fs.pyx#L112) only has one parameter `max_attempts`.
Note that this only addresses S3. GCSConfig and AzureConfig do not have retry settings.
> [BUG] Propogate S3Config.num_tries to pyarrow S3 filesystem

- daft/dataframe/dataframe.py
- daft/datatype.py
- daft/runners/partitioning.py
- daft/runners/ray_runner.py
- daft/series.py
- daft/table/micropartition.py
- daft/table/table.py
- src/daft-core/src/python/datatype.rs
- tests/dataframe/test_creation.py
Cleanup PR.
1. Removes `cast_tensors_to_ray_tensor_dtype` as a user-facing argument in our export methods (e.g. `to_arrow`, `to_pandas` etc) -- this is really only intended to be used when a user is converting a Daft dataframe to a Ray dataset anyways and there isn't a need to expose this functionality to a user
2. Instead, the logic for casting `daft.DataType.tensor` data to a Ray Data tensor type is done inside of the conversion code for Ray Data (`_make_ray_block_from_micropartition`). This lets us contain the ickiness of that code without having it touch all of our `to_arrow` logic
3. Also removes `_trim_pyarrow_large_arrays` which was a legacy codepath that doesn't get hit anymore
> [CHORE] Remove user-facing arguments for casting to Ray's tensor type

- daft/dataframe/dataframe.py
- src/daft-core/src/ffi.rs
- src/daft-core/src/python/datatype.rs
- src/daft-core/src/python/schema.rs
Fixes `to_arrow()` to use Table.from_batches for performance
Driveby: fix args `results_buffer_size` documentation by using a num_cpus literal
> [PERF] Use to_arrow_iter in to_arrow to avoid unnecessary array concats

- src/daft-sql/src/lib.rs
- src/daft-sql/src/planner.rs
- tests/sql/test_sql.py
This adds support to SQL to run global aggregation when there are only aggregations and no group by, which is inline with many other SQL implementations.
It is similar in nature to https://github.com/Eventual-Inc/Daft/issues/1979, but specific to SQL - depending on how that issue is resolved the SQL planner code here could be redundant.
Example:
```
d = daft.from_pydict({"i": [1,2,3,4,5]})
daft.sql('''SELECT sum(i) FROM d''', SQLCatalog({'d': d})).collect()
╭───────╮                                                                                                    
│ i     │
│ ---   │
│ Int64 │
╞═══════╡
│ 15    │
╰───────╯
```
*note*: I know the SQL support is new, so sorry if this is jumping the gun! Is it better to first create discussions or issues for this kind of change? I've been …
> [FEAT] [SQL] Add global agg support for SQL

- src/daft-scan/src/glob.rs
- src/daft-scan/src/lib.rs
Resolves #2709
- Previously if there were multiple urls in the logical plan, it cluttered the output of 'df.explain' with massive text. Now we add ellipses if there are more than six, improving readability.
- The current test emulates multiple urls from  the same test fixture 'mvp.parquet'. Ideally there should be a test fixture with multiple parts of a parquet file.
> [FEAT] Ellipsize glob scan paths

- src/daft-core/src/array/ops/cast.rs
- src/daft-core/src/array/ops/image.rs
- src/daft-core/src/array/ops/trigonometry.rs
- src/daft-core/src/count_mode.rs
- src/daft-core/src/datatypes/agg_ops.rs
- src/daft-core/src/datatypes/infer_datatype.rs
- src/daft-core/src/join.rs
- src/daft-core/src/kernels/hashing.rs
- src/daft-core/src/kernels/search_sorted.rs
- src/daft-core/src/series/array_impl/binary_ops.rs
- src/daft-core/src/series/ops/abs.rs
- src/daft-core/src/series/ops/ceil.rs
- src/daft-core/src/series/ops/exp.rs
- src/daft-core/src/series/ops/floor.rs
- src/daft-core/src/series/ops/list.rs
- src/daft-core/src/series/ops/log.rs
- src/daft-core/src/series/ops/round.rs
- src/daft-core/src/series/ops/sign.rs
- src/daft-core/src/series/serdes.rs
- src/daft-core/src/utils/supertype.rs
- removed all instances of `use MyEnum::*;` from `daft-core`
- using that pattern has a huge chance of hard-to-catch bugs being created in the future
> [CHORE] Remove enum imports daft core

- .github/workflows/python-package.yml
- benchmarking/parquet/benchmark-requirements.txt
- daft/dataframe/dataframe.py
- daft/io/__init__.py
- daft/io/_deltalake.py
- daft/table/table_io.py
- requirements-dev.txt
- src/arrow2/src/io/parquet/read/schema/convert.rs
- tests/integration/io/docker-compose/retry_server/retry-server-requirements.txt
- tests/io/delta_lake/conftest.py
Deltalake v0.19 changes their `_convert_pa_schema_to_delta` function to take in a `schema_conversion_mode` instead of `large_dtypes`. Pyarrow also needed to be upgraded to v16.0.0 as well to be compatible with the new version of deltalake
The difference between this PR and #2754 is that it still maintains compatibility with older deltalake versions.
The reason why this PR also includes a change to arrow2 is because starting in version 0.19, deltalake uses arrow-rs by default instead of pyarrow to write files when calling `deltalake.write_deltalake`. We do not actually use this functionality but our tests do, and arrow-rs writes map arrays in a way that does not conform to the parquet spec. I figured it would be good to just add that compatibility in there just in case some user is using …
> [CHORE] Ensure compatibility with deltalake version v0.19

- daft/datatype.py
- daft/runners/ray_runner.py
- daft/series.py
- tests/series/test_concat.py
Prior to this PR, Ray data extension tensor types are handled in Daft's importing logic from Arrow. This PR moves this logic to Ray runner code when creating a partition set from a Ray dataset.
> [CHORE] Decouple Ray tensor types from main Daft logic

- daft/dataframe/dataframe.py
I don't know a good way to test this since we believe this issue only arises when you mount a fabric table onto the local filesystem. However it is a pretty change that should not affect any existing behavior. I will verify that it works with our users once it is released.
> [FEAT] Delta lake allow unsafe rename for local writes

- daft/sql/sql_connection.py
- daft/sql/sql_scan.py
- daft/table/table_io.py
When Daft executes a read_sql scan task, it calls the `def read_sql` function in table_io.py. This function then calls the `.read` method on the SQLConnection object. However, the `.read` method will reconstruct the sql query and add another layer of subqueries, which is unnecessary.
This is because the `.read` method constructs a sql query given additional predicates, projections, and limits, then executes it. However, the scan task is already given a constructed query with pushdowns applied, so this reconstruction is unnecessary.
This PR removes the `.read` method and instead exposes the `execute_sql_query` method. Having `.read` do construction and execution together is confusing.
> [BUG] Avoid reconstructing sql query in read_sql

- daft/dataframe/dataframe.py
- docs/source/api_docs/dataframe.rst
- tests/dataframe/test_filter.py
closes https://github.com/Eventual-Inc/Daft/issues/2846
Note, this does not rename 'where' to 'filter' but instead just adds an alias. We can revisit at a later date if we want to deprecate the `where` method.
> [FEAT]: Dataframe.filter method

- daft/expressions/expressions.py
https://github.com/Eventual-Inc/Daft/issues/2863
> [BUG] Fix concat expression typing

- daft/sql/sql_scan.py
- tests/conftest.py
- tests/integration/sql/conftest.py
- tests/integration/sql/test_sql.py
When scanning an empty SQL table, if a user specifies `num_partitions > 1`, then we get `TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'` or `Failed to get partition bounds: {self._partition_col} is not a numeric or temporal type, and cannot be used for partitioning`.
These are both results of attempts to partition the scan using a column with no data. Despite the table not having rows, we attempt to fulfill the user's request to use `num_partitions > 2`, only to run into errors because there is no min and max value available compute partition range sizes on.
Furthermore, in some cases SQL databases do not return type information when a table has no rows, so an empty integer column might be read as an empty string column which cannot be used for partitioning.
We …
> [BUG] Fix partitioning SQL scans on empty tables

- src/daft-schema/src/dtype.rs
- fixed decimal printout
- was being printed out like `{}.{}`
- changed to `Decimal(precision={}, scale={})` instead
> [BUG] Fix display for decimal types

- daft/execution/physical_plan.py
- daft/runners/ray_runner.py
- daft/udf.py
- tests/actor_pool/test_ray_actor_pool.py
Added tests from https://github.com/Eventual-Inc/Daft/pull/2677/commits/675b0b121a9f0253609c65c59197856e85f94f1c
> [FEAT] Add ability for RayRunner to run actor pool projects (beta feature)

- src/daft-sql/src/planner.rs
- tests/sql/test_sql.py
Called it a bug because the error is confusing, this fixes error behavior of multistatement sql. Before:
```py
daft.sql('''SELECT * FROM df; SELECT count(*) FROM df''', cat)
```
results in this error:
```py
daft.exceptions.InvalidSQLException: Unsupported SQL: 'SELECT * FROM df'
```
but of course that SQL is supported! With this change, error becomes:
```py
daft.exceptions.InvalidSQLException: Unsupported SQL: 'Only exactly one SQL statement allowed, found 2'
```
which I believe is at least currently correct, and any future support of multiple statements would have to touch this area of code anyway.
> [BUG] improve error reporting for multistatement sql

- src/daft-functions/src/minhash.rs
- src/daft-sql/src/functions.rs
- src/daft-sql/src/modules/hashing.rs
- src/daft-sql/src/modules/mod.rs
- tests/sql/test_exprs.py
add a few more missing scalars (hash and minhash)
> [FEAT]: SQL add hash and minhash

- daft/iceberg/iceberg_write.py
- daft/table/table_io.py
- tests/cookbook/test_write.py
- tests/io/delta_lake/test_table_write.py
- tests/io/iceberg/test_iceberg_writes.py
If one partition is empty the write will return a list of file paths / partition cols but the data type is NULL. This is problematic because it will cause schema mismatch with other partitions that did have writes.
```
import daft
df = (
daft.from_pydict({"foo": [1, 2, 3], "bar": ["a", "b", "c"]})
.into_partitions(4)
.write_parquet("z", partition_cols=["bar"])
)
print(df)
daft.exceptions.DaftCoreException: DaftError::SchemaMismatch MicroPartition concat requires all schemas to match, ╭─────────────┬──────╮
│ Column Name ┆ Type │
╞═════════════╪══════╡
│ path        ┆ Utf8 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ bar         ┆ Utf8 │
╰─────────────┴──────╯
vs ╭─────────────┬──────╮
│ Column Name ┆ Type │
╞═════════════╪══════╡
│ path        ┆ Null │
╰─────────────┴──────╯
```
> [BUG] Writes from empty partitions should return empty micropartitions with non-null schema

- src/daft-core/src/datatypes/infer_datatype.rs
if you tried to add utf8 to another unsupported dtype, it would result in the incorrect error message of 'Cannot add types: {other}, {other}' instead of 'Cannot add types: Utf8, {other}'
this fixes that error message
> [BUG]: error messages for add

- Cargo.lock
- src/daft-plan/Cargo.toml
- src/daft-plan/src/logical_ops/join.rs
- tests/dataframe/test_joins.py
The issue fixed here had a workaround previously - aliasing the duplicate column name. This is not needed anymore as the aliasing is performed under the hood, taking care of uniqueness of individual column keys to avoid the duplicate issue.
> [BUG] Fix join errors with same key name joins (resolves #2649)

- daft/execution/physical_plan.py
- daft/runners/pyrunner.py
- daft/runners/ray_runner.py
- daft/runners/runner.py
- tests/actor_pool/test_pyactor_pool.py
- tests/test_resource_requests.py
Fix for #2878
Not sure how feasible it is to unit test this since it would likely require access to a GPU. However I tested this on a GPU machine and can confirm that this PR fixes GPU availability in stateful actors when using the ray runner.
> [BUG] Add resources to Ray stateful UDF actor

- src/daft-plan/src/logical_optimization/rules/split_actor_pool_projects.rs
Previously, this would fail:
```py
import os
os.environ["DAFT_ENABLE_ACTOR_POOL_PROJECTIONS"] = "1"
import daft
from daft import udf
@udf(
return_dtype=daft.DataType.int64(),
batch_size=1
)
class MyUDF:
def __init__(self):
pass
def __call__(self, _):
import os
pid = os.getpid()
return [pid]
MyUDF = MyUDF.with_concurrency(4)
df = daft.from_pydict({"a": list(range(10))})
df = df.into_partitions(4)
df = df.select(MyUDF(df["a"]))
df = df.select(MyUDF(df["a"]))
df.show()
```
This is because when we split the project into multiple actor pool projects, we create new names for intermediate columns and lose the information about the original name. This PR fixes that by adding an alias to the end of the actor pool projects.
> [BUG] Fix actor pool project splitting when column is not renamed

- Cargo.lock
- src/arrow2/src/io/parquet/mod.rs
- src/common/error/Cargo.toml
- src/common/error/src/error.rs
In https://github.com/Eventual-Inc/Daft/commit/7fe3dbceb3ca3ee0c555753f0a55bd7e0c57bba6, two changes were made that caused parquet2 io errors to be mishandled.
Firstly, a `IoError` for parquet2 was introduced.  However in the implementation of `parquet2::error::Error` for `arrow2::error:Error`, any parquet2 error that is not `FeatureNotActive` or `Transport` is transformed into an `ExternalFormat` error.
Secondly, arrow2 IO errors are intended to be marked as `ByteStreamError`s, primarily so that they are handled as transient errors and can be retried appropriately. However this special case was removed.
This PR makes now classifies parquet2 io errors as arrow2 io errors, and arrow2 io errors are now marked as `ByteStreeamError`s.
> [BUG] Pass parquet2 io errors correctly into arrow2

- src/daft-parquet/src/file.rs
* The inferred schema from a Parquet file includes logical types
* However, when reading Series from the Parquet file, we read the "arrow types" from the Parquet schema
* This causes the Table to crap itself because the schemas don't match (we try to pass in the inferred schema with logical types but it doesn't match the Series types which are inferred from arrow types on the Parquet file)
> [BUG] Fix reading of logical types from Parquet files in s3

- src/daft-parquet/src/stream_reader.rs
Follow on from https://github.com/Eventual-Inc/Daft/pull/3026
> [BUG] Fix reading of logical types from streaming parquet

- daft/logical/schema.py
- daft/series.py
This is an issue where Daft Extension types were not getting converted to PyArrow properly. @jaychia discovered this while trying to write parquet with a tensor column, where the Extension metadata for tensor was getting dropped. 
A simple test to reproduce the error: 
```
import daft
import numpy as np
from daft import Series
tensor_data = [np.array([[1, 2], [3, 4]]), None, None]
df_original = daft.from_pydict({"tensor_col": Series.from_pylist(tensor_data)})
print(df_original.to_arrow().schema)
```
Output:
```
tensor_col: struct<data: large_list<item: int64>, shape: large_list<item: uint64>>
child 0, data: large_list<item: int64>
child 0, item: int64
child 1, shape: large_list<item: uint64>
child 0, item: uint64
```
It's not a tensor type! However if you uncomment the …
> [BUG] Register super extension on to_arrow

- src/daft-table/src/lib.rs
- tests/dataframe/test_sample.py
Addresses: https://github.com/Eventual-Inc/Daft/issues/3033
Fixes the sampling without replacement logic to actually sample without replacement (added a test for this as well)
> [BUG] Sampling without replacement not working

- daft/logical/schema.py
- src/daft-micropartition/src/micropartition.rs
- src/daft-schema/src/schema.rs
In the definition of `Schema::union`, the error message suggests that we intended to throw errors when performing a union on two schemas with overlapping keys. However, the original implementation took the set difference of keys between one side of the union and itself, which would never throw an error.
This bug was not noticed because the python tests went through the python code path which would check for the intersection correctly. But if one uses the Rust API directly, then this property is not upheld.
We fix this bug by instead checking that the two sides of the union have distinct keys.
> [BUG] Fix intersection checking when unioning schemas

- src/daft-local-execution/src/intermediate_ops/mod.rs
- src/daft-local-execution/src/intermediate_ops/sample.rs
- src/daft-local-execution/src/pipeline.rs
- src/daft-physical-plan/src/lib.rs
- src/daft-physical-plan/src/local_plan.rs
- src/daft-physical-plan/src/translate.rs
- tests/dataframe/test_sample.py
Adds sample as an intermediate operator. Unskips all the sample tests (except one which depends on concat).
> [FEAT] Enable sample for swordfish

- daft/dataframe/dataframe.py
- daft/execution/execution_step.py
- daft/execution/physical_plan.py
- src/daft-scheduler/src/scheduler.rs
Previous implementation of `into_partitions()` would fully materialize the results in order to provide even splitting of partitions. However, this can be very costly when all a user might want to do is to split the partitions into smaller chunks for more memory-efficient processing.
> [BUG] Fix into_partitions to use a more naive approach without materialization

- daft/io/__init__.py
fixes: https://github.com/Eventual-Inc/Daft/issues/3097
> [BUG] Disable Linux SSL CERT override

- daft/execution/physical_plan.py
> [PERF] Remove stateful actor child materialization limit

- .github/workflows/python-package.yml
- daft/sql/sql_scan.py
- requirements-dev.txt
- src/daft-dsl/src/expr/mod.rs
- tests/integration/sql/conftest.py
- tests/integration/sql/docker-compose/docker-compose.yml
- tests/integration/sql/test_sql.py
Addresses: https://github.com/Eventual-Inc/Daft/issues/3075
SQL server requires an `OVER` clause to be specified in percentile queries (because it's a window function). Read sql uses percentiles to determine partition bounds. 
Adds AzureSqlEdge as a test database. Might as well since a lot of ppl use us to read sqlserver, and have had bugs with sql server. Kind of a pain to get it set up since it requires odbc and drivers etc. but it works. It's also not much of a hit on CI times, installing drivers takes around ~15s and the extra tests take around 5s. 
Additionally made some modifications to some tests and pushdowns, left comments on the rationale.
> [BUG] Add over clause in read_sql percentile reads

- daft/delta_lake/delta_lake_scan.py
- daft/io/aws_config.py
- daft/io/catalog.py
We do this already when we read from S3, but delta-rs does not, so their metadata reads fail. This is especially an issue for unity catalog tables, where the region is not specified anywhere.
Tested locally, it works but I'm unsure how I would test this in unit tests since this is sort of unity+aws behavior specific
Fix for #2903
> [BUG] Autodetect AWS region during deltalake scan

- src/daft-dsl/src/expr/mod.rs
- src/daft-dsl/src/lit.rs
- src/daft-sql/src/planner.rs
- tests/sql/test_exprs.py
closes https://github.com/Eventual-Inc/Daft/issues/3085
> [FEAT]: sql `IN` operator

- daft/execution/stateful_actor.py
- daft/runners/pyrunner.py
- src/daft-dsl/src/functions/python/mod.rs
- src/daft-local-execution/src/intermediate_ops/actor_pool_project.rs
- src/daft-local-execution/src/intermediate_ops/anti_semi_hash_join_probe.rs
- src/daft-local-execution/src/intermediate_ops/inner_hash_join_probe.rs
- src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
- src/daft-local-execution/src/intermediate_ops/mod.rs
- src/daft-local-execution/src/pipeline.rs
- src/daft-physical-plan/src/lib.rs
- src/daft-physical-plan/src/local_plan.rs
- src/daft-physical-plan/src/translate.rs
- tests/expressions/test_udf.py
> [FEAT] Swordfish Stateful UDF support

- .github/workflows/build-artifact-s3.yml
Reverts Eventual-Inc/Daft#3144
The rust cache did not work as intended. We should try sccache instead.
> [CHORE] (Revert:) Add rust cache to s3 build artifacts action

- Cargo.lock
- src/daft-sql/Cargo.toml
- src/daft-sql/src/planner.rs
- tests/sql/test_exprs.py
Thanks to the [great work](https://github.com/Eventual-Inc/Daft/pull/3018) from @universalmind303 , Daft now supports `INTERVAL` type exposed from `arrow2`.
Beyond DataFrame supports, this PR aims to unlock SQL simple `INTERVAL` usage in SQL syntax, mainly copied from [planner.rs](https://github.com/sgl-project/sglang/pull/1790/files#diff-ea02b059cdabc0939616c35c6566dbcf980a5794306dedd241c2823afd9b2db2).
Notes: This naive impl doesn't fully support complex interval scenarios, like leap year or relative duration addition and subtraction. We might need more carefully handled logic as the follow ups.
> [FEAT] Support SQL `INTERVAL`

- src/daft-core/src/array/ops/between.rs
- src/daft-core/src/datatypes/matching.rs
- src/daft-core/src/series/ops/between.rs
- src/daft-schema/src/dtype.rs
- tests/table/test_between.py
* Enables Between for Decimal128
> [FEAT] enable decimal between

- Cargo.toml
I'm using RustRover to code and debug Rust related code and I noticed the debug run in RustRover doesn't work out of box: there's no variable showing when breakpoint is hit.
It turns out that the RustRover IDE will launch debug process with test profile, which is inherited from dev[^1] profile. I am not sure why the dev[^2] profile in this project is configured without debug enabled. I add the test profile with debug enabled in this PR.
[^1]: https://doc.rust-lang.org/cargo/reference/profiles.html#test
[^2]: https://github.com/Eventual-Inc/Daft/blob/main/Cargo.toml#L86
> [CHORE] Enable debug in test profile

- daft/execution/execution_step.py
- daft/runners/pyrunner.py
- daft/runners/ray_runner.py
- tests/physical_plan/test_physical_plan_buffering.py
This PR marks `PartitionTasks` as done only after they have been explicitly marked as done by the runner.
Previously, we used the existence of the `.results` on a PartitionTask to determine whether or not it is done. However, this is not quite correct in the case of the RayRunner, which will attach a result containing a Ray ObjectRef, which is a future. This future may not (and is likely not) be completed yet at the time of PartitionTask creation.
> [BUG] Separate PartitionTask done from results

- docs/source/user_guide/expressions.rst
@jaychia @colin-ho Just added temporal doc section to expressions.rst. Let me know what you think of the content and then we can finalize which page or user-guide section to put it on from there. Thanks!
> Temporal docs added to expressions.rst

- daft/context.py
When running in a Ray Job, without the user invoking any Ray commands or `ray.init()` explicitly, the `ray.is_initialized()` function returns False.
This means that Daft "does not know" that it is running inside of a Ray cluster, and thus will not default to using the RayRunner. This can lead to unexpected behavior when using `daft-launcher` because a user must know to call `daft.context.set_runner_ray()`.
This PR changes that behavior by attempting to look up the `$RAY_JOB_ID` environment variable, as a heuristic to tell whether or not it is currently running inside of a Ray job.
To test, I just ran a Ray job and called `daft.context.get_context()` after initializing a Daft dataframe
> [FEAT] Add better detection of Ray Job environment

- Cargo.lock
- Cargo.toml
- src/daft-io/Cargo.toml
- src/daft-io/src/azure_blob.rs
- src/daft-io/src/lib.rs
- src/daft-io/src/python.rs
- tests/integration/io/parquet/test_reads_azure.py
Resolves #3142
This PR also adds a dependency for the `derive_builder` crate, which I'm hoping to introduce into our repo and use throughout our code to reduce builder boilerplate.
> [FEAT] Infer Azure storage account from uri

- Cargo.lock
- src/daft-core/Cargo.toml
- src/daft-core/src/array/ops/cast.rs
- src/daft-core/src/series/mod.rs
There are no existing tests for decimal casting. This PR adds some randomized tests.
> [CHORE] Add tests for decimal casting

- src/daft-plan/src/logical_optimization/rules/eliminate_cross_join.rs
- src/daft-sql/src/lib.rs
- src/daft-sql/src/planner.rs
- tests/sql/test_joins.py
One follow-up of #3161: add `on a <=> b` support for SQL's Join operation.
> [FEAT] Support null equal safe join in SQL

- src/daft-core/src/array/ops/cast.rs
I noticed this failure on another PR's CI run: https://github.com/Eventual-Inc/Daft/actions/runs/11715735385/job/32632612788?pr=3134
This is a flaky test and should be fixed.
> [CHORE] Fix flaky test in test_decimal_to_decimal_cast

- daft/daft/__init__.pyi
- daft/runners/ray_metrics.py
- daft/runners/ray_runner.py
- daft/runners/ray_tracing.py
- src/common/daft-config/src/lib.rs
- src/common/daft-config/src/python.rs
Adds tracing for the RayRunner. This is turned off by default, and can be deactivated via `DAFT_ENABLE_RAY_TRACING=1`.
Visualize this with https://ui.perfetto.dev/ 
1. The RayRunner dispatch loop view gives us a good idea of what that crazy while loop is doing, as well as overall Ray metrics such as number of tasks in flight, number of cores available etc
2. The Ray Task Execution view gives us a view of the Ray Tasks that were scheduled, when they were received as completed and also their ResourceRequests.
3. I also added views for each node and their worker processes. These views get updated on the end of every "wave" by polling a metrics actor
4. A "Stages" view allows us to point to the tasks that were launched by each stage, into (3)
> [FEAT] Add tracing for runner

- daft/dataframe/dataframe.py
Should be `write_mode` not `mode`.
> [DOCS] Fix typo in write_parquet's parameters

- Cargo.lock
- daft/daft/__init__.pyi
- src/common/io-config/Cargo.toml
- src/common/io-config/src/gcs.rs
- src/common/io-config/src/python.rs
- src/daft-io/Cargo.toml
- src/daft-io/src/google_cloud.rs
- src/daft-sql/src/modules/config.rs
- tests/integration/io/parquet/test_reads_public_data.py
- tools/check_for_rustls.sh
* Introduces retries with exponential backoffs for GCS (default 5)
* Introduces connection and read timeouts (default 30 seconds)
* Introduces maximum connections for GCS (default 8/thread or 64)
* introduces idle connection clean up (max of 70)
> [PERF] Harden GCP Retries

- docs/source/conf.py
We should set the canonical link for Daft docs so that google does not index old versions of our docs.
> [DOCS] Set canonical link

- docs/source/conf.py
Based on https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls#use-rel=canonical-link-annotations
> [DOCS] Use an absolute path for the canonical link

- daft/io/_sql.py
- daft/sql/sql_scan.py
- tests/integration/sql/test_sql.py
Currently, read_sql calculates partition bounds using the `PERCENTILE_DISC` function. However, this function does not scale well to large tables, as it is an expensive window + sort function. A better alternative is to take samples, then estimate partition bounds, as described in this issue: https://github.com/Eventual-Inc/Daft/issues/3245.
In the meantime, we should default to using the min-max calculations instead, which was previously the fallback option.
> [CHORE] Expose read_sql partition bound strategy and default to min-max

- benchmarking/tpch/__main__.py
- daft/context.py
- daft/runners/ray_runner.py
- tests/test_context.py
Removes the concept of RunnerConfigs.
Our Runners are now materialized in 2 places:
1. When a user calls `daft.context.set_runner_*`, eagerly!
2. When a user first interacts with a Daft API that calls `get_context().get_or_create_runner()` under the hood
> [CHORE] Remove the concept of runner configs

- daft/filesystem.py
- daft/table/table_io.py
- tests/cookbook/test_write.py
- tests/io/test_write_modes.py
Writes for empty dataframes currently error out if the target directory does not exist. This happens in the `overwrite_files` method when looking for files to delete, and also in `write_empty_tabular` when trying to write a file in a non-existent directory.
> [BUG] Fix writes for empty dataframes if target directory does not exist

- Makefile
I encountered an inconvenient dependency on a pre-installed version of Python.
It is very convenient to create an environment with the required version via uv.
> [CHORE] Possibility to create environment with system installed uv

- src/daft-sql/src/modules/config.rs
- src/daft-sql/src/modules/hashing.rs
- src/daft-sql/src/modules/utf8.rs
Closes #3268 
Still WIP. Awaiting approval for current document updates
> [DOCS] Update incomplete SQL doc pages

- benchmarking/tpch/__main__.py
Using `ctx.get_or_create_runner` in benchmarking warmup code / metrics builder causes subsequent `ray.inits` to crash. Just check the `DAFT_RUNNER` environment var instead, which should be set.
Tested:
- local -> https://github.com/Eventual-Inc/daft-benchmarking/actions/runs/11838323155
- remote -> https://github.com/Eventual-Inc/daft-benchmarking/actions/runs/11838783067
> [BUG] Check env in benchmarking script

- src/daft-sql/src/modules/utf8.rs
- tests/sql/test_utf8_exprs.py
`regexp_replace` should set regex to True
> [BUG] Fixes regexp_replace expression

- src/daft-sql/src/planner.rs
- tests/sql/test_joins.py
closes https://github.com/Eventual-Inc/Daft/issues/3311
> [BUG]: tbl alias with join

- src/daft-dsl/src/expr/mod.rs
- src/daft-dsl/src/lib.rs
- src/daft-dsl/src/optimization.rs
- src/daft-logical-plan/src/ops/project.rs
- src/daft-logical-plan/src/partitioning.rs
- src/daft-schema/src/schema.rs
- src/daft-sql/src/functions.rs
- src/daft-sql/src/lib.rs
- src/daft-sql/src/planner.rs
- src/daft-sql/src/table_provider/mod.rs
- src/daft-table/src/lib.rs
This PR adds support for converting SQL queries with correlated subqueries into LogicalPlans. It does not add the ability to execute queries with correlated subqueries, but if I am correct, this is the last large piece of support we need on the SQL side for TPC-H questions, and most of the remaining work is plan rewriting, optimization, and translation.
I believe with the new `alias_map` value in `SQLPlanner`, we can actually simplify a lot of the logic in `plan_aggregate_query` and `plan_non_agg_query` but I will not attempt to do that in this PR.
Relevant for TPC-H questions 4, 17, 20, 21, 22.
Todo:
> [FEAT] Support for correlated subqueries in SQL (not yet executable)

- src/common/py-serde/src/python.rs
- tests/io/test_s3_credentials_refresh.py
`visit_seq` is used when using serde_json to serialize/deserialize Rust objects, since the byte buffer is just stored as a list of numbers in JSON.
> [BUG] Implement deserialize for Python objects serialized as sequences

- src/daft-sql/src/lib.rs
- src/daft-sql/src/planner.rs
Adds support for things like:
```sql
SELECT * FROM a JOIN b ON a.x = b.x AND a.y > 0
```
Enables TPC-H q13
> [FEAT] Filter predicates in SQL join

- .github/actions/install/action.yaml
- .github/workflows/build-commit.yaml
New workflow to build commit and upload to AWS S3.
- faster than previous
- uses buildjet
- utilizes build caching (from buildjet)
> [FEAT] Build release python wheels and upload to AWS S3

- .github/assets/benchmarking_ray_config.yaml
- .github/workflows/build-commit.yaml
- .github/workflows/run-cluster.yaml
- .github/workflows/run-command-on-ray.yaml
- new steps that:
- spin up
- submit job
- spin down ray clusters
If any of the previous steps fail, the "tear-down" step (responsible for tearing down the ray cluster), will still always run. (The only way this tear-down step would not be run is if the workflow is *manually* cancelled).
> [FEAT] Add steps to spin up, submit job, and spin down ray clusters

- src/common/daft-config/src/lib.rs
We added a new `DAFT_RUNNER` environment variable, so we should use this environment variable when creating the execution configuration.
> [FEAT] Get native execution enablement from DAFT_RUNNER

- src/daft-dsl/src/resolve_expr/mod.rs
- src/daft-logical-plan/src/ops/agg.rs
- src/daft-logical-plan/src/ops/pivot.rs
- tests/dataframe/test_aggregations.py
> [CHORE] Cleanup ExprResolver

- .github/assets/benchmarking_ray_config.yaml
- .github/workflows/run-cluster.yaml
Nodes were being stopped and saved for future re-use purposes. This PR turns off caching by settings `cache_stopped_nodes` to `false`. This tells ray to shut down the nodes when `ray down ...` is invoked.
> [BUG] Terminate nodes instead of stopping them

- .github/workflows/run-cluster.yaml
For all filenames that contain a semicolon, replace each instance of the semicolon with an underscore.
> [BUG] Replace semicolons in filenames with underscore

- docs/source/api_docs/expressions.rst
Add
- list.count
- list.max
- list.mean
- list.min
- list.sum
expressions from https://github.com/Eventual-Inc/Daft/pull/2032.
Additionally, sorted the expressions in this subsection.
> [DOCS] Add missing list expression entries

- src/common/runtime/src/lib.rs
Addresses: https://github.com/Eventual-Inc/Daft/issues/3435
> [CHORE] Explain block_on function in common-runtime

- Cargo.lock
- Cargo.toml
- src/daft-csv/src/metadata.rs
- src/daft-csv/src/python.rs
- src/daft-json/src/python.rs
- src/daft-json/src/schema.rs
- src/daft-parquet/src/python.rs
- src/daft-parquet/src/read.rs
- src/daft-scan/Cargo.toml
- src/daft-scan/src/builder.rs
- src/daft-scan/src/glob.rs
- src/daft-scan/src/lib.rs
- src/daft-scan/src/python.rs
- src/daft-sql/Cargo.toml
- src/daft-sql/src/table_provider/read_csv.rs
- src/daft-sql/src/table_provider/read_parquet.rs
Converts schema inference operations for CSV, JSON, and Parquet files to use async/await instead of synchronous runtime blocking. This architectural change ensures that blocking operations happen at the highest level possible (the Python API boundary) rather than deep within the inference logic. Key changes include:
- Making read_csv_schema, read_json_schema, and read_parquet_schema async
- Updating scan builder interfaces to use async finish() methods 
- Removing unnecessary runtime.block_on calls from schema inference paths
- Moving runtime.block_on calls to Python API layer where blocking is unavoidable
- Converting schema-related tests to use tokio async runtime
- Adding common-runtime dependency where needed
- Fixes #3423
This change improves the consistency of async IO handling and …
> [FEAT] migrate schema inference → async, block at py boundary

- src/daft-local-execution/src/sinks/hash_join_build.rs
- tests/dataframe/test_joins.py
Add empty tables when building probe tables for hash joins such that the probing still works with empty probe tables.
> [CHORE] Put empty table when building probe table

- daft/dataframe/dataframe.py
- daft/expressions/expressions.py
- docs/source/api_docs/misc.rst
- src/daft-core/src/count_mode.rs
CountMode is used in [`Expression.count`](https://www.getdaft.io/projects/docs/en/latest/api_docs/doc_gen/expression_methods/daft.Expression.count.html), but it's not user friendly to have users figure out how to use a CountMode object. Instead we get public methods to accept countmode strings instead.
ResourceRequest is used in [DataFrame.with_column](https://www.getdaft.io/projects/docs/en/latest/api_docs/doc_gen/dataframe_methods/daft.DataFrame.with_column.html) and [DataFrame.with_columns](https://www.getdaft.io/projects/docs/en/latest/api_docs/doc_gen/dataframe_methods/daft.DataFrame.with_columns.html) but these are deprecated from public use for the same reasons as CountMode. We thus remove ResourceRequest from the dataframe methods.
> [CHORE] Remove CountMode and ResourceRequest from public API

- daft/dataframe/dataframe.py
- tests/integration/io/conftest.py
- tests/io/lancedb/test_lancedb_writes.py
Fixes: https://github.com/Eventual-Inc/Daft/issues/3450
> [BUG] Include storage options in lance write commit

- daft/.ruff.toml
- daft/context.py
- daft/daft/__init__.pyi
- daft/dataframe/dataframe.py
- daft/expressions/expressions.py
- daft/filesystem.py
- daft/runners/runner.py
- daft/series.py
- daft/table/table.py
- daft/udf_library/url_udfs.py
Small clean up to simplify docs by banning unnecessary union on literals.
For example, in `DataFrame.write_parquet`, the `write_mode` argument has the following signature:
```
write_mode: Union[Literal['append'], Literal['overwrite']] = 'append',
```
But according to [PEP 586 --- Literal Types](https://peps.python.org/pep-0586/#shortening-unions-of-literals), this can be equivalently written as
```
write_mode: Literal['append', 'overwrite'] = 'append',
```
which is much easier for users to follow.
> [DOCS] Shorten union of Literals

- daft/.ruff.toml
- daft/unity_catalog/unity_catalog.py
Linters don't seem to catch unbound local variables if they are defined in multiple branches.
> [BUG] Explicitly set IO config in unity catalog load table

- src/daft-core/src/datatypes/matching.rs
Importing enums is extremely bad style in Rust. This can lead to nasty errors in the future when enum definitions change.
Please stop doing this.
> [BUG] Remove enum imports from match statements

- src/daft-schema/src/dtype.rs
Our extension type displays were changed after #2794 and do not properly show that it is an extension type
> [BUG] Fix extension type display

- .github/assets/.template.yaml
- .github/assets/template.yaml
- .github/ci-scripts/templatize_ray_config.py
- .github/workflows/run-cluster.yaml
- When running a job on a ray-cluster using GHA, we want to be able to configure the configuration of the cluster.
- this is achieved via "cluster profiles"
- essentially, this is a set number of configurations (e.g., `medium-x86`, `debug_xs-x86`, etc.) that end-users can select from
- this will take care of all of the configurations without leaking the internals of the ray-configuration story
- `medium-x86`
- `debug_xs-x86`
I will plan on adding more in the future. For now, this should suffice.
> [FEAT] Add cluster profiles

- .github/assets/.template.yaml
- .github/ci-scripts/templatize_ray_config.py
- .github/workflows/run-cluster.yaml
- pyproject.toml
This PR extends the existing `run-clusters` workflow with the ability to run on any arbitrary daft-wheel that is given to it.
> [FEAT] run cluster on commit

- daft/daft/testing.pyi
- src/daft-scan/src/python.rs
- src/lib.rs
- tests/test_size_estimations.py
Unskipping the tests produces failures with 2 passing cases:
```
FAILED tests/test_size_estimations.py::test_estimations_unique_strings[dict-snappy] - AssertionError: Expected 8.16MB file estimated vs actual to be within 30.0%: 24.47MB vs 113.89MB (-365.40%)
FAILED tests/test_size_estimations.py::test_estimations_unique_strings[dict-no_compression] - AssertionError: Expected 109.93MB file estimated vs actual to be within 30.0%: 329.80MB vs 113.89MB (65.47%)
FAILED tests/test_size_estimations.py::test_estimations_unique_strings[no_dict-snappy] - AssertionError: Expected 8.14MB file estimated vs actual to be within 30.0%: 24.42MB vs 113.89MB (-366.43%)
FAILED tests/test_size_estimations.py::test_estimations_unique_strings[no_dict-no_compression] - AssertionError: Expected 109.91MB file …
```
> [CHORE] Add tests for parquet size estimations

- src/daft-connect/src/lib.rs
- src/daft-connect/src/translation.rs
- src/daft-connect/src/translation/datatype.rs
- src/daft-connect/src/translation/expr.rs
- src/daft-connect/src/translation/expr/unresolved_function.rs
- tests/connect/test_basic_column.py
Works:
```
Column.alias(*alias, **kwargs)
Column.cast(dataType)
Column.isNotNull()
Column.isNull()
Column.name(*alias, **kwargs) (= name)
```
> [FEAT] connect: support basic column operations

- .github/ci-scripts/get_wheel_name_from_s3.py
- .github/workflows/build-commit.yaml
`upload_wheel_to_s3.py` script was updated to use the `argparse` module. However, consumers of this script were not updated; they were still using the old calling syntax.
This PR fixes that bug.
> [BUG] Fix build commit workflow

- src/daft-connect/src/translation/expr/unresolved_function.rs
- src/daft-connect/src/translation/logical_plan.rs
- src/daft-connect/src/translation/logical_plan/with_columns.rs
- tests/connect/test_group_by.py
- Add `%` operator and `sum` function to unresolved functions
- Implement withColumns transformation
- Add test coverage for group by with modulus operation
> [FEAT] connect: add modulus operator and withColumns support

- src/daft-connect/src/translation/expr.rs
- src/daft-connect/src/translation/logical_plan.rs
- src/daft-connect/src/translation/schema.rs
it seems that the `common` is **always** set, producing the warning for every single operation when using spark connect. This changes it so that it'll only warn if `common.origin` is set.
> [FEAT] connect: remove excessive warnings from spark connect

- Cargo.lock
- benchmarking/parquet/conftest.py
- src/daft-parquet/Cargo.toml
- src/daft-parquet/src/file.rs
- src/daft-parquet/src/lib.rs
- src/daft-parquet/src/stream_reader.rs
- src/daft-parquet/src/utils.rs
Implement a parallelism cap on remote parquet tasks, and use compute runtime instead of rayon (swordfish reads only). Follow on from https://github.com/Eventual-Inc/Daft/pull/3310 which implemented it for local.
Benchmarks in comments below
> feat(parquet): Limit parallel tasks in remote parquet reader

- .github/ci-scripts/templatize_ray_config.py
When parsing a python script's inline metadata, add a null-check if the file contains no metadata.
> fix(run-cluster-workflow): Add null check when parsing metadata

- tools/gha_run_cluster_job.py
Example usage:
```
uv run tools/gha_run_cluster_job.py .github/working-dir/simple.py
```
> ci: add a tool to launch workloads on cluster

- Cargo.lock
- src/daft-connect/Cargo.toml
- src/daft-connect/src/translation/logical_plan.rs
- src/daft-connect/src/translation/logical_plan/local_relation.rs
- src/daft-local-execution/src/pipeline.rs
- src/daft-local-execution/src/run.rs
- src/daft-local-execution/src/sources/in_memory.rs
- src/daft-micropartition/Cargo.toml
- src/daft-micropartition/src/lib.rs
- src/daft-micropartition/src/micropartition.rs
- src/daft-micropartition/src/partitioning.rs
most of this is ported from the python impl inside `daft/runners/partitioning.py`. 
For context around why this is needed. The `DataFrame` class uses `PartitionSet` extensively for various common operations such as `show`, and `collect`. In order to add this functionality to our spark connect implementation, we need a similar construct in rust. 
Ideally, I'd like to port over the python implementation to use this new rust one, but there are still a few things that I'm not entirely sure how to implement (such as `RayPartitionSet`)
Not all of the methods inside `partitioning.rs` are used yet, But I intend to follow up this PR with an implementation for https://github.com/Eventual-Inc/Daft/issues/3498, and this is a prerequisite as `show` relies on `get_preview_micropartitions`.
> refactor: create a rust based `PartitionSet` 

- tests/test_size_estimations.py
This test currently fails as we underestimate by 2x
> test: Add more size estimation tests from our s3 bucket

- src/daft-core/src/array/fixed_size_list_array.rs
- src/daft-functions/src/list/value_counts.rs
- tests/expressions/test_expressions.py
> feat(list): add fixed-size list support for value_counts

- .gitignore
- benchmarking/tpcds/__main__.py
- benchmarking/tpcds/datagen.py
- benchmarking/tpcds/helpers.py
- benchmarking/tpcds/ray_entrypoint.py
- tests/test_size_estimations.py
This PR enables TPC-DS benchmarking on your local computer.
If the TPC-DS parquet data does *not* exist, it will be created for you (inside of `benchmarking/tpcds/data`). You can configure the location of this output via the `--tpcds-gen-folder` argument provided by the script.
For running with the native runner, run:
```sh
DAFT_RUNNER=native python -m benchmarking.tpcds --questions "3"
```
For executing with the ray runner, run:
```sh
DAFT_RUNNER=ray python -m benchmarking.tpcds --questions "3"
```
You can also specify different scale-factors (e.g., `--scale-factor 0.5`) and dry-run modes (e.g., `--dry-run`).
> feat(tpcds-benchmarking): Add basic tpcds benchmarking for local testing

- src/daft-logical-plan/src/builder.rs
- src/daft-logical-plan/src/optimization/rules/mod.rs
- src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
- src/daft-logical-plan/src/optimization/rules/reorder_joins/mod.rs
This PR adds the functionality to create join graphs from logical plans. This is currently not used by Daft for now, as it's a building block for join reordering.
More concretely, what this PR allows us to do is to take a query tree, e.g.
```
InnerJoin (a = d)
/            \
InnerJoin (a = b)    InnerJoin (c = d)
/        \           /         \
Agg      Scan(b)   Project       Scan(d)
(Count(a))         (c_prime)
|                    |
Project               |
(a <- a_prime)        |
|                    |
Scan(a_prime)      Scan(c_prime)
```
and create a join graph.
Join graphs contain sufficient information to reconstruct a query tree that is equivalent to the query tree used to create join graph. In the example above, this would entail storing information about how relations are …
> feat(optimizer): Add scaffolding to create join graphs from logical plans

- .github/workflows/pr-labeller.yml
This PR adds the "build" label type to the accepted "Conventional Types" labels that are accepted.
This is specifically for build-related things (e.g., `Makefile`s). The existing labels did not really address certain types of possible changes, in my opinion.
> ci: Add "build" label type to accepted PR titles

- Makefile
This PR updates the installer that `maturin` uses during builds from the default `pip` to `uv`.
> build: Use uv for maturin builds instead

- src/daft-core/src/array/ops/comparison.rs
- tests/series/test_comparisons.py
- tests/table/test_between.py
Resolves #3512
A fun truth table ($V_{x}$ is the validity $x$, $L$ is left, and $R$ is right):
| $L$ | $V_{L}$ | $R$ | $V_{R}$ | $∧$ | $V_{∧}$ | $∨$ | $V_{∨}$ |
| :-----: | :-----: | :-----: | :-----: | :-----: | :-----: | :-----: | :-----: |
| ⬜️ | ⬜️ | ⬜️ | ⬜️ |     | ⬜️ |     | ⬜️ |
| ⬜️ | ⬜️ | ⬜️ | ✅  | ⬜️ | ✅  |     | ⬜️ |
| ⬜️ | ⬜️ | ✅  | ⬜️ |     | ⬜️ |     | ⬜️ |
| ⬜️ | ⬜️ | ✅  | ✅  |     | ⬜️ | ✅  | ✅  |
| ⬜️ | ✅  | ⬜️ | ⬜️ | ⬜️ | ✅  |     | ⬜️ |
| ⬜️ | ✅  | ⬜️ | ✅  | ⬜️ | ✅  | ⬜️ | ✅  |
| ⬜️ | ✅  | ✅  | ⬜️ | ⬜️ | ✅  |     | ⬜️ |
| ⬜️ | ✅  | ✅  | ✅  | ⬜️ | ✅  | ✅  | ✅  |
| ✅  | ⬜️ | ⬜️ | ⬜️ |     | ⬜️ |     | ⬜️ |
| ✅  | ⬜️ | ⬜️ | ✅  | ⬜️ | ✅  |     | ⬜️ |
| ✅  | ⬜️ | ✅  | ⬜️ |     | ⬜️ |     | ⬜️ |
| ✅  | ⬜️ | ✅  | ✅  |     | ⬜️ | ✅  | ✅  |
| ✅  | ✅  | ⬜️ | ⬜️ |     | ⬜️ | ✅  | …
> fix: boolean and/or expressions with null

- src/daft-core/src/array/iterator.rs
This PR adds more iterators to daft-core datatypes.
> feat: Add iterators to more types

- benchmarking/tpcds/ray_entrypoint.py
- src/common/py-serde/src/python.rs
Serialization of subqueries currently fails. Thus, when ray tries to serialize subqueries, the ray-task fails and *indefinitely* hangs.
This PR updates the failure mechanism of serialization of subqueries. Instead of unwrapping the `Err` in rust, it is passed through instead.
> feat: Make serialization code not unwrap and panic on failures

- src/daft-dsl/src/expr/mod.rs
- src/daft-logical-plan/src/logical_plan.rs
- src/daft-logical-plan/src/optimization/optimizer.rs
- src/daft-logical-plan/src/optimization/rules/drop_repartition.rs
- src/daft-logical-plan/src/optimization/rules/eliminate_subquery.rs
- src/daft-logical-plan/src/optimization/rules/lift_project_from_agg.rs
- src/daft-logical-plan/src/optimization/rules/mod.rs
- src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
- src/daft-logical-plan/src/optimization/rules/push_down_limit.rs
- src/daft-logical-plan/src/optimization/rules/push_down_projection.rs
- src/daft-logical-plan/src/optimization/rules/split_actor_pool_projects.rs
- src/daft-logical-plan/src/optimization/rules/unnest_subquery.rs
- src/daft-logical-plan/src/optimization/test/mod.rs
- src/daft-sql/src/planner.rs
- tests/benchmarks/test_local_tpch.py
- tests/sql/test_utf8_exprs.py
Subquery execution now possible through rewrite rules that convert them into joins. This only covers subqueries that can be converted into equi joins and not general subqueries. However that already gets us to 21/22 TPC-H (although Q16 is still missing count distinct implementation on the SQL side).
Also includes a drive-by fix for SQL substring.
---
Note on alternative implementations:
- Although Datafusion's optimizer rules for subqueries are more capable than these, they make use of non-equi joins yet do not allow for decorrelating all subqueries. Instead, once we have non-equi joins we should implement the [Unnesting Arbitrary Subqueries](https://cs.emis.de/LNI/Proceedings/Proceedings241/383.pdf) paper (which [duckdb also implements](https://duckdb.org/2023/05/26/correlated-subqueries- …
> feat: support for basic subquery execution

- src/daft-local-execution/src/pipeline.rs
- src/daft-local-execution/src/sinks/outer_hash_join_probe.rs
- tests/sql/test_joins.py
Enable left/right joins to build on either side. E.g. if left join, we can build on left and save used values in a bitmap (same as outer join), then emit the unmatched rows from the finalize.
Total tpch time after this pr: 65s, down from 88s
> feat(swordfish): Enable left/right joins to build probe table on either side

- daft/catalog/__init__.py
`memray` reports that a not-insignificant amount of memory is being taken by our catalog module at import-time
This PR makes those imports lazy
> perf: lazily import pyiceberg and unity catalog if available

- .github/workflows/run-cluster.yaml
Changes code to always download logs even in the event of a failure
> ci: Always download logs

- .github/workflows/build-artifact-s3.yml
- .github/workflows/nightlies-tests.yml
- .github/workflows/notebook-checker.yml
- .github/workflows/property-based-tests.yml
- .github/workflows/python-package.yml
- .github/workflows/python-publish.yml
- .ruff.toml
- Cargo.toml
- daft/dataframe/dataframe.py
- daft/pickle/cloudpickle.py
- daft/pickle/compat.py
- pyproject.toml
- requirements-dev.txt
- tests/dataframe/test_intersect.py
- tests/io/delta_lake/test_table_read.py
- tests/io/delta_lake/test_table_read_pushdowns.py
- tests/io/delta_lake/test_table_write.py
- tests/io/lancedb/test_lancedb_writes.py
- tests/series/test_temporal_ops.py
- tests/test_datatypes.py
BREAKING CHANGE: Python 3.8 has reached EOL, set our minimum version to 3.9
> chore!: drop support for Python 3.8

- .github/workflows/python-package.yml
- daft/table/table_io.py
- pyproject.toml
- tests/integration/iceberg/conftest.py
- tests/io/delta_lake/test_table_read.py
- tests/io/delta_lake/test_table_read_pushdowns.py
- tests/io/delta_lake/test_table_write.py
- tests/io/hudi/test_table_read.py
- tests/io/iceberg/test_iceberg_writes.py
- tests/io/lancedb/test_lancedb_reads.py
- tests/io/lancedb/test_lancedb_writes.py
Updates the lower bound of pyarrow to `pyarrow>=8.0.0`.
This allows us to flatten some code checks.
However, it turns out that our tests aren't being properly skipped -- I had to update the tests to just skip based on our lower bound (skip if version < 9.0.0) which very loose, but otherwise searching for the individual versions for each suite of tests was quite difficult.
> chore!: upgrade Ray pins and pyarrow pins

- .github/workflows/build-commit.yaml
- .github/workflows/run-cluster.yaml
The `run-cluster` workflow now also builds the commit by calling the `build-commit` workflow first.
> ci: Add build step to run-cluster

- src/daft-algebra/src/boolean.rs
- src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
By converting the predicate to Conjunctive Normal Form, we are able to split the predicate into expressions that are isolated to the schemas of an individual side of a join. Then, we can split by conjunctions and push those new expressions through the joins.
For example, consider the schemas:
```
left = [a: Utf8]
right = [b: Utf8]
```
If our plan was
```
Filter
|  by: (col(a) = "FRANCE" & col("b") = "GERMANY") | (col(a) = "GERMANY" & col("b") = "FRANCE")
|
Join
| \
|  Scan(right)
Scan(left)
```
That filter predicate in CNF is
```
(col(a) = "FRANCE" | col(a) = "GERMANY") 
& (col(a) = "FRANCE" | col(b) = "FRANCE") 
& (col(b) = "GERMANY" | col(a) = "GERMANY") 
& (col(b) = "GERMANY" | col(b) = "FRANCE")
```
The first and last expressions in this conjunction only have columns from a single …
> perf(optimizer): convert filter predicate to CNF to push through join

- daft/dataframe/dataframe.py
> fix: unity catalog import from write_deltalake

- daft/runners/progress_bar.py
- src/daft-local-execution/src/lib.rs
- src/daft-local-execution/src/progress_bar.rs
Theres 2 progress bars for swordfish, a rust based one thats for terminals, and a python one thats for jupyter notebooks (uses tqdm).
This pr makes it so that the tqdm bar is only rendered on first update (the rust based one is already lazy rendered), + increase the refresh rate of both progress bars to 500ms.
native
https://github.com/user-attachments/assets/c55e51a4-4919-4246-9add-2fe13d305435
py
https://github.com/user-attachments/assets/8be184c5-5b48-4fee-9579-deb485f37e07
> chore: Build progress bar only on first update

- daft/daft/__init__.pyi
- daft/expressions/expressions.py
- src/daft-functions/src/python/uri.rs
- src/daft-functions/src/uri/mod.rs
- src/daft-functions/src/uri/upload.rs
- src/daft-io/src/lib.rs
- tests/io/test_url_upload_local.py
Addresses #3320
`Expression.url.upload()` can now take in a column of urls to upload each row to a specific url.
> feat(expressions): Extend Expression.url.upload() to support row-specific URLs

- daft/dataframe/dataframe.py
- daft/io/_iceberg.py
- daft/logical/builder.py
In addition to the new features, I restructured our `_convert_iceberg_file_io_properties_to_io_config` in two ways:
1. we no longer import the property key constants from PyIceberg and instead hard-code them ourselves. this is because many of the keys only exist depending on the PyIceberg version being used, so we would need to add a multitude of version checks to cover all the possible keys.
2. we now directly construct the configs using a new `get_first_property_value` function, instead creating a dictionary to pass into the constructors. This allows us to better take advantage of the type system and enables type checkers to catch potential issues. Also this function allows us to have multiple properties that can be used for a config value
I also cleaned up `read_iceberg` just a little …
> feat: support new PyIceberg IO properties and custom IOConfig in write_iceberg

- src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
Missed a comment to https://github.com/Eventual-Inc/Daft/pull/3616#discussion_r1893614089:
```
In [src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs](https://github.com/Eventual-Inc/Daft/pull/3616#discussion_r1893614089):
>  };
-#[derive(Debug)]
-struct JoinNode {
+// TODO(desmond): In the future these trees should keep track of current cost estimates.
+#[derive(Clone, Debug)]
+pub(super) enum JoinOrderTree {
+    Relation(usize),                                          // (id).
+    Join(Box<JoinOrderTree>, Box<JoinOrderTree>, Vec<usize>), // (subtree, subtree, nodes involved).
I dont think you need to keep an explicit stack. I think you should be able to something like
std::iter::chain(left.into_iter(), right.into_iter())
```
This PR removes the stack and simply …
> chore: Clean up join order iteration

- src/daft-scan/src/scan_task_iters/mod.rs
- src/daft-scan/src/scan_task_iters/split_parquet/fetch_parquet_metadata.rs
- src/daft-scan/src/scan_task_iters/split_parquet/mod.rs
- src/daft-scan/src/scan_task_iters/split_parquet/split_parquet_decision.rs
- src/daft-scan/src/scan_task_iters/split_parquet/split_parquet_file.rs
Implements a new module `daft-scan/src/scan_task_iters/split_parquet` which contains all the functionality for splitting an iterator of ScanTasks into smaller ScanTasks if they are Parquet files.
The public interface is `SplitParquetScanTasks`, which under the hood uses private functionality in the form of `DecideSplitIterator -> RetrieveParquetMetadataIterator -> flatten` to produce a new (split) iterator of ScanTasks.
> feat(scantask-2): Implement new module for splitting Parquet ScanTask

- src/common/daft-config/src/lib.rs
- src/daft-logical-plan/src/builder.rs
- src/daft-logical-plan/src/logical_plan.rs
- src/daft-logical-plan/src/optimization/mod.rs
- src/daft-logical-plan/src/optimization/optimizer.rs
- src/daft-logical-plan/src/optimization/rules/enrich_with_stats.rs
- src/daft-logical-plan/src/optimization/rules/mod.rs
- src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
- src/daft-logical-plan/src/optimization/rules/reorder_joins/mod.rs
- src/daft-logical-plan/src/optimization/rules/reorder_joins/naive_left_deep_join_order.rs
- src/daft-physical-plan/src/physical_planner/planner.rs
Applies the naive left deep join order from #3616 as an optimizer rule.
This optimizer rule is gated behind an environment variable that allows us to validate the rule on our current workloads.
Currently join reordering results in errors for 50% of TPC-H queries during join graph building. We'll tackle these in a follow-up PR.
> feat(optimizer): Add join reordering as an optimizer rule

- src/daft-io/src/google_cloud.rs
- tests/integration/io/test_url_download_public_gcs.py
> fix: special characters in GCS urls

- .github/workflows/python-publish.yml
closes: https://github.com/Eventual-Inc/Daft/issues/3564
* Create new daft release `daft-lts` that supports older cpus
* upgrade regular daft to use more modern cpu features
* move off using API token for PYPI to using identity based upload
> build: Publish A Long Term Support CPU Release of Daft

- benchmarking/tpcds/ray_entrypoint.py
- tools/tpcds.py
- tools/tpch.py
This PR adds the ability for the `run-cluster` GitHub Actions workflow to output:
1. a file containing the entire printed out plan for one given question
2. additional stats for the planning + execution time for one given question
These files are stored inside of `/tmp/ray`, which is then downloaded via the `run-cluster` workflow, which is then uploaded to the GitHub Actions Summary Page.
You can run this locally or through CI.
```sh
DAFT_RUNNER=ray python benchmarking/tpcds/ray_entrypoint.py --question=1 --scale-factor=1
```
```sh
uv run tools/tpcds.py --questions='1,2' --scale-factor=1
```
> ci: Improve visualization of tpcds + tpch benchmarking outputs

- src/daft-logical-plan/src/optimization/optimizer.rs
Only run the filter null join key optimization once before filter pushdown, instead of 3 times together with the other rules, otherwise you end up with something like `[not(is_null(key)) & not(is_null(key))] & not(is_null(key))`.
> fix: Run filter null join key optimization once

- .pre-commit-config.yaml
- src/daft-sql/src/planner.rs
- tests/assets/json-data/small.jsonl
- tests/sql/test_table_funcs.py
This PR introduces a check on the FROM source to error when using string literal syntax (single-quoted identifiers). This PR will no longer be a draft once table path strings are added (see skipped tests).
closes https://github.com/Eventual-Inc/Daft/issues/3197
> feat(sql): Adds FROM source check for string paths

- Cargo.lock
- daft/expressions/expressions.py
- src/daft-functions/Cargo.toml
- src/daft-functions/src/python/uri.rs
- src/daft-functions/src/uri/download.rs
- src/daft-functions/src/uri/mod.rs
- src/daft-functions/src/uri/upload.rs
- src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
- src/daft-sql/src/functions.rs
- src/daft-sql/src/modules/image/decode.rs
- src/daft-sql/src/modules/mod.rs
- src/daft-sql/src/modules/uri/mod.rs
- src/daft-sql/src/modules/uri/url_download.rs
- src/daft-sql/src/modules/uri/url_upload.rs
- tests/sql/test_uri_exprs.py
#3575 
This change is a bit larger because I had to change how url_download and url_upload handled the parsing of keyword arguments to be more like image functions. I also moved some re-usable SQL argument parsing logic to a functions::args module.
I've left some notes/TODOs regarding input validation and handling of named parameters, but addressing these is outside the scope of this PR.
> feat(sql): Adds url_download and url_upload to daft-sql

- src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
- src/daft-logical-plan/src/optimization/rules/reorder_joins/naive_left_deep_join_order.rs
We make three fixes to join graph construction. With these changes, join ordering using the naive left deep join orderer produces correct results for TPCH queries.
Instead of pushing up all Projections and Filters until we hit an unreorderable node, we go down each linear chain of (reorderable) Projections and Filters until we hit a Join node, then push up the Projects and Filters we encountered along the way. If we hit an unreorderable node first, we simply treat the operator that sits at the top of the current linear chain as the relation to pass into the join.
For example, consider this query tree:
```
//                InnerJoin (a = d)
//                    /        \
//                   /       Project
//                  /        (d, quad <- double + double)
//                 / …
```
> fix(optimizer): Fix issues with join graph construction

- CONTRIBUTING.md
- Makefile
- requirements-docs.txt
```shell
make docs
```
- installs the mkdocs deps in _requirements-docs.txt_
- runs mkdocs serve
> build(docs): Adds make docs phony target

- docs-v2/terms.md
- mkdocs.yml
Little PR to tidy up the SQL section and adds a copy-to-clipboard to all code examples.
> feat(docs): Adds copy-to-clipboard to code samples

- daft/dataframe/dataframe.py
- daft/filesystem.py
- tests/io/test_write_modes.py
Closes https://github.com/Eventual-Inc/Daft/issues/1768
Overwrite-partitions mode will only overwrite files in the partition directories that were written into as part of the write operation. E.g. partition "A" will be overwritten if and only if partition "A" was written into.
This PR also refactors the test code a bit.
> feat: Overwrite partitions mode

- Cargo.lock
- src/daft-connect/src/execute.rs
- src/daft-micropartition/Cargo.toml
- src/daft-micropartition/src/micropartition.rs
- src/daft-table/src/lib.rs
- src/daft-table/src/ops/explode.rs
- src/daft-table/src/ops/joins/hash_join.rs
- src/daft-table/src/ops/joins/mod.rs
- src/daft-table/src/ops/unpivot.rs
makes Micropartition streamable over `Table`, and makes `Table` a bit cheaper to clone by wrapping the `columns` column in an `Arc`. 
The driving force for these changes is that currently the logic to go from micropartition to table does not work nicely withing a streaming context as the `get_tables` method returns `Arc<Vec<Table>>`. So you can't easily chain streaming methods when working with micropartitions and tables.
> feat(core): make micropartition streamable over tables

- daft/dataframe/dataframe.py
- tests/dataframe/test_iter.py
Addresses: https://github.com/Eventual-Inc/Daft/issues/3634
Add an option to iter_rows to decude the format of columns during iteration, either Python (default), Arrow, or Numpy.
> feat: Add column format option to iter rows

- tests/integration/sql/docker-compose/docker-compose.yml
SQL server tests are failing sporadically, pin the version in the docker compose to prevent this.
> chore: Pin sql server version in docker compose

- src/daft-local-execution/src/sources/scan_task.rs
- src/daft-parquet/src/read.rs
- src/daft-parquet/src/stream_reader.rs
Parquet reads in swordfish currently do not respect the `_chunk_size` parameter that users pass in.
> feat: Expose parquet chunk size to swordfish reads

- daft/context.py
- daft/daft/__init__.pyi
- src/common/daft-config/src/lib.rs
- src/common/daft-config/src/python.rs
- src/daft-dsl/src/expr/mod.rs
- src/daft-scan/src/scan_task_iters/mod.rs
- tests/io/test_merge_scan_tasks.py
Don't merge more than `N` (default 10) sources in a scan task. This is so that we don't over merge, given that our estimates with filter selectivity might be off.
> feat: Limit number of sources in merged scan task 

- src/daft-dsl/src/expr/mod.rs
Set filter selectivity estimate lower bound to 1%, to prevent overly selective and likely inaccurate estimations.
> fix: Set filter selectivity estimate lower bound

- tools/git_utils.py
Had trouble running the benchmarking tool when local branch names didn't match remote branch names. Fix it so that we check for upstream branch names and use them.
E.g. if I run the tool on `local-branch-name`, it finds `origin/user/remote-branch-name` then runs the action on `user/remote-branch-name`.
> ci: Allow upstream git refs to be used for benchmarking

- .github/workflows/python-publish.yml
- tests/io/mock_aws_server.py
Tests were failing for unknown reasons: https://github.com/Eventual-Inc/Daft/actions/runs/13064922153/job/36455524516
We skip tests now when publishing, and should just use `main` as the source of truth
> ci: skip tests during publishing of release

- src/daft-connect/src/spark_analyzer.rs
- tests/connect/test_spark_set_ops.py
pyspark does not seem to have an `except` op, only `exceptAll`
> feat: spark connect set operations

- Cargo.lock
- src/daft-catalog/Cargo.toml
- src/daft-catalog/src/errors.rs
- src/daft-catalog/src/lib.rs
- tests/sql/test_catalog.py
closes https://github.com/Eventual-Inc/Daft/issues/3758
note for @ukclivecox, this is still a breaking change from 0.4.3 as it will require you to properly quote any table names that would be interpreted as multiple identifiers. 
so in your example:
```py
import daft
df1 = daft.from_pydict({"idx":[1,2],"val":[10,20]})
catalog = {"c0.t1":df1}
df_sql = daft.sql("select * from c0.t1", catalog=SQLCatalog(catalog)).show()
```
you will need to make a small modification to get it to work 
```py
import daft
df1 = daft.from_pydict({"idx":[1,2],"val":[10,20]})
catalog = {'"c0.t1"':df1} # <--- note the quotes here
df_sql = daft.sql('select * from "c0.t1"', catalog=SQLCatalog(catalog)).show()
```
> fix: catalog table names

- tools/tpch.py
TPCDS benchmarks allow this. We should do the same for TPCH.
> ci: Allow TPCH benchmarks to use ARM cluster profile

- Cargo.lock
- Cargo.toml
- src/daft-catalog/python-catalog/src/python.rs
- src/daft-catalog/src/data_catalog.rs
- src/daft-catalog/src/data_catalog_table.rs
- src/daft-catalog/src/error.rs
- src/daft-catalog/src/errors.rs
- src/daft-catalog/src/identifier.rs
- src/daft-catalog/src/lib.rs
- src/daft-catalog/src/session.rs
- src/daft-connect/Cargo.toml
- src/daft-connect/src/config.rs
- src/daft-connect/src/connect_service.rs
- src/daft-connect/src/execute.rs
- src/daft-connect/src/response_builder.rs
- src/daft-connect/src/session.rs
- src/daft-connect/src/spark_analyzer.rs
- src/daft-session/Cargo.toml
- src/daft-session/src/error.rs
- src/daft-session/src/lib.rs
- src/daft-sql/Cargo.toml
- src/daft-sql/src/lib.rs
- src/daft-sql/src/planner.rs
- src/daft-sql/src/python.rs
This defines an initial session for table resolution which simply wraps the existing meta catalog. The purpose of this PR is to (1) introduce a primary stateful object for planning and execution which is shared by frontends and (2) audit the planner's current state management and name resolution to see what is required once bridging over to python. 
**Notes**
* This PR includes many follow-up TODOs which are being converted to issues.
* This primarily introduces indirection first to keep the diff minimal, switchovers come later.
* The session will hold a reference to the global context singleton from #3767.
* This session will be converged with the ConnectSession and made available through python once stabilized.
> feat(catalog): Defines a session for connection state

- Cargo.lock
- Cargo.toml
- src/daft-connect/Cargo.toml
- src/daft-connect/src/functions.rs
- src/daft-connect/src/functions/aggregate.rs
- src/daft-connect/src/functions/core.rs
- src/daft-connect/src/functions/math.rs
- src/daft-connect/src/functions/partition_transform.rs
- src/daft-connect/src/functions/string.rs
- src/daft-functions/src/float/mod.rs
- src/daft-functions/src/numeric/round.rs
- src/daft-functions/src/python/numeric.rs
- src/daft-sql/src/modules/numeric.rs
adds the following:
- all of spark's [math functions](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/functions.html#math-functions) we currently have implemented. 
- all of spark's [string functions](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/functions.html#string-functions) we currently have implemented
- all of spark's [normal functions](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/functions.html#normal-functions) we currently have implemented
> feat: add functions to daft-connect

- .github/workflows/python-publish.yml
"Slack notification on failure" keeps failing due to Slack API updates
> build: update python-publish workflow

- CONTRIBUTING.md
- daft/unity_catalog/unity_catalog.py
Allow user to indicate if they only intend to read a table so that read-only credentials can be obtained from Unity where read-write credential requests would be rejected. Addresses Issue #3708
> fix: unity managed table reads

- docs/mkdocs/distributed.md
Update the docs for distributed mode to account for the rename of daft launcher to daft cli. Also, account for the fact that we now split the cli commands into both provisioned (the old way) as well as byoc (Kubernetes). 
I removed some details from the existing doc to make it a bit more concise, let me know if you'd like those to be added back in.
> docs: Update distributed docs to add byoc mode, change name to daft cli

- src/daft-sql/src/planner.rs
- tests/sql/test_select_expr.py
This adds support for SELECT without FROM,
```python
>>> import daft
>>> daft.sql("SELECT 1 + 1").show()
╭─────────╮
│ literal │
│ ---     │
│ Int64   │
╞═════════╡
│ 2       │
╰─────────╯
>>> daft.sql("SELECT lower('ABC') AS l, upper('xyz') as u").show()
╭──────┬──────╮
│ l    ┆ u    │
│ ---  ┆ ---  │
│ Utf8 ┆ Utf8 │
╞══════╪══════╡
│ abc  ┆ XYZ  │
╰──────┴──────╯
```
> feat(sql): SELECT without FROM

- src/daft-logical-plan/src/optimization/rules/reorder_joins/brute_force_join_order.rs
- src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
- src/daft-logical-plan/src/optimization/rules/reorder_joins/naive_left_deep_join_order.rs
- src/daft-scan/src/lib.rs
There are three missing pieces with our join ordering implementation:
1. Infer additional join graph edges from existing edges. For example, if we have (A.x join B.x) and (B.x join C.x), then we infer (A.x join C.x). Additionally, in the absence of NDV stats, the total domain for these three columns (A.x, B.x, C.x) should be the minimal value of |A|, |B|, |C|.
2. Adjust total domain computation from `total domain = |size of relation|` to `total domain = |size of relation| / (selectivity of relation)`. `|size of relation|` does not reflect the true total domain of a join because filters reduce the size of the relation despite not affecting the selectivity of the join (assuming a primary key - foreign key join, and independence between join keys).
3. Set the lower bound estimation for the …
> perf(optimizer): Infer additional join graph edges during join reordering

- daft/series.py
- tests/series/test_series.py
We are unable to construct a series from a python list of numpy datetime64['D'] because this is not supported by pyarrow. I was able to find an easy workaround by turning the list into a numpy array first.
**Tests**
I've added tests for the customers use-case along with other datetime types. Testing with both from_pylist and from_numpy was how I discovered the easy solution.
**Context**
* https://github.com/Eventual-Inc/Daft/issues/3826
* https://github.com/apache/arrow/issues/40580
**Example**
```python
data = [np.datetime64(datetime.now(), "D") for _ in range(10)]
data2 = np.array(data) # wrap with np.array and it works
print(pa.array(data2))
[
2025-02-19,
2025-02-19,
2025-02-19,
2025-02-19,
2025-02-19,
2025-02-19,
2025-02-19,
2025-02-19,
2025-02-19,
2025-02-19
]
```
> fix: create series of np.datetime64['D']

- src/daft-context/src/lib.rs
This PR makes it so that we call the `from_env` methods for `DaftExecutionConfig` and `DaftPlanningConfig` when creating a new context.
> fix: Grab Daft config from environment variables for new contexts

- Cargo.lock
- src/daft-dsl/src/lit.rs
- src/daft-sql/Cargo.toml
- src/daft-sql/src/functions.rs
- src/daft-sql/src/lib.rs
- src/daft-sql/src/planner.rs
- src/daft-sql/src/schema.rs
- src/daft-sql/src/table_provider/read_csv.rs
- src/daft-sql/src/table_provider/read_json.rs
- src/daft-sql/src/table_provider/read_parquet.rs
- tests/sql/test_sql_table_functions.py
This PR adds support for providing schemas in the read_json, read_csv, and read_parquet table-value functions.
```sql
SELECT * FROM read_json('/path/to/data.json', schema := {
'x': 'int',
'y': 'string',
'z': 'bool',
});
-- ditto for read_csv and read_parquet
```
> feat(sql): supports schemas in read_json, read_csv, read_parquet

- .github/workflows/broken-link-checker.yml
- docs/mkdocs/migration/dask_migration.md
Exclude a bunch of external links from the broken link checker, e.g. x.com, scarf, linkedin, etc.
> fix: Add excludes to broken link checker

- src/daft-logical-plan/src/optimization/rules/reorder_joins/naive_left_deep_join_order.rs
The random graph generator for testing join graph creation occasionally runs into a stack overflow. We reduce the size of the test case to avoid this.
> fix: Reduce number of nodes in random join graph test

- src/daft-logical-plan/src/logical_plan.rs
- src/daft-sql/src/lib.rs
- src/daft-sql/src/planner.rs
This fixes an issue where a nested alias is retrieved from a place where it is out of scope:
```sql
SELECT tbl.x FROM (SELECT * FROM tbl) AS tbl2  -- should fail but does not
```
Now, we can have nested subquery aliases without issue, so I've simplified `SQLPlanner::plan_relation` as per discussion in #3846 (this PR should be merged instead of that one)
> fix: LogicalPlan::get_schema_for_alias should stop when it hits any alias

- daft/context.py
- docs/mkdocs/advanced/memory.md
- docs/mkdocs/integrations/iceberg.md
- docs/mkdocs/resources/architecture.md
- docs/sphinx/source/configs.rst
- tests/test_context.py
- tutorials/intro.ipynb
- tutorials/talks_and_demos/linkedin-03-05-2024.ipynb
- tutorials/text_to_image/text_to_image_generation.ipynb
Edit the configuration docs to show `set_runner_native` instead of the pyrunner. Additionally combed through our docs to replace any instances of the pyrunner with the native runner.
> docs: Update configuration docs to show `set_runner_native`

- daft/dashboard.py
- daft_dashboard/daft_dashboard/__init__.py
- daft_dashboard/pyproject.toml
This PR fixes how dashboard imports work. The previous method threw type errors. This PR also changes the name of the `cli` function to `_cli`.
> fix: Update dashboard import

- daft/dashboard.py
- daft/dataframe/dataframe.py
- daft_dashboard/daft_dashboard/__init__.py
- daft_dashboard/src/lib.rs
This PR enables capturing logs when running on the native runner and broadcasting it over HTTP to port 3238.
Now, all printouts directed towards `STDOUT` will be captured and stored in some internal buffer. When the HTTP broadcast message is emitted, all of the captured logs for *that query* will be sent alongside the rest of the query information.
Create a python file with the following contents:
```py
import daft
print("Hello, world!")
daft.from_pydict({}).collect()
```
Start your dashboard and run the python script:
```sh
daft-dashboard launch
DAFT_DASHBOARD=1 python my_daft_script.py
```
The logs should be captured. You can test that this is true (without using the UI) by running:
```sh
curl http://localhost:3238/api/queries
```
This should return to you a list with one object in it. …
> feat: Enable capturing and broadcasting logs when running on the `Native` runner

- src/daft-dsl/src/expr/mod.rs
- src/daft-local-execution/src/pipeline.rs
- src/daft-logical-plan/src/optimization/rules/reorder_joins/brute_force_join_order.rs
- src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
This PR fixes join cost estimates in the following ways:
- Uses number of rows instead of size in bytes for making probe side decisions
- Decreases the aggressiveness of cardinality reductions when there is an `is not NULL` filter
- Decreases the aggressiveness of inequality filters, especially since these often appear as pairs of a "between" clause
- Increases the aggressiveness of exact equality filters.
- For join edges where there are more than one join condition, adjust cost estimations so that we compute the total domain as `|(key1, key2, ...)| ~= min(|left side|, |right side|)`.
With multiple join conditions, we know that the join is not a pk-fk join on each join key. Rather, it's a pk-fk join on the tuple of join keys, which we estimate as the cardinality of the smaller table of …
> perf: Fix join cost estimates

- daft/runners/ray_runner.py
Clear input object refs from task upon dispatching to ray. The scheduler doesn't need to hold the object refs once the task is dispatched. By holding it, it prevents it from being freed until after task completion, leading to unnecessary spillage. We don't need to hold it for retry purposes since Ray can automatically retry tasks.
Note: It's not guaranteed that the inputs are actually freed when we clear it. It's more like, if Ray needs to evict memory from object store to produce new objects, it is able to free these inputs.
Results:
Question | Before | After | Difference | % Change
-- | -- | -- | -- | --
1 | 27.44 | 28.07 | 0.63 | 2.30%
2 | 26.43 | 28.16 | 1.73 | 6.55%
3 | 38.06 | 39.94 | 1.88 | 4.94%
4 | 19.22 | 19.71 | 0.49 | 2.55%
5 | 153.86 | 109.42 | -44.44 | -28.88%
6 | 10.19 | …
> perf: Clear task inputs upon dispatch

- docs/mkdocs.yml
Cairo keeps throwing an error during local docs build even though it succeeds via Github Actions. Having trouble resolving even with https://squidfunk.github.io/mkdocs-material/plugins/requirements/image-processing/?h=cairo#cairo-library-was-not-found, so commenting out for now and can revisit later.
Context: Cairo is one of the packages that generates social previews for docs, ie:
We will lose social previews by disabling Cairo but social previews are not a priority for docs at the moment.
> docs: remove cairo

- docs/mkdocs/core_concepts.md
- docs/sphinx/source/functions.rst
- docs/sphinx/source/index.rst
This PR adds documentation for the functions module and refactors several functions from expressions to the functions module. Key changes:
- Moves list_, struct, and coalesce from expressions to the dedicated functions module
- Adds new functions.rst file with structured documentation
- Organizes functions into logical categories (sequence, general, constructor)
> docs: Add documentation for functions module

- src/daft-core/src/array/ops/map.rs
- tests/recordbatch/map/test_map_get.py
closes https://github.com/Eventual-Inc/Daft/issues/3891
> fix: map.get on empty dataset

- daft/pyspark/__init__.py
- daft/runners/ray_runner.py
updates docstring for pyspark + ray and fixes issue when calling `ray.init` from `RayRunner` for `ray://` prefixed urls. 
closes https://github.com/Eventual-Inc/Daft/issues/3897
> fix: small fix for pyspark+ray.

- src/daft-core/src/utils/supertype.rs
- src/daft-dsl/src/expr/mod.rs
- src/daft-functions/src/coalesce.rs
- tests/sql/test_coalesce.py
Fixes some small coalesce bugs and adds additional tests related to #3752 
* use minimal common supertype logic for conformant typing rather than first arg
* null as first argument would always return null, check the type too
* use to_field checks rather than runtime panics on mistyping
Might need a follow-up to ensure our case-when has correct typing as well.
> fix: coalesce panics, supertype handling, and null handling bugs

- daft/catalog/__iceberg.py
- daft/catalog/__init__.py
- daft/catalog/__memory.py
- daft/catalog/__unity.py
- daft/session.py
- daft/unity_catalog/unity_catalog.py
- tests/catalog/test_catalog.py
This PR adds,
* names to catalogs and tables so they're now optional when attaching
* additional table sources to the Catalog.from_pydict method providing better ergnomics
```python
import daft
from daft.catalog import Catalog, Table
dictionary = {"x": [1, 2, 3]}
dataframe = daft.from_pydict(dictionary)
table = Table.from_df("temp", dataframe)
cat = Catalog.from_pydict(
{
"R": dictionary,
"S": dataframe,
"T": table,
}
)
```
> feat(catalog): adds additional table sources for Catalog.from_pydict

- src/daft-session/src/session.rs
- tests/sql/test_sess_sql.py
SQL name resolution was setup for 3+ level naming, so `<catalog>.<schema>+.<table>` with support for nested schemas (namespaces). However, we are coming from Python (and will migrate SQLCatalog) so this PR relaxes the restriction allow us to do things like..
```python
from daft import Session, Catalog
sess = Session()
sess.attach(Catalog.from_pydict({ 
"T": {  
"x": [ 1,3,5 ],
"y": [ 2,4,6 ],
}
}))
sess.sql("SELECT * FROM T").show()
╭───────┬───────╮
│ x     ┆ y     │
│ ---   ┆ ---   │
│ Int64 ┆ Int64 │
╞═══════╪═══════╡
│ 1     ┆ 2     │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 3     ┆ 4     │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 5     ┆ 6     │
╰───────┴───────╯
``` 
Relaxing this restriction makes it possible to migrate `daft.sql` with SQLCatalog to `Session.sql` without breaking APIs.
> fix: allow resolving tables at catalog root

- .github/workflows/build-wheel.yml
Also upgrades the manylinux version since Bun expects a higher glibc version than the one provided in the manylinux2014 container. This does remove support for certain ancient versions of linux but I'm not particularly concerned. 
> Built wheels are also expected to be compatible with other distros using glibc 2.28 or later, including:
> * Debian 10+
> * Ubuntu 18.10+
> * Fedora 29+
> * CentOS/RHEL 8+
https://github.com/pypa/manylinux
> fix: bun install in build-wheel.yml

- src/daft-io/src/google_cloud.rs
- src/daft-io/src/lib.rs
- src/daft-io/src/retry.rs
- src/daft-io/src/s3_like.rs
Also contains a tiny refactor to centralize logic for exponential backoff retry
> fix: add retry to getting GCS client config

- Cargo.lock
- daft/daft/__init__.pyi
- daft/io/_warc.py
- daft/recordbatch/micropartition.py
- src/daft-micropartition/src/micropartition.rs
- src/daft-micropartition/src/python.rs
- src/daft-scan/Cargo.toml
- src/daft-scan/src/lib.rs
- src/daft-warc/Cargo.toml
- src/daft-warc/src/lib.rs
This PR makes the following changes for `read_warc`:
- Reduce memory consumption
- Adds `WARC-Identified-Payload-Type` as an extracted metadata column
- Improve stats estimation for scan tasks that read WARC
When reading a single Common Crawl file, the file size is typically 1GB, which decompresses to 5GB of data.
Before this Resident Set Size peaks at `5.15GB` while heap size peaks at `10.98GB`:
After this PR, Resident Set Size peaks at `4.3GB` while heap size peaks at `6.6GB`, which is more in line with expectations:
For ease of filtering WARC records, we extract `WARC-Identified-Payload-Type` from the metadata as its own column. Since this is an optional column, it is often NULL.
A single Common Crawl .warc.gz file is typically 1GB in size, but takes up ~5GB of memory once …
> perf: Reduce memory consumption for WARC reads and improve estimates

- Cargo.lock
- src/daft-scan/Cargo.toml
- src/daft-scan/src/lib.rs
Addresses this comment: https://github.com/Eventual-Inc/Daft/pull/3935#discussion_r1985934682
> chore: Favor OnceLock over lazy_static for WARC column sizes

- daft/dataframe/dataframe.py
- pyproject.toml
- tests/io/delta_lake/test_table_write.py
Since deltalake>=[0.20.0](https://github.com/delta-io/delta-rs/releases/tag/python-v0.20.0), the api for providing custom metadata has changed.
Before, custom metadata could be provided as dict; now it has to be encapsulated by a `CommitProperties` object. 
See [here](https://github.com/delta-io/delta-rs/commit/507b50ecc9943f8e5e5ba87802fd97dd2acaff7b#diff-46ab267ec248467a8b23ae7e0653736fa000406afb18743cd4d3192490e09cfd).
Other commit properties not relevant atm. 
There are no version constraints used for deltalake at the moment, so i kept it untouched. 
Might be the time to add >=0.20.0.
> fix: Pass CommitProperties object custom metadata in deltalake

- src/daft-dsl/src/expr/mod.rs
- tests/dataframe/test_monotonically_increasing_id.py
Fixed a bug that caused a PanicException when directly casting `monotonically_increasing_id()` to string, allowing users to write more concise code without needing a two-step workaround.
> fix: fix error when casting monotonically_increasing_id directly

- .github/workflows/daft-profiling.yml
- .github/workflows/nightly-publish-s3.yml
- .github/workflows/notebook-checker.yml
- .github/workflows/property-based-tests.yml
- .github/workflows/python-package.yml
- .github/workflows/ray-compatibility.yml
v2 of [slackapi/slack-github-action](https://github.com/slackapi/slack-github-action) no longer allows you to set the webhook and webhook type as the env vars, and instead you should pass them in as workflow inputs. It looks like we've been copying the incorrect code for a while.
> fix(ci): slack failure notification parameters

- .github/workflows/python-package.yml
- pyproject.toml
- requirements-dev.txt
We don't actually use `lancedb` in Daft, we just use `pylance`. It used to work since `lancedb` depended on `pylance`, but it no longer does.
Also fixes test failures caused by issue here https://github.com/lancedb/lancedb/issues/2202
> fix: depend on pylance instead of lancedb

- tutorials/embeddings/daft_tutorial_embeddings_stackexchange.ipynb
It looks like the [notebook check workflow](https://github.com/Eventual-Inc/Daft/actions/workflows/notebook-checker.yml) has been failing for a while but we just started seeing it now that the slack notification is fixed.
In #3804, we removed the struct get syntactic sugar from DataFrame, which the notebook uses. I changed it to just use `.struct.get(..)` instead.
> fix: tutorial code

- src/daft-core/src/array/ops/list.rs
- tests/recordbatch/list/test_list_sort.py
```
(
daft.from_pydict(
{"group_col": [1, 1, 1, 2, 2], "id_col": ["c", "a", "b", "e", "d"]}
)
.groupby("group_col")
.agg(daft.col("id_col").agg_list().list.sort().alias("ids_col"))
.show()
)
```
was reported as failing with `DaftCoreException: DaftError::ValueError Need at least 1 series to perform concat`
This happens when the number of partitions in our groupby is greater than the actual number of partitions needed. This results in some empty partitions with nothing to sort. We should handle these cases accordingly.
The same happens for fixed size lists.
This PR fixes the issue.
Closes #3969
> fix: Fix list sort with groupby

- daft/catalog/__init__.py
- daft/catalog/__s3tables.py
- requirements-dev.txt
- tests/catalog/test_s3tables.py
This adds our native read for S3 Tables along with the remaining catalogs APIs. Because we have implemented `get_table` and the catalog interface, we can attach to sessions and execute SQL against S3 Tables. We will raise an error on writes and suggest Glue Iceberg REST which we have demonstrated enables us to write. We are actively working on native writes or similar, but I wanted to get this read API into the latest release.
```shell
❯ python ./tests/catalog/test_s3tables.py
profile `sso-session eventual` ignored because `sso-session eventual` was not a valid identifier
╭─────────┬───────┬──────╮
│ x       ┆ y     ┆ z    │
│ ---     ┆ ---   ┆ ---  │
│ Boolean ┆ Int64 ┆ Utf8 │
╞═════════╪═══════╪══════╡
│ true    ┆ 1     ┆ a    │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ true    ┆ 2     ┆ b    │ …
```
> feat(catalog): adds native s3tables read and catalog apis

- daft/catalog/__memory.py
- tests/catalog/test_catalog.py
This PR allows you to use namespaces with the `Catalog.from_pydict(..)` factory method. We still lookup the string as-is like SQLCatalog (resolution unchanged) but we split out the table name when we create a table, and we can list namespaces by splitting out the namespace component from the in-memory map.
We've had several issues in this regard, and now we are appropriately setup to handle this with the Catalog interface.
* https://github.com/Eventual-Inc/Daft/pull/3760
* https://github.com/Eventual-Inc/Daft/issues/3758
* Treat keys of the the from_pydict argument as (possibly) qualified identifiers (dot-delimited)
* Parse namespaces from keys when doing a list_namespaces.
- [n/a] Documented in API Docs
- [n/a] Documented in User Guide
- [n/a] If adding a new documentation page, doc is …
> feat(sql): namespace support with in-memory catalog

- src/daft-dsl/src/expr/mod.rs
Refactors a few selectivity estimates, notably the AND estimate to use `min(left_selectivity, right_selectivity)`, so as to be more conservative given that predicates may not be independent.
Question | Before | After | Difference | % Difference
-- | -- | -- | -- | --
Q1 | 508.29 | 506.38 | -1.91 | -0.38%
Q2 | 108.34 | 117.91 | 9.57 | 8.83%
Q3 | 473.53 | 477.83 | 4.30 | 0.91%
Q4 | 263.18 | 268.82 | 5.64 | 2.14%
Q5 | 429.79 | 449.23 | 19.44 | 4.52%
Q6 | 150.14 | 154.94 | 4.80 | 3.20%
Q7 | 465.79 | 474.59 | 8.80 | 1.89%
Q8 | 596.81 | 635.88 | 39.07 | 6.55%
Q9 | 1063.30 | 1079.90 | 16.60 | 1.56%
Q10 | 2308.10 | 678.97 | -1629.13 | -70.58%
Q11 | 218.64 | 223.40 | 4.76 | 2.18%
Q12 | 322.70 | 329.32 | 6.62 | 2.05%
Q13 | 937.53 | 922.74 | -14.79 | -1.58%
Q14 | 533.22 | 551.91 | 18.69 | 3.51%
Q15 …
> perf: Refactor selectivity estimates

- daft/expressions/expressions.py
- src/daft-functions/src/binary/codecs.rs
- tests/functions/test_codecs.py
You can do `expr.encode("gz")` and `expr.decode("gz")` now, which was a hackathon feature request.
#3907 
* Adds another extension alias.
- [n/a] Documented in User Guide
- [n/a] Documentation builds and is formatted properly (tag [@ccmao1130](https://github.com/ccmao1130) for docs review)
> feat: adds gz as gzip alias for encode, decode methods

- daft/catalog/__iceberg.py
- daft/catalog/__init__.py
- daft/catalog/__s3tables.py
- docs/mkdocs.yml
- docs/mkdocs/integrations/s3tables.md
- tests/catalog/test_s3tables.py
Updates the `Catalog.from_s3tables` and `S3Tables.from_arn` to use the Iceberg REST endpoint which gives us write support. 
```python
import daft
table_bucket_arn = "..."
catalog = Catalog.from_s3tables(table_bucket_arn)
print(catalog.list_tables("demo"))
catalog.read_table("demo.points").show()
catalog.write_table(
"demo.points",
daft.from_pydict(
{
"x": [True],
"y": [4],
"z": ["d"],
}
),
)
catalog.read_table("demo.points").show()
tests/catalog/test_s3tables.py ['demo.points']
╭─────────┬───────┬──────╮
│ x       ┆ y     ┆ z    │
│ ---     ┆ ---   ┆ ---  │
│ Boolean ┆ Int64 ┆ Utf8 │
╞═════════╪═══════╪══════╡
│ true    ┆ 1     ┆ a    │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ true    ┆ 2     ┆ b    │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ false   ┆ 3     ┆ c    │
╰─────────┴───────┴──────╯
(Showing first 3 of …
```
> feat(catalog): adds s3tables iceberg rest endpoint

- src/daft-logical-plan/src/optimization/rules/reorder_joins/brute_force_join_order.rs
- src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
Two changes:
- Previously the brute force join ordering algorithm was agnostic to which relation was on the left. We should pick the smaller one to be on the left.
- Additionally, limit join ordering to when there are 7 or less joins to reorder. This is temporary until we implement faster join reordering algorithms.
These are the last two pieces we need before we can turn on join reordering.
> perf: Favor smaller relations on the left for join ordering

- daft/expressions/expressions.py
- docs/mkdocs/core_concepts.md
- docs/sphinx/source/expressions.rst
- tests/expressions/test_getitem.py
Add `Expression.__getitem__`, which works as list.get for ints and struct.get for strings.
none
add the new method to Expresssion + fix docs to use it
> feat: syntactic sugar for Python list and struct gets

- .github/pull_request_template.md
- docs/CONTRIBUTING.md
- docs/mkdocs/core_concepts.md
- docs/mkdocs/sql/datatypes.md
- docs/mkdocs/sql/overview.md
This PR fixes broken links from moving the SQL overview into a nested folder.
* #4052 
* #4027 
* updates to contributing clarification
* fix relative paths for api docs
* change `col(*)` to `col("*")`
- [n/a] All tests have passed
- [n/a] Documented in API Docs
- [n/a] Documented in User Guide
> docs: fix broken links and clarify contributing

- src/daft-dsl/src/functions/python/mod.rs
- src/daft-local-execution/src/intermediate_ops/actor_pool_project.rs
- src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
- src/daft-local-execution/src/intermediate_ops/project.rs
- src/daft-local-execution/src/pipeline.rs
Set batch size as morsel size for non actor-pool projects. Provides much better control and ux over the udf. 
Set batch size as morsel size for non actor-pool projects.
> feat: Set batch size as morsel size for project

- src/daft-dashboard/build.rs
the `rerun-if-changed` was incorrect, so it was always rebuilding, so if you had rust-analyzer or anything else running in the background, it was thrashing the `.next` directory, causing the flakes.
closes https://github.com/Eventual-Inc/Daft/issues/4049
> fix: dashboard flaking

- daft/io/_generator.py
- tests/io/test_range.py
Collect iterators in `read_generator` to list. This is so that dataframes that use `read_generator` can be called multiple times.
Closes https://github.com/Eventual-Inc/Daft/issues/4041
Collects iterators in `read_generator` to list.
> fix: Collect iterators in read_generator to list

- requirements-dev.txt
`uv pip install vllm` does not work for certain platforms and needs to be manually installed. Restricting it so that the dependency install does not fail on local MacOS development
none
requirements-dev.txt
> fix: only install vllm in requirements-dev.txt for linux

- tests/test_context.py
Check that stderr contains the `cannot set runner more than once` error instead of ends with the error. It does not always end with the error as other processes, such as ray init, may append their own errors after ours.
Similar to https://github.com/Eventual-Inc/Daft/pull/4046
Check that stderr contains the `cannot set runner more than once` error instead of ends with the error.
> fix: Fix local to ray runner switch test

- daft/expressions/expressions.py
- requirements-dev.txt
adds a link to the sql datatypes page for `cast`
Closes https://github.com/Eventual-Inc/Daft/issues/4050
> docs: add link to sql reference page inside cast

- src/daft-dsl/src/expr/mod.rs
- src/daft-logical-plan/src/builder/resolve_expr.rs
- src/daft-logical-plan/src/optimization/rules/unnest_subquery.rs
- src/daft-recordbatch/src/lib.rs
- src/daft-sql/src/lib.rs
Some cleanup on the unresolved/resolved column stuff. 
- more understandable errors if you just mistype the name of a column or you pass in a column from a different dataframe
- add PlanRef to `ResolvedColumn::OuterRef`. currently not being used for anything because we just assume that the column exists in the immediate scope of the outer query. However, that may not be true, and with ordinals we can support cases like this:
```python
df1 = daft.from_pydict({"a": [1, 2, 3], "b": [1, 2, 3]})
df2 = daft.from_pydict({"a": [2, 3, 4], "b": [2, 3, 4]})
subquery_df = daft.from_pydict({"b": [3, 4, 5]})
df1.join(df2, on="a", how="outer").where(df2["b"] == subquery_df.agg(col("b").min()))
```
none
see above
> fix: improve column error messages + add PlanRef to outer column

- daft/catalog/__iceberg.py
- daft/catalog/__init__.py
- daft/catalog/__memory.py
- daft/catalog/__unity.py
- daft/session.py
- src/daft-catalog/src/python.rs
- tests/test_session.py
This PR introduces a daft "NotFoundError" which is descriptive for the customers, but also let's the session (via read_table) ignore this while it looks up the chain of possible table locations. This is necessary because we support unqualified, schema-qualified, and catalog-qualified identifiers **with** nested namespaces, so we check that chain in that order and return NotFound if all three fail.
The previous logical treated all errors as NotFound which was swallowing connection errors.
#3984 
> fix: surface non 'NotFound' errors during table resolution

- src/daft-algebra/src/boolean.rs
- src/daft-core/src/join.rs
- src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
Adds logic to the PushDownFilter optimizer rule that will change the join types for left, right, and outer joins if a filter above will eliminate the nulls of a null-producing side.
none
This will improve certain queries, but more importantly it's actually a necessary condition for applying non-inner join reordering rules that I will implement.
> perf(optimizer): simplify join types with null-eliminating filter predicates

- docs/mkdocs/integrations/s3tables.md
fix typos in s3tables integrations doc
n/a
> docs: s3tables typo fixes

- src/daft-parquet/src/file.rs
Use io-runtime for task in remote parquet reader. Fixes deadlock.
> fix: Use io-runtime for task in remote parquet reader

- src/daft-logical-plan/src/ops/monotonically_increasing_id.rs
- src/daft-logical-plan/src/optimization/rules/detect_monotonic_id.rs
Currently, using a monotonically increasing id function was not allowed with a dataframe that also has an "id" column.
For example,
```
import daft;
from daft.functions import monotonically_increasing_id;
df = daft.from_pydict({"id": ["a", "b", "c"]});
df = df.with_column("partition", monotonically_increasing_id());
df.show()
```
does not work.
We fix this by not reusing "id" as a column name during logical plan optimization. This is a temporary workaround until we use ordinals to refer to columns.
> fix: Allow aliased monotonically increasing id functions to coexist with columns named "id"

- src/daft-scan/src/scan_task_iters/mod.rs
- tests/io/test_merge_scan_tasks.py
Disable scan task merging for warcs.
> fix: Disable warc merging

- daft/dataframe/dataframe.py
This adds the verbose argument (print or don't print header info) and better documents the behavior when no format is given since this takes a special formatting path for backwards compatibility.
#4100
> feat: adds verbose and documents no format behavior

- src/daft-logical-plan/src/optimization/optimizer.rs
- src/daft-logical-plan/src/optimization/rules/mod.rs
- src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
- src/daft-logical-plan/src/optimization/rules/simplify_null_filtered_join.rs
Quick refactor of some of the logic that previously lived in PushDownFilter into its own rule. 
I previously implemented it in PushDownFilter because it could have interactions with the other filter pushdown logic. However, we should try to keep PushDownFilter as simple as we can, just for pushing filter nodes through  a plan. Thus, I am moving this logic into a new rule and using the repeated execution of the rule batch to deal with interactions between the two rules.
Related to why we closed #4118
> chore(optimizer): move join type simplification into new rule

- daft/dataframe/dataframe.py
- tests/expressions/test_expressions.py
avoid superfluous .where with empty iterable when nothing to filter.
closes #4126
> fix: skip drop_nan when no float columns

- src/daft-logical-plan/src/optimization/optimizer.rs
- src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
- src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
- tests/dataframe/test_joins.py
In #4113 we have an alias in between join nodes. The join graph constructor has a bug where aliases of non-unique columns across different query tree branches would all be aliased. This is incorrect behaviour.
As a quick fix, we avoid reordering projects in between join nodes if the projection has any non-column-reference. A longer term fix (tracked in #4131) is to add projection and filter pushups during join ordering.
Closes #4113
> fix(join ordering): Fix bug with aliasing columns between joins

- daft/dataframe/dataframe.py
- daft/expressions/expressions.py
- docs/sphinx/source/dataframe.rst
- docs/sphinx/source/expressions.rst
- tests/dataframe/test_distinct.py
- tests/recordbatch/list/test_list_distinct.py
We call the functions `distinct` but make users think of `unique`. Change the docs to use consistent wording.
Additionally, added `unique` aliases for `Dataframe.distinct` and `Expression.list.distinct`.
> docs: Make wording around distinct more consistent

- .github/workflows/broken-link-checker.yml
HuggingFace link is valid but gives 403. This change fixes the workflow, https://github.com/Eventual-Inc/Daft/actions/runs/14224250387
n/a
n/a
> fix: ignore hugging face in broken link workflow

- .github/workflows/python-package.yml
- Makefile
- daft/dataframe/dataframe.py
- daft/datatype.py
- daft/expressions/expressions.py
- daft/functions/functions.py
Use native runner for doctests. Modify code examples to add a sort if needed (e.g. groupbys) because swordfish does not have ordering guarantees without an order by.
Also, don't run them for monotonically increasing id, because it requires partitioning.
> ci: Native doc tests

- src/daft-core/src/array/ops/list.rs
- tests/recordbatch/list/test_list_numeric_aggs.py
When performing a list agg on an empty partition, we throw `daft.exceptions.DaftCoreException: DaftError::ValueError Need at least 1 series to perform concat`.
To fix this, this PR adds a check if the series is empty. In this case we simply return an empty series.
Addresses #4153
> fix: Fix list aggregates on empty series

- docs/mkdocs.yml
- docs/mkdocs/sql/identifiers.md
- src/daft-catalog/src/bindings.rs
- src/daft-catalog/src/catalog.rs
- src/daft-catalog/src/error.rs
- src/daft-catalog/src/identifier.rs
- src/daft-catalog/src/table.rs
- src/daft-session/src/error.rs
- src/daft-session/src/options.rs
- src/daft-session/src/session.rs
- src/daft-sql/src/modules/aggs.rs
- src/daft-sql/src/planner.rs
- tests/sql/test_sql_identifiers.py
This PR extends the bindings to support both case-sensitive and case-normalized identifier handling for attached catalogs and tables. It does not modify column resolution (yet) and it does not add case-insensitive matching (yet). This PR also includes documentation for the goal state which will be [linked once built](https://www.getdaft.io/projects/docs/en/rchowell-identifiers/sql/identifiers/). I have also implemented case-insensitive for the attached catalogs and attached tables, but it is not possible to use yet since I have the exact-case hardcoded as default as to not break things.
[Documentation](https://www.getdaft.io/projects/docs/en/rchowell-identifiers/sql/identifiers/)
**Whats next?**
* Case-insensitive as default mode.
* Session options with SET statement.
* Session option for …
> feat: adds case-sensitive and case-normalized catalog and table identifiers [1/3]

- docs/mkdocs/resources/tutorials.md
- tutorials/embeddings/daft_tutorial_embeddings_stackexchange.ipynb
- tutorials/text_to_image/text_to_image_generation.ipynb
Our tutorial notebooks were out of date due to:
- breaking changes with struct syntactic sugar
- using `Series.to_pylist()` instead of Series iterators
- mini DALL-E being too large for CI (I switched to Stable Diffusion)
- in general dataframes were too large for CI
- broken image urls
Fixes CI
@ccmao1130 I updated the docs but not sure if that also updates getdaft.io
> docs: Fix tutorial notebooks

- tutorials/embeddings/daft_tutorial_embeddings_stackexchange.ipynb
Try setting SentenceTransformer's device explicitly to `cpu` or `cuda` depending on what is available.
Fixes CI
> docs: Fix incorrect device in tutorial notebook

- .github/workflows/nightly-publish-s3.yml
- .github/workflows/python-package.yml
- requirements-dev.txt
- tests/functions/test_llm_generate.py
Our nightly integration tests on arm machines have been failing, this should fix it. Also move from buildjet arm to Github's recently announced arm runners.
none
> ci: fix vllm import on arm and skip test if not imported

- daft/expressions/expressions.py
- daft/iceberg/iceberg_scan.py
- daft/iceberg/iceberg_write.py
- src/daft-core/src/series/ops/partitioning.rs
- src/daft-dsl/src/functions/partitioning/evaluators.rs
- tests/cookbook/test_write.py
- tests/series/test_partitioning.py
- When constructing Iceberg partition fields for writing, use partition field name specified in Iceberg metadata
- Day partitioning expression now returns Date type, in order to conform with other Iceberg implementations
Resolves #4157
> fix(iceberg): partition field names and day transform type

- .github/workflows/python-package.yml
- tests/connect/test_config.py
- tests/dataframe/test_shuffles.py
- tests/test_resource_requests.py
Upgrade runners to ubuntu-latest because Github is removing ubuntu-20.04. This causes code coverage to fail, so I added macOS to the unit test matrix to get the coverage.
Also remove windows from unit test matrix because it has never worked, and also bump unit test timeout because we've been hitting it with our Ray runners recently.
Resolves #3801
> ci: upgrade runners to ubuntu-latest

- tutorials/embeddings/daft_tutorial_embeddings_stackexchange.ipynb
our notebook checker CI run keeps failing on this notebook (ex: https://github.com/Eventual-Inc/Daft/actions/runs/14454716266/job/40535235128). This is likely a memory issue, so we'll reduce the size to fix it.
none
> ci: reduce notebook data size to avoid errors

- pyproject.toml
Pins httpx to 0.27.2 for `daft[unity]` install
> fix: Add httpx pin for `daft[unity]` install

- README.rst
fix the url for the readme badge
none
> chore: fix badge in readme

- daft/expressions/expressions.py
- src/daft-functions/src/distance/cosine.rs
- tests/expressions/test_cosine_distance.py
Currently, `expr1.embedding.cosine_distance(expr2)` only works when `expr2` is a literal. We should be able to take a column reference and compute the pairwise cosine distance in a given record. i.e. we should be able to do
```
df = df.with_column(
"cosine_distance",
col("a").embedding.cosine_distance(col("b"))
)
```
This PR enables this behaviour.
Closes #4211
> feat: Support pairwise cosine distance

- src/daft-context/src/python.rs
- tests/test_context.py
Propagates set runner errors instead of overriding them with `PyRuntimeError::new_err("Cannot set runner more than once")`, as there could be an actual error when setting the runner.
For example, a ray error when initializing ray.
> fix: Propagate set runner errors

- tests/integration/io/test_dataloading.py
Simplify the example by using `GlueCatalog.from_session()` instead of `load_glue()`
> test: Small cleanup for the Glue/Iceberg to Pytorch dataloading test

- src/daft-catalog/src/bindings.rs
- src/daft-connect/src/execute.rs
- src/daft-connect/src/spark_analyzer.rs
- src/daft-session/src/session.rs
- src/daft-sql/src/exec.rs
- src/daft-sql/src/functions.rs
- src/daft-sql/src/lib.rs
- src/daft-sql/src/planner.rs
- src/daft-sql/src/python.rs
- src/daft-sql/src/statement.rs
The commit moves SQLPlanner to use session references instead of owning the Session through Rc. This simplifies lifetime handling and state management.
- `SQLPlanner` now takes `&Session` instead of `Rc<Session>`
- Removed `fork()` from Session API
- Added bound_tables to `PlannerContext` for local table bindings
- Updated all callers to pass session references
closes https://github.com/Eventual-Inc/Daft/issues/4207
> refactor: Rework SQLPlanner to use session references

- daft/catalog/__glue.py
- tests/catalog/test_glue.py
Previously `GlueCatalog.from_session()` only accepted a boto3 session. Add a runtime check so that it can accept a botocore session too.
> feat: Allow GlueCatalog to be created from a botocore session

- daft/catalog/__glue.py
- daft/catalog/__iceberg.py
- daft/catalog/__init__.py
- daft/catalog/__memory.py
- daft/catalog/__s3tables.py
- daft/catalog/__unity.py
- daft/session.py
- docs/sessions.md
- tests/catalog/test_catalog.py
Adds a property map to the `create_table` APIs, context and use cases are linked in #4195 
closes #4195
> feat(catalog): support arbitrary properties in create_table

- docs/api/expressions.md
Fix a typo in the section header
> docs: Fix typo s/emedding/embedding/

- daft/execution/actor_pool_udf.py
Fix the unregistration for actor pool shared memory.
> fix: Use _name for shared memory unregistration

- daft/io/_lance.py
- daft/io/object_store_options.py
- requirements-dev.txt
- tests/io/lancedb/test_lancedb_writes.py
1. Increase the minimum version requirement of pylance from `0.10.12` to `0.20.0`
2. Pass the S3 `force_virtual_addressing` configuration to the Lance SDK
#4216
> fix: Read/Write Lance files on S3 error in ray mode

- daft/catalog/__init__.py
This PR improves the docstrings for the Catalog class and its associated static from_ methods:
- Added a usage example to the Catalog class docstring to clarify how to instantiate a catalog.
Provided code examples for the following static methods:
- from_iceberg
- from_unity
- from_s3tables
#4166
> docs: add usage examples to Catalog class and from_ methods

- daft/session.py
Added usage examples to the Session class docstring to make it clearer how to instantiate and use a session object.
The examples show how to create a temporary table, read it as a DataFrame, execute SQL queries, and retrieve the current session.
#4165
> docs: add usage examples to Session docstring

- src/daft-image/src/ops.rs
When we generate thumbnails to display in notebooks, we encoded them as JPEG by default. This does not work if images have an alpha channel.
This PR changes it so that we generate PNGs instead. This should have minimal performance impact because we're generating small 128x128 thumbnails and this only happens when previewing a small amount (typically <= 8) of results in a notebook.
Closes #4072
> fix: Allow PNGs to be displayed notebooks

- .github/CODEOWNERS
- daft/catalog/__init__.py
- daft/session.py
* Adds ChanChan as CODEOWNER for `docs/*`
* Fixes typos in doc examples.
* Closes #4165
* #4259
* #4252
> docs: fix doc typos

- .github/workflows/pr-test-suite.yml
- benchmarking/parquet/benchmark-requirements.txt
- pyproject.toml
- requirements-dev.txt
- src/daft-core/src/datatypes/logical.rs
- src/daft-schema/src/dtype.rs
- tests/integration/io/docker-compose/retry_server/retry-server-requirements.txt
Upgrades our pyarrow version in tests to 19.0.0, additionally removes the pin in `pyproject.toml`
In order to support 19.0.0, this PR also fixes our map type conversion code, which is the only thing that failed. See https://github.com/Eventual-Inc/Daft/issues/4206
Map types are required to be annotated with `not null` for the keys, and currently this is not propagated from daft datatype to arrow. This PR modifies the `to_arrow` conversion for map types and arrays to obey this constraint. Previous version of pyarrow did not have this error as they auto-added the annotation when importing from the C data interface.
Closes https://github.com/Eventual-Inc/Daft/issues/4256
> chore: Upgrade supported pyarrow version to 19.0.0

- src/common/scan-info/src/python.rs
- src/daft-dsl/src/expr/mod.rs
- src/daft-recordbatch/src/lib.rs
- src/daft-schema/src/schema.rs
- src/daft-sql/src/modules/aggs.rs
Created a `BoundColumn` column variant that holds an ordinal/index and a field. 
This is not currently used anywhere except in RecordBatch for evaluating an expression. The plan is to move the binding step up the planning/execution pipeline, until it completely replaces the Resolved variant. That way, we can do this refactor incrementally and ensure that tests pass the whole time. See [the roadmap](https://github.com/Eventual-Inc/Daft/issues/4270) for more details
#4270
> refactor(ordinals): add bound column variant

- .github/workflows/build-wheel.yml
- .github/workflows/pr-test-suite.yml
- .github/workflows/publish-dev-s3.yml
- src/daft-dashboard/build.rs
Downgrades our minimum supported glibc version from 2.28 to 2.24 by changing the manylinux Docker image. Also move bun build out of the rust build
Requested by Amazon since they use Amazon Linux 2, which has glibc 2.26
> ci: compile release build with glibc 2.24

- .github/workflows/daft-profiling.yml
This should fix the CI issue on main
none
> ci: add bun build step to CI profiling workflow

- src/daft-context/src/lib.rs
If ray is initialized, `DAFT_RUNNER=native` still uses the ray runner. This PR changes the behaviour so that if `DAFT_RUNNER=native` is explicitly set, we choose the native runner. This allows users to use the native runner in environments where ray might be initialized.
> chore: Use native runner if config is set regardless of ray initialization

- .github/workflows/benchmark-distributed-tpch.yml
- .github/workflows/benchmark-local-tpch.yml
uv currently has issues with our nightly tests (see https://github.com/astral-sh/uv/issues/13248). Temporarily fix this by using an earlier version of uv
> ci: Fix uv issues for nightly TPCH benchmarks

- src/arrow2/src/compute/arithmetics/time.rs
- src/daft-core/src/array/from.rs
- src/daft-core/src/array/ops/time.rs
- src/daft-core/src/datatypes/infer_datatype.rs
- src/daft-core/src/series/ops/arithmetic.rs
- src/daft-sql/src/lib.rs
- tests/sql/test_exprs.py
this pr allows executing multiplication arithmetics for interval data type. like:
```py
import daft
daft.sql("select interval '1 day' * 3;").collect()
```
first time submitting a PR here, appreciate the feedback!
fixes #4144
> feat: allow making multiplication arithmetics with Interval data type

- .github/workflows/property-based-tests.yml
fix property based test by adding bun build for dashboard
none
> ci: add bun run build to property based testing

- CONTRIBUTING.md
- tools/attach_debugger.py
The docs for setting up the debugger in `CONTRIBUTING.md` don't specify what python code it will debug. I quickly figured it out after skimming the given `launch.json` and `tools/attach_debugger.py`, but I can imagine others not figuring it out very quickly. This PR adds that small detail to the docs to make it immediately clear.
```json
"configurations": [
{
"name": "Debug Rust/Python",
...
"args": [
"${file}"
],
...
},
```
> docs: Specify what script the debug config uses in `CONTRIBUTING.md`

- src/daft-dsl/src/functions/mod.rs
- src/daft-functions/src/float/mod.rs
- src/daft-functions/src/lib.rs
- src/daft-functions/src/numeric/mod.rs
- src/daft-functions/src/python/mod.rs
- src/daft-image/src/functions/mod.rs
- src/daft-sql/src/functions.rs
- src/lib.rs
small PR to move the FUNCTION_REGISTRY from daft-functions to daft-dsl. This improves compilation by making other modules such as `daft-image` and `daft-functions-json` not need to depend on `daft-functions` and only need to depend on `daft-dsl`.
> refactor(exprs): move func registry from daft-functions -> daft-dsl

- Cargo.lock
- src/daft-io/Cargo.toml
- src/daft-local-execution/src/sinks/write.rs
- src/daft-shuffles/src/shuffle_cache.rs
- src/daft-writers/Cargo.toml
- src/daft-writers/src/batch.rs
- src/daft-writers/src/catalog.rs
- src/daft-writers/src/file.rs
- src/daft-writers/src/ipc.rs
- src/daft-writers/src/lance.rs
- src/daft-writers/src/lib.rs
- src/daft-writers/src/partition.rs
- src/daft-writers/src/physical.rs
- src/daft-writers/src/pyarrow.rs
- src/daft-writers/src/test.rs
The native file writers (e.g. https://github.com/Eventual-Inc/Daft/pull/4260) that we intend to implement are asynchronous. As prep, we move our file writer traits from synchronous to asynchronous.
> feat: Make file writers async

- src/daft-physical-plan/src/physical_planner/translate.rs
Currently, most of the actual work for count_distinct is done at the finalization step, which only runs on 1 task / thread. Thus, very little parallelism is possible. With this change, Daft will perform a local distinct operation on micro-partitions during the sink phase, which can be done in parallel.
Performance results of running ClickBench Queries 4 & 5 (6 runs each, skipping first) on a M4 Max MacBook Pro w/ 14 cores & 32 GB memory:
| Query |	Before | After | Improvement |
| ------ | ------- | ----- | ------------- |
| Q4 | 2.95s | 1.89s| 1.56x |
| Q5 | 2.82s | 1.30s | 2.16x |
> perf: Perform Local Distinct list_agg in count_distinct aggregations

- Makefile
Added a rule to the Makefile to build the daft-dashboard frontend because I had to keep doing it manually every time I pull from main.
> chore: Add daft-dashboard frontend build step to Makefile

- tutorials/window_functions/demo.ipynb
Add pip installs for the dependencies in window function demo notebook.
> fix: Add pip installs to window demo

- tests/integration/io/parquet/test_reads_public_data.py
This PR changes `raw.githubusercontent.com` requests to go to our public S3 bucket to avoid throttling from Github which has recently been breaking GH actions / CI.
Ran locally,
```shell
tests/integration/io/parquet/test_reads_public_data.py ........................................................................................................................................................................................... [ 54%]
..............................................................................................................................................................                                                                                     [100%]
============================================================================================================ 345 …
```
> fix: mirror raw.githubusercontent via S3 to avoid CI throttling

- Makefile
- requirements-dev.txt
- tests/sql/test_uri_exprs.py
Integ tests using torch were added, but the dep was not included in reqs. This meant I could not `make test` a fresh repo since you'd get a missing dep error. This has not failed in CI because we scope pytest to `tests/` in CI, but not in `make test`. Possible solutions are lazy-dep, scope `make test` down, or add this dep.
n/a
> fix: ignores tests/integration for make test target

- docs/spark_connect.md
- pyproject.toml
Adds the required dependencies for pyspark to work in `pip install daft[spark]`
Closes #4310
> feat: Add optional spark dependency for pyspark connector

- src/common/io-config/src/http.rs
- src/daft-io/src/http.rs
- src/daft-io/src/huggingface.rs
- src/daft-sql/src/modules/config.rs
Adds reqwest retry logic to `https://` and `hf://` based upon the existing GCS retry logic. https://github.com/Eventual-Inc/Daft/pull/3253
> fix: adds HTTP and HF retry logic based upon exist GCS retry logic

- daft/delta_lake/delta_lake_scan.py
In our current deltalake scanner, we use botocore to grab the region name of a given S3 bucket. This adds a botocore dependency to using deltalake. We can remove this dependency by instead making a HTTP request to the S3 url which returns a region name in the header.
Closes #4189
> fix: Remove botocore dependency when working with deltalake

- tests/actor_pool/test_actor_cuda_devices.py
This test has been flaky on the macOS PyRunner, and I'm not sure why. It might be because of the way that macOS handles environment variable setting in subprocesses.
Either way, didn't want to debug this too much since our py runner is deprecated anyway, so I'm just skipping this test.
> fix: skip flaky actor pool GPU test

- src/daft-io/src/s3_like.rs
Added a put_multipart implementation to s3_like. 
Things to note:
* Splits input Bytes buffer into parts using a configurable part_size.
* Performs all part uploads in parallel - this is expected to be OK given that this will be an individual parquet file - we can revisit this and change it easily (at least at a per-upload, if not global level).
* Completes multi-part upload. Doesn't abort on failure - so you could have dangling part files. Customers must set some sort of policy. [See](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpu-abort-incomplete-mpu-lifecycle-config.html) 
* Respects `requester_pays`.
* Includes part-level bandwidth update. 
Open items:
* Should each part be counted as an individual put in IOStat? Or is it OK to introduce a separate field to track? This is a …
> feat: Add put_multipart to s3_like

- .github/workflows/nightly-publish-s3.yml
- .github/workflows/pr-test-suite.yml
With the latest improvements to projections and URL handling, we should be able to deprecate the `py` runner soon. At a minimum, we won't be making significant changes to the `py` runner. Thus, we don't need to run `py` runner tests on PR CI anymore.
Note that I kept the nightly tests, just removed the PR CI tests. That's because GitHub Actions limits the number of concurrent runners per repo, especially for MacOS. Thus, this should speed up CI times.
> ci: Remove `py` runner tests from PR CI

- .github/workflows/notebook-checker.yml
Add matplotlib as an import to our notebook checker so that it succeeds.
none
> fix(ci): import matplotlib for window function tutorial

- docs/index.md
- docs/js/readthedocs.js
- docs/roadmap.md
Adds new selector every time a new page is clicked.
Also made a small fix to Daft overview page and added an item to Daft Roadmap
See build here: https://www.getdaft.io/projects/docs/en/chanchan-readthedocs/
> docs: fix readthedocs version dropdown 

- daft/expressions/expressions.py
- tests/integration/io/parquet/test_reads_public_data.py
Not 100% sure if this will fix it, but the errors in CI are coming from this `pyarrow.parquet.read_table` call.
none
> fix(tests): add retry to pyarrow parquet read

- src/daft-io/src/lib.rs
- src/daft-writers/src/parquet_writer.rs
The `parse_url` utility function didn't map `s3n` to the S3 source type, leading us to throw a `NotImplementedSource` error when parsing s3n urls. This PR fixes this.
> fix: Add s3n to parse_url

- .github/workflows/pr-test-suite.yml
- README.rst
Cancel old PR test suite runs when there is a new push to a PR. This allows us to hammer github actions less, but also lets us start testing the latest push faster since it won't have to wait as long for runners to become available.
> ci: Cancel ongoing PR tests on push

- CONTRIBUTING.md
- src/daft-dsl/src/functions/mod.rs
- src/daft-dsl/src/functions/prelude.rs
Adds the required deps for implementing a ScalarUDF to the common interface package. We could also `pub use` in the ScalarUDF module. Reduces loc in each function impl from 15 to 1, since you have to import these anyways. Minor docs edits for consistent spacing, casing and punctuation,.
n/a
> feat: adds functions prelude and clean up contributing notes.

- .github/workflows/build-wheel.yml
- Makefile
- src/daft-dashboard/build.rs
splits the `dashboard/build.rs` into 2 separate mains. one for ci, and one for normal.
Prior to the build.rs changes in https://github.com/Eventual-Inc/Daft/pull/4272, you could manually install daft via
```sh
uv pip install daft@file:///path/to/repo/Daft
```
but after these changes, this no longer works. 
So this PR essentially reverts those for everywhere except CI. 
Notes regarding ci. 
Maturin passes the `GITHUB_` env vars through to the image, so by detecting the `GITHUB_ACTIONS` flag, the build should use the existing code path. 
- https://github.com/PyO3/maturin-action/blob/main/src/index.ts#L866
- https://github.com/PyO3/maturin-action/blob/main/src/index.ts#L250
so it should run as expected inside the CI.
⚠️ before merging, we must validate a manual run of the build CI.
> build: make dashboard self contained again, except when running in ci

- daft/expressions/expressions.py
Noticed that the API docs for `Expression.embedding.cosine_distance` were not rendering correctly, so fixed it. 
Current:
Rendered on PR:
> docs: Fix docs generation for `Expression.embedding.cosine_distance`

- daft/runners/progress_bar.py
Daft runs into panics in a notebook when trying to render a progress bar:
This is because `type 'tqdm' is not subscriptable`. So we remove the subscript.
> fix: Progress bar no longer panics

- tests/integration/iceberg/docker-compose/docker-compose.yml
https://github.com/minio/mc/issues/5206
```mc: <ERROR> `config` is not a recognized command. Get help using `--help` flag.```
replaced with `mc alias set`
> fix: Fix iceberg docker compose entrypoint command

- daft/udf.py
- tests/dataframe/test_iter.py
- tests/expressions/test_udf.py
This PR makes the UDF errors more descriptive, easier to understand, and actionable. Additionally, it also improves the readability of the internal code that runs the UDF, `run_udf`.
```
Error when running pipeline node Project
File "/Users/colinho/Desktop/Daft/daft/udf.py", line 134, in run_udf
results = [func(*args, **kwargs)]
File "/Users/colinho/Desktop/Daft/test.py", line 9, in add_one
raise ValueError("oopsie")
ValueError: oopsie
The above exception was the direct cause of the following exception:
File "/Users/colinho/Desktop/Daft/test.py", line 16, in <module>
df = df.collect()
File "/Users/colinho/Desktop/Daft/daft/api_annotations.py", line 26, in _wrap
return timed_method(*args, **kwargs)
File …
```
> fix: Improve UDF errors

- .github/workflows/broken-link-checker.yml
changed daft's twitter & linkedin handle to `@daftengine`, exclude from broken link checker
> fix: update broken-link-checker.yml

- daft/io/__shim.py
- daft/io/source.py
Now that we have python classes for PartitionField and PartitionSpec, they can be hooked up to the DataSource API, and the __shim does the PyPartitionField unwrapping.
- #4228
> feat: adds python partition fields to the DataSource API

- .github/workflows/build-wheel.yml
- .github/workflows/nightly-publish-s3.yml
- .github/workflows/publish-dev-s3.yml
- .github/workflows/publish-pypi.yml
- daft/__init__.py
- pyproject.toml
- requirements-dev.txt
With our upcoming v0.5 release, we will no longer publish to the PyPI package `getdaft`, and instead only publish to `daft` and `daft-lts`. This PR makes that change.
#3913
> ci: remove publish with name 'getdaft'

- Cargo.lock
- daft/daft/__init__.pyi
- src/daft-local-execution/Cargo.toml
- src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
- src/daft-local-execution/src/pipeline.rs
- src/daft-local-execution/src/run.rs
- src/daft-local-execution/src/runtime_stats.rs
- src/daft-local-execution/src/sinks/blocking_sink.rs
- src/daft-local-execution/src/sinks/streaming_sink.rs
- src/daft-local-execution/src/sources/source.rs
This currently isn't being used yet, but the general idea is that for the OSS dashboard visualizations, we need some way to know information about the plan structure (nodes and their children). Which we later fill in with `RuntimeContext` information. `get_relationship_info` is purely just to get the tree hierarchy. 
As an added bonus, the otel subsciber now has access to some additional fields that'll be useful for generic telemetry purposes (id, and plan_id).
ÏÏ
> feat: add id and plan_id to otel subscribers, and add method for getting tree hierarchy for a pipeline

- daft/functions/__init__.py
- daft/functions/functions.py
- tests/dataframe/test_format_function.py
Implemented `f""` string style string concatenation (see linked issue for more detail) and added some tests. Probs want to also add this to the docs at some point?
https://github.com/Eventual-Inc/Daft/issues/4001
> feat: `f""` string style string concatenation

- daft/context.py
- daft/daft/__init__.pyi
- src/common/daft-config/src/python.rs
- tests/benchmarks/test_parquet_writes.py
Adds a harness that allows us to create datasets with different shapes, which we can then use for benchmarking parquet write speeds.
To run:
```
DAFT_RUNNER=native pytest tests/benchmarks/test_parquet_writes.py -m benchmark -s
```
> perf: add harness for benchmarking parquet writes

- src/daft-connect/src/functions/core.rs
- tests/connect/test_basics.py
adds support for spark's control flow expression `when().otherwise()`
related: https://github.com/Eventual-Inc/Daft/issues/4514
> feat(connect): add support for spark when/otherwise

- daft/expressions/expressions.py
> docs: fix bad markdown links

- src/common/tracing/src/lib.rs
- src/daft-local-execution/src/run.rs
Previously the chrome trace would emit an empty file followed by a malformed file. This is because we always start a new trace on query run but don't close the trace.
> fix: Fix chrome trace

- src/daft-writers/src/lib.rs
- src/daft-writers/src/parquet_writer.rs
- src/daft-writers/src/storage_backend.rs
- src/daft-writers/src/utils.rs
Pull out the storage backends and utility functions currently used for the parquet writer. This sets us up for reusing this when writing to other file formats like JSON.
> chore: Refactor storage backends for native writers

- daft/series.py
- daft/utils.py
- src/common/arrow-ffi/src/lib.rs
- src/daft-core/src/python/series.rs
This PR improves the efficiency of `to_arrow` for structs and fixed size lists, namely getting rid of a redundant `to_arrow` and enabling parallelization for the array ipc ser/de.
When testing on the imagenet inference workload, the speedup was 6:15s -> 4:50s, roughly 30%
> perf: Improve efficiency of `to_arrow` for struct / fixed size lists

- daft/pyspark/__init__.py
- daft/runners/ray_runner.py
- docs/distributed.md
- docs/spark_connect.md
Testing against the most recent version of Ray (2.47.0):
When Daft connects to Ray, #3899 strips the `ray://` protocol. However this seems to be broken against new versions of Ray (I only tested from 2.44 onwards)
```
ray.init("ray://localhost:10001")  # ok
ray.init("localhost:10001")  # not ok -- gcs_client.cc:178: Failed to get cluster ID from GCS server: RpcError: RPC Error message: Method not found!; RPC Error details:
ray.init("localhost:6379")  # not ok -- 2025-06-19 11:30:45,578	INFO node.py:1047 -- Can't find a `node_ip_address.json` file from /tmp/ray/session_2025-06-19_10-54-08_399102_1. Have you started Ray instance using `ray start` or `ray.init`?
ray.init("ray://localhost:6379")  # not ok -- it just hangs
```
This PR fixes these issues, and standardizes across our …
> fix: fix ray connection issues with ray:// protocol

- daft/utils.py
- src/daft-catalog/src/impls/memory.rs
- src/daft-connect/src/execute.rs
- src/daft-context/src/lib.rs
- src/daft-context/src/partition_cache.rs
- src/daft-context/src/python.rs
- tests/test_context.py
Consider the following:
```
import concurrent.futures
from daft.context import get_context
with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:
futures = [
executor.submit(lambda: get_context().get_or_create_runner()) for _ in range(10)
]
results = [future.result() for future in concurrent.futures.as_completed(futures)]
```
where we just call `get_or_create_runner()` across multiple threads.
Thread 1: Acquires `DaftContext` rwlock
Thread 1: Checks if runner is set. Runner is not set
Thread 1: Checks if should use ray. Tries to import ray, releases GIL.
Thread 2: Acquires GIL, and tries to acquire `DaftContext` rwlock. Deadlock because Thread 1 is holding it.
> fix: Fix `get_or_create_runner` deadlock

- daft/io/_range.py
- tests/io/test_range.py
`daft.range` with partitions doesn't work properly.
Example:
```
df = daft.range(8, partitions=2)
print(df.to_pydict())
{'id': [0, 1, 2, 3]}
```
I expect the full range from 0-8
> fix: Fix daft.range partitioning logic

- tests/io/conftest.py
- tests/io/delta_lake/conftest.py
- tests/io/test_s3_credentials_refresh.py
- tests/io/test_url_upload_local.py
- tests/recordbatch/numeric/test_numeric.py
- tests/test_datatypes.py
improve some test cases describe in https://github.com/Eventual-Inc/Daft/discussions/4564
```
FAILED tests/io/test_s3_credentials_refresh.py::test_s3_credentials_refresh - botocore.errorfactory.BucketAlreadyOwnedByYou: An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operati...
FAILED tests/io/test_url_upload_local.py::test_upload_local_no_write_permissions - Failed: DID NOT RAISE <class 'daft.exceptions.DaftCoreException'>
FAILED tests/recordbatch/numeric/test_numeric.py::test_table_numeric_trigonometry[sinh-False-False] - assert False is True
FAILED tests/recordbatch/numeric/test_numeric.py::test_table_numeric_trigonometry[cosh-False-False] - assert False is True
FAILED tests/recordbatch/numeric/test_numeric.py::test_table_numeric_trigonometry[arccos-True-False] …
```
> chore: improve the stability of unit test

- daft/pyspark/__init__.py
Changed local daft spark-connect server address to work both in linux and windows
Now doesn't hang in windows, no changes for linux
Closes #4559 
Behaviour before the fix:
daft version 0.5.5, pyspark version 3.5.6
this works in linux, but hangs in windows:
```
from daft.pyspark import SparkSession
from pyspark.sql.functions import col
spark = SparkSession.builder.local().getOrCreate()
col("a") + col("b")
```
> fix: daft spark-connect server on windows hangs

- Cargo.lock
- src/daft-distributed/Cargo.toml
- src/daft-distributed/src/lib.rs
- src/daft-distributed/src/pipeline_node/limit.rs
- src/daft-distributed/src/pipeline_node/mod.rs
- src/daft-distributed/src/pipeline_node/sink.rs
- src/daft-distributed/src/pipeline_node/translate.rs
- src/daft-local-execution/src/pipeline.rs
- src/daft-local-execution/src/sinks/commit_write.rs
- src/daft-local-execution/src/sinks/mod.rs
- src/daft-local-execution/src/sinks/write.rs
- src/daft-local-plan/Cargo.toml
- src/daft-local-plan/src/lib.rs
- src/daft-local-plan/src/plan.rs
- src/daft-local-plan/src/translate.rs
- tests/io/test_write_modes.py
Adds a `CommitWrite` sink to swordfish, which performs overwrite / overwrite partitions. In the future it will allow us to add other functionality needed to do `commits`.
Mainly this PR is to allow flotilla to properly perform overwrites, as previously it was doing it at a per-task level, which was incorrect.
> feat: Commit write sink

- CONTRIBUTING.md
https://github.com/Eventual-Inc/Daft/issues/4575
@universalmind303 @colin-ho  If you have time, please help check if my usage is correct. Since the Python environment installed by venv now doesn't come with libpython_3x.so, if we directly add some ut of rust libraries related to pyto3 here, it can't run directly. So I've added some explanations here. Thank you.
> fix: missing libpython when using pyo3 in cargo test

- tests/series/test_series.py
We have a test assertion that a Series iterator takes less peak memory than converting the Series to pylist. This test is flaky in CI, but it's still useful for sanity checks. We can disable this test in CI environments.
Closes #4580
> ci: Deflake series iter memory test

- daft/runners/flotilla.py
- daft/runners/ray_runner.py
- src/daft-distributed/src/python/ray/worker.rs
- src/daft-distributed/src/python/ray/worker_manager.rs
- src/daft-distributed/src/scheduling/autoscaler.rs
- src/daft-distributed/src/scheduling/dispatcher.rs
- src/daft-distributed/src/scheduling/mod.rs
- src/daft-distributed/src/scheduling/scheduler/default.rs
- src/daft-distributed/src/scheduling/scheduler/linear.rs
- src/daft-distributed/src/scheduling/scheduler/mod.rs
- src/daft-distributed/src/scheduling/scheduler/scheduler_actor.rs
- src/daft-distributed/src/scheduling/worker.rs
Enable autoscaling functionality in the flotilla scheduler. 
For now it's quite basic, if there's no workers then request `num_cpus=num_pending_tasks`. In the future we should consider implementing autoscaling strategies. 
The ray worker manager autoscales via https://docs.ray.io/en/latest/cluster/running-applications/autoscaling/reference.html.
To check for new workers, the dispatcher now has a tick interval that queries the worker manager for updates. Upon receiving request for worker snapshots, the worker manager will now always check for new nodes to run workers on if available.
Tested this on a simple `read_parquet("TPCH_1000_LINEITEM").collect()` in a ray cluster with 0 workers and it autoscaled properly.
> feat(flotilla): Flotilla autoscaling

- daft/daft/__init__.pyi
- daft/dependencies.py
- daft/expressions/expressions.py
- daft/expressions/visitor.py
- daft/io/_lance.py
- src/daft-dsl/src/python.rs
- tests/expressions/test_to_arrow_expr.py
This PR adds a daft expression to pyarrow compute translator so that we can leverage pushdowns in other sources such as lance. There has been ongoing discussion, and the pieces are ready.
I need to add some tests, but this get's us quite far.
https://github.com/Eventual-Inc/Daft/discussions/4615
* #4278 
* #4203 
* #4239
> feat: adds daft expr to pyarrow compute translator

- daft/context.py
The `min_cpu_per_task` config cannot update now because it is not set into the new config when using `daft.context.set_execution_config`.
> fix: Fix setting `min_cpu_per_task` when using `daft.context.set_execution_config`

- daft/recordbatch/micropartition.py
- daft/recordbatch/recordbatch.py
- tests/recordbatch/test_micropartition.py
Found a side issue when working on flotilla that affects writing to Ray object store, which uses Ray cloudpickle.
> fix: Picking MicroPartitions with duplicate column names

- src/daft-distributed/src/pipeline_node/actor_udf.rs
- src/daft-distributed/src/pipeline_node/limit.rs
- src/daft-distributed/src/pipeline_node/materialize.rs
- src/daft-distributed/src/pipeline_node/mod.rs
- src/daft-distributed/src/plan/mod.rs
- src/daft-distributed/src/python/mod.rs
- src/daft-distributed/src/python/ray/task.rs
- src/daft-distributed/src/scheduling/dispatcher.rs
- src/daft-distributed/src/scheduling/scheduler/mod.rs
- src/daft-distributed/src/scheduling/scheduler/scheduler_actor.rs
- src/daft-distributed/src/scheduling/task.rs
- src/daft-distributed/src/utils/stream.rs
- tests/integration/iceberg/docker-compose/docker-compose.yml
To make repartition easier to implement and less flaky, it would be better if all returned partitions from a task are packaged together into one MaterializedOutput instead of multiple. This makes other sections that work better on individual partitions a bit more complicated, so reworked other operators.
> fix(flotilla): Change MaterializedOutput to return a Vec<Partitions>

- docs/core_concepts.md
Add a section in the UDF docs about how to debug udfs
Closes https://github.com/Eventual-Inc/Daft/issues/3796
> docs: Add debugging udfs docs

- src/daft-distributed/src/scheduling/dispatcher.rs
- src/daft-distributed/src/scheduling/scheduler/default.rs
- src/daft-distributed/src/scheduling/scheduler/linear.rs
- src/daft-distributed/src/scheduling/scheduler/mod.rs
- src/daft-distributed/src/scheduling/scheduler/scheduler_actor.rs
This PR renames two key components in the scheduling code to improve semantic clarity and alignment with actual behavior:
1. SchedulableTask -> PendingTask - Think "Schedulable" and "Scheduled" are quite a mouthful for verbal conversations. Besides, we already have a method called 'num_pending_tasks'. So I just chose 'PendingTask'.
2. get_schedulable_tasks -> schedule_tasks - This was a mutating method that actually performs the scheduling (i.e. assigns tasks to workers).
No functional behavior has changed—this is a naming/clarity refactor only.
> chore(flotilla): Refactor task naming for clarity

- src/daft-distributed/src/statistics/http_subscriber.rs
Query nodes may not receive task progress, in which case they don't appear as part of the nodes list in the query graph. Make sure we initialize the query graph to contain all logical nodes.
N/A
> fix: populate query graph nodes even if they lack task progress

- src/daft-functions-list/src/list_fill.rs
- src/daft-logical-plan/src/ops/set_operations.rs
Swap arg order for list fill so that we can use the first arg for the name.
> fix: Swap arg order for list_fill

- src/daft-distributed/src/pipeline_node/actor_udf.rs
- src/daft-distributed/src/scheduling/scheduler/default.rs
- src/daft-distributed/src/scheduling/scheduler/scheduler_actor.rs
- tests/expressions/test_udf.py
If there are multiple actor pool projects in a row, the notify tokens get overridden.
This PR makes it such that a task can have multiple notify tokens, so multiple pipeline nodes can subscribe to the task finished notification.
> fix(flotilla): Add multiple notify tokens to task

- src/daft-distributed/src/pipeline_node/mod.rs
- src/daft-distributed/src/pipeline_node/repartition.rs
This PR prevents propagation of empty partition refs for subsequent tasks
> fix: Ignore partition refs if they are empty

- daft/io/turbopuffer/__init__.py
- daft/io/turbopuffer/turbopuffer_data_sink.py
Adds an experimental turbopuffer data sink. Currently it transforms each row of the dataframe into a document. This means that an `id` column is always required, and a `vector` column is required if the namespace has a vector index. All other columns become attributes.
For more details, see the turbopuffer documentation: https://turbopuffer.com/docs/write
```
import daft
from daft.io.turbopuffer import TurbopufferDataSink
df = daft.from_pydict({
"id": [1, 2, 3, 4, 5],
"val": ["a", "b", "c", "d", "e"]
})
tpuf_sink = TurbopufferDataSink(namespace="desmond_test_sink")
df.write_sink(tpuf_sink).show()
```
```
from __future__ import annotations
import os
import daft
from daft.io.turbopuffer import TurbopufferDataSink
def openai_or_rand_vector(text: str) -> list[float]:
if not …
```
> feat: Add experimental turbopuffer sink

- .github/workflows/build-wheel.yml
- .github/workflows/publish-dev-s3.yml
Make LTO optional so we can build Daft wheels more quickly for platform testing.
fyi @kevinzwang @ohbh @rchowell 
N/A
> ci: enable building wheels without LTO

- .vscode/settings.json
- src/daft-core/src/array/ops/repr.rs
- tests/series/test_html_repr.py
The following should not crash the Jupyter UI:
```py
import daft
df = daft.from_pydict({ 'x': ['foo' * 10000000] })
df.show()
```
This is just a first start, there's more work to do here to lazy fetch data.
N/A
>  fix(repr): avoid crashing notebook UI when visualizing large strings

- daft/io/turbopuffer/turbopuffer_data_sink.py
> fix: use pc.field in turbopuffer sink

- daft/__init__.py
- daft/api_annotations.py
- daft/dataframe/dataframe.py
- daft/errors.py
- daft/execution/actor_pool_udf.py
- daft/udf.py
- tests/dataframe/test_iter.py
- tests/expressions/test_udf.py
Improves the traceback printed by Python for errors raised from UDFs by suppressing some of our internals. 
With the following example:
```py
import daft
def g(x):
raise RuntimeError("This is a custom exception")
@daft.udf(return_dtype=daft.DataType.string())
def f(x):
return g(x)
df = daft.from_pydict({"x": ["a", "b", "c"]})
df.with_column("transformed", f(daft.col("x"))).show()
```
Before:
```
File "/Users/slade/daft/main/tracing.py", line 11, in <module>
df.with_column("transformed", f(daft.col("x"))).show()
File "/Users/slade/daft/main/daft/api_annotations.py", line 34, in _wrap
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/Users/slade/daft/main/daft/dataframe/dataframe.py", line 3377, in show
preview = self._construct_show_preview(n) …
```
> fix: Improve UDF Error Messaging

- .github/workflows/pr-test-suite.yml
- daft/execution/ray_actor_pool_udf.py
- src/daft-distributed/src/pipeline_node/actor_udf.rs
- src/daft-distributed/src/python/ray/worker_manager.rs
- src/daft-distributed/src/scheduling/scheduler/default.rs
- src/daft-distributed/src/scheduling/scheduler/mod.rs
- tests/expressions/test_udf.py
When scheduler receives worker updates, it should override all worker snapshots.
> fix: Propagate worker failures to scheduler

- daft/datatype.py
- daft/execution/ray_actor_pool_udf.py
- src/daft-distributed/src/pipeline_node/actor_udf.rs
- src/daft-distributed/src/pipeline_node/mod.rs
- src/daft-distributed/src/scheduling/task.rs
- src/daft-local-execution/src/intermediate_ops/distributed_actor_pool_project.rs
Spread actor UDF tasks and pass all the handles to the swordfish worker, let it choose which actor to use based on the location.
> feat: Spread actor udf tasks

- src/daft-functions-list/src/list_fill.rs
Felt like cleaning something up, did ctrl+f and found a dbg! and now it's gone.
None
> chore: remove dbg from tests

- daft/__init__.py
Fixes Python LSP / Intellisense understanding of `daft.context` and `daft.io` by explicitly re-exporting it. https://docs.astral.sh/ruff/rules/unused-import/#unused-import-f401
> fix: LSP handling for `daft.context` and `daft.io`

- CONTRIBUTING.md
- src/lib.rs
Currently, if you want to set the log level, you need to follow the following method, which is rather cumbersome. Therefore, an environment variable is introduced here as the top - priority identifier for the log level of Rust.
```
logging.basicConfig(
level=logging.DEBUG,
format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
stream=sys.stdout
)
daft.refresh_logger()
```
In addition, some instructions on how to view debug logs in pytest were added to CONTRIBUTE.md.
> chore: add DAFT_LOG env indicates log level

- daft/expressions/expressions.py
Add the `Expression.unnest` method. Since we already have the mechanism for unnesting with `Expression.struct.get("*")`, I'm just reusing that for now. We will need to change it once we introduce selectors anyway.
> feat: struct Expression.unnest()

- daft/dataframe/dataframe.py
- daft/io/turbopuffer/turbopuffer_data_sink.py
Turbopuffer client construction and writes accept many possible arguments. Instead of enumerating them and always trying to stay in sync, lets add support for kwargs.
> feat(turbopuffer): Add client and write kwargs

- .github/workflows/pr-test-suite.yml
- daft/io/writer.py
- src/daft-core/src/array/ops/cast.rs
- tests/io/test_roundtrip_embeddings.py
- tests/series/test_cast.py
- tests/utils.py
Fixes reading embedding-typed columns from DataFrames saved to both Parquet and Lance data formats.
Primary fix is to in `daft-core`'s `array/ops/cast.rs`. Specifically the `FixedSizeListArray`'s `cast` implementation.
There is now a match arm for `DataType::Embedding`. Upon encountering this, Daft will now properly cast the 
data into an `EmbeddingArray` struct (from `datatypes::logical`). Before, this case was unrecognized and thus 
led an `unimplemented!` error.
Secondary fix is related to this Arrow 8 bug: https://issues.apache.org/jira/browse/ARROW-12201 . When writing to Parquet in Arrow 8, the logical datatype information for u32 values are incorrectly written. They will instead be written as signed 64 bit integers! The fix is to always use Parquet version >= 2.0. In later versions …
> fix: read/write embeddings for Parquet and Lance

- src/daft-decoding/src/deserialize.rs
- src/daft-scan/src/hive.rs
- tests/io/test_hive_style_partitions.py
Use the existing daft-decoding code used in csv deserialization for hive partition values as well. Previously, we were using arrow2's utf8 cast to do this, which caused issues as seen in https://github.com/Eventual-Inc/Daft/issues/4821.
Closes https://github.com/Eventual-Inc/Daft/issues/4821
> feat: Use daft-decoding for hive value deserialization

- daft/dataframe/dataframe.py
- daft/io/turbopuffer/turbopuffer_data_sink.py
When writing to turbopuffer, it's common to write data to multiple namespaces. We extend the turbopuffer data sink so that the `namespace` parameter can take either a string or an expression. If we're given a string, all data gets written to the given namespace. Otherwise, we evaluate the expression and partition the data by namespace value before writing to their respective namespaces.
> feat: Support multiple namespaces in the turbopuffer writer

- src/daft-io/src/s3_like.rs
- tests/integration/io/conftest.py
- tests/integration/io/test_files_roundtrip_s3_minio.py
- tests/integration/io/test_write_files_s3_minio.py
We previously assumed that uploads could not be anonymous, but have since learnt that there are setups that allow this.
> fix: Allow anonymous mode to be used for S3 uploads

- daft/series.py
- daft/udf.py
- tests/expressions/test_udf.py
As mentioned in https://github.com/Eventual-Inc/Daft/issues/4851, the `pyarrow.concat_arrays()` doesn't support concat chunked arrays, so need to loop each chunks at first and then concat them together
https://github.com/Eventual-Inc/Daft/issues/4851
> fix: concat chunked array safety

- daft/io/sink.py
- src/daft-writers/src/sink.rs
- tests/io/test_sink.py
If an exception is thrown in the data sink and is unserializable, we may get errors like
```
File ~/anaconda3/lib/python3.12/site-packages/daft/dataframe/dataframe.py:1304, in DataFrame.write_sink(self, sink)
1302 builder = self._builder.write_datasink(sink.name(), sink)
1303 write_df = DataFrame(builder)
-> 1304 write_df.collect()
1306 results = write_df.to_pydict()
1307 assert "write_results" in results
...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ray/anaconda3/lib/python3.12/site-packages/ray/exceptions.py", line 54, in from_ray_exception
raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception
```
Catching and reraising their string representations allow us to report the actual exception to the user.
> fix: Handle unserializable exceptions from data sinks

- Cargo.lock
- src/daft-io/Cargo.toml
- src/daft-io/src/huggingface.rs
- tests/integration/test_huggingface.py
Adds a unique parameter to huggingface urls to prevent getting cache hits. 
Closes https://github.com/Eventual-Inc/Daft/issues/4780
> fix: add cachebusting parameter to huggingface urls

- src/daft-functions-list/src/kernels.rs
- tests/recordbatch/list/test_list_sort.py
When we split data into morsels, list operations operate on a slice of the original list. In this case, when performing a list sort, we create new lists that should have offsets starting from 0. However we incorrectly assumed that offsets do not change when sorting. This PR fixes that.
Related to #4862. We need a proper audit to close the issue.
> fix: Fix list sorting when operating on a morsel slice

- src/common/runtime/src/lib.rs
POSIX thread names are limited to 16 characters. The thread names for CPU and IO threadpools appear truncated in dumps and stack traces.
Source: https://man7.org/linux/man-pages/man3/pthread_setname_np.3.html
> fix(runtime): Reduce thread name length for compute and I/O threadpools

- src/daft-io/src/azure_blob.rs
Update the azure storage resource URL. With our upgrade of the Azure libraries, it no longer adds the `/.default` for us automatically. Confirmed to work by Piqi Chen.
https://dist-data.slack.com/archives/C041NA2RBFD/p1754006398444219
> fix: azure storage resource url

- Cargo.lock
- src/daft-dsl/Cargo.toml
- src/daft-dsl/src/python_udf.rs
Implement parallel execution using batched GIL acquisitions. Process chunks of rows within each thread to avoid GIL contention. Chunk size dynamically calculated as `num_rows / (n_cpus * 4)` with bounds `[1, 512]`.
This enables parallel execution of python udf while avoiding gil contention that would occur with naive per-row parallelization.
> perf: Add parallel execution for Python UDFs with batched GIL acquisitions

- daft/dataframe/dataframe.py
Adds warnings to `into_partitions` and `repartition`.
Closes #3652
> chore: add warning on repartition in native runner

- Cargo.lock
- Cargo.toml
- src/daft-local-execution/src/run.rs
- src/daft-local-execution/src/runtime_stats/mod.rs
- src/daft-local-execution/src/runtime_stats/subscribers.rs
- src/daft-local-execution/src/runtime_stats/subscribers/dashboard.rs
- src/daft-local-execution/src/runtime_stats/subscribers/debug.rs
- src/daft-local-execution/src/runtime_stats/subscribers/opentelemetry.rs
- src/daft-local-execution/src/runtime_stats/subscribers/progress_bar.rs
- src/daft-local-execution/src/sources/source.rs
Rather than sending updates per active node to runtime subscribers, we should just send them all at once and let the subscriber decide what to do (whether to iterate or not). This is useful for the Flotilla subscriber because it allows us to send one packet rather than internal batching.
Also includes changes from the logging PR since they should be fixed ASAP and can help reduce that PR to narrow the segfault.
> fix: Batch RuntimeSubscriber updates for all nodes 

- docs/index.md
pandas link was linking to polars docs
> docs: fix link for pandas

- daft/dataframe/dataframe.py
Strategy is not support in a cross join, so raise with details.
Closes #4944
> fix: raise error on invalid cross join parameters

- src/daft-local-execution/src/intermediate_ops/into_batches.rs
Fixes issue here https://github.com/Eventual-Inc/Daft/actions/runs/16889682307/job/47846055281
merge conflict between https://github.com/Eventual-Inc/Daft/pull/4935 and https://github.com/Eventual-Inc/Daft/pull/4921
> fix: use associate type for swordfish into_batches operator state

- src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
- src/daft-local-execution/src/lib.rs
- src/daft-local-execution/src/run.rs
- src/daft-local-execution/src/runtime_stats/mod.rs
- src/daft-local-execution/src/streaming_sink/base.rs
Fixes the 
```
thread '<unnamed>' panicked at src/daft-local-execution/src/run.rs:368:18:
There should only be 1 stats manager instance by the end
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at src/daft-local-execution/src/run.rs:500:26:
Execution engine thread panicked: Any { .. }
Error in sys.excepthook:
File "/Users/colinho/Desktop/Daft/.venv/lib/python3.12/site-packages/ray/_private/worker.py", line 1887, in custom_excepthook
def custom_excepthook(type, value, tb):
```
issues
> fix: Add handle for swordfish runtime stats manager

- src/daft-connect/src/spark_analyzer.rs
- tests/connect/test_basics.py
- tests/connect/test_spark_sql.py
> feat: Add offset support to Spark Connect

- .github/workflows/broken-link-checker.yml
Since we couldn't find any broken link checker settings to ignore 308 redirects, just filtering out HTTP_308 and failing if things are still broken.
* `grep` returns 0 if there are any matches. `!` flips that to 1 and the workflow fails.
* `grep` returns 1 if there are no matches. `!` flips that to 0 and the workflow succeeds.
> fix(blc): Attempt to fix the broken link checker.

- daft/ai/openai/text_embedder.py
- daft/execution/udf.py
- requirements-dev.txt
While debugging some OpenAI text_embed failures, I couldn't figure out why my OPENAI_API_KEY wasn't being picked up. 
n/a
> fix: subprocess UDF inherits current process env

- .github/workflows/build-wheel.yml
- .github/workflows/publish-dev-s3.yml
> fix: Fix venv command for windows build

- src/daft-core/src/array/fixed_size_list_array.rs
- src/daft-core/src/array/list_array.rs
- src/daft-core/src/array/ops/arrow2/comparison.rs
- tests/dataframe/test_aggregations.py
- tests/expressions/test_expressions.py
I'm rewriting minhash deduplication using only Daft expressions, and that requires performing GroupBy on a Int and FixedSizeList column. That doesn't work because Arrow2 doesn't support comparing FixedSizeList values, so I manually override.
In addition, implemented a mini-optimization when calling `series.into_iter` on list columns to allocate once. Helps with functions like `list_min`, `list_max`, etc.
> fix: Implement Multi-Column Aggregations with List-like columns 

- daft/ai/sentence_transformers/text_embedder.py
- tests/ai/test_sentence_transformers.py
From the docs:
> The PyTorch backend is the default backend for Sentence Transformers. If you don’t specify a device, it will use the strongest available option across “cuda”, “mps”, and “cpu”.
Instead of setting cuda or cpu, we should let mps be used too so that we use Metal on MacOS with GPUs.
Planning to explore ONNX and OpenVINO backends next.
> perf(embed_text): Let Sentence Transformers select the best available device

- daft/execution/udf.py
- daft/execution/udf_worker.py
- tests/expressions/test_legacy_udf.py
In process-based UDFs, if the UDF throws an exception and it is not picklable, then we should still send the traceback through. The error message is formatted slightly differently though, unfortunately.
Normal
```
Error when running pipeline node UDF udf
ValueError: test
File "/Users/slade/daft/main/mor.py", line 7, in udf
raise ValueError("test")
ValueError: test
The above exception was the direct cause of the following exception:
File "/Users/slade/daft/main/mor.py", line 15, in <module>
print(df.collect())
^^^^^^^^^^^^
daft.errors.UDFException: User-defined function `<function udf at 0x16662db20>` failed when executing on inputs:
- city (Utf8, length=3)
```
Can't serialize or de-serialize.
```
Error when running …
```
> fix: Handle Unserializable Errors in Process UDFs

- docs/index.md
Apparently if your system settings is in dark mode, this interacted strangely with our docs.
> docs: More fixes to the overview page in light mode

- docs/SUMMARY.md
- docs/install.md
- docs/js/install-tool.js
- mkdocs.yml
- pyproject.toml
Some improvements:
- Focus on making this a How To guide based on https://diataxis.fr/
- Installation comes after the quickstart. The quickstart gets you going and contains a self-contained installation instruction. There's no need to boggle down the user with installation before a quickstart.
- List most important optional dependencies (if a user wants pandas or numpy they can figure it out themselves).
- Remove info on installing nightlies or building from source. Fastest path to success.
- Emphasize that they should only look at the legacy cpu support section for troubleshooting only.
> docs: Improve installation instructions

- .github/workflows/pr-test-suite.yml
We skipped premerge tests for non-code changes in https://github.com/Eventual-Inc/Daft/pull/5057
But we shouldn't do this for postmerge
> ci: Do not skip postmerge tests

- docs/connectors/turbopuffer.md
- docs/modalities/text.md
Add guide on embedding and chunking text.
> docs: Add text guide

- docs/hooks.py
- docs/overrides/main.html
- mkdocs.yml
Adds noindex tag to all docs that are not `/stable/`
As per https://aioseo.com/docs/when-to-use-noindex-or-the-robots-txt/
> The biggest difference to understand is that if you want search engines to not include content in search results, then you MUST use the NOINDEX tag and you MUST allow search engines to crawl the content. If search engines CANNOT crawl the content then they CANNOT see the NOINDEX meta tag and therefore CANNOT exclude the content from search results.
> 
> So if you want content not to be included in search results, then use NOINDEX. If you want to stop search engines crawling a directory on your server because it contains nothing they need to see, then use “Disallow” directive in your robots.txt file.
i.e. we should:
1. Allow for crawling of all docs (fix robots.txt) …
> docs: add noindex tag to non-stable pages

- daft/ai/openai/__init__.py
- daft/ai/openai/text_embedder.py
- daft/ai/provider.py
- docs/modalities/text.md
- tests/ai/test_lm_studio.py
Add LM Studio as a text embedding provider.
For example
```
import daft
from daft.ai.provider import load_provider
from daft.functions.ai import embed_text
provider = load_provider("lm_studio", base_url="http://127.0.0.1:1234")  # This base_url parameter is optional if you're using the defaults for LM Studio. You can modify this as needed.
model = "text-embedding-nomic-embed-text-v1.5"  # Select a text embedding model that you've loaded into LM Studio.
(
daft.read_huggingface("Open-Orca/OpenOrca")
.with_column("embedding", embed_text(daft.col("response"), provider=provider, model=model))
.show()
)
```
> feat(embed_text): Support LM Studio as a provider

- docs/index.md
On the overview page, when the typewriter animation finished rendering the text, it flickered, which didn't feel good on your eye. Fixed by removing the abrupt fade-in effect and replacing with a subtle cursor fade that falls gently.
https://github.com/user-attachments/assets/00dc1aff-c70d-4e07-8490-7f9b13698ecf
https://github.com/user-attachments/assets/c4efc583-7e14-438e-a38b-e22d37ff0a72
Closes https://linear.app/eventual/issue/EVE-839/on-the-overview-page-when-the-animation-finishes-rendering-the-text-it
> docs: fix flickering typewriter animation on overview page

- daft/context.py
- daft/daft/__init__.pyi
- daft/dataframe/dataframe.py
- daft/runners/ray_runner.py
- src/common/daft-config/src/lib.rs
- src/common/daft-config/src/python.rs
- src/daft-distributed/src/pipeline_node/join/translate_join.rs
- src/daft-distributed/src/stage/stage_builder.rs
- src/daft-local-plan/src/translate.rs
- tests/actor_pool/test_actor_cuda_devices.py
- tests/cookbook/test_joins.py
- tests/dataframe/test_aggregations.py
- tests/dataframe/test_decimals.py
- tests/dataframe/test_into_batches.py
- tests/dataframe/test_joins.py
- tests/dataframe/test_pivot.py
- tests/dataframe/test_shuffles.py
- tests/expressions/test_legacy_udf.py
- tests/sql/test_joins.py
- tests/sql/test_window.py
- tests/test_resource_requests.py
- tests/window/test_order_by_only.py
- tests/window/test_partition_only.py
- tests/window/test_partition_order_by_lag_lead.py
- tests/window/test_partition_order_by_rank.py
- tests/window/test_running_agg.py
Removes the flotilla fallback. If the plan is not translatable raise a helpful error message.
Additionally changes the flotilla execution config to be `use_legacy_ray_runner` instead of `use_experimental_distributed_engine`.
> fix: Remove flotilla fallback

- .github/workflows/pr-test-suite.yml
`unit-tests` is the check to encompass all the unit tests, and it is a 'required' job. It should fail if any unit test failed or cancelled (i.e. timeout), and pass otherwise (skipped or success). 
Previously, it had a dependency on `unit-test`, which meant that as long as one unit test cancelled due to timeout, it will be skipped. This overrides the `if` condition, as the `if` condition is not an `always()`. https://github.com/orgs/community/discussions/25286
> ci: Always run the `unit-tests` required check

- docs/SUMMARY.md
- Replace generic "Overview" labels with descriptive section names in sticky header navigation
https://github.com/user-attachments/assets/01b3b58e-9b87-4668-9f44-d18033c49e64
Closes EVE-845
> docs: fix navigation labels to match section names

- .github/workflows/pr-test-suite.yml
- .gitignore
- AGENTS.md
- tests/actor_pool/test_actor_cuda_devices.py
I noticed that AI agents like Cursor seem to default to using our underlying tools (`uv`, `maturin`, `pytest`) rather than the nicer Makefile commands that do other setup. That might be a documentation issue, but after talking to the agent, it seems to prefer using the underlying tools. So I added an `AGENTS.md` to mitigate it.
`AGENTS.md` is supposed to be the emerging standard (https://agents.md/), but Claude Code doesn't support it yet. We can symlink this file to `CLAUDE.md` if others prefer.
Feel free to also add more details about development patterns, opening PRs, or anything else. But from my understanding, the shorter the better.
> chore: Add AGENTS.md

- .github/workflows/pr-test-suite.yml
Undo the change in the AGENTS.md that broke the check
> fix: Undo skipcheck change

- src/daft-recordbatch/src/lib.rs
- src/daft-recordbatch/src/python.rs
I need it for both a process UDF PR and for the dashboard stuff, so just moved it to this PR to rebase the others on top of it. Lmk if you want me to add a test for this specifically, but I do test it E2E in the others.
> feat: Add Arrow IPC conversion for RecordBatches

- daft/ai/_expressions.py
- daft/ai/protocols.py
- daft/ai/provider.py
- daft/ai/transformers/protocols/image_embedder.py
- daft/ai/transformers/protocols/text_classifier.py
- daft/ai/transformers/provider.py
- daft/ai/typing.py
- daft/ai/utils.py
- daft/functions/__init__.py
- daft/functions/ai/__init__.py
- docs/api/ai.md
- tests/ai/openai/test_openai_text_embedder.py
- tests/ai/transformers/test_transformers.py
- tests/ai/transformers/test_transformers_image_embedder.py
- tests/ai/transformers/test_transformers_text_classifier.py
- Creates a TextClassifier protocol and supporting operations.
- Implements `classify_text` with string labels for transformers.
n/a
> feat: adds support for classify_text 

- .github/workflows/pr-test-suite.yml
Seems like haskell + swap storage is enough, and seems like android is quite the offender.
Ran three times.
> ci: Reduce free disk space time

- README.rst
- docs/index.md
- Added Examples link between Quickstart and API Documentation in docs/index.md
- Added Examples link to More Resources section in README.rst
- Maintains consistency across documentation entry points
> docs: add Examples link to getting started sections

- daft/expressions/expressions.py
- daft/series.py
- tests/recordbatch/utf8/test_split.py
- tests/series/test_utf8_ops.py
- tests/sql/test_utf8_exprs.py
Based on the discussion in https://github.com/Eventual-Inc/Daft/pull/5191#issuecomment-3293354079, split the function into 2 forms and deprecate the `regex` kwarg.
> chore: Split `.str.split` into `.str.split` and `.str.regexp_split`

- src/daft-functions-list/src/list_map.rs
- tests/functions/test_list_map.py
Remove input name renaming in get_return_field method to preserve original field names from expressions. This fixes the issue where extracting struct fields from list of structs requires an alias due to name mismatch.
Fixes #5200
> fix: remove unnecessary field renaming in ListMap scalar UDF

- daft/expressions/expressions.py
- daft/functions/__init__.py
- daft/functions/str.py
I originally named it `index` because that matched a Python function that did a similar thing, but I just realized Python also has `str.find` which is actually more similar to what we have here, since `str.find` returns -1 when not found, whereas `str.index` raises an exception.
> fix: rename index function to find

- daft/__init__.py
Allow for this to work:
```
import daft
df = daft.from_pydict({"path": ["Screenshot 2025-09-16 at 10.47.20 AM.png"]})
df = df.select(daft.functions.file(df["path"]))
df.collect()
```
Previously, it would fail on `daft.functions` because you need to import it separately, but this PR adds it as an export of `daft/__init__.py` so it should work with just `import daft`.
> feat: allow for functions module to be accessed from daft import

- daft/expressions/expressions.py
- daft/functions/__init__.py
- daft/functions/image.py
- daft/functions/numeric.py
Missed a few on the initial migration. Fixed them here.
> feat: migrate remaining basic expressions

- src/daft-functions-uri/src/download.rs
- src/daft-functions-uri/src/upload.rs
- src/daft-io/src/lib.rs
It's kinda annoying especially if theres a lot of invalid urls. Also, the on_error method doesn't say anything about logging or warning, it just says the row will be set to null. Don't see why we need to log it actually.
> chore: Don't log failures in url download if `on_error="null"`

- daft/io/_warc.py
- src/daft-warc/src/lib.rs
- tests/io/test_warc.py
Add WARC-Target-URI as a top-level column for WARC reads. For more details, see https://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1/#warc-target-uri
This is a mandatory column for ‘response’, ‘resource’, ‘request’, ‘revisit’, ‘conversion’ and ‘continuation’ records, and optional for 'metadata' records.
'warcinfo' records do not have this field.
> feat: Add WARC-Target-URI as a top-level column for WARC reads

- docs/index.md
Fixed inconsistent capitalization and improved clarity of copy on the documentation index page:
- Updated all sections to use sentence case for descriptive phrases (e.g., "Object Store" → "Object storage") 
- Changed "use-cases" to "use cases" for standard usage
- Replaced vague "data silos" phrasing with specific description of Daft's multimodal capabilities vs traditional dataframes
> docs: improve copy and consistency on index page

- daft/io/lance/_lance.py
- daft/io/lance/lance_scan.py
- tests/io/lancedb/test_lancedb_reads.py
When the number of fragments is large, the current implementation method assigns one task to each fragment, which results in a long planning time. Therefore, some fragment filtering and fragment grouping implementations have been added here to reduce the number of tasks.
> refactor: add fragment_group_size to reduce lance scan task

- daft/expressions/__init__.py
- daft/expressions/expressions.py
- daft/functions/__init__.py
- daft/functions/misc.py
- docs/api/expressions.md
Last function for our expressions migration! The `when` function replaces the existing `Expression.if_else`. Currently still uses `Expr::IfElse` under the hood because I didn't want to bother adding an expression variant.
https://github.com/Eventual-Inc/Daft/issues/2554
> feat: when function

- src/daft-core/src/array/ops/comparison.rs
Based on codecov, our array comparison code has 491 lines of untested code: https://app.codecov.io/gh/Eventual-Inc/Daft/tree/main/src%2Fdaft-core%2Fsrc%2Farray%2Fops
I was curious to see how good codex is so I gave it a prompt to add tests for the misses. It did a remarkable job planning out all the tests we needed, but didn't write compilable code.
I then let Cursor with claude-4-sonnet in agent mode try to fix it. Not bad, and we actually caught a missing implementation error!
Alas, claude-4-sonnet simply added a `#[should_panic]` tag to the test case. Bad claude.
Made a small fix for that case.
> test: Complete coverage for array comparisons

- src/daft-dashboard/src/lib.rs
- tests/dataframe/test_repr.py
Use {} for the dataframe cell route. Also add a test that makes the cell request
> fix: Use {} for dashboard dynamic route

- daft/datasets/common_crawl.py
- tests/datasets/test_common_crawl_mocked.py
- tests/integration/io/test_common_crawl_integration.py
In #5244 I missed passing the io config into the url download. This PR fixes that.
Good on the credentialed integration test for catching it.
> fix: Pass io config when grabbing Common Crawl manifest

- src/daft-core/src/lit/python.rs
- tests/test_datatype_inference.py
* Uses `format` instead of `str` when handling decimal conversions — this normalizes the decimals from either scientific or decimal notation into decimal notation.
* Adds tests for various scientific notation forms.
* Adds tests for all failure cases listed by the customer 
* Closes #5302 
- [n/a] Documentation builds and is formatted properly
> fix: decimal format for handling scientific notation

- .github/workflows/broken-link-checker.yml
Found a couple broken links in docs, and turns out the broken link checker doesn't check it.
The broken link checker currently checks `daft.ai`, and doesn't check `docs.daft.ai` because its a subdomain. This adds docs.daft.ai (as well as eventual.ai) to the broken link checker.
> docs: Add docs to broken link checker

- tests/property_based_testing/strategies.py
Fixes the generation of columns by removing the ability to generate a column named "*", since doing `col("*")` gets all of the columns.
> ci: fix property test column name

- .github/workflows/broken-link-checker.yml
Broken link checker by default fails on anything non 200, but we don't care about pages that are redirects or ones that denies bots. We don't want to exclude the domain because they might eventually become 404s though, like https://platform.openai.com/docs/guides/embeddings could totally change.
This PR we only fail if there are 404s, but still print out any link that was 'broken'.
```
Broken links (non-404, non-fatal):
├─BROKEN─ http://www.daft.ai/ (HTTP_308)
├─BROKEN─ http://www.daft.ai/slack (HTTP_308)
├─BROKEN─ https://code.visualstudio.com/docs/editor/debugging#_launch-configurations (HTTP_500)
├─BROKEN─ https://dl.acm.org/doi/abs/10.1145/2670979.2670997 (HTTP_403)
├─BROKEN─ https://dl.acm.org/doi/pdf/10.1145/2670979.2670997 (HTTP_403)
├─BROKEN─ …
```
> ci: Only fail broken link checker on 404s

- docs/SUMMARY.md
- docs/api/udf.md
- docs/custom-code/func.md
- docs/custom-code/udfs.md
Added
- docs page in the user guide about `@daft.func`
- section in the UDF docs that mentions `@daft.func` as the next generation UDF
- API docs for the decorator
> docs: add daft.func docs page and APIs
